### ISSUE TITLE
Keyboard hotkeys should loop around when reaching the end of the working area

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#1]
A naive approach has been attempted here, which only works when you have monitors of identical resolution with no offsets. Some restructuring internally is required for this to work properly.

**Comment by llinfeng** [comment]
@vegardlarsen I observe the same symptom for the 2.0.0-beta6. If I keep advancing the window to the right, it will get stuck at the farthest monitor on the right. (I have setup multiple monitors in a row.)

Please comment if "looping" is an option for the new MaxTo.

PS: great work for implementing the command-line tools, yet, I am confused by how to make us of it: it seems to run within a command prompt window, and the demo showed that it can "resize" *THE* command prompt window in which the `maxto ...` command was issued. I tried to let AutoHotKey fire up the command, but it does not seem to apply any change to any window that are opening. Please point me to other demos for proper use of the command line tool :)

**Comment by vegardlarsen** [comment]
This regression is not on purpose, but I won't be able to fix it for 2.0 final. A flag for this is a great idea.

PS! You can resize the current command line window, if you are running the command from inside the command prompt window itself. In that case, the command prompt is the foreground window, and it gets moved. If you do this from AutoHotkey or similar, I cannot make any guarantees as to what window is the foreground window, and you would have to target the command prompt window using the `/Window` switch. I'd recommend using MaxTo recipes for this instead, if possible.
