### ISSUE TITLE
Feature request: add a keyboard shortcut to restart MaxTo

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#100]
MaxTo handles multi-workstation setting pretty badly. When I transfer from one workstation to another, I would have to manually **restart** MaxTo by right-clicking the icon, hitting "Exit" and starting the process again. This becomes cumbersome.

@vegardlarsen Could you implement a shortcut that "restart" MaxTo? I tried to use AutoHotKey but it was unable to terminate the process "MaxTo" after the new release (2015.7).

Looking forward for a quick implementation.

Thank you!

**Comment by vegardlarsen** [comment]
@llinfeng I am working on a much better solution; fixing the multi-workstation scenario. As such, I am closing this.

**Comment by llinfeng** [comment]
Oh, sounds sweet! Do you have an estimated release date? 

Thanks!

**Comment by vegardlarsen** [comment]
@llinfeng It is part of a major restructuring of MaxTo, so [6-8 weeks](https://news.ycombinator.com/item?id=4406316) seems like a likely estimate. :)
