### ISSUE TITLE
Old winplit regions

### ISSUE THREAD

**Issue by bymaximus** [digitalcreations/MaxTo#101]
Any tip to get MaxTo works with/as same old WinSplit revolution window positions? 

For example, positioning a window at screen right side, if press same key more than one time it changes window positioning at right side instead of just move the window to right side?!

**Comment by vegardlarsen** [comment]
@bymaximus We have no plans currently of changing MaxTo to work identically to WinSplit. We may at some point incorporate some of the features when we find a good way to do so, but there are no plans currently.
