### ISSUE TITLE
Regardless of set regions (1x1 , 2x2) windows always snap to center

### ISSUE THREAD

**Issue by oduncan** [digitalcreations/MaxTo#105]
Windows 7 Pro, fresh install of the latest version, no matter how i set up the regions, when I double click the top bar all the windows snap to the middle of the screen.

**Comment by vegardlarsen** [comment]
@oduncan Thanks for reporting this. Do you have a screenshot or video that shows me what is happening?

**Comment by vegardlarsen** [comment]
Since I haven't received any feedback, I am closing this issue. Feel free to report back with more details if you experience this again.
