### ISSUE TITLE
Support for padding/margins around the snappable areas

### ISSUE THREAD

**Issue by freshpotatoe** [digitalcreations/MaxTo#106]
Currently used to using BetterTouchTool on OSX which supports setting a border around the snappable regions, although it doesn't increase information density I think it does improve aesthetics at a small cost of implementation. 

Alternatively make it an easy thing to configure in the settings file directly.

**Comment by vegardlarsen** [comment]
I haven't used BetterTouchTool (or OS X much, for that matter). After a recent bug on Windows 10, I know for a fact that I don't want to work with padding between my windows, but maybe there is a different opinion among everyone else?

**Comment by vegardlarsen** [comment]
I am closing this for now. I will not be doing this right now, but if interest sparks up, I'll reconsider.
