### ISSUE TITLE
Invalid Data Exception

### ISSUE THREAD

**Issue by hyyperlite** [digitalcreations/MaxTo#107]
Using Windows 10.  MaxTo had been working with no issue for me from the Windows10 preview version through release and up until the past week or so.  

Issue:
Exception:  System.IO.InvalidDataException
Target Site: NBug.Core.Util.Storage.ZipStorer Open(System.IO.Stream, System.IO.FileAccess)
Message: "Found invalid data while loading"
Source: NBug
Stack Trace:
    at NBug.Core.Util.Storage.ZipStorer.Open(Stream _stream, FileAccess _access)
    at NBug.Core.Submission.Dispatcher.GetDataFromZip(Stream stream)
    at NBug.Core.Submission.Dispatcher.Dispatch()
    at NBug.Core.Submission.Dispatcher..ctor(Boolean isAsynchronous)  
HResult:  -21462333087

**Comment by vegardlarsen** [comment]
@hyyperlite This seems like a crash report was written in a way that was invalid. When the crash reporting system tries to load the data to submit it to us, it crashes again, and there is no recovery.

You can probably easily fix this. Go into `C:\Program files\MaxTo` and look for `Exception_<whatever>.zip`. Move those files out of the MaxTo folder, and try starting it again.

I would be very interested in seeing those files, so if you could send them to me via e-mail that would be much appreciated. I have a suspicion the files are empty, but lets give it a go anyhow?

**Comment by hyyperlite** [comment]
Thanks,

Removing the exception files did resolve the issue and I can now start it.
I couldn't attach the zip file (Gmail security)  and when I tried to
extract the XML file it contained winRAR claims that the archive is
corrupted.  I did put the whole zip file on google drive and you can
download from the following link:

https://drive.google.com/file/d/0B9EaWNVKnyFdSUVjMWZoWktZd2s/view?usp=sharing


(Love the application by the way, I'm using a 21:9 aspect monitor and MAXTO
is invaluable on it, even with the new quad layout/snap options in
Windows10.  In fact with those options in Windows10 I get really a 3rd
layout profile.

-Nick

On Thu, Oct 29, 2015 at 2:05 AM, Vegard Andreas Larsen <
notifications@github.com> wrote:

> @hyyperlite <https://github.com/hyyperlite> This seems like a crash
> report was written in a way that was invalid. When the crash reporting
> system tries to load the data to submit it to us, it crashes again, and
> there is no recovery.
>
> You can probably easily fix this. Go into C:\Program files\MaxTo and look
> for Exception_<whatever>.zip. Move those files out of the MaxTo folder,
> and try starting it again.
>
> I would be very interested in seeing those files, so if you could send
> them to me via e-mail that would be much appreciated. I have a suspicion
> the files are empty, but lets give it a go anyhow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalcreations/MaxTo/issues/107#issuecomment-152099112>
> .
>



-- 
Thanks,
-Nick

**Comment by vegardlarsen** [comment]
I've updated the crash reporting library, which was blocking MaxTo from starting in your case. The original exception I am tracking already in an internal crash tracker, since it has been reported by others. I don't know exactly what is causing it yet.

Therefore, I am closing this issue.
