### ISSUE TITLE
issues installing maxto 2015-11 

### ISSUE THREAD

**Issue by prnock** [digitalcreations/MaxTo#109]
tried installing on 64bit 8.1 windows got errors complaining about 32bit visual c++ needing to be installed then after installing it still had other error - see pictures
![maxto-error3](https://cloud.githubusercontent.com/assets/15730092/11034647/1c89e5be-86bb-11e5-8fcc-7130d71cfa26.JPG)
![maxto-error2](https://cloud.githubusercontent.com/assets/15730092/11034646/1c887b2a-86bb-11e5-9c00-7a7c72bd31af.JPG)
![maxto error](https://cloud.githubusercontent.com/assets/15730092/11034645/1c8652f0-86bb-11e5-99d5-4e2095de4360.JPG)

**Comment by vegardlarsen** [comment]
I am looking at what causes this, but in the mean time you [can download and install](https://www.microsoft.com/en-us/download/details.aspx?id=48145) the required components from Microsoft. You need both the 64-bit (x64) and 32-bit (x86) releases.

**Comment by prnock** [comment]
Once the error popped up the first time – i installed the 2013 as stated in the error -  but I see this is the 2015 versions – can I remove the 2013

**Comment by vegardlarsen** [comment]
Yes, you can. The error message contains an error in addition to the problem that the installer apparently didn't install the correct files.

**Comment by Xeltom** [comment]
Hello,

I confirm exactly the same issue.
Thank you in advance.

**Comment by Xeltom** [comment]
In the mean while I'm reverting to previous version.

**Comment by vegardlarsen** [comment]
A new, fixed installer is [now available](https://maxtostorage.blob.core.windows.net/releases/MaxToSetup-2015-11.exe). You'll need to uninstall before installing this. It will be live on the website in a few minutes.

**Comment by prnock** [comment]
Thanks for the quick response! It installed perfectly

**Comment by Xeltom** [comment]
Perfect! Thank you very much
