### ISSUE TITLE
Install without Admin privileges

### ISSUE THREAD

**Issue by icymist** [digitalcreations/MaxTo#110]
I would like to install without Admin privileges. Otherwise, I will have to get approval from the IT department at the corporate!

**Comment by vegardlarsen** [comment]
MaxTo's installer may have trouble installing without admin privileges, but the app itself works fine. It runs with `highestAvailable` privileges, which means it will prompt you for admin access, and then you can say no. It will still run just fine.

We are working on implementing this in a better way for a future release.
