### ISSUE TITLE
Change/Highlight Regions broken

### ISSUE THREAD

**Issue by nakdeyes** [digitalcreations/MaxTo#111]
Hello! 

I have now tried this program on two separate windows 7 machines and found the same issue on both: When I author and save regions, they tend to work right after I set them, but every subsequent preview or edit of the regions, shows me just the default single split exactly down the center ( vertically ).

This also happens when I save a profile with the Regions. The saved region will draw as just the two default split windows. If I then play around a bit, going in and out of the edit regions screen, it will eventually just start functioning as the two default split regions, rather than my loaded profile.

I am in the trial period right now, not sure if this is a trial issue.. I fully plan on buying if I can get the program to work reliably full time.

Would also suggest a lower price while you guys are still working out the bugs. 19$ is the highest asked for this type of software, and I will happily pay it, but only if it works as intended 99% of the time.

**Comment by basshead22** [comment]
Same problem for me, I have to manually set my region after each reboot. I also have some transparency issues that came back in this release

**Comment by nakdeyes** [comment]
For me, it is every reboot, but also every so often it just does it anyways.. maybe when my computer does the screen saver?

I know I set the regions about 2 hours ago and they were working great ( except the preview, which always just displays the default 2 regions like I mentioned above ).. then they just stopped working just now ( reverting back to the 2 default regions split in the middle of the screen ).

Things I can think of:
 * My PC did go screen saver, which at my work, asks me to log back in when I come back, dunno if this is treated as a full log out under the hood or not ( I would guess not ).
 * I do use Synergy as well, and think maybe, just maybe, they are conflicting?

**Comment by vegardlarsen** [comment]
First, I apologize for the slow response. I've been away for the last two days.

This may be related to a settings-reading bug I have been tracking. If I am right, this would have previously have led to a crash.

Could the both of you take the contents of `%LocalAppData%\Digital_Creations_AS\MaxTo.exe_<something strange>\user.config` and paste it here right after you've set up your regions as you'd like?

**Comment by basshead22** [comment]
Mine was in a level deeper 
>%LocalAppData%\Digital_Creations_AS\MaxTo.exe_<something strange>\2015.11.0.0\user.config

When I set the region I see the file date stamp change but it's content doesn't, same for the alternate region.



[user.config.txt](https://github.com/digitalcreations/MaxTo/files/33959/user.config.txt)

**Comment by vegardlarsen** [comment]
@basshead22 I uploaded a fix for this in issue #112. Thank you for reporting this, I'll have an official  release out shortly, but feel free to use the workaround in the meantime.

**Comment by basshead22** [comment]
Workaround did indeed fix my issue with the region. thx

**Comment by nakdeyes** [comment]
I appreciate such a fast turn around! You have earned a purchase from me. Thanks.
