### ISSUE TITLE
Updated but still problems

### ISSUE THREAD

**Issue by jglazer63** [digitalcreations/MaxTo#112]
Below is my preferred setup.  I have 3 identical monitors Labeled 3,2,1 in the system (from left to right).  3 is portrait, 2 is landscape and 1 is portrait (flipped).   Below is the layout I setup with MAXTO that I want to maintain for these monitors:
![maxto1](https://cloud.githubusercontent.com/assets/11459102/11146837/bb94b3a6-89df-11e5-8429-21966902a50c.jpg)

After setting up the layout and saving the profile and then returning to MAXTO (or rebooting the system) to see the settings, below is the result (all messed up).  You'll note that the monitors are labeled incorrectly with two #1s.
![maxto2](https://cloud.githubusercontent.com/assets/11459102/11146839/bda52716-89df-11e5-8296-e5af08cc9daa.jpg)

So there are definitely still issues here.  I am happy to help you test if you wish.  I love the program but I have to reset my layout every time I reboot, which is something of a pain.

**Comment by vegardlarsen** [comment]
Can you send me (or paste the content here, it shouldn't be sensitive) of your `%LocalAppData%\Digital_Creations_AS\MaxTo.exe_<something>\user.config` right after you've set up your regions as you'd like?

The numbering is because MaxTo assumes that the primary monitor is monitor 1, and has just hardcoded that number on that display (you can see that the controls are slightly different on that monitor). I am going to fix that bug right now.

**Comment by jglazer63** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="MaxTo.UserSettings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <MaxTo.UserSettings>
            <setting name="FirstRunTime" serializeAs="String">
                <value>08/19/2015 17:23:11</value>
            </setting>
            <setting name="EnableMoveTransparency" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="SelectedUiCulture" serializeAs="String">
                <value>en-US</value>
            </setting>
            <setting name="EnableMoveTransparencyAnimation" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="VirtualKeyModifier" serializeAs="String">
                <value>ShiftKey</value>
            </setting>
            <setting name="RegionConfiguration" serializeAs="Xml">
                <value>
                    <RegionConfiguration>
                        <Monitor Name="\\.\DISPLAY2" Primary="true">
                            <Region IsSplit="false" />
                        </Monitor>
                        <Monitor Name="\\.\DISPLAY1">
                            <Region IsSplit="true" Orientation="Horizontal" SplitterDistance="0.5">
                                <Region IsSplit="true" Orientation="Vertical" SplitterDistance="0.5"
                                    Placement="1">
                                    <Region IsSplit="false" Placement="1" />
                                    <Region IsSplit="false" Placement="2" />
                                </Region>
                                <Region IsSplit="true" Orientation="Vertical" SplitterDistance="0.764869888475836"
                                    Placement="2">
                                    <Region IsSplit="false" Placement="1" />
                                    <Region IsSplit="false" Placement="2" />
                                </Region>
                            </Region>
                        </Monitor>
                        <Monitor Name="\\.\DISPLAY3">
                            <Region IsSplit="true" Orientation="Horizontal" SplitterDistance="0.27812">
                                <Region IsSplit="false" Placement="1" />
                                <Region IsSplit="false" Placement="2" />
                            </Region>
                        </Monitor>
                    </RegionConfiguration>
                </value>
            </setting>
            <setting name="LastUpdateFound" serializeAs="String">
                <value>2015.11</value>
            </setting>
            <setting name="SnapRange" serializeAs="String">
                <value>15</value>
            </setting>
            <setting name="UserProfiles" serializeAs="Xml">
                <value>
                    <Profiles>
                        <MonitorProfile ProfileName="Jon" GUID="0f5fe05f-f558-4a2c-b765-80bdd584d0a5">
                            <Region IsSplit="false" />
                        </MonitorProfile>
                    </Profiles>
                </value>
            </setting>
            <setting name="LastVersionRun" serializeAs="String">
                <value>2015.11.0.0</value>
            </setting>
            <setting name="AskForExitConfirmation" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="PassiveMode" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="SnapEdges" serializeAs="String">
                <value>None</value>
            </setting>
            <setting name="MoveTransparency" serializeAs="String">
                <value>70</value>
            </setting>
            <setting name="HotkeyActions" serializeAs="Xml">
                <value>
                    <ArrayOfHotkeyAction xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>ToggleMode</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>ChangeRegionsMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>ChangeRegionsAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>HighlightRegionsMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>HighlightRegionsAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>FitAllWindows</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad4</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveLeftMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad8</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveUpMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad6</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveRightMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad2</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveDownMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad4</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapLeftMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad8</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapUpMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad6</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapRightMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad2</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapDownMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad4</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveLeftAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad8</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveUpAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad6</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveRightAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad2</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveDownAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad9</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MaximizeToScreen</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>Next</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>TaskSwitchRegionNext</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>Prior</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>TaskSwitchRegionPrevious</UniqueId>
                        </HotkeyAction>
                    </ArrayOfHotkeyAction>
                </value>
            </setting>
            <setting name="AlternativeProfileKey" serializeAs="String">
                <value>Menu</value>
            </setting>
        </MaxTo.UserSettings>
    </userSettings>
</configuration>

**Comment by jglazer63** [comment]
I should mention I am a programmer of 30 years as well (dot-net) so I can speak a little more technically if needed.

**Comment by vegardlarsen** [comment]
I [uploaded a fix here](https://dl.dropboxusercontent.com/u/12591686/MaxToSetup-issue112.exe). The file is digitally signed, and has the same version number as the current release version, so you should uninstall the current version before running this. The issue was that changing the position of the splitter didn't update an internal variable in some cases.

Since it is Friday afternoon, I won't risk putting out a new version just yet, but please confirm if this works for you, and I'll probably release a new version on Monday. (I am keeping this open so I can track fixed issues for that release)

**Comment by jondcoleman** [comment]
This is kind of amazing.  I was about to uninstall just a few minutes ago because of this issue but decided to come here and just installed that updated and it works! Timing couldn't have been better.

**Comment by jglazer63** [comment]
Yes this seemed to fix the issue.

**Comment by vegardlarsen** [comment]
This fix has been released now. Waiting over the weekend gave me a chance to check for automated crash reports as well, and I am happy to report that I haven't received any :)
