### ISSUE TITLE
Windows are scattered after sleep

### ISSUE THREAD

**Issue by jglazer63** [digitalcreations/MaxTo#113]
Again, I have 3 monitors numbered 3,2,1 (left to right).   After coming back from sleep all the windows on #1 are on #2 and vice versa.   Vaguely in the same places but still screwed up.   I have to drag them all back to the areas they were in when I left the PC.  This has become a problem since a version or so ago (maybe longer, I don't know for sure).

Any ideas?

**Comment by jacobbenlewis** [comment]
+1  Using this on Windows 10 with a large tv screen.  Whenever the PC goes to sleep and I log back in my apps are in different locations and sizes.

**Comment by woodpile72** [comment]
+1 I'm on Win7 Pro with a Dell U3415W.  Resolution is 3440x1440.  When the computer sleeps, same issue... Log in and all windows that were visible are no longer "maximized" and are, instead, resized to a much smaller size.  I'd love to pay for this (just installed yesterday to test) and begin using it, but need this fixed.  Anyone?

**Comment by woodpile72** [comment]
This just happened again.  Woke from sleep and ALL windows, even minimized windows, were resized to a strange size and shoved off to the left of the first virtual screen.  I've got my money ready and want to pay - please give this some attention so I can give you my money.

**Comment by vegardlarsen** [comment]
@woodpile72 I'd love to fix this, but I can't for the love of me figure out why it is happening (and it doesn't happen on any of my three machines). A few questions; are you running this monitor in high DPI? Which graphics card and driver versions do you have?

**Comment by woodpile72** [comment]
I think I figured this one out and it might be unrelated to MaxTo.  I was daisy chaining 2 monitors with display port without having maxto loaded and still had the problem - same as having maxto enabled on one giant monitor.  What happens is that Win7 sees the windows as being out of a legit screen region when returning from sleep and moves them into a spot it knows it ok.  Seems the same behavior happens in both configurations, so maybe with maxto loaded, windows returns from sleep too fast for maxto to establish itself and starts moving things.  With the 2 monitor configuration, when I switched from daisy chaining them to doing real dual-head, the problem went away.  Never got it to go away with maxto and larger monitor.  Make sense?  COuld all be bullshit, but I have found the pattern and fixed it without maxto - maybe it helps you fix it with maxto.

**Comment by vegardlarsen** [comment]
I suspect you may be onto something, and it matches what I have believed to be the cause of this. I think Windows (or the video driver) somehow disconnects the monitor for a short time when suspending or resuming. That would lead Windows to rearrange the windows onto the monitors that are left active.

With daisy chaining, I believe the outer monitor will most likely be disconnected from Windows whenever the inner monitor is turned off.

Now, if I could just figure out if MaxTo somehow causes this, I'd be happy... :)

**Comment by vegardlarsen** [comment]
Can someone please try if this is still the case with the preview versions? See #220 for details on those.

I do not have a machine which exhibits these symptoms, so I am relying on your help here.

**Comment by hensm** [comment]
@vegardlarsen Still happening on 2.0.0-alpha3.

**Comment by vegardlarsen** [comment]
OK then. Looks like I still have some work left. :)

**Comment by jglazer63** [comment]
I will give it a shot.   Although I don’t know how I can try to make it happen.  It only occurred sporadically.

**Comment by jglazer63** [comment]
I tried the preview (alpha) version install but could not get past the license screen.  I entered my license key but the REGISTER button would not work.

**Comment by vegardlarsen** [comment]
@jglazer63 Please read the release notes in #220 thoroughly. You need to exchange your old license key for a new one to try out the previews.
