### ISSUE TITLE
Feature Request - Dynamic region/window resizing

### ISSUE THREAD

**Issue by hensm** [digitalcreations/MaxTo#117]
Being able to hold down a hotkey, resize a window in a region and have the surrounding regions/windows adapt accordingly. Something in the same vein as this:
![wcFF1io.gif](https://i.imgur.com/wcFF1io.gif).

Not sure how difficult this would be, though I'd find it tremendously useful. Excellent software in any case, don't think I'd be able to live without it now. [Got my license](https://i.imgur.com/mkgrUrk.png) a few days after starting the trial.

**Comment by reidrankin** [comment]
Seconded! Really missing this as it's standard for Aero Snap with the Threshold 2 update for Windows 10.

**Comment by vegardlarsen** [comment]
Without saying too much, I have been looking at prototyping this. :)

**Comment by thewavelength** [comment]
Also emphasizing on this request.

**Comment by thewavelength** [comment]
Hi, I think you've activated the gh-actions bot without prior warning and now it closed this issue. I'd like to put back attention to this one to avoid it going missing.

**Comment by vegardlarsen** [comment]
@thewavelength You are right. The bot was a bit quicker than anticipated, it is set to mark as stale after 30 days, and then close 5 days afterwards; but with older issues it got a bit trigger-happy. :)

However, I am keeping this closed, for a few reasons. We want to keep the list of issues "clean", i.e. only issues we have an intention on fixing. We are putting a separate tag on ideas (which I just did here), but will still be closing them. Periodically we will go back and revisit them, and perhaps re-open and assign them to a milestone.

Now, I have a few hours of going through issues the bot closed ahead of me :)
