### ISSUE TITLE
Window Snap Region Edges

### ISSUE THREAD

**Issue by shiift** [digitalcreations/MaxTo#118]
I can drag and snap to monitor edges and window edges just fine, but when I select "Region edges (main regions only)" it does not seem to recognize the main regions. I have tried this with both only the Region edges box checked and with combinations of them checked. If there is a way to reset the program I would love to know because it's possible that it was working yesterday when I installed the program and broke at some point when I was changing settings.

I am running windows 10.

**Comment by vegardlarsen** [comment]
I apologize for my slow response time. What happens to that same window if you maximize it? Does it get placed in a region?

You can try restarting MaxTo, or restarting your computer. Sometimes a full reboot is required because of the way MaxTo hooks into Windows.

**Comment by shiift** [comment]
If I maximize the window it gets placed in the closest region. Restarting the computer does not seem to change anything.

**Comment by vegardlarsen** [comment]
It seems this is reproducible on my machine. I will have a go at fixing it for the next release. Thank you for reporting it!

**Comment by reidrankin** [comment]
I too have this issue and am running Windows 10. It also used to work for me, but now I've noticed that it does not. Not a lot of new info here, but perhaps suggestive of an interaction with a recent windows update?

My windows install started at vanilla Threshold 2 (so it was fine under that) and the latest cumulative update is KB3124200 on 12/22/2015. I'm sure it was happening by that time, so if it was an update there's at least somewhere to start.

**Comment by miked-mellanox** [comment]
issue still happens on latest version.

**Comment by vegardlarsen** [comment]
@miked-mellanox With version 2.0.0-rc.1? Or 2017.07?

**Comment by miked-mellanox** [comment]
2.0.0-rc1
