### ISSUE TITLE
Hot Key Request: Move to next monitor, but not to a region

### ISSUE THREAD

**Issue by mkizer** [digitalcreations/MaxTo#120]
For multi-monitor setups.
Currently, in Win7 the Win+Arrow Left/Right will move a window first to the edge of the current monitor, then to the edge of the next monitor, then to its original size/position on the next monitor. It would be nice to have a hot key that would simply move window to the next monitor, but not into a specific region.

Example: You have a small window centered that you wish to move to the next monitor, but not into one of the defined regions. The normal Win+Arrow key will take three presses to get it to the center of the next monitor. Perhaps something like Win+[Numpad] 0

Thanks.

**Comment by vegardlarsen** [comment]
That does make sense, but we are rapidly running out of possible keyboard shortcuts. We've already had to relegate our keyboard shortcuts to the numpad (which some machines simply does not have). I am assuming your suggestion means that Win+0 would move it one monitor to the right and cycle around?

**Comment by mkizer** [comment]
Yes, cycling around would work or you could use Win+[numpad] 1 to go left
and Win+[numpad] 3 to go right. You could also use some modifier on the the
existing numpad arrows (4 & 6), but it might start getting ridiculous
trying to type Win+Ctrl+Shift+[numpad] 4. ;-)

~Michael Kizer
http://MichaelKizer.com

**Comment by thewavelength** [comment]
I'd like to call attention on this one again. It might be something for 2.x as now as users we can select hotkeys on our own.

**Comment by thewavelength** [comment]
Hi, I think you've activated the gh-actions bot without prior warning and now it closed this issue. I'd like to put back attention to this one to avoid it going missing.
