### ISSUE TITLE
Support having regions spanning displays

### ISSUE THREAD

**Issue by pmurfitt** [digitalcreations/MaxTo#121]
Apologies if this is supported but I couldn't work out how. I have triple 2560x1440 displays in portrait mode - there are some cases where I would like to have a region in my alternate layout to be completely over the middle display and also slightly over the left and right displays.

If we could have a way to configure a region to be anywhere in the total display canvas and not just restricted to a single display that would be awesome!

**Comment by vegardlarsen** [comment]
@pmurfitt  I also think this would be a nice feature, but we would have to come up with a brand new way of defining the regions. Any suggestions here are welcome. Remember you have to take into account that the total display surface is not a rectangle... :)

**Comment by vegardlarsen** [comment]
I am closing this issue as it seems to be a lot more work than what the outcome is worth. Feel free to comment if you disagree... :)
