### ISSUE TITLE
Blacklist of programs

### ISSUE THREAD

**Issue by CharlieEriksen** [digitalcreations/MaxTo#125]
Hi,

I was wondering if it'd be possible to maybe add a small feature to MaxTo, which allows you to blacklist certain executables from being affected by MaxTo? For instance, I may want to have my remote desktop client, video games that are in windowed mode, etc. not be affected by MaxTo. 

Would that be viable?

Thanks for a great tool!

**Comment by vegardlarsen** [comment]
Hi Charlie, this already exists and you may not want to use it. :)

Inside the MaxTo folder there is an XML file, called shims.xml. You can edit this file to add programs to the ignore list (anything under the `<ignore>` tag is ignored as best can by MaxTo). After editing this file, you have to restart MaxTo for the changes to take effect.

If you want to temporarily deactivate MaxTo, you can simply hold Shift when maximizing the window. That would probably be easier for you. Or, you can assign a shortcut key to toggle MaxTo's active or passive mode (in passive mode windows maximize normally until you hold Shift).

I believe those will be better suited for your use, but that is clearly up to you to decide... :)

**Comment by CharlieEriksen** [comment]
Hi Vegard,

I have been using the shift key fairly extensively, but I was wondering if there wasn't an easier way, so I don't have to press it every time I deal with rdp/a game. 

In regards to the shims.xml/ignore list, is there a reason why I wouldn't want to use it? :-)

Thanks for the very quick response!

**Comment by vegardlarsen** [comment]
Basically because I believe the other ways are easier, but feel free. Know that the shims.xml can be overwritten when you upgrade to the next version, so it is a good idea to back it up and take note of the things you add to it. It wasn't really designed to be user-extensible, but I may be fixing that in a future release.
