### ISSUE TITLE
Unattended Installer

### ISSUE THREAD

**Issue by JSmatt** [digitalcreations/MaxTo#126]
From running the setup with /? I can see that "/exenoui" should do an unattended automatic installation. However when I run with this switch the installer just loads the ui normally and sits there waiting for user input.

How can I do an unattended admin installation?

Thanks!

**Comment by vegardlarsen** [comment]
Unfortunately we do not officially support unattended installation. Those instructions are basically defaults from the installation system we are using.

As far as I can tell there shouldn't be anything in the way of doing it unattended (we are not doing anything special), but it may be that it needs to download the .NET Framework, which can take a while.

If I am not mistaken you can extract the MSI using `MaxToSetup.exe /e MaxToSetup.msi` and use standard MSI tools to do the installation. I am not familiar enough with MSIs to know if this will include the .NET Framework, but if it doesn't, you'll need version 4.5.2 of that in addition to MaxTo's setup.
