### ISSUE TITLE
Possible minor issue with triple monitors

### ISSUE THREAD

**Issue by mkizer** [digitalcreations/MaxTo#128]
I have a pieced together triple monitor setup at work. Left to right: 
(1) Portrait 16:9 | (2) Landscape 16:9 | (3) 4:3

Occasionally on startup, monitor 3 will load the alternate region layout (split horizontal) instead of main (no splits). The other two monitors load the main region layouts just fine. I can verify this by moving windows to monitor 3 or by looking at the Highlight Regions->Main.

If I then go into Change Regions, I see that all three monitors have the correct region layouts for main.
I click Done (without making any changes), and now the monitor 3 has the correct region layout for main.

Not really a huge issue, just a little annoying. Let me know if you need any more information.
Thanks.

**Comment by vegardlarsen** [comment]
Thanks for reporting this. I have no idea what may cause this behavior.

I have a similar setup at my office, so if you could send me the `user.config` file from `%LocalAppData%\Digital_Creations_AS\MaxTo.exe_<some more stuff>\<version>` I can try loading it on my machine when I get a chance to debug this (you can paste it in a code block here if you want).

A few control questions:

1. Are you certain that the alternate regions are loaded? It would be easier to understand if it simply loaded blank regions.
2. Are any of your monitors high-DPI monitors?
3. Which version of Windows are you running? Win+R, type `winver` to get complete version information.

**Comment by mkizer** [comment]
1. The alternate region for monitor 3 always loads. It is a horizontal
split. My main region for that monitor is no split, and I've tried saving a
profile for it. It always shows up correctly in Change Regions, but not in
Highlight Regions.
2. I don't believe so.
3. Windows 7 Enterprise version 6.1 (Build 7601: SP 1)

Thanks,

~Michael Kizer
http://MichaelKizer.com

**Comment by vegardlarsen** [comment]
This issue should no longer be present in the 2.0.0 preview releases. See details in #220 about how to try them out on your machine.
