### ISSUE TITLE
Close Pop-up Windows Crashes Program

### ISSUE THREAD

**Issue by itrumsey** [digitalcreations/MaxTo#130]
Hi,

I'm using the MiiCollab Client (think Skype) for phones and when I get a call, it creates an additional pop up window. If that new window is on the other region, both windows close/crash. If it's in the same region, it closes normally.

**Comment by vegardlarsen** [comment]
That sounds extremely strange. You could add a shim to stop MaxTo touching this application, which should resolve the problem if it is indeed MaxTo's fault.

Open the `shims.xml` file in `C:\Program Files\MaxTo` in your favorite text editor, and add a line under the `<nosubclass>` node, like `<process>miicollab</process>`. The name of the process needs to match the executable name for the MiiCollab Client, which you can find in Task Manager. Simply remove the `.exe` ending and that is the name you put in the shims file.

Please let me know if this works and what the name of the executable is, and I can include it by default in the next release.

**Comment by itrumsey** [comment]
Hi Vegard,

That seems to have worked! The MiiCollab executable is called “UCA”, below is the line I entered:



    <process title="uca">uca</process>

Could that be added into the main build? Also, for any other computers with this problem, would I be able to copy and paste the shims file over the old ones?

Myles Adams |Jr Network Administrator| Rumsey Electric
Office: 610-832-9145 | Fax: 610-941-8183
visit us @ www.rumsey.com<http://www.rumsey.com/>
[Description: Description: facebook_button]<http://www.facebook.com/#!/pages/Rumsey-Electric/129663577049040>[Description: Description: cid:image002.jpg@01CC5829.E759D7B0]<http://www.linkedin.com/company/rumsey-electric-co.> [Description: Description: http://www.iconarchive.com/icons/fasticon/web-2/256/Twitter-icon.png] <http://twitter.com/#!/RumseyElectric>

**Comment by vegardlarsen** [comment]
Awesome, I'll make sure that this is included in the next release. You should be able to copy the shims file across, yes, but it will be overwritten by any new installs.

**Comment by vegardlarsen** [comment]
Does this still crash in the preview releases we just put up? We have made some changes (in 2.0.0-alpha.3) as to how this functionality works, and it should hopefully reduce these kinds of crashes. See #220 for details about the preview releases.
