### ISSUE TITLE
Issues with Itunes

### ISSUE THREAD

**Issue by scoleman81** [digitalcreations/MaxTo#131]
Itunes Crashes whenever Maximizing in a region.

**Comment by cheshyrp** [comment]
Confirmed. And what's this about an anniversary edition of MaxTo? There have been no updates since last year. 15.11 is the latest release.

**Comment by vegardlarsen** [comment]
@scoleman81 Is `itunes` and `ituneshelper` listed in your `shims.xml` file inside the MaxTo installation folder?

@cheshyrp There is no "anniversary edition" of MaxTo. I don't know exactly where you have that from, but it may be a reference to the Windows 10 Anniversary Update, which is an update of Windows, not of MaxTo.

**Comment by cheshyrp** [comment]
@vegardlarsen My apologies. On another thread you mentioned the "big anniversary update" and I assumed you were talking about MaxTo; not Windows 10. *blush*

**Comment by vegardlarsen** [comment]
Ah, well, there is a big update to MaxTo coming, but I don't think I have ever called it an anniversary update. :) 

Hopefully I will have more time for MaxTo going forward, as we recently hired another developer who will be taking over some of my day-to-day projects that have been taking up a lot of time.
