### ISSUE TITLE
Next / Previous Window in Region is in a world of it's own

### ISSUE THREAD

**Issue by BranicYeti** [digitalcreations/MaxTo#137]
Some basic system information:
- Windows 10
- MaxTo 2015.11.1.0

NWR = The function known as "Next Window in Region"
PWR = The function known as "Previous Window in Region"
NPWR = Both NWR and PWR together

Since I just downloaded MaxTo, I was playing around with features and their hotkeys so I could learn how to use it and configure it to how I like. Whilst configuring NPWR, I found a few small issues:

**Display Not Region**
When editing regions, the default behaviour is that the entire display is the only region. I have 2 regions on my primary monitor, but didn't change my secondary monitor, since I use it in landscape for writing code. I haven't tested on my primary monitor, but NPWR does not work on my secondary monitor, presumably because it is recognising the default 1 region as 0 regions, and assuming there is nothing to cycle over. This isn't a major issue, I just expected NPWR to work as normal*. In order to get around this, I simply added the smallest possible region at the bottom of my monitor and aligned everything to the top one.

**Multiple Hotkey Presses**
Some applications (list below) require the hotkey to be pressed twice**. This does not effect all of these applications all of the time. Currently on my secondary monitor, I have 2 of the 3 listed applications open and it's working flawlessly. However earlier, I had multiple combinations of the listed applications open over both monitors and was getting the problems. The behaviour of NPWR differs slightly between NWR and PWR.

Infected Application = Application currently going through what the bug is explaining.

_NWR_
For NWR, when cycling _from_ an infected application, the first hotkey press appears to unfocus the application whilst leaving it open on the display, and the second hotkey press cycles to the next application as expected.

_PWR_
For PWR, the inverse is true. When cycling _to_ an infected application, the first hotkey press appears to cycle to an unfocused instance of the application whilst leaving the "previous" application visible on the display. The second hotkey press cycles to the infected application as expected.
- [Google Chrome for Work***, 64-bit, 50.0.2661.87](https://www.google.co.uk/work/chrome/browser/)
- [Sublime Text 3, 64-bit, Build 3103](https://www.sublimetext.com/3)
- [Viber, 32-bit, 6.0.1](https://www.viber.com/en/)

![multiple-hotkey-presses](https://cloud.githubusercontent.com/assets/1971818/14795520/c63f4e5c-0b20-11e6-887e-21a3c22b1bed.gif)

The above gif is to demonstrate what is going on when trying to cycle through applications. When you see the top bar go white, that is when it has attempted to cycle to the next application, however as you can see from the taskbar, it hasn't.

**Fit Windows into Closest Regions**

As the title might suggest, this bug may not be relevant to NPWR, however it is how I found it. When I press the hotkey assigned to fitting windows to regions, everything looks like it should on my monitors, however NPWR doesn't seem to recognise (all of) the windows in the region. I am currently unable to reproduce this, so will keep my eye on things and if it is an actual issue, create another report for it. This is just a little reminder to myself.

**Breaking From the Region**

When using NPWR on my primary monitor, it breaks out of the region. The only clue I have is that during cycling, the "Show Hidden Items" tooltip pops up on my taskbar, so I assume it's also cycling through those hidden items. According to the application icons on the taskbar, it stays on the "previous" application until doing the full cycle back to the beginning.

When using NPWR on the larger of 2 regions, it cycles between the windows in that region as well as the ghost applications. However on the smaller of the 2 regions, it breaks into the larger region and stays there, ignoring the smaller region altogether. There is only 1 window open in the smaller region.
## 

|  | Footnotes |
| --- | --- |
| * | By normal, I mean working as intended by the developer, not working as it currently does on my system. |
| ** | In my testing, it appears be twice, however I can't be sure that it's dependent on something in particular and therefore more for other people. |
| *** | This bug doesn't apply to every open instance of Chrome, only to a select 1 or 2, if any. It also seems to change which instances of Chrome this affects between restarts of MaxTo. |

**Comment by vegardlarsen** [comment]
Thank you for this very detailed report.

- When a region covers an entire display, MaxTo basically ignores whatever happens inside that rectangle. This also means that NPWR won't work, because NPWR works by looking at the window and seeing which region it is in. On a full display, it won't be in a region. I will fix this.

- Multiple hotkey presses; what probably happens when you press the hotkey the first time, is that the next window is focused, but it is not put in the foreground. I don't know what causes this.

Do you have any other software running that may be interfering with MaxTo? Anything that interacts with other programs in the same manner as MaxTo does?

**Comment by BranicYeti** [comment]
Judging by the taskbar that shows which program is selected, it's not focusing the next window, but that could be graphical I guess. Nothing that interacts with open windows like MaxTo does, but these are the ones that aren't necessarily standard:
- A couple of cloud drive apps (iCloud, OneDrive, etc)
- [ShareX](https://getsharex.com/) - Comprehensive screenshot application which can create images of just a window, but it doesn't edit anything. [Git](https://github.com/ShareX/ShareX)
- Nvidia GeForce Experience for my GPU. GPU is only powering 1 of 2 displays, and the bug was present on both, so I assume this isn't involved.
- TeamViewer

Also regularly open:
- Spotify
- Telegram
- Viber
- HipChat
- Logitech software for my headset

I did install [AquaSnap](http://www.nurgo-software.com/products/aquasnap) before MaxTo, but since it didn't have the features I was looking for, I killed the process and prevented it from starting with Windows. Absolutely certain it isn't running, and looking at Task Manager, doesn't look like any sister / helper applications are running.

**Comment by vegardlarsen** [comment]
Considering we haven't had support for Next / Previous Window in Region since version 2.0 was launched, I am closing this issue as it is no longer relevant.
