### ISSUE TITLE
Automatically select Regions profile depending on the connected monitors

### ISSUE THREAD

**Issue by papadi** [digitalcreations/MaxTo#140]
It would be great if Regions profile is automatically select when I connect my desktop monitor to my laptop. When the monitor isn't connected and I'm using my laptop monitor, I would like a different profile to be selected automatically.

**Comment by vegardlarsen** [comment]
This is a feature that will be coming in a future version of MaxTo. At the moment the loaded profile follows the monitor number, in the future it will follow something like the serial number of the monitor.

I am closing this issue, as this is already being worked on.
