### ISSUE TITLE
Support for overlapping regions in layouts

### ISSUE THREAD

**Issue by Robbson** [digitalcreations/MaxTo#142]
Coming from the discontinued WinSplit Revolution application (their original domain now points to maxto.net) I basically like the feature set of MaxTo, especially the Windows 10 compatibility.

But WinSplit Revolution had a feature that I miss here terribly: Overlapping windows! I always use tools that don't fit in the grid layout very well so I need to give them more space. Sometimes it's the app on the left side, sometimes the one on the right side, this can change from one second to another depending on their own content. And there are also apps which work best in the center of the screen or just horizontally centered but aligned to the top screen border.

The only way to achieve this in MaxTo is to waste the second regions layout but it just barely fits for one of the scenarios from above. And exporting/importing layouts is too time consuming, especially when required each minute or so.

All those scenarios could be handled in one single layout configuration in WinSplit Revolution. Also their impressive keyboard shortcuts allowed switching windows to all alternative region sizes just by pressing the direction on the Numpad keys again. MaxTo on the other hand just rotates the regions.

**Comment by Robbson** [comment]
Btw. this could be done without changing the current easy to use layout editor by allowing multiple layers of layouts merged into a single one.

The numeric (percentage) approach in WinSplit Revolution is probably not everybody's taste even though it has a nice preview.

I have seen this layering of layouts approach in another tool but unfortunately it doesn't support customizing the size of those regions. ;-)

**Comment by vegardlarsen** [comment]
Hi @Robbson, and thanks for getting in touch. In the future MaxTo will support multiple layers of regions, exactly as you suggest.

The approach will be one of the following:

- Toggling between each layer using a keyboard shortcut, and using shortcuts to move around. This has the advantage of working with the mouse.
- Moving around with shortcut keys picks the closest region from all the layers, acting as if they were merged. This would not work as well with the mouse.
- Some combination of the above, where a layer is selected for mouse operations, but they are merged for keyboard operations.

If you have any suggestions for this would work optimally for you, I would love to hear them.

**Comment by vegardlarsen** [comment]
After quite a bit of work on this; I dropped the "multiple layers" thinking here, and instead went for "load presets very quickly". In the preview releases of MaxTo, you can now assign a keyboard shortcut to load a specific preset (on the current monitor or on a specific named monitor), and move a window into the regions that were created (as a consequence of the same keyboard shortcut).

I know this doesn't quite solve your issue about overlapping windows, but I am thinking about other ways this can be done.

I am closing this issue because it is quite clear that it won't happen in the manner in which you described above, but know that we are looking at other solutions that you may find satisfactory.

**Comment by treybrisbane** [comment]
I came here looking for this feature. I'm sad to hear it's no longer being worked on. 😢

My usecase for overlapping regions is essentially the following region configuration:

- One region that encompasses the entire screen (could simply use "maximize" for this)
- Four regions to divide my screen into quaters
- Three regions to divide my screen vertically into thirds
- Two regions to divide my screen vertically in half
- Two regions to divide my screen horizontally in half
- One small-medium sized region in the center of my screen (used to center a window; could be replaced by a "drag to small area in center of screen to center window" feature)

Admittedly I haven't tried MaxTo, but from what I can tell from screenshots etc, there's currently no way to represent such a configuration.

**Comment by treybrisbane** [comment]
For what it's worth, if you were to ever return to the "layers of regions" approach, I think my ideal UX would be something like the following.

### For mouse
While dragging a window to preview its location, scrolling up or down with the scroll wheel would select a new region layer (having the window location preview update accordingly).

### For keyboard
Two types of shortcut; absolute (i.e. "move to this exact region") and relative (i.e. "move left to the next region").

#### Absolute
Absolute shortcuts would basically be two-stage keyboard shortcuts. The first key-combo would select region layer, then the second key-combo would select region within that layer.
E.g. `Ctrl+Win+1, Ctrl+Win+Num7` to select, from the first layer, the top-left region.

#### Relative
Relative shortcuts would be something like `Ctrl+Win+[Direction]` that would select the region that:
- Is closest to the current window in terms of the distance between their center-points, and
- Is closest to the current window in terms of the difference between the angle between their center-points, and the angle of the specified direction, and
- Is in the highest layer less than (if moving away from screen center), or lowest layer greater than (if moving towards screen center), the layer of the region the window currently occupies

No idea if any of that is helpful, but I figured I'd throw it here in case it was. 🙂

**Comment by vegardlarsen** [comment]
Take a look at the [2.1 previews](https://maxto.net/en/release/alpha). We've added a few things that I think will make this easier, if not exactly what you want:

1. Support for WinSplit Revolution-style keyboard shortcuts, letting you quickly move an application to a specific position. Basically what you specify as absolute keyboard shortcuts above. These are customizable. Keyboard shortcuts are Ctrl+Alt+NumPad1-9.
2. Two new commands; "Expand" and "Contract" window in direction, which will expand a window to the closest edge in that direction. You can set this to either find the closest window edge, region edge or monitor edge, to quickly enlarge a window to span multiple regions. We haven't assigned default shortcuts to these yet.

I hope that helps.
