### ISSUE TITLE
not work with Acrobat Reader DC

### ISSUE THREAD

**Issue by Hilde25** [digitalcreations/MaxTo#144]
Hi,
the Version 2015.11.1.0 not work with the software Acrobat Reader DC.
The press of the MAX button does nothing
Win10 64bit
Frank

**Comment by vegardlarsen** [comment]
This is not a bug. Acrobat Reader is strange; and MaxTo's functionality has been disabled for it. You can read more about this [here](https://maxto.net/shim/Details/acrobat_reader).

I am assuming that you meant that the maximize button maximize to the screen, not to one of MaxTo's regions.
