### ISSUE TITLE
Keyboard shortcuts don't work - need to reopen

### ISSUE THREAD

**Issue by Volvorocks** [digitalcreations/MaxTo#145]
Hi Vegard, I have been unable to use my keyboard to move windows like I have in the past. I see issue 124 was closed. I tried using the numpad keys but they don't work either. I watched you video and none of this works for me. This has been broke for a while - I just haven't had time to report it. I should mention I am running Windows 10 pro on a surface 3 running a 50" 4K TV. Thanks Vegard

**Comment by vegardlarsen** [comment]
@Volvorocks Did you go into MaxTo's settings and try to reset to the defaults? Note that the keyboard shortcuts did change with Windows 10, since Microsoft "stole" our shortcuts for the virtual desktops feature.

Also, when using the numpad, are you sure NumLock is on?

**Comment by Volvorocks** [comment]
Thanks for the quick reply.

When you say reset defaults, I see to places where I can do that – Actually one that works I think.

In Options/Hotkeys, you have an edit hotkey function that is never enabled – it just states none is light grey text and the default button is the same.
In Options/Windows features, there is also a defaults button but nothing happens when I click on it.
When I run options/Diagnostics/Run self-test, the keyboard shortcuts never get the checkmark that they used to get. Also, I only get checks on system hook Elevated 32 and 64 bit.

Yes, the numlock is enabled. I have a popup whenever I toggle the numlock key.
Could I have something disabled without knowing about it?

Thanks again
Kev

**Comment by Volvorocks** [comment]
I should also note that I uninstalled MaxTo, went to your site and downloaded the latest release and reinstalled. Even created a new profile re regions but still nothing re keyboard shortcuts.

From: Kevin Raymond
Sent: Friday, July 8, 2016 10:34 AM
To: 'digitalcreations/MaxTo' <reply@reply.github.com>; digitalcreations/MaxTo <MaxTo@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [digitalcreations/MaxTo] Keyboard shortcuts don't work - need to reopen (#145)

Thanks for the quick reply.

When you say reset defaults, I see to places where I can do that – Actually one that works I think.

In Options/Hotkeys, you have an edit hotkey function that is never enabled – it just states none is light grey text and the default button is the same.
In Options/Windows features, there is also a defaults button but nothing happens when I click on it.
When I run options/Diagnostics/Run self-test, the keyboard shortcuts never get the checkmark that they used to get. Also, I only get checks on system hook Elevated 32 and 64 bit.

Yes, the numlock is enabled. I have a popup whenever I toggle the numlock key.
Could I have something disabled without knowing about it?

Thanks again
Kev

**Comment by vegardlarsen** [comment]
Hi Kev,

Whenever you select a shortcut you should be able to reset it to its defaults, like this:

![image](https://cloud.githubusercontent.com/assets/436508/16721763/0c043d00-4742-11e6-94c6-db225fdfb3fc.png)

There is currently no "reset all" functionality, unfortunately.

In some specific cases a reboot of the machine will solve these issues, as MaxTo integrates so closely with Windows that if something goes wrong it may get "stuck" until Windows is rebooted.

**Comment by Volvorocks** [comment]
Works like a charm. Sorry to bother you about stuff like this. Have a good one.
Kev

**Comment by vegardlarsen** [comment]
No problem! :) Did you have to reboot or was defaulting enough?

**Comment by Volvorocks** [comment]
Defaulting was enough Vegard.

**Comment by shanegray** [comment]
This doesn't always work for me. Need to exit and restart MaxTo or Windows
