### ISSUE TITLE
License not working

### ISSUE THREAD

**Issue by arshadfarooqui** [digitalcreations/MaxTo#146]
Hi,

I have just now purchased Maxto License for windows 10 machine. Maxto only works on the admin user account. when logged in as standard user, it asks for license and does not accept the license key used for initial activation

**Comment by pinkie2003** [comment]
I am an administrator of my Windows 10 Pro machine but the software also will not accept the license information I have just purchased. Whats going on guys?

**Comment by vegardlarsen** [comment]
@pinkie2003 Please contact us at the support e-mail address with your registration information and the error message you are experiencing and we will provide a solution.
