### ISSUE TITLE
Main Regions Not Loading On Start

### ISSUE THREAD

**Issue by deto** [digitalcreations/MaxTo#147]
I have two monitors.  On my primary monitor, my Main region set just has a single region for the whole monitor.

However, when I first launch MaxTo, the regions are defined as being split vertically in the middle.  Maximization indicates this as well as doing the "highlight regions >> main" command.

However, if I go to "Change regions >> main", the correct regions are shown (just one fullscreen region on that monitor).  Then, if I exit using "Done", the regions are saved, and function correctly.

**Comment by vegardlarsen** [comment]
This sure does sound like a bug.

- Which version of MaxTo are you running?
- Which version of Windows are you running?

Could you paste the contents of your `user.config` file (found in `%LocalAppData%\Digital_Creations_AS\MaxTo.exe_<gibberish>\<version>`) here?

**Comment by deto** [comment]
Windows Version:  1607 (OS Build 14393.10)
MaxTo Version: 2015.11.1.0

user.config:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="MaxTo.UserSettings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <MaxTo.UserSettings>
            <setting name="LastVersionRun" serializeAs="String">
                <value>2015.11.1.0</value>
            </setting>
            <setting name="FirstRunTime" serializeAs="String">
                <value>08/04/2016 19:10:32</value>
            </setting>
            <setting name="RegionConfiguration" serializeAs="Xml">
                <value>
                    <RegionConfiguration>
                        <Monitor Name="\\.\DISPLAY2" Primary="true">
                            <Region IsSplit="false" />
                        </Monitor>
                        <Monitor Name="\\.\DISPLAY1">
                            <Region IsSplit="true" Orientation="Horizontal" SplitterDistance="0.38563829787234">
                                <Region IsSplit="false" Placement="1" />
                                <Region IsSplit="false" Placement="2" />
                            </Region>
                        </Monitor>
                    </RegionConfiguration>
                </value>
            </setting>
            <setting name="AlternativeRegionConfiguration" serializeAs="Xml">
                <value>
                    <RegionConfiguration>
                        <Monitor Name="\\.\DISPLAY2" Primary="true">
                            <Region IsSplit="true" Orientation="Vertical" SplitterDistance="0.5">
                                <Region IsSplit="false" Placement="1" />
                                <Region IsSplit="false" Placement="2" />
                            </Region>
                        </Monitor>
                        <Monitor Name="\\.\DISPLAY1">
                            <Region IsSplit="true" Orientation="Horizontal" SplitterDistance="0.331914893617021">
                                <Region IsSplit="false" Placement="1" />
                                <Region IsSplit="true" Orientation="Horizontal" SplitterDistance="0.4976"
                                    Placement="2">
                                    <Region IsSplit="false" Placement="1" />
                                    <Region IsSplit="false" Placement="2" />
                                </Region>
                            </Region>
                        </Monitor>
                    </RegionConfiguration>
                </value>
            </setting>
            <setting name="HotkeyActions" serializeAs="Xml">
                <value>
                    <ArrayOfHotkeyAction xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                        <HotkeyAction>
                            <Hotkey>NumPad4</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveLeftMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad8</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveUpMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad6</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveRightMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad2</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MoveDownMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad4</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapLeftMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad8</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapUpMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad6</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapRightMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad2</Hotkey>
                            <HotkeyModifierValue>10</HotkeyModifierValue>
                            <UniqueId>SwapDownMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad4</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveLeftAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad8</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveUpAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad6</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveRightAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad2</Hotkey>
                            <HotkeyModifierValue>9</HotkeyModifierValue>
                            <UniqueId>MoveDownAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>NumPad9</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>MaximizeToScreen</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>ToggleMode</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>ChangeRegionsMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>ChangeRegionsAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>HighlightRegionsMain</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>HighlightRegionsAlternate</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>Next</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>TaskSwitchRegionNext</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>Prior</Hotkey>
                            <HotkeyModifierValue>8</HotkeyModifierValue>
                            <UniqueId>TaskSwitchRegionPrevious</UniqueId>
                        </HotkeyAction>
                        <HotkeyAction>
                            <Hotkey>None</Hotkey>
                            <HotkeyModifierValue>0</HotkeyModifierValue>
                            <UniqueId>FitAllWindows</UniqueId>
                        </HotkeyAction>
                    </ArrayOfHotkeyAction>
                </value>
            </setting>
            <setting name="UserProfiles" serializeAs="Xml">
                <value>
                    <Profiles>
                        <MonitorProfile ProfileName="p1" GUID="1027c769-0093-410e-9ae4-6a5e68fd2602">
                            <Region IsSplit="false" />
                        </MonitorProfile>
                        <MonitorProfile ProfileName="p2" GUID="62508839-8a7b-48a5-96bf-0940b2ea5e9d">
                            <Region IsSplit="true" Orientation="Horizontal" SplitterDistance="0.38563829787234">
                                <Region IsSplit="false" Placement="1" />
                                <Region IsSplit="false" Placement="2" />
                            </Region>
                        </MonitorProfile>
                    </Profiles>
                </value>
            </setting>
        </MaxTo.UserSettings>
    </userSettings>
</configuration>
`

**Comment by vegardlarsen** [comment]
Thank you. There does not seem to be anything wrong with your configuration either, so I am will be looking at this before the release of the next version.

**Comment by deto** [comment]
I think I was able to find out a bit more on this.  Apparently, what's
happening is that the regions for the Alternate configuration are being
loaded as the Main regions on startup.  However, if I go to "Change Regions
>> Main" the correct Main regions are shown, and clicking "Done" fixes it.
I verified this by changing the splits in my Alternate regions,and
restarting MaxTo to see that they had been loaded as the Main regions.
This is only happening on my #2 monitor (identified as #2 in the Windows
display settings dialog).

**Comment by killroy42** [comment]
I have a problem that might be related. My "secondary" monitor seems to reset to a single region on both main and alternate when I reboot. The "primary" monitor seems to remember the setting, though.

**Comment by vegardlarsen** [comment]
@killroy42 This is probably not related. I think your issue is caused by your secondary monitor "detaching" (probably because of how your video driver works) whenever Windows either goes to sleep or shuts down.

**Comment by vegardlarsen** [comment]
@deto I have just identified and fixed this issue. It happened on the primary monitor when the alternative regions was divided into more regions than the main region.

We are waiting for an update to Advanced Installer before we can deploy this.

If you want to try this out as a "pre-release" you can download and unzip these files over your existing MaxTo installation. For it to run, you will need to install the following dependencies:

- [.NET Framework 4.7](https://www.microsoft.com/en-us/download/details.aspx?id=55170)
- [Visual C++ Redistributable for Visual Studio 2017 x64](https://go.microsoft.com/fwlink/?LinkId=746572)
- [Visual C++ Redistributable for Visual Studio 2017 x86](https://go.microsoft.com/fwlink/?LinkId=746571)

[AlternativeRegionsBugFix.zip](https://github.com/digitalcreations/MaxTo/files/979184/AlternativeRegionsBugFix.zip)

**Comment by killroy42** [comment]
Well, after rebooting I still had to load my main profile twice and my alternate once to get it up and running. And some process crashed on start up. I'll check on next boot up and driver update if it repeats again.
