### ISSUE TITLE
MaxTo: An unknown error occured during validation. No reaction from MaxTo support

### ISSUE THREAD

**Issue by peterproducts** [digitalcreations/MaxTo#155]
I have ordered a MaxTo license and have entered the registration form. A green sign appeares, so the user name and registration code seem to be OK. The validation fails and an error message eappears.

I have contacted MaxTo support more than one, and also Digital Creations AS (Vegard Andreas Larsen), but without any reaction or support. My trial license will stop today, I have paid 19 dollars, but no working license... 

I like the MaxTo product very much on my 4K 40 inch monitor, but I am very disappointed right now.

Can anyone help? Maybe the problem is occured by de &-sign in my username (P.B. Software & Internet).

Kindly regards,

Peter

![maxto1](https://cloud.githubusercontent.com/assets/23093418/19757604/17d11e46-9c24-11e6-9156-020ce7662c6e.jpg)
![maxto2](https://cloud.githubusercontent.com/assets/23093418/19757610/1ce12318-9c24-11e6-95cb-067a6e080da9.jpg)

**Comment by vegardlarsen** [comment]
Peter, please contact us via the support e-mail address in the about screen, and I will fix this for you.
