### ISSUE TITLE
Hotkey for Profile Switching

### ISSUE THREAD

**Issue by pixelarbeit** [digitalcreations/MaxTo#156]
It would be great to go through all layout profiles with a hotkey, so I can change the layout quickly.
At the moment, I am faster resizing all my windows manually than changing the profile and assigning the windows. This would be great for work where I have different workspaces.

Is there a possibility this could be added?

**Comment by vegardlarsen** [comment]
Yes! I am working on a faster way of loading profiles using hotkeys, so this is happening in some form or another.

**Comment by pixelarbeit** [comment]
Is there an estimate for a release date for a new version? Last release is more than a year ago,

**Comment by vegardlarsen** [comment]
Unfortunately no. This is a very large change, and there will likely be an alpha release period first, which I will likely be open to anyone with a license.
