### ISSUE TITLE
Regions loading "squashed" the first time

### ISSUE THREAD

**Issue by killroy42** [digitalcreations/MaxTo#159]
I currently need to reload after each nVidia driver update. The first time I load my saved regions they are squished horizontally, with the left most regions slightly wider, and the rightmost regions narrower. Loading them a second time loads them correctly. So I currently have to re-load 8 times per driver update (2 monitors by 2 region sets by 2 re-loads).

**Comment by vegardlarsen** [comment]
This sounds very weird. Could you get me screenshots of the various steps so it is a bit easier to understand what happens?

**Comment by killroy42** [comment]
Ok, will screenshot with the next driver update... they happen pretty often, so shouldn't be too long!

**Comment by killroy42** [comment]
Ok, I managed to grab some screenshots after the nVidia driver update yesterday.

So this is what I get after I load my alternate profile for the first time:
![screenshot 2016-12-15 18 06 52](https://cloud.githubusercontent.com/assets/1201793/21265262/f066e562-c3a0-11e6-918b-e41c4432fe31.png)

And this is what it looks like after I do the same thing again:
![screenshot 2016-12-15 18 07 11](https://cloud.githubusercontent.com/assets/1201793/21265280/004378d8-c3a1-11e6-8750-62d929b733d3.png)

As you can see, on the first load the regions on the large monitor are different. I don't know if they are miss-scaled, or if they are similar to some other profile I had used before (the layout looks familiar).
So this could be an issue of some kind of caching, or somehow loading the wrong file.

**Comment by vegardlarsen** [comment]
Could you send me the `user.config` file, you'll find it under `%LocalAppData%\Digital_Creations_AS` underneath some horrible folder structure. Make sure you find the one that has the same version as the MaxTo version your are running. Either paste it in here (there shouldn't be anything secret in there), or e-mail it to me at the address in the About dialog.

**Comment by killroy42** [comment]
Looks safe enough to attach here...

[user.config.txt](https://github.com/digitalcreations/MaxTo/files/657370/user.config.txt)

**Comment by vegardlarsen** [comment]
There are a few strange things here. Your monitors are numbered 16 and 17, which is strange in and of itself (I know MaxTo says it is 1 and 17, which is a bug in MaxTo that assumes the main monitor is number 1, but this does not affect things here).

I have a suspicion that this is caused by one monitor being 4K, and you having DPI scaling enabled for just one monitor. It makes everything behave really strangely. See #30.

Can you try setting the same DPI-scaling for both monitors, restart, and see if the problem is gone then? At least that would narrow this down for me.

**Comment by killroy42** [comment]
Hmm, according to my settings they are both at 100% scaling (they're 49" and 24", so basically have the same DPI) Perhaps that's what's messing MaxTo up? Can I force MaxTo to treat them both as 100% scaling?

**Comment by vegardlarsen** [comment]
Sorry for the slow response, I got quite sick last weekend and it has taken me some time to recover.

If they are both at 100% I can rule out DPI scaling as being the issue. What happens if you set it up correctly, use the "Save profile" function to save it, and try to load it from there? Does it load correctly every time?

**Comment by killroy42** [comment]
If I load it when there is no issue, it loads normally. Only after it was "disrupted" either after booting or after a driver update does it fail on the first load.

**Comment by vegardlarsen** [comment]
Do you monitors appear to change resolution when Windows boots in these cases?

**Comment by killroy42** [comment]
No. No change to my res or monitors.

**Comment by vegardlarsen** [comment]
Can you try to load the fix for issue #147, and see if that helps. I have a nagging suspicion that this may have the same root cause.

Please get back to me if that does not fix this issue for you.

**Comment by killroy42** [comment]
I loaded it. Did not fix. And now ConEmu no longer works with the zones. It worked previously.

**Comment by killroy42** [comment]
While I can' test it exactly as before anymore, since nVidia driver updates no longer reset my regions, just trying to load the region normally works fine, first time. So I think this has been fixed as well, THANKS!!!!

**Comment by killroy42** [comment]
I spoke too soon. Opened options window, it was frozen. Killed the process and restarted MaxTo. It forgot my regions. When loading my regions It loaded main on first try, but alternate was squashed again and had to be loaded twice. So there is still something wrong... After restarting the program the options dialog isn't freezing. Haven't tried after a reboot yet.
