### ISSUE TITLE
Bins incompatibility

### ISSUE THREAD

**Issue by MafuJosh** [digitalcreations/MaxTo#16]
"Bins" from http://www.1upindustries.com
When running MaxTo while also running Bins, it causes Bins to not display some applications (like Outlook) in the correct bin while it is running.
I understand that you don't have control what the Bins software is doing.  But just wanted to let you know of the incompatibility, and I'd rather have only Bins installed rather than only MaxTo. (sorry)
Seems to still happen even when all of the features are unchecked.

**Comment by vegardlarsen** [comment]
I am closing this issue, since I have not yet received a ping back from the Bins guys, and their application does not even seem to work on my machines. I'll reopen if this changes.
