### ISSUE TITLE
Regions do not works well

### ISSUE THREAD

**Issue by birmantorpel** [digitalcreations/MaxTo#160]
Hello I'm working with 4 monitors that I split vertically. The problem is that when I split any windows 7 window to his assigned region,is working fine , but when I try to fit any other program ( ICQ , virtual box virtual machine, etc) it doesn't work.
Tnx

**Comment by vegardlarsen** [comment]
- Have you clicked Done in the region configuration?
- Does this happen with all programs, or are some programs working and some not? Try it with Notepad for instance.
- Have you rebooted your machine since installing (sometimes that can help).

**Comment by birmantorpel** [comment]
Yes I clicked done in the region configuration.
Is happening with Virtual box ( virtual machines that I use) and with ICQ.
Yes I have rebooted, this problem is coming a few months ago. 
Is very strange situation because with a notepad or with any windows window is working well...

**Comment by vegardlarsen** [comment]
This indeed seems strange. Is this happening with all VirtualBox windows, or just the VM display windows?

**Comment by birmantorpel** [comment]
It happening with all VirtualBox windows.

**Comment by vegardlarsen** [comment]
I just tried this on Windows 10, and I can't make this happen with VirtualBox. On my machine VirtualBox is running under my user account, and I have administrative privileges with UAC turned on. Is that the case on your machine as well?

**Comment by vegardlarsen** [comment]
Closing this as no response received in 5 months.
