### ISSUE TITLE
Clover doesn't respond to shortcut keys

### ISSUE THREAD

**Issue by Volvorocks** [digitalcreations/MaxTo#161]
Hi Vegard, 
I have been using your app with great success. I have run into an issue where the clover application (the one the adds tabs to windows explorer) doesn't respond to the shortcut keys I set up for MaxTo. Everything else is awesome and consistent. Great job on this utility. I have also uninstalled and reinstalled MaxTo to no avail. I didn't see any other issues related to Clover so I am submitting issue

**Comment by vegardlarsen** [comment]
That is really strange. Does it work when you maximize the window using the mouse?

I am afraid there may not be a lot I can do here; it may be that Clover works by creating a partially invisible window, and MaxTo avoids doing this with windows that are "strange" so it can avoid messing up windows that really shouldn't be moved (for instance your taskbar, which is a window).

**Comment by vegardlarsen** [comment]
Closed due to no response from user.
