### ISSUE TITLE
Enhancement - A hotkey to extend a window to occupy the vertical space above or below it

### ISSUE THREAD

**Issue by rerrett** [digitalcreations/MaxTo#163]
Apologies if there's already a way to do this.  In Windows10, when you snap a window to a region using windows+left or right, you can then press windows+up or down, to extend the window vertically.  Is there a way to do this with MaxTo?  

When I press windows+down, it reverts to the windows regions instead of following the MaxTo guide (as expected) and when I windows+2 or windows+8 it moves the entire window to the defined area below the window.  As expected.  It would be nice to extend a window vertically by pressing modifier+window+ (2 or 8) or even just window+7 or 1.  Thanks, I love this tool!

**Comment by vegardlarsen** [comment]
This is an idea I will take with me, and it may very well appear in a future version of MaxTo. :)

**Comment by rerrett** [comment]
Thank you!

**Comment by jneuhaus20** [comment]
FYI, In 2.1 (currently Alpha) one of the recipe ingredients is Expand Edge which lets you specify which edge, and to what it should extend (Window/Region/Screen edges.)

**Comment by vegardlarsen** [comment]
You are right. This should have been closed. Will be in 2.1.0.
