### ISSUE TITLE
Applications on the left, move right by 8 pixels, Windows 10

### ISSUE THREAD

**Issue by hyperion007** [digitalcreations/MaxTo#164]
When trying to split my 4K monitor (3840x2160) into 4 equal zones I get two zones on the top half of the display that are, from left to right: 1910x1053 | 1915x1053
And two zones on the bottom half of the display that are, from left to right: 1910x1051 | 1915x1051

When I open any application, put it in one of the left side zones and maximize it, it will maximize just fine, as will any application in any other zone. But when I close any application that is maximized on the left hand side and then open up that same application, its position have changed to the right by 8 pixels. 
I have to manually maximize all application that I want to be positioned to the two zones on the left.

This might be a windows problem but even so, maybe you know of a fix for it.

**Comment by vegardlarsen** [comment]
@hyperion007 MaxTo does not control where programs go when they start up. That is the job of Windows, or the program itself can choose to remember where it was the last time. I am assuming that if you maximize the window after starting the program, it goes to the correct region?

**Comment by hyperion007** [comment]
Yes, it seems to be a windows 10 issue that has to do with invisible borders. I used Winaero Tweaker to change the border width padding to 0 and that made the application windows shift to the right by about 2-3 pixels instead of 8 like before. 

But what about the issue of the "split horizontally" and "split vertically" not actually splitting the display into equal sized zones? This is an issue when snapping for example Adobe Reader to the left part of the display so that it takes up half of the display in a portrait layout. It will not adhere to the zones created by MaxTo so if MaxTo isn't configured to split the display in exactly the middle (vertically) then all applications that are maximized within MaxTo zones won't align with the window of Acrobat Reader. 

The sizes of the 4 zones in MaxTo also differs depending on which orientation you split first. So if you split the entire display vertically first followed by splitting horizontally in each of the now two parts, then you get one result. But if you first split horizontally, followed by two vertical splits then you get a different result.

**Comment by vegardlarsen** [comment]
I hate those invisible borders. Then I know what is happening there, and there isn't that much I can do about it I think. Windows will force your windows to be inside the monitor bounds when it starts, and due to the margins MaxTo has to force the windows to be slightly outside. Very annoying.

Due to the way MaxTo works today, and the WinForms platform, it is very difficult to get exact measurements for the regions. I believe that if you edit the configuration file yourself, `user.config` somewhere in `%LocalAppData%\Digital_Creations_AS`, you should be able to set the split distance for the outermost region to be 0.5. If you edit your regions using MaxTo, that number may change.

**Comment by balimund** [comment]
When will this larger release be?

**Comment by vegardlarsen** [comment]
Hopefully soon, but it will most likely go out as an alpha first, and some features we have today will probably go missing in the first release. Keep watching this issue tracker for announcements. :)

**Comment by vegardlarsen** [comment]
See issue #220 for preview versions of this larger release.
