### ISSUE TITLE
Unity 5.5 editor window does not repaint on window resize while MaxTo is running.

### ISSUE THREAD

**Issue by corpsinhere** [digitalcreations/MaxTo#165]

**Comment by vegardlarsen** [comment]
This is on Windows 10? It could be that MaxTo is doing something strange here; but it could also be Unity's fault. I am logging this for something that needs closer examination.

**Comment by corpsinhere** [comment]
Oh man I am really sorry - this is for Win 7. I am sorry if I sent you on a
wild goose chase.

Thanks,
Broos

**Comment by vegardlarsen** [comment]
No worries. I will look into this before the next release.

**Comment by corpsinhere** [comment]
Looks like MaxTo is also interfering with repainting the Jing preview window. The window turns black if moved -problem goes away when MaxTo is closed.

**Comment by turkian** [comment]
I have the same problem with ManicTime tracker on Windows 10.  Only the border will be drawn after moving the window.  A free version is available if you need it for testing : http://www.manictime.com/.

**Comment by rthill91** [comment]
I'm seeing this same issue with MaxTo on Windows 10

**Comment by balimund** [comment]
Same problem. Windows 10.

**Comment by balimund** [comment]
Is MaxTo abandoned? Nobody seems to be correcting this countless bugs.

**Comment by vegardlarsen** [comment]
@balimund We have not abandoned it, and there is a bug fix in the works. We are currently waiting for our installer software to support installing .NET Framework 4.7, which was released last month. I do not think we will have this bug fixed though, as it appears to be more difficult to track down.

**Comment by vegardlarsen** [comment]
Did not mean to close the issue. :)

**Comment by artur-ag** [comment]
This happens when MaxTo's windows transparency option is activated. If you disable it, Unity's interface won't stop drawing after you move it. This should serve as a workaround, and maybe help tracking down the bug.
Tested on 2015.11.1.0 and Unity 5.6.1f1.

**Comment by corpsinhere** [comment]
Works! Thanks for tracking this down :D.

**Comment by tynril** [comment]
I'm also experiencing this bug (with Windows 10, MaxTo 2017.7.0.0, and Unity 2017.3.1f1), but the workaround suggested by @artur-ag worked.

**Comment by vegardlarsen** [comment]
Can anyone please try this again with the preview releases (specifically 2.0.0-alpha.3)? See #220 on how to test it.

We've changed quite a bit about how MaxTo subclasses other windows, and it is likely this problem will be solved.

**Comment by rthill91** [comment]
No dice
MaxTo v2.0.0-alpha3
Unity v5.6.3p2

I'm still seeing the same behaviour

**Comment by vegardlarsen** [comment]
You should now be able to go into *Settings*, *Compatibility* and press *Check for updates* to download a new compatibility shim that will prevent this issue for Unity. The shim is a bit heavy handed, and disables all subclassing for Unity for now, which means you'll loose functionality such as drag-to-region for the main Unity window.

I am also adding the capability of targetting just the window transparency option with a compatibility shim, which is what is causing the issue with Unity in the first place. This will have to wait until the next alpha release.

**Comment by vegardlarsen** [comment]
The fix I spoke of has been implemented, and will be in 2.0.0-alpha4.
