### ISSUE TITLE
Maxto & Server 2012 (Remote Desktop Server) & user without admin rights

### ISSUE THREAD

**Issue by AlbertHakvoort** [digitalcreations/MaxTo#166]
MaxTo needs admin rights on the server. I've tried it with runas with /savecred option, that works, but every user then uses the profile of the admin user.. A commandline option to select wich profile to be used would be helpfull. (or no need for admin right ;) )

**Comment by AlbertHakvoort** [comment]
This is my solution for running MaxTo with admin rights, create a shortcut and place it into the startup folder. After starting you have to fill in the admin password once

C:\Windows\System32\runas.exe /env /savecred /user:domain\administrator "C:\Program Files\MaxTo\MaxTo.exe —start-hidden"

**Comment by vegardlarsen** [comment]
Wouldn't your command run MaxTo as the domain administrator? 

MaxTo was designed to run with the highest privileges it can obtain while running as the current user, meaning it can access all the windows that you as a user have access to. Have you disabled UAC or set it to a stricter policy? Just saying "No" to the UAC prompt should allow it to work just fine.

**Comment by vegardlarsen** [comment]
Closed due to no feedback from customer.
