### ISSUE TITLE
How to setup even splits?

### ISSUE THREAD

**Issue by Sawtaytoes** [digitalcreations/MaxTo#168]
When you split a view, you get a 50/50 split. If you split one size, you get a 50/25/25 split. Now from this point, how would you change it to a 33/33/33 split without a calculator or trail and error?

**Comment by vegardlarsen** [comment]
Unfortunately, this is not something that is currently possible with MaxTo. It only allows two-way splits (which you can then subdivide).

The closest would probably be first creating a 50/50 split, move the divider som the left-most (or top-most) part is 1/3 of the way, and then dividing the right-most part again (which would be 50/50 of the remaining area).
