### ISSUE TITLE
UAC Prompt Terminal Server

### ISSUE THREAD

**Issue by Matt-Digit** [digitalcreations/MaxTo#17]
We are running max too and experiencing an issue where the user is being prompted for admin rights we have installed the latest version 2014.11.1

I found a post regarding this and the response was the de-elevate the application? just wondering how this works?

**Comment by AlbertHakvoort** [comment]
This is my solution for running MaxTo with admin rights, create a shortcut and place it into the startup folder. After starting you have to fill in the admin password once

C:\Windows\System32\runas.exe /env /savecred /user:domain\administrator "C:\Program Files\MaxTo\MaxTo.exe —start-hidden"
