### ISSUE TITLE
Application refuse to valid/accept my user/serial couple

### ISSUE THREAD

**Issue by mvedie** [digitalcreations/MaxTo#170]
Hello

When i write my user and serial, i have this message. 
![image](https://cloud.githubusercontent.com/assets/10563981/22968746/f38af94a-f36b-11e6-96d1-ffdb4e1912e4.png)

Please fix this fast, it's unbelivable to sell a product that is like a beta product !

Thx lot. 

My email user : m.vedie@dreamcentury.com

**Comment by mvedie** [comment]
My email user : m.vedie@dreamcentury.com

**Comment by vegardlarsen** [comment]
I have sent you an e-mail in private, as the solution to this exposes your serial key.
