### ISSUE TITLE
Bug with iCloud

### ISSUE THREAD

**Issue by brunocantuaria** [digitalcreations/MaxTo#171]
If iCloud is open on Windows, even if just on taskbar, MaxTo stops working after a few seconds, fixing only closing through Task Manager and re-opening after close iCloud

**Comment by vegardlarsen** [comment]
Thanks for reporting this. I apologize for the very slow response. You may try the following. Find the `shims.xml` file in the MaxTo installation folder. Under the `<ignore>` tag, add `<process title="iCloud">icloud</process>` (here I am assuming that the name of iCloud's executable is `icloud.exe`, and therefore I put `icloud` between the tags, the title field can really be whatever you want).

Please let me know if this helps, and I can add it by default to the next release.

**Comment by brunocantuaria** [comment]
After reviewed I discovered that iCloud wasn't the issue, but the Screen Record Service of GeForce Experience. I was able to make it work after including those 3 lines on shims:

    <process title="NVIDIA Share">NVIDIA Share</process>
    <process title="OpenAutomate wrapper cache">OAWrapper</process>
    <process title="NVIDIA Capture Server">nvspcaps64</process>

**Comment by vegardlarsen** [comment]
Great that you managed to resolve this. I may add these to the shims list for the next release.
