### ISSUE TITLE
Feature Request: Turn on/off based on monitor connected

### ISSUE THREAD

**Issue by phillogomaker** [digitalcreations/MaxTo#172]
Hi I recently purchased and was wondering if it's possible to add a feature to have MaxTo either turn off if there's no monitor attached or maybe make it specific to an attached monitor. MaxTo is great when I've got my laptop attached to my widescreen monitor and have the extra screen space to work with, but when I'm using just my laptop detached I don't need it. Thanks! -Phil

**Comment by vegardlarsen** [comment]
Hi! If you don't set up any regions on a monitor, MaxTo will not interfere with windows on that monitor. As long as your attached monitor isn't set as your primary monitor (that messes up the monitor numbering which currently confuses MaxTo), this should in theory work rather well.
