### ISSUE TITLE
Hotkeys for focusing the window in the next/previous region

### ISSUE THREAD

**Issue by ksaua** [digitalcreations/MaxTo#173]
Hi.

Would it be possible to add a hotkey which would focus the next/previous window.

My monitor is split into three, one for my IDE and two terminals.  If I could use a hotkey to change the active window I would not need the mouse that often :)

Thanks in advance.

- Knut

**Comment by vegardlarsen** [comment]
Hi Knut, this is absolutely a good idea. We already do support going up and down the stack, so allowing "Focus in direction" would be smart. We are however running out of possible keyboard combinations, though, so it may be that the shortcuts will not be on by default.

**Comment by vegardlarsen** [comment]
This is working in the 2.0.0-alpha.2 release that I put out earlier today. See #220.
