### ISSUE TITLE
If one opens ADOBE  Acrobat DC MaxTo stops working

### ISSUE THREAD

**Issue by davidlma** [digitalcreations/MaxTo#174]
Some windows go to the border and stick but Adobe Acrobat reader DC
![issues with maxto and adobe](https://cloud.githubusercontent.com/assets/9935338/25900163/78868dcc-3560-11e7-876b-2a976adab9ee.jpg)
![image](https://cloud.githubusercontent.com/assets/9935338/25900188/953d8808-3560-11e7-8794-54d69a209897.png)

Please help to get Adobe to stick to the regions ...
David

**Comment by vegardlarsen** [comment]
@davidlma Are you referring to the compatibility shim that disables MaxTo for Adobe Reader? See [this document](http://maxto.net/shim/Details/acrobat_reader) for more details.

If not, please try to explain more clearly what you mean.

**Comment by davidlma** [comment]
Hi, I don't know if the problem if due to Adobe Acrobat DC, what I get it does not seem to be a crash with MaxTo, but the diagnostics show:

And Adobe Pdfs don't stick to the borders regions. 
Is there an update for MaxTo, or Is there a way that at least other docs do stick to the borders?  
What kind of other info would you need so it can help fixing the issue?
Thanks for your help !

David
On 5/10/2017 9:13:35 AM, Vegard Andreas Larsen <notifications@github.com> wrote:
@davidlma [https://github.com/davidlma] Are you referring to the compatibility shim that disables MaxTo for Adobe Reader? See this document [http://maxto.net/shim/Details/acrobat_reader] for more details.
If not, please try to explain more clearly what you mean.

**Comment by vegardlarsen** [comment]
David, please see the link I posted earlier. This is because of a security feature in Adobe Reader, that we can only get around if you are willing to use the workaround listed in that document.
