### ISSUE TITLE
Windows sometimes get stuck as transparent

### ISSUE THREAD

**Issue by hensm** [digitalcreations/MaxTo#175]
When dragging to the top of a region.

Example:
http://puu.sh/w39Ty/65dcf144f4.mp4

Also, unrelated, but sometimes when moving a window out of a region, they end up partially above the top of the screen, forcing me to use the keyboard shortcuts to move them into another region. Not quite sure how to reproduce it.
Edit: Just happened:
![](http://puu.sh/w3a81/7f2c0237c5.png)

**Comment by vegardlarsen** [comment]
Thank you for reporting this. I will attempt to reproduce this and try to have it fixed for the next release (we are currently waiting for support in the installer software we use for .NET Framework 4.7, which is the only thing holding back the new release).

**Comment by vegardlarsen** [comment]
I could not reproduce this in time to fix it before the current release. I'm sorry.

**Comment by marcii** [comment]
Oh, hey, don't worry about it. I'll try and narrow down the conditions that cause it. Let me know if there's any way for me to collect some debug info that would help.

**Comment by vegardlarsen** [comment]
Please try the preview releases (see issue #220 for details), where we have overhauled the transparency option completely.

**Comment by DanAvni** [comment]
Issue still happens to me on 2017.7.0.0
Any solution?

**Comment by vegardlarsen** [comment]
@DanAvni Have you tried the preview releases (see issue #220 for details)? The transparency option should have been completely overhauled.

**Comment by vegardlarsen** [comment]
@DanAvni Stability of this is like an alpha; expect it to crash sometimes. You may not want to use this day-to-day yet; but feel free to try it out and it may work fine for you.

You can "buy" (for free, using a test credit card number, details on the website) a license for the preview version on the [preview website](https://preview.maxto.net), but it will be invalidated when we end the preview program.
