### ISSUE TITLE
Request for ability to split regions in thirds

### ISSUE THREAD

**Issue by Wargazm** [digitalcreations/MaxTo#176]
Basically what I said above.  I'd like the ability to split a region in thirds, not just in half.  So I can quickly make a pixel-perfect layout like this:

```
+-----+-----+-----+
|     |     |     |
|  1  |  2  |  3  |
|     |     |     |
+-----+-----+-----+
|                 |
|        4        |
|                 |
+-----------------+

```

In fact, an even better enhancement would be to just ask how many regions to split into when you click "Split vertical" or "Split horizontal".  

Thanks!

**Comment by vegardlarsen** [comment]
Hi, this is unfortunately more work than it appears. But I am taking your suggestion into consideration, and probably leaning more towards making it easy to move a border to 1/3, 2/3, etc.

**Comment by nesl247** [comment]
I just took a look at MaxTo as I'm using an Ultrawide monitor, and noticed this feature missing almost immediately. Hopefully in the future this is added because MaxTo is unfortunately worthless to me until then.

**Comment by vegardlarsen** [comment]
@nesl247 You can still make this work, by splitting twice and resizing it to fit. Your layout is saved, so you only have to do this work.

Here's how I'd do it:

1. Split vertically
2. Move the border to 1/3 of the screen.
3. Split the right-most half again. It should split in half, effectively splitting your monitor into thirds.

**Comment by nesl247** [comment]
How do you resize? I tried to drag the regions to resize it figuring I could do that and it didn't work, so I gave up assuming it wasn't possible.

**Comment by nesl247** [comment]
Reinstalled and figured it out. The cursor didn't change right away for me. Had to really get it on point on the split to drag it the first time. Worked fine after that.

Thanks!
