### ISSUE TITLE
Feature request - add right mousebutton as modifier key

### ISSUE THREAD

**Issue by PatrickDem** [digitalcreations/MaxTo#177]
Hi,
I would like to position windows with the mouse hand. I don't want to have the second hand on the keyboard every time. Could you add the right mouse button as a modifier key? That would be a reason for me to buy.
Thank you very much!

**Comment by vegardlarsen** [comment]
Hi Patrick, this is quite a bit more difficult than it seems, and won't work at all with windows that implement custom title bars. I don't think this will be something we will be doing.
