### ISSUE TITLE
.net framwork 4.7 is needed but my pc with win10 is not supported by it

### ISSUE THREAD

**Issue by andriywu** [digitalcreations/MaxTo#179]
This morning I update the MaxTo and now it did not work.
How to download the old version?

**Comment by vegardlarsen** [comment]
The old version is [here](http://maxto.net/Release/download/30). Can you please tell me which version of Windows you have so I can have a go at fixing this if it affects other people?

**Comment by andriywu** [comment]
windows 10 professional 64bit

**Comment by vegardlarsen** [comment]
Can you run `winver` and tell me the version reported there?
