### ISSUE TITLE
Windows 10 Enterprise Edition not compatible with latest version of MaxTo

### ISSUE THREAD

**Issue by raulajr** [digitalcreations/MaxTo#182]
The latest version of MaxTo requires .NET v4.7. The issue is that Microsoft did not incorporate Windows 10 Enterprise Edition compatibility into 4.7. One must upgrade to Windows 10 Anniversary Edition. Since most of us on Enterprise Edition cannot upgrade to Anniversary Edition at our discretion, MaxTo will no longer function. Please provide a version of MaxTo that will work with a .NET version that is supported by Windows 10 Enterprise Edition.

**Comment by npapandreou** [comment]
I confirm that Windows 10 Enterprise 2015 LTSB (version 1507, build 10240) cannot support the installation of .NET Framework 4.7.

The Windows 10 Enterprise 2016 LTSB (version 1607, build 14393) supports the .NET Framework installation.

We could have either an older version of MaxTo available for download,
or some reduced functionality when running older Windows 10 versions.

Microsoft has created a mess with the LTSB version,
not being able to install the latest versions of drivers for nVidia GPUs and Intel Ethernet Adapters.

**Comment by brianhartman** [comment]
I am having the same issue as raulajr.  I work in a corporate environment and don't have the permissions to upgrade to Anniversary Edition.  Please put out a notice when this issue is fixed.  I love the product and am now missing its functionality.

**Comment by vegardlarsen** [comment]
For anyone who cannot install the latest release due to this issue, here is a [download link to the previous release](maxto.net/release/download/30).

**Comment by GAZWOOD** [comment]
I also wish to use the earlier edition, why does the above download link not work, I get a 404.

**Comment by vegardlarsen** [comment]
I fixed the download link. Sorry.

**Comment by GAZWOOD** [comment]
Thank you for your prompt attention.

**Comment by vegardlarsen** [comment]
Just a quick note, that the preview releases (2.0.0-alphas) no longer require .NET Framework 4.7 (instead requiring .NET Framework 4.6.2). 4.7 was necessary to support per-monitor DPI awareness in MaxTo 2017.07, but is no longer necessary in the 2.0.0 previews, as we are no longer using Windows Forms as the base technology for the user interface.

See issue #220 for details on how to try out the preview releases.

**Comment by brianhartman** [comment]
Hi,

Will I be able to use the 2.0 version on Windows 10 Enterprise Edition computers?

Thanks,

Brian

**Comment by vegardlarsen** [comment]
As long as you can install .NET Framework 4.6.2, which you can [get from here](https://www.microsoft.com/en-us/download/details.aspx?id=53344). The installer will also attempt to install it for you. There is also a "System requirements" list on that site, which lists the supported operating systems as:

- Windows 7 SP1 (x86 and x64)
- Windows 8.1 (x86 and x64)
- Windows 10 version 1507 (x86 and x64)
- Windows 10 November Update version 1511 (x86 and x64)
- Windows Server 2008 R2 SP1 (x64)
- Windows Server 2012 (x64)
- Windows Server 2012 R2 (x64)
