### ISSUE TITLE
regions under taskbar in multi-monitor setup (only on monitors 2 & 3)

### ISSUE THREAD

**Issue by 8biten** [digitalcreations/MaxTo#183]
The primary display behaves as expected.  However, on monitor 2, I have the screen split 50% vertically.  The right side is split 50% horizontally.  Windows on the left side extend under the taskbar (which I have displaying on all monitors) extends under the taskbar.  The windows on the bottom right side do not.  No other monitor/region exhibits this behavior.  This is on Windows 10 build 15063.483

**Comment by vegardlarsen** [comment]
Does this correct if you disconnect and reconnect a monitor? Can you attach a screenshot of windows in all three regions?

**Comment by 8biten** [comment]
Well, It may… I had to undock and travel.  Upon my return I noticed that it is not putting the windows under the taskbar anymore.  I received your email while travelling, so I was unable to be scientific about this issue.

Dennis

**Comment by vegardlarsen** [comment]
Please let me know if this behavior resumes, so we can test it more closely. I am closing this for now.
