### ISSUE TITLE
An option to disable the HotKeys?

### ISSUE THREAD

**Issue by JackCroww** [digitalcreations/MaxTo#184]
While I love MaxTo's regions, I am already using a different utility to control moving/sizing/navigating windows, and MaxTo's HotKeys are conflicting with that utility.  Can we have an option to disable the MaxTo HotKeys?

**Comment by vegardlarsen** [comment]
@JackCroww Thanks for writing. We do not have any current plans on implementing this specifically, but you can unassign all the hotkeys in the options window. Would that help?
