### ISSUE TITLE
automatic opening

### ISSUE THREAD

**Issue by lakawet** [digitalcreations/MaxTo#187]
Hello,

I wanted to know if it was possible that at the start of windows, different internet pages could open directly in the zones that I will have defined?

Thank's

Lakawet

**Comment by vegardlarsen** [comment]
This is unfortunately not possible. We are evaluating if we can do something similar; starting an application and putting its main window in a region, but this will not work with individual web pages unless you start a dedicated browser for each page.

**Comment by lakawet** [comment]
Hello,

Thank you for your answer.
Actually, I managed to make start 3 Web windows in the starting up of Windows but it would be good if we could position them directly in predefined zones.

I work for a hospital and we would like to integrate your solution for the supervision. But for it, I shall need that the maximum is automated in the starting up of the pc.

Thank's

Lakawet

**Comment by vegardlarsen** [comment]
Please do follow our future releases. If you can at this point open a browser to a specific web page in its own window, the solution we are looking at may work for your needs, if we can get it to work the way we want.
