### ISSUE TITLE
Hotkeys don't work at all

### ISSUE THREAD

**Issue by Lomacar** [digitalcreations/MaxTo#188]
I am trying the latest version of MaxTo (2017) on my Windows 10 machine with 1 4K TV for a monitor. The hotkeys don't work. I am trying the Win + Num key shortcuts and the Win + PgUp/PgDn ones. Also, when I try to open the MaxTo options it crashes.

**Comment by vegardlarsen** [comment]
Hi, and thanks for writing. After the crash, before you restart MaxTo, can you look for `Exception_something.zip` files in `C:\Program Files\MaxTo`, and perhaps send them to me via the support e-mail? They may contain clues as to what is happening.

**Comment by Lomacar** [comment]
OK, sent.

**Comment by Lomacar** [comment]
Issue resolved by deleting user.config.

**Comment by vegardlarsen** [comment]
Closing this as it appears to have been a one-time thing.
