### ISSUE TITLE
Outlook 2016 is opaque when maximized. 

### ISSUE THREAD

**Issue by thickdrew** [digitalcreations/MaxTo#190]
I have a really annoying issue.  
- 2 x 2k monitors in landscape, 1 x 4k in portrait.  
- created zones in the 4k monitor - appear to be fine.  
- left the 2 x 2k monitor without a zone (or full monitor if that is how it is done).  

Issue:  Outlook, when maximized in the 2k monitors, turns opaque.   I basically can't maximize it ever or I won't be able to see.  All other applications are fine.  Just wondering if I am doing anything wrong? 
![sample of issue](https://user-images.githubusercontent.com/32201097/30750980-3d9854e6-9f75-11e7-8a45-f06bfb8fb716.jpg)

**Comment by vegardlarsen** [comment]
Hi, and thanks for writing. Have you tried disabling window transparency in MaxTo's options, and then restarting Outlook?

**Comment by thickdrew** [comment]
thanks - that worked.   I'm not really sure how I messed up to start with, but I just turned the window transparency to none - and it works.   thank you.
