### ISSUE TITLE
Issue when using Remote Desktop Manager from Devolution

### ISSUE THREAD

**Issue by varnar** [digitalcreations/MaxTo#192]
Hello
The Remote Desktop Manager from Devolution looks like is not working with your application when the application is in Pause mode.
When it is in active mode and I maximize it it maximize randomly on the regions or some times maximize to screen size but with transparency.

Thanks

**Comment by vegardlarsen** [comment]
@varnar Thanks for getting in touch. You will have to clarify a few things:

1. Which application is in Pause mode? Do you mean MaxTo's passive mode?
2. Can you describe what "is not working" means?

Screenshots or short videos often helps.

For the transparency issue, it may help to disable transparency in MaxTo's options.

**Comment by varnar** [comment]
Attaching video

**Comment by vegardlarsen** [comment]
Thank you for the video, but it appears that all of the action is happening on a different monitor than the one you are recording. Or are you pressing keyboard shortcuts at the same time?

When MaxTo is in "passive mode" (indicated by the pause symbol), the keyboard shortcuts still work, but clicking maximize on a window will let the window maximize to the entire monitor.

**Comment by vegardlarsen** [comment]
Closed due to lack of feedback.
