### ISSUE TITLE
"EXE and MSI file signature mismatch." error message when running installer

### ISSUE THREAD

**Issue by PhilipHagenbruch** [digitalcreations/MaxTo#193]
When I'm running the installer `MaxToSetup-2017-07.exe` downloaded from your website, the installation fails during the "Configuring MaxTo" phase with the following error message:

> EXE and MSI file signature mismatch.

Screenshot: 
![image](https://user-images.githubusercontent.com/19719283/31316710-2da59e7a-ac33-11e7-9f91-234910a0b3d9.png)

An Explorer window opens after dismissing the error message and the installer correctly rolls back its changes.

I tried disabling my anti-virus software (Avast Free Antivirus 17.7.2314) prior to running the installer to no avail.

I want to try MaxTo. No previous versions have ever been installed.

**Comment by vegardlarsen** [comment]
I apologize for my slow response on this. First, I'd like you to try to [re-download the file from here](https://maxtostorage.blob.core.windows.net/releases/MaxToSetup-2017-07.exe). I just tried it and it works the way it should on my machine, and it could be that the download failed somehow.

If that doesn't work, please try producing a log. To do this, you will have to open up a Command Prompt in your download folder. Run `MaxToSetup-2017-07.exe /L*V "install.log"`. This will create a log file called `install.log`. Take its contents and upload it here, or send it to support@maxto.net (if you fear it may include private information) and I will have a look at it.

**Comment by vegardlarsen** [comment]
An additional thought; since this is related to the digital signature of the file, it may be the case that it fails if the date and time on your computer is very far in the past or the future. Please check that as well.

**Comment by PhilipHagenbruch** [comment]
Hello @vegardlarsen, thanks for your response.

I have downloaded the file from the link you provided and the problem still persists. I confirmed that the date and time on my system is correct.

Interestingly, I tried to run the installer on another system (a VM) and the installation finished successfully on that system. So I figure, it must be a configuration problem on my end. Unfortunately, googling for the error message reveals no clue other than it seems to be related to the installer system you use for your application.

I ran the installer with the command line arguments you provided in an elevated command prompt.  
https://gist.github.com/PhilipHagenbruch/70d5bb47471b58f80961196bdc47d795

**Comment by vegardlarsen** [comment]
I can't really see what is wrong, but it would appear our installer software has fixed this issue in a later version than we compiled MaxTo with.

I believe you can get it to work by extracting the MSI from the EXE, and running the MSI:

1. Run `MaxToSetup-2017-07.exe /extract foo` (I don't know why the 'foo' part has to be there)
2. This will create a folder called `80AB7EA`. Inside you will find the MSI (you should be able to use either of the `x64` or non-`x64`-variants).

If the MSI fails to install, you can simply copy the contents of that folder to where you want it installed, and run MaxTo.exe. If that fails, we can get you the prerequisites manually afterwards.

**Comment by PhilipHagenbruch** [comment]
According to their [documentation](http://www.advancedinstaller.com/user-guide/exe-setup-file.html) `foo` is the target directory to which the extracted files are copied to. Since it didn't exist (on my system), the files were extracted into the current directory. The argument can be omitted and then defaults to the current directory.

I extracted the package and the installation finished successfully.

If I can provide any more details to help with troubleshooting you just have to ask. Otherwise, this issue can be closed.

Thank you very much for your assistance!

**Comment by vegardlarsen** [comment]
We are replacing the entire Advanced Installer with a [Squirrel-based](https://github.com/Squirrel/Squirrel.Windows) installer shortly, so I don't think we'll do anything about this issue.
