### ISSUE TITLE
Freezing on Windows 10 Fall Creators Update (Version 1709 / Build 16299.15)

### ISSUE THREAD

**Issue by janwerner** [digitalcreations/MaxTo#194]
Version: 2017.7.0.0

I'm using the release version of the upcoming Windows 10 Fall Creators Update. MaxTo works but freezes after a short while. I have to kill it using Task Manager. Any logs I can upload?

**Comment by vegardlarsen** [comment]
Thanks for letting me know. Are you doing anything specific when it freezes? Which MaxTo services are running when this freeze happens? (There should be 3 processes)

Unfortunately, the current version of MaxTo does not provide any logs unless it detects a crash. Check for `Exception_<whatever>.zip` files in the installation folder.

**Comment by janwerner** [comment]
Hi,

I'm not doing anything in particular. It's just sitting in the background
and if I try to use it, it's not working any more and the tray icons
doesn't react to clicks any more.

All three services are running when it happens.

Thanks,
Jan


—
​
Jan Werner //
​+​
49 (0)172 3665526
​ // mail@janwerner.de

**Comment by vegardlarsen** [comment]
@janwerner This is very strange. I am myself running the fall creators update now, and it does not appear to have any issues on my machines. Can you try uninstalling and reinstalling to see if that helps?

**Comment by ograso** [comment]
Definitly there is a problem on this update. Same issue for me. Sometimes windows can get crazy to all of us. I shouldnt use Microsoft silly update

**Comment by janwerner** [comment]
Did a reinstall - no change. It doesn't happen all the time, but it's definitely there. Is there some kind of debug log that I might enable? Anything else to help you get to the root of the problem?

**Comment by vegardlarsen** [comment]
Can you try deleting your MaxTo settings? You should be able to find them in `%LocalAppData%\Digital_Creations_AS`.

**Comment by wreetojyoti** [comment]
I am facing the same problem, windows 10 is freezing abruptly since I updated it to fall creators update.

**Comment by wimdevriendt** [comment]
I have same issue. This morning i got message from adobe acrobatdc that maxto will not work properly

**Comment by vegardlarsen** [comment]
@wimdevriendt This is not related to the above, but caused by a security feature in Adobe Reader. See [this link](https://maxto.net/shim/Details/acrobat_reader).

**Comment by vegardlarsen** [comment]
@janwerner Can you try the alpha releases (see issue #220), and see if this has been solved there?
