### ISSUE TITLE
Remote desktop applications do not snap correctly in windows 10

### ISSUE THREAD

**Issue by rmcarrey** [digitalcreations/MaxTo#196]
On our domain, we have applications published through remote desktop. When you snap those applications into a maxto window, the application becomes unusable until you minimize from taskbar and bring the window back up (unsnapped). Can attach screen shots if need be.

**Comment by vegardlarsen** [comment]
@rmcarrey I apologize for the slow response, I have been away on paternity leave.

Can you please attach screenshots that show this situation? Which remote desktop software do you use?

**Comment by rmcarrey** [comment]
Mr Larsen,


Now I get to apologize for the delay on our behalf. Attached are the screenshots of what we are working with. The setup is windows 7 with 2x Dell Ultrawide 21:9 27". I have not done anything funky with the maxto setup. When maxto is at its default (1 zone per monitor) the remote apps maximize correctly. If I split the screen in half (2 zones per screen) then the snap issue happens.


Regards,

Madison

________________________________

**Comment by vegardlarsen** [comment]
Unfortunately, images do not come through here when you reply by e-mail. You can either visit this issue on Github and upload the images, or you can send them to me via e-mail at support AT maxto DOT net.

**Comment by vegardlarsen** [comment]
![maxto_putty_remote_broken](https://user-images.githubusercontent.com/436508/33667641-b3cea9c2-da9d-11e7-8803-e7517b141201.PNG)

Image as forwarded by @rmcarrey via e-mail. 

Does this happen when you run PuTTY locally? What is the method you use for "forwarding" single applications?

**Comment by vegardlarsen** [comment]
I am closing this due to lack of feedback.
