### ISSUE TITLE
Different arrangements per virtual desktop

### ISSUE THREAD

**Issue by bojordan** [digitalcreations/MaxTo#199]
Allow similar configurability to multi-monitor, but also for the virtual desktops that are present in Windows 10.

**Comment by vegardlarsen** [comment]
I am working on this. :)

**Comment by obfuscurity** [comment]
Shoot, I was hoping for this feature when installing MaxTo. I'll try it again once this ships. :heart:

**Comment by vegardlarsen** [comment]
👍

**Comment by obfuscurity** [comment]
Was this closed by accident?

**Comment by vegardlarsen** [comment]
Nope, just because I have another ticket internally tracking this. :)

**Comment by bojordan** [comment]
👍

Looking forward to it!
