### ISSUE TITLE
MaxTo stuck after session lock in 4K multi-monitor configuration

### ISSUE THREAD

**Issue by cyraxan** [digitalcreations/MaxTo#201]
Win10 1709, 2017.7.0.0 MaxTo
4K cross-splitted primary monitor and FHD full-size secondary
After session lock and/or remote RDP connection to workstation MatTo not working. Windows not maximizing to defined regions, both primary and secondary regions highlights on primary monitor.
Have to restart MaxTo every time after session unlock

**Comment by vegardlarsen** [comment]
Do you have different DPI settings on both monitors? Is Windows 10 kept up to date (either Creators Update or Fall Creators Update)?

**Comment by cyraxan** [comment]
The problem is not showing up right now, but I can't say what fixed it.
It was default DPI and 100% scale settings
Latest 1709 up-to-date OS patches.
I'll keep watching and if problem repeat I'll write there...
Thanks you for reply.

**Comment by vegardlarsen** [comment]
Thanks. I am closing this, so I don't forget if this doesn't occur again. Feel free to reply and I'll reopen.
