### ISSUE TITLE
Virtualbox VM "monitor" window maximises full screen, not to the defined region

### ISSUE THREAD

**Issue by kxtcd950** [digitalcreations/MaxTo#203]
On my installation of Windows 10, MaxTo and VirtualBox (Windows10: 1709, 16299.125; Virtualbox: 5.1.30 r118389; MaxTo: 2017.7.0.0), when I click on the maximise button of a virtual machine's monitor window, I get the monitor window maximising to my whole monitor, not to the region I've defined.  I believe that the regions have been defined correctly, when I tell maxto to show me the regions, they are as I'd expect and all other application windows (this includes the Virtualbox Manager window) I've tried maximising will maximise to the regions I've defined, correctly.

**Comment by vegardlarsen** [comment]
I apologize for the slow response, this apparently fell through the cracks. 

There could be something different about how VirtualBox maximizes those specific windows. I have a suspicion that they cannot be maximized normally because it has to adapt to the content, but I may be wrong.

I am leaving this open as a reminder until I get to look closely at this.

**Comment by kxtcd950** [comment]
I've just noticed today that Virtualbox "monitor windows" have started working as I'd expect with MaxTo; I tried maximising a window expecting it to go full-screen, but instead it went to the MaxTo defined area of the screen.  It actually took me a couple of minutes to work out what was happening.  Deleting the Maxto area then makes the window go full-screen again (probably ought to memorise the key modifier for not obeying the MaxTo areas on maximise, though).

**Comment by kxtcd950** [comment]
And would you believe it, having looked at the alternate keys mechanism for maximising to two different areas, the VirtualBox monitor windows don't maximise to the alternate region with the Alt key pressed down.  Other applications do.  I've defined the MaxTo Main area to be a vertical split and the alternate area to be fullscreen, and Alt-clicking the maximise button in any window other than a Virtualbox monitor window will send the window full screen.  Virtualbox monitors *always* go to the 50% split.

**Comment by gjasch** [comment]
I'm having the same issue while testing an evaluation copy of MaxTo v2017.7.0.0 with VirtualBox 5.2.12. The VirtualBox VMs will not maximize within the defined area.

**Comment by kxtcd950** [comment]
I've just retested, and I've found it does misbehave; Virtualbox 5.2.12 monitor windows aren't maximising to the defined areas.  Not quite sure how I got it to work in January.

**Comment by vegardlarsen** [comment]
Have you tried this in the preview versions (see issue #220 for details)? It changes a few things about how MaxTo works internally, and there is a chance it could work.

**Comment by drbuckingham** [comment]
In VirtualBox 6.0.10 r132072, the "monitor" window does not respond to any defined region.  Maximizing the window always goes to full screen per Windows 10 normal behavior.
