### ISSUE TITLE
Can not run MaxTo on clean PC install

### ISSUE THREAD

**Issue by Reapsert** [digitalcreations/MaxTo#204]
Tried to start MaxTo but I got this error:

![cantstartmaxtocauseneeds47](https://user-images.githubusercontent.com/35064193/34519817-386c3e62-f086-11e7-84b4-45df3e38df46.PNG)

So I clicked Yes to download it:

![downloaded47](https://user-images.githubusercontent.com/35064193/34519838-5223bdc6-f086-11e7-96ba-9074cf43f533.PNG)

But I am getting this error when I'm trying to install .NET:

![47notsupported](https://user-images.githubusercontent.com/35064193/34519868-71b7e91e-f086-11e7-9045-fd2228c17ec9.PNG)

Is this just a problem with my windows version not being updated properly or is this something that MaxTo can sort out in a new version?

**Comment by vegardlarsen** [comment]
Thanks for writing. Are you on Windows 10 Enterprise, which can block .NET Framework 4.7? 4.7 requires the Anniversary Update of Windows, can you check to see if you have it?

**Comment by Reapsert** [comment]
SOLVED: Sometimes it seems you're just too eager to install software before your PC is ready for it. I believe the clean Windows 10 install at first was version 1507 (build 10240) or version 1511 (build 10586), but after updating it to version 1709 (version 16299) MaxTo works flawlessly again!

**Comment by vegardlarsen** [comment]
Good to hear. :)
