### ISSUE TITLE
Persistent Windows

### ISSUE THREAD

**Issue by npapandreou** [digitalcreations/MaxTo#207]
When turning off my DisplayPort monitor, the windows are disarranged.
I found a utility, with source code provided, that eliminates to some extent, this behavior.

I strongly believe, that it should be embedded into MaxTo's functionality.

http://www.ninjacrab.com/persistent-windows/

**Comment by vegardlarsen** [comment]
This issue should be eliminated in MaxTo 2.0.0-alpha.2 and later. Please see the preview program for details: #220.
