### ISSUE TITLE
Altap Salamander [Filemanager crashes when using MaxTo]

### ISSUE THREAD

**Issue by LostinAllThatCode** [digitalcreations/MaxTo#208]
Altap Salamander has a built in interval viewer for *.txt and other unknown files.
This viewer automatically opens and maximizes a window when using the F3 hotkey.
Sometimes Altap Salamander crashes. This happens only if MaxTo is running.

I have added this line to __shims.xml__ to the `<ignore>` attributes:
`<windowclass title="Salamander's Viewer Window">Salamander's Viewer Window</windowclass>`
which i guess forces MaxTo to ignore windows with the given classname.

I don't know what the actual problem is but if it's not fixable could you guys add this filter to your shims.xml so maybe other Altap Salamander users wouldn't have this bug. 

Thanks alot. I really like your product.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. I will make sure to include this in a future release.

**Comment by vegardlarsen** [comment]
You can safely move the `<windowclass>` tag to `<no_subclass>` and have less loss of functionality. I have reproduced this issue on my machine, and will be distributing a fix for this issue with 2.0.0-alpha.3, see #220.

**Comment by vegardlarsen** [comment]
2.0.0-alpha.3 is now available for download.
