### ISSUE TITLE
Why shortcuts like last Winsplit-Version for EACH of WIN- windows are IMPOSSIBLE to set in MaxTo?!?

### ISSUE THREAD

**Issue by Blueearthmoon** [digitalcreations/MaxTo#209]
Hi,
why shortcuts like last Winsplit-Version for EACH of WIN- windows are IMPOSSIBLE to set in MaxTo?!?
MaxTo says to be "better" as Winsplit ... really?

**Comment by vegardlarsen** [comment]
Hi,

can you please elaborate on what you mean by "for each of win"? Are you referring to some sort of scripting support?

**Comment by Blueearthmoon** [comment]
Hi vegardlarsen,
with "each of WIN-windows" I mean each (application- etc.) window you have open like the browser- window, E-Mail-application- window, the WinWord- Windows, the PDF-application- window and more others.
In WinSplit you can set only ONE shortcut p.ex. like "Strg+EmtySpace+0" for all application- windows to direct positioning each application- window at a predefined position on your screen(s): So if you click on one application- window and press your shortcut "Strg+EmtySpace+0" -» (1) at the FIRST click you'll be asked to save the position of THIS application- window and if you (2) click (later) again this application- window with your shortcut "Strg+EmtySpace+0" THIS apllication- window will be situated at this position. If you choose an other application- window an press your shortcut "Strg+EmtySpace+0" it's the SAME (...).
Thx. for implement this feature - if you can.

**Comment by vegardlarsen** [comment]
So this is more of a memory feature (think calculators), where you press a shortcut to remember a window position, and you press another shortcut to apply that position to the active window?

**Comment by Blueearthmoon** [comment]
... there are presaved windows positions ... as I wrote, it's always the SAME predifined shortcut like "Strg+EmtySpace+0" to set EACH window to his predifined position back. You predefine the position with this (the SAME) shortcut like "Strg+EmtySpace+0", too. - If you press this shortcut the FIRST time, you'll be asked to save the actually win position of the app.
I don't know what you mean with "this is more of a memory feature (think calculators)". I noticed the claim of MaxTo to be better as Winsplit ... Winsplit do exactly that. Please try it out.

**Comment by Blueearthmoon** [comment]
... there are presaved windows positions ... as I wrote, it's always the SAME predifined shortcut like "Strg+EmtySpace+0" to set EACH window to his predifined position back. You predefine the position with this (the SAME) shortcut like "Strg+EmtySpace+0", too. - If you press this shortcut the FIRST time, you'll be asked to save the actually win position of the app.
I don't know what you mean with "this is more of a memory feature (think calculators)". I noticed the claim of MaxTo to be better as Winsplit ... Winsplit do exactly that. Please try it out.

**Comment by Blueearthmoon** [comment]
[sorry clicked accidentally to "close" ... the issue was NOT closed ;-)]

**Comment by vegardlarsen** [comment]
Hi, have a look at issue #220, as I believe the new recipe functionality in the previews will solve your issue.

**Comment by Blueearthmoon** [comment]
18-06-11: [Win7] Can't install/run alpha4 and alpha3 (ERROR doing setup.exe and setup.msi):
- doing setup.exe → Error: "Does not function anymore"
- doing setup.msi → Nothing happens without I found "MaxTo Wide Installer" in setup-dialog ...

**Comment by Blueearthmoon** [comment]
... in alpha5 you can only predifine shortcuts like "Strg+EmtySpace+0" to "Move" a window => "up", "down", "left", "right" and with "Focus" => "up", "down", "left", "right", "in", "out" ... and therefore not to a predefined (exact!) window-position. Look to winsplit, how they done it - also HOW TO define THIS window- Position, plz.

**Comment by vegardlarsen** [comment]
Direct placement is a command that will be coming, it may not be in version 2.0, but it will probably be there quite quickly afterwards.

**Comment by vegardlarsen** [comment]
This is now possible in MaxTo version 2.1.0 (currently in alpha).
