### ISSUE TITLE
Enhancement - Bind profiles to monitors on a per-screen basis

### ISSUE THREAD

**Issue by kevinjonesgarmin** [digitalcreations/MaxTo#213]
For my laptop I use at work, I have 3x 24" displays, each with their own Main and Alternate profiles. When I hop off to meetings, I have a profile I use for just the laptop display itself. When I work from home, I have a single 34" 4k monitor that I use with both Main and Alternate profiles. In each case, I have to manually change the profile, and then inevitably forget to change it back until windows snap-to in unexpected ways. 

It'd be nice to see a feature that binds profiles to whatever monitors are detected, and automatically restores those profiles. Another application I use--Stardock Fences--does this quite well, and with no required interaction from me. At the very least, it would be nice to have a "Master" profile switch in a sub-menu of the tray app, so I could save a "Home", "Work" and "Laptop" master profile that automatically applies my preferred display profiles.

Regardless, love the app!

**Comment by vegardlarsen** [comment]
@kevinjonesgarmin Thank you for reporting this. I am going to close this issue, as I have already fixed this in an upcoming release, MaxTo will no longer identify monitors by their number (1, 2, 3), but instead by their serial number (or if that fails, by a set of properties that are reasonably unique). This means that MaxTo will remember which monitor is connected, and whenever you connect a specific monitor, MaxTo will remember the regions you last used on that specific monitor.
