### ISSUE TITLE
Cycle windows in the region

### ISSUE THREAD

**Issue by ionoy** [digitalcreations/MaxTo#214]
First of all, great software!

My issue is "Switch to previous/next Window in region" seems to be stopping at the "edge" windows. So you need to remember if you need the previous or next window to switch to. Usually, it's not that many windows in each region. So why not add a hotkey to just cycle through all the windows?

Also, "Switch to previous/next Window in region" doesn't always work for me or requires multiple presses. Maybe it's the issue with the hotkeys though, I'm not sure.

Thanks!

**Comment by vegardlarsen** [comment]
We are adding cycling into this by default.

The "in region" part sometimes confuses people; the window has to be exactly the size of the region, meaning it doesn't include windows that are partially or completely in the region if the edges don't line up. 

Does that help?

**Comment by ionoy** [comment]
The windows are definitely "in" the region because I maximized them with the hotkey. Still, it doesn't always work and stops working entirely at specific windows. That's why I was confused about the cycling.

**Comment by vegardlarsen** [comment]
Which specific windows would that be? Is it windows from the same application each time?

**Comment by ionoy** [comment]
It was Chrome and Visual Studio Code in that case.

**Comment by llinfeng** [comment]
For Version 2.0.0-alpha3, I doubt if "cycling" has been dropped? If I keep executing the "Move window receipt", the window will get stuck at the right-most (or left-most) window.
