### ISSUE TITLE
Shortcut to change profile

### ISSUE THREAD

**Issue by jeff38100** [digitalcreations/MaxTo#215]
I am working to two different location and i haven't the same screen configuration. Can i change the profile with a shortcut ? Can i change profile with the command line ? (I can make .bat file)

thx

**Comment by vegardlarsen** [comment]
Hi Jeff,

currently you cannot set the profile using a shortcut key, but this is a feature we are working on.

Also, command line support is coming!

**Comment by jeff38100** [comment]
Thx, i hope the next version will have the command line support :)
