### ISSUE TITLE
can't create a specific layout, please make "changing regions"-tool easier/better

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#217]
I wanted to create the following layout:
Three areas:
One fourth of the total area each being in a rectangle at the top and bottom,
spanning from the left to right.
The third area having the rest (50% of the total area).

I can create something close to it by starting on no borders,
then do a 'split horizontal' and then do it again for each area, created after the first.
Now I have the area subdivided in four equal rectangles from top to bottom.
But if I click the 'remove' button, it just undoes one of the 'split horizontals'.

A solution would be, if could right-click the middle border from here and then click remove. However I can only do the remove 'command' on an area, not on a border. Since this is, as I understand it, some kind of location specific 'undo'-command, it relies on you to remember what you just did and isn't always helpful for getting you what you want. Remebering what you just did, is also next to impossible, when you load up an old or preset profile. It's usually the button you click, wanting for something specific to happen and you really hope that it'll actually do it. Mostly it does not, though.
It's also not like you could move border A into border B to make A disappear either, because then it would resize the stuff below border B (and using the mouse is too inaccurate, anyway and the borders seem to have a one-pixel window for resize-selection, which is a pain, if you have 3840 vertical pixels).
TBH, I never really understood how the resizing tool was supposed to quite work. I understand the split-commands just fine, but the 'remove' command and the general approach to take of making the borders to be exactly how I want them, always eluded me.

Please change this or if this is all possible and I'm just being super dense, then document it better please.

**Comment by vegardlarsen** [comment]
Thanks for writing! Can you do a quick drawing of what you want to do, so I can make sure I understand?

**Comment by davidermined** [comment]
There you go. 
<a href="https://imgur.com/H4P0bPe"><img src="https://i.imgur.com/H4P0bPe.jpg" title="source: imgur.com" /></a>
