### ISSUE TITLE
USB Display Adapter

### ISSUE THREAD

**Issue by jordan9095** [digitalcreations/MaxTo#218]
The window regions do not consistently save on a monitor that is connected via a USB display adapter. Mine is a USB to HDMI. I believe the issue is that MaxTo does not always read the monitor as the same monitor as before. My two monitors that stay plugged into the video card never have an issue and are always appropriately numbered 1 & 2 in the MaxTo software. 
The monitor number changes randomly for the monitor connected via the USB adapter. It is currently 55 (started around 17 I believe). As a result of MaxTo thinking it is a newly connected monitor, the regions are not saved. This typically happens after I restart, put the computer to sleep, or more obvious - switch ports for the adapter.

**Comment by vegardlarsen** [comment]
This is a known issue, which we are fixing in the next release (which, because of the scope of the changes, will be an alpha release for a while first). It is the same as #206, so I am closing this issue.
