### ISSUE TITLE
Impossible to install hooks

### ISSUE THREAD

**Issue by OliverSWyck** [digitalcreations/MaxTo#219]
Server: Windows Server 2012 R2
Roll: Terminal Server / RDS
WinSplit Revolution v11.03

All users get the error message "impossible to install hooks" a few minutes after loging onto the Terminal Server Session.
This effects also the administrator.

When selecting the tixbox "dont continue to show" (Diese Meldung nicht mehr anzeigen/germen) the message will popup at the latest when logging on again. 

![grafik](https://user-images.githubusercontent.com/38938855/39572785-d8789e84-4ed0-11e8-8b4e-3f57d3b21b91.png)

**Comment by vegardlarsen** [comment]
Hi Oliver,

we are not the maintainers or owners of WinSplit Revolution, and cannot help you with this message.

**Comment by OliverSWyck** [comment]
Oh, my bad! It seems that TaxTo took over the URL and the link is forwarded.
Thanks for your feedback

**Comment by vegardlarsen** [comment]
Yeah, we took over the domain after they disappeared from the internet because we felt their users would find some use in our product.
