### ISSUE TITLE
Announcing MaxTo 2.0.0 previews

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#220]
I am happy to announce that we are starting open previews of the next version of MaxTo today. I strongly recommend reading through this introduction to familiarize yourself with the changes.

### Brand new bugs!
  
Let's just be honest here: this is a preview program. That's right, we've fixed a lot of bugs, and probably introduced a lot of new ones. Don't expect anything to work well in the early alpha releases.

We've basically rewritten everything from scratch, so expect some crashes.

### Brand new user interface

We've separated the user interface from the underlying functionality in MaxTo, and re-implemented it completely.

This means that everything should feel a lot nicer and fresher; and it should look a lot better on Windows 10!

It also means that we now have full, complete mixed-DPI support! Finally!

### Recipes

Recipes are a powerful new feature of MaxTo, that replaces the previous keyboard shortcut functionality. A recipe is a set of commands assigned to a keyboard shortcut; which means that you can run a lot of commands using one keystroke.

Commands that are ready now include:

- **Move a window** into a region
- **Focus on a window** in a given direction
- **Center a window** on a given monitor
- **Load preset** on a specific monitor
- **Highlight regions** on a given monitor (or on all monitors)
- **Launch a program**
- **Maximize to screen**

You can mix and match these commands as you see fit; and we have nice editors for their arguments in the user interface.

### Open source documentation

We've started writing proper documentation. Obviously it is not finished as of now, but we have published what we have on the preview website.

Also, if you have suggestions, you can [edit the documentation directly](https://github.com/digitalcreations/MaxTo). We will include any approved changes on the website as it is updated.

### Virtual desktop support

You can now have different regions on each virtual desktop. Or you can have the same regions on all virtual desktops. It's a setting.

### Automatically updated compatibility shims

We can now update the compatibility shims (that ensure MaxTo is compatible with other programs) without releasing a new version of MaxTo. You can selectively disable the shims on your machine if desired.

### Monitors are identified by serial number by default

This is a bigger deal than it seems. Previously MaxTo used the monitor number as reported by Windows. That meant that if you had two monitors, MaxTo would only know of them as monitor 1 and monitor 2. If you detached monitor 1, its regions would be applied to the second monitor, as that monitor got renamed "monitor 2", and the settings for the second monitor would be forgotten.

Now MaxTo knows the serial number of each monitor, and will remember the settings for that monitor forever.

### New settings system

We've introduced a new, JSON-based, settings system that automatically reloads any changes to the configuration file immediately. You can find MaxTo's settings in `%AppData%\MaxTo%` (by default, [you can change this](https://preview.maxto.net/docs/configuration/location) to e.g. store them in your Dropbox).

### New installer

Our new installer is based on [Squirrel](https://github.com/squirrel/Squirrel.Windows), which means we get automatic updates and delta packages "for free". So that's good.

### Command line support

The recipes and commands are designed to work well with a command line interface, so expect to see this to pop up shortly. You'll be able to do things like (syntax may not be final):

```
C:\> maxto window move -Window "Untitled - Notepad" -Position 0,0 -VirtualDesktop 3
C:\> maxto recipe "Notepad on the left"
C:\> maxto preset load "4x4" -Monitor "Dell U3011 (DP)"
```

### Translations

All the translation options are missing in this initial alpha release, but it is coming back.

## What was removed?

Quite a few things from previous versions of MaxTo where removed, and will not be re-introduced:

- **Self-test** is gone forever, as it frequently produced false positives.
- **Alternate regions** will not be coming back. It is now extremely simple to load presets by assigning them to hotkeys. The additional complexity of having multiple regions applied at once made this one an easy choice to remove.

## Why 2.0.0?

We are jumping on the [semantic versioning](https://semver.org/) bandwagon. Basically this means that you should be able to tell if there are breaking changes in the version that you are updating to just from the version number.

Since we had previously used `<year>`.`<month>` to identify releases, we chose to start at version 2.0 for semantic versioning purposes. Version 2.0.0 nicely reflects what we intended; namely that this is a major upgrade for MaxTo.

## What happened to the pricing?

As you can probably see from the preview website, we've changed our prices. The new prices are differentiated between personal and business licenses.

### Personal licenses

These licenses work as they always have, buy it and you have a lifetime license for anyone in your household.

The price will be $29, which is a price hike from the previous $19. We still think this is quite cheap for a tool such as MaxTo, that you can use for the rest of your life without purchasing another license.

### Business licenses

Business licenses are new in that they require renewal every year. The price starts at $19/user/year, and we give significant discounts for purchasing more than one year at a time, as well as volume discounts.

Site licenses are of course still available.

### Previous licenses

All licenses that are purchased under the old system will continue to be valid going forward.

Note that to use version 2.0.0 or later (including the preview releases), you will need to [exchange your old license key for a new one](https://preview.maxto.net/license/exchange).

## Get started

You will have to do a few things to get started.

1. Uninstall any previous version of MaxTo (**important**)
2. Download and install the alpha release from [the preview website](https://preview.maxto.net)
3. Get a license:
   - If you have a license issued before May 9th 2018, you can [exchange your license for a license in the new format](https://preview.maxto.net/license/exchange).
   - If you do not have a license, you can test our new website by "purchasing" a license with a test credit card number (`4242 4242 4242 4242`) on the preview website. These licenses will be revoked when the preview program ends.

**Comment by atollis** [comment]
![image](https://user-images.githubusercontent.com/4598812/40454588-ae0bba8e-5f2c-11e8-9008-0915713c3fdf.png)
I get this error when trying to create a new license at https://preview.maxto.net/license/exchange

**Comment by sheldonhull** [comment]
This seems promising. I've never found a perfect fit for windows based users other than WindowPadX, but it's still not one I'd say fits perfectly. If this solves the window arrow key mapping and more then this is going to be one to recommend. 

I'm getting the failure as well, so not able to install. 
I'd throw out there that the experience of being told "No trial for you on alpha" comes across a little unfriendly, though I know you didn't mean it that way. It's kinda like being told, "You took the time to download and alpha and aren't worthy to try it" :-)

**Comment by vegardlarsen** [comment]
@atollis I've corrected the website and you should get a proper error message now. Basically the problem was that it could not find your existing license, and I hadn't gotten around to creating a proper error message for that.

**Comment by atollis** [comment]
I purchased a license on 19 May but it does not work for the preview

**Comment by vegardlarsen** [comment]
I have just published 2.0.0-alpha.3, which fixes the following issues:

- Fix transparent windows turning opaque after dragging. See issue #141.
- Fix Office apps fail to display context menus. See issue #221.
- Fix issue with compatibility shims storing to working directory, now
stores in `%LocalAppData%\MaxTo\shims.json`.

The release should automatically be applied after two restarts of MaxTo (I know, that's weird, working on it), you can check which version you are currently running under Settings, About.

**Comment by Blueearthmoon** [comment]
18-06-11: Can't install/run alpha4 and alpha3 (ERROR doing setup.exe and setup.msi):
- doing setup.exe → Error: "Does not function anymore"
- doing setup.msi → Nothing happens without I found "MaxTo Wide Installer" in setup-dialog ...

**Comment by skewty** [comment]
Is there a **beta 6** release out yet?

**Comment by vegardlarsen** [comment]
@skewty I am currently on paternity leave, so it will be a while before the next release. If you have any suggestions/crashes/other issues, feel free to let us know here... :)

**Comment by vegardlarsen** [comment]
I have just opened up [the translation project on POEditor](https://poeditor.com/join/project/bIKpeRO8fb) for MaxTo version 2.0. 

I hope anyone interested in getting MaxTo in their language will take the time to contribute the best possible translations. **I am asking the community for help** here because our experiences with translation services have previously not given the best results. 

The following languages is now open for translation:

- Chinese (simplified)
- French
- German
- Italian
- Korean
- Russian
- Spanish

These languages have been selected based on the usage patterns of our users. We hope to add more languages shortly, but feel free to request languages as new issues here if you are willing to help with the translation.

For reference; I translated everything to Norwegian in approximately 4 hours of total work.

**Comment by vegardlarsen** [comment]
2.0.0 alpha 6 is now out. Since 2.0.0-alpha.5, we've done these cool things:

- Added localization support. For now Norwegian and English have been translated.
  [Help us get MaxTo translated to your language](https://poeditor.com/join/project/bIKpeRO8fb).
- When editing your regions:
  - You can look up the details of your monitor using our new, handy "Monitor info" button.
  - "Save as preset" now saves what you've set up, not something else entirely.
    See [issue #248](https://github.com/digitalcreations/MaxTo/issues/248).
  - "Save as preset" is now cancellable.
  - Fixes size and placement on mixed DPI machines.
    See [issue #239](https://github.com/digitalcreations/MaxTo/issues/239).
  - Shows physical and logical pixels when setting regions on monitors with DPI scaling.
  - Set regions windows are now topmost.
- In the settings:
  - More accessible buttons when editing recipes.
    See [issue #246](https://github.com/digitalcreations/MaxTo/issues/246).
  - First-level navigation menu now collapses when editing recipes.
  - Clear up language around window snapping.
  - Add a small text to let you know if MaxTo is currently running elevated.
    See [issue #244](https://github.com/digitalcreations/MaxTo/issues/244).
- Improved the first run welcome dialog, and added a 30-day trial.

**Comment by vegardlarsen** [comment]
2.0.0 alpha 7 is now out. It fixes a problem with the welcome screen when already registered.
See issue #257.

**Comment by vegardlarsen** [comment]
Beta 1 is now available, and we have launched the preview website as the official website.
