### ISSUE TITLE
MaxTo 2.0.0-alpha3: windows become transparent after several rounds of "maximization".

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#222]
If I keep executing the following "recipe" for a couple of times, the window under operation will become transparent.
# The recipe
![setting](https://user-images.githubusercontent.com/5890407/40560414-f0cb711a-6027-11e8-91e5-0e2aa0bb1a52.jpg)

# Issues with transparent windows, for Firefox and GVim

* Fully transparent Firefox window, with solid setting at the background.
![transparant_window3](https://user-images.githubusercontent.com/5890407/40560442-06d6732e-6028-11e8-8a98-80876689098a.jpg)
* Transparent Firefox window
![transparant_window2](https://user-images.githubusercontent.com/5890407/40560443-0711d964-6028-11e8-95a8-c622d1f98ab8.jpg)
* Transparent Gvim window over Firefox
![transparant_window1](https://user-images.githubusercontent.com/5890407/40560445-07339a68-6028-11e8-953d-ee9fd870c49f.jpg)

**Comment by vegardlarsen** [comment]
I am looking into this, it seems to be timing-based, and only appears to happen on one of my machines.

**Comment by llinfeng** [comment]
@vegardlarsen I think the track for reproducing is to toggle the function a good number of times. Say, more than 10 times or so. At a certain point, the transparency will be established *successfully*, and the effect should be persistent afterwards.

**Comment by vegardlarsen** [comment]
This should be fixed in alpha4.

**Comment by llinfeng** [comment]
@vegardlarsen How to get alpha4? I am in alpha3, and did not find an option to "update".

**Comment by vegardlarsen** [comment]
Alpha 4 is not ready yet. See the [milestone](/digitalcreations/MaxTo/milestone/8).
