### ISSUE TITLE
MaxTo 2.0.0-alpha3 system_maximize is not always on the correct screen

### ISSUE THREAD

**Issue by NKame** [digitalcreations/MaxTo#223]
In Winsplit Revolution, I moved a lot maximized windows between screens.

With MaxTo 2.0.0-alpha3, when I do "maximize" -> "move" (which brings me to next monitor, but I lose maximization) -> "maximize", the maximization tends to happens on the original monitor, not the one where I moved the window to.

**Comment by vegardlarsen** [comment]
You should be able to do both operations in one in many cases. You can specify a monitor for the `system_maximize` command, so if you want to place a window maximized on a monitor, you'd use that command and set its *Monitor* property.

I'm thinking about adding `$next` and `$previous` as options for the monitor property, so you can move windows around quickly.

That said, does this happen when you assign all of the commands into a single recipe, or when you execute each step as separate recipes?

**Comment by NKame** [comment]
I can't really do it in one recipe like in Winsplit Revolution: I would need a conditional like "if the window was maximized before moving". My use case is really about keeping the maximization state and the region as two separate information. For instance, I just did a test: window on the top right region on the right screen, maximize -> maximized on the right screen, move left -> window moved to the left screen, BUT at the bottom, not a the top. (Ok, that last sentence is not really useful ^^;)

**Comment by NKame** [comment]
Or maybe it could be done in one recipe if the window state was at the same level as the keybinding, this way we could have two recipes with the same keybinding.

**Comment by vegardlarsen** [comment]
I think you could do this so it always works:

1. `system_maximize` on the active window
2. `center` window on the monitor you want it
3. `system_maximize` again

This relies on the fact that currently, `system_maximize` is a toggle; it maximizes a window to the monitor if it wasn't maximized, or it restores the window if it does. This means, put the window in the same state that it was but on this other monitor.

Currently, with the `center` command (and all other commands), you can only specify a monitor by number. I am thinking of adding variable support here, so you could `$previous` and `$next` as values here.

**Comment by vegardlarsen** [comment]
Closing as this is not really a bug.
