### ISSUE TITLE
MaxTo 2.0.0-alpha3: Positioning difference between shortcuts and maximize. 

### ISSUE THREAD

**Issue by acasto** [digitalcreations/MaxTo#225]
When positioning windows with hotkeys it leaves a small gap between between the region border and application window. Maximizing into the region the usual way cause this. However after positioning via hotkey trying to re-maximize it will cause it to restore back to the previous region which then needs to be dragged over and maximized in the desired region, thus defeating the purpose of hotkeys.

**Comment by vegardlarsen** [comment]
Can you provide a screenshot and which applications this happens to? Preferably default Windows apps if you can find any?

**Comment by vegardlarsen** [comment]
I have determined what caused this, and a fix will be available tomorrow.
