### ISSUE TITLE
MaxTo 2.0.0-alpha3: Doesn't adjust after disconnecting/reconnecting monitor.

### ISSUE THREAD

**Issue by acasto** [digitalcreations/MaxTo#226]
Not sure what the behavior is supposed to be in this situation for this version. It does seem to recognize the change in resolution where the old version needed to be reloaded, however I'm not sure what to do about needing to reposition every window after my monitor goes to sleep. Is this something that will eventually be handled automatically or does it need a recipe?

**Comment by acasto** [comment]
Looked into this a bit more and it seems that it's not detecting that the monitor has changed. Going to "Change regions" shows the same monitor that is present when MaxTo is first loaded. It also wasn't creating the profiles of new monitors in %AppData%\Roaming\MaxTo\Monitor when switched. Reloading MaxTo did cause the correct profile to be created/detected, but again that would stick when reconnecting until reloaded.

**Comment by vegardlarsen** [comment]
I have figured out what caused this, and the changes will be in alpha 4, probably ready sometime tomorrow.
