### ISSUE TITLE
'your keyboard shortcuts have been changed'-message

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#227]
The conflicting keyboard shortcut message upon starting MaxTo is too vague and unspecific. It should tell me, if the MaxTo default shortcuts have been changed or if the Windows-shortcuts have been changed.
It should also tell me which shortcuts or which options have been changed in what way.

**Comment by vegardlarsen** [comment]
I agree, and the message is completely gone in the 2.0.0 preview versions.

The message was meant to only be displayed to users who upgraded from Windows 8.1 to Windows 10, but somehow it shows for all Windows 10 users.
