### ISSUE TITLE
Enhancement - Gaps between windows

### ISSUE THREAD

**Issue by chris-gilbert** [digitalcreations/MaxTo#228]
Hi there,

I'm a longtime user of i3-gaps in Linux, and I recently started trying MaxTo on Windows. I'm very pleased with it so far as it makes my 4k multimonitor setup much less cumbersome!

One feature I really miss though is the ability to set up a gap between different windows. I work with a lot of text (coding, mostly) and having a visual separator between terminals--supported by a background that gives a decent amount of contrast--makes it much easier to maintain focus in the current window.

I can _almost_ set this up by segmenting out a region in between my actual windows, but the smallest region I can configure is something like 100px.

Ideally, there would be a configuration option to set a gap width around the border of each monitor, as well as the size of the gaps between windows.

For reference, here's just a quick sample of what 4 temrminals looks like with gaps:
![vd1-bash](https://user-images.githubusercontent.com/3208589/41102095-02cbb152-6a34-11e8-8c41-b4a0d9c5f923.png)

And a couple other screenshots, courtesy of r/unixporn/:
![lqnbh0s2pj1y](https://user-images.githubusercontent.com/3208589/41102495-04c0129a-6a35-11e8-916e-3d748715e93c.png)
![i3-gaps-wiki](https://user-images.githubusercontent.com/3208589/41102496-067ad4e4-6a35-11e8-8482-b8f891228b8b.png)

This is a great product, and I appreciate the effort you put into it.

Thanks!
Chris

**Comment by vegardlarsen** [comment]
I've been thinking about this, and it shouldn't be that hard to do. However, I won't have the opportunity to put this in until after version 2.0.0 is released; 2.1 seems like a good place to put it.

The method I'll probably end up using:

- .NET/XAML margin/padding syntax, which is different from CSS:
  - `0,10` means 0px horizontal padding, 10px vertical padding
  - `0,1,2,3` means 0px left padding, 1px top padding, 2px right padding, 3px bottom padding
- Padding for each individual region that is set when the region is defined.
- Global padding that applies to all regions (can be negative), so you can overlap windows by default.
- Additional padding settable via compatibility shims.

**Comment by vegardlarsen** [comment]
Actually, I'm closing this issue because of #149, which is basically the same request. :)
