### ISSUE TITLE
MaxTo 2.0.0-alpha4 region editors don't line up with monitors

### ISSUE THREAD

**Issue by repentsinner** [digitalcreations/MaxTo#230]
@vegardlarsen, when I go to change regions in MaxTo 2.0.0-alpha (either 3 or 4) the regions don't re-open in the correct place on my monitors. They work correctly, just don't seem to edit properly - the left one is shifted over by ~15 pixels, the right by a few hundred.

It would be nice if the region editor windows maximized/snapped into place on the monitors.

![maxto offset regions](https://user-images.githubusercontent.com/4462072/41505340-c95d87b2-71bb-11e8-918c-c52bfda2468d.png)

Also will there eventually be a license exchange mechanism for licenses issued after May 9th, or will those licenses just work directly in MaxTo 2.x once it leaves prerelease?

Thanks!

**Comment by vegardlarsen** [comment]
I apologize for the extremely slow response to this. I have been away on paternity leave, and apparently the e-mail notification for this issue just went by me.

Licenses bought after May 9th will of course work when we release this as a non-preview release (we haven't quite decided if that will be when we hit beta or final).

I will have a look at reproducing your issue in the next few days or weeks as I catch up.

Are both monitors at the same DPI?

**Comment by repentsinner** [comment]
Hi, not to worry. Congrats on the new child!

Both displays are at the same model (Benq BL3201PH), resolution (3840x2160), refresh rate (60Hz), and Windows scale factor (125%), connected to multiple outputs of a single GPU (NVidia Quadro P6000).

If the task bar is at the bottom of the left display or on the right display, the left region editor does a better job of landing in the right place, so I guess the task bar position/size logic needs some testing. The region editor for the right display seems to be incorrect regardless of where the task bar is.

FWIW this issue remains in alpha5.

**Comment by vegardlarsen** [comment]
This could very well be related. I have done a poor job earlier of testing with the taskbar on the side; so I will have to try this out in the next few days.
