### ISSUE TITLE
Main region always copying alternate region layout

### ISSUE THREAD

**Issue by vincentmathis** [digitalcreations/MaxTo#231]
Sometimes on startup or seemingly random the main region behaves like the alternate region.
Although when configuring the main region it looks like the main region was configured. 

After clicking done the main region works like before.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. This will not be fixed.

The reasoning is that we are putting all of our efforts into the 2.0 version of MaxTo, which is available from issue #220 as a preview. In that version, there are no more alternate regions; there is only one set of active regions at a time.

I am therefore closing this issue.
