### ISSUE TITLE
Install stops at Netframework 4.61

### ISSUE THREAD

**Issue by ejbcpask8** [digitalcreations/MaxTo#233]
Just contributing to the cause!  :)

The install does not complete.  the installer seems to run twice at one mouse click.  Both versions want to install Microsoft net framework 4.61.  When trying to install a message pops up and the install fails.  Tried to work around and install 4.61 directly and that did not work.  Net Framework 4.71 is install on my machine running windows 7 pro.

[error message.pdf](https://github.com/digitalcreations/MaxTo/files/2159491/error.message.pdf)

Ed

**Comment by vegardlarsen** [comment]
Thanks for reporting this. I recommend you try out the preview versions (see details in issue #220) instead. We won't be making any updates to the currently published version, and we've completed changed the installer software so this may no longer be an issue.

PS! I am currently on paternity leave, so I may not respond as quickly as I'd like.

**Comment by vegardlarsen** [comment]
If this is still an issue in the preview releases; please let me know here.
