### ISSUE TITLE
Chrome won't snap to region when being moved from a currently snapped region

### ISSUE THREAD

**Issue by octovert** [digitalcreations/MaxTo#235]
I have to move the window, then grab it again with the hotkey to snap to a region.

**Comment by octovert** [comment]
no, it's literally every time i grab a chrome window to move it.  Repro is
100%, on multiple PCs

**Comment by vegardlarsen** [comment]
Which version of MaxTo are you running? Is this on the preview versions (see issue #220 for details)?

**Comment by octovert** [comment]
Version 2017.7.0.0

**Comment by octovert** [comment]
Just downloaded the preview version.  2.0.0-alpha5.  The issue does not seem to be present.

**Comment by ledicjp** [comment]
I have the same issue and only with the latest Chrome... The funny thing is it also happens with all similar software to MaxTo so I'm extremely frustrated and may switch to Firefox because of that

**Comment by vegardlarsen** [comment]
This issue is no longer present in MaxTo 2.0.0-alpha.5 and Chrome 69.
