### ISSUE TITLE
wrong splitting

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#238]
150% scaling settings (recommend),
resolution of 3840x2160
I split the main regions from no borders set to applying a horizontal split
and then in the upper region I added another vertical split.
Expected behaviour:
The upper region is split in two regions of equal length, because 3840 is divisible by 2.
Observed behaviour:
The left region had a width of 1762, the right one of 2063.

That's not what I wanted it to do and I don't think, that's how the program is intended to work.
![maxtosplitbug](https://user-images.githubusercontent.com/23729465/42758267-453cc90c-8903-11e8-8ccb-a1cd7ad07804.PNG)

edit: Just saw that there's a 2.0.0 preview. I'll just switch to that.

**Comment by vegardlarsen** [comment]
Closing this at it will not be fixed.
