### ISSUE TITLE
2.0.0 4k mistaken for 2k-ish resolution; lost pixels

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#239]
My monitor is 3840x2160.
MaxTo shows it as 2558x 1558, so it thinks it's 2560x1440 and then cuts off another 2 vertical and 2 horizontal pixels.

![image](https://user-images.githubusercontent.com/23729465/42759643-ff693816-8907-11e8-8d09-8aa547fade3a.png)

**Comment by vegardlarsen** [comment]
I don't know the exact reason for this; but I'd like to know:

- do you have multiple monitors at different DPI settings?
- are the actual regions the correct size?

**Comment by davidermined** [comment]
No, I use an external monitor with MiniDisplayPort for a laptop with the laptop lid closed and the laptop screen not being listed in Windows anymore.
Yes I think so. Haven't reinstalled yet, so I can't reopen the program anymore.

**Comment by vegardlarsen** [comment]
I am fixing this to make it more clear in the next release.

![image](https://user-images.githubusercontent.com/436508/46596845-180f3380-cade-11e8-9516-fd5770bd397e.png)

This is an issue of logical pixels vs physical pixels when doing DPI scaling. On monitors where DPI scaling is active, we will now show both measurements, with priority to physical pixels.

PS! I have also fixed an issue where the set regions windows did not fully cover some monitors. Both of these will be made available in the next release.
