### ISSUE TITLE
2.0.0 snapping not well explained

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#240]
I don't know what these options mean. "How close do you have to be..." doesn't make sense as a help text.
'I' am outside the plane behind the monitor. I don't think the 'snap to region edges work, but I can't read out the expected behaviour here, anyway.
Is it the distance of any edge of a window to one of these things? Or the distance from the corner of the window to one of these things? When does it trigger the snapping?
Once I let go off the moved window or will it show a snap-outline first, letting me choose or will it just snap the window out of my hands, whilst I am moving it?

<img width="596" alt="maxtounclear" src="https://user-images.githubusercontent.com/23729465/42759763-719d9120-8908-11e8-8a9c-b5e63beb58db.PNG">

**Comment by vegardlarsen** [comment]
I will try to add a descriptive introduction text here.

Draft:

> When you drag or resize windows; the window will automatically snap to these other edges:

**Comment by davidermined** [comment]
Yes, but what does the snap distance mean exactly?

**Comment by vegardlarsen** [comment]
I have changed this for the next release. There will be a text at the top: "MaxTo can make windows snap to other windows, region edges and monitor edges when you move or resize a window."

The label under "Snap distance" will read: "Minimum distance between edges before snapping is triggered".

Does that represent things more clearly, @davidermined?

**Comment by davidermined** [comment]
No it doesn't. Consider 'Window Snapping' is enabled and you have a window ('Snapper'), that another window ('Snapee') could potentially be snapped to:
Snapper is of a different size than the Snapee, does that mean, that the Snapee is changing it's size? If so, in what way does it change its size? Does a whole side of the Snapee be in the Snap-area of the Snapper or does it only have to be a part of a side?
What if the Snapee gets moved into the vertical and horizontal snap-area of the Snapper?
Does snapping vertically mean, that the snappee fills out the rest of the monitor above or below a Snapper? Or does it mean, that it fills out a predetermined region? (same questions for horizontal)
Just ask a couple people unfamiliar with the software and ask them to predict exactly what a specific window movement or resize would do on pen and paper. If would bet, that they are unsure or they come up with multiple solutions. People shouldn't have to learn your software by trial and errror.

If you want people to understand what that feature does exactly, it probably needs a small gif playing right there in the settings. Or at the very least a YT-video showing off, all of the possible "window A moves into the snap-area of region/monitor/window B"-permutations.
Just one small example scenario, that I scribbled down, where a Snappee (window 2) gets moved alongside the x-axis and gets partially within the snap-area of the snapper (window 1). No idea, what your software would do here.
[Scan 2018-10-04 15.30.48.pdf](https://github.com/digitalcreations/MaxTo/files/2446507/Scan.2018-10-04.15.30.48.pdf)

**Comment by vegardlarsen** [comment]
You are right, a video would be very helpful here. This is something I want to do, and we have been working on for the website. I am unsure about shipping it with the software though, as it would add considerably to the size of the download (unless we can play it online).

This is probably not something that we will get to right away.
