### ISSUE TITLE
2.0.0 rubber icons doesn't look rubber-like enough

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#241]
I thought it that's where I would move the borders, only then to delete my borders.
I thought with frustration that I couldn't move the borders at all.
Then at some point I saw the "psst..."-hint.
A trashcan might be more obvious.

![image](https://user-images.githubusercontent.com/23729465/42760251-21cc144e-890a-11e8-9433-7b045e2158cf.png)
I'd expect the lower rectangle edge of a stylized rubber to not be snug with the upper rectangle's edge. The lower part should have less width.

**Comment by vegardlarsen** [comment]
I want to try to stick as closely to Microsoft's design language as possible, and this icon is the recommended icon for "erase". See [Segoe MDL2 Icons](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font).

**Comment by vegardlarsen** [comment]
(Note that I do not necessarily disagree with your assessment here, the icon is far from perfect).
