### ISSUE TITLE
2.0.0 workaround settings

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#243]
Doesn't tell me what exactly is enabled or disabled here. The text below wont tell me, if I should click the slider as the last step or not click the slider after doing the Adobe-stuff to get my Adobe reader compliant with the program.
![image](https://user-images.githubusercontent.com/23729465/42760616-4dc3714a-890b-11e8-987a-4888f54f6729.png)

**Comment by davidermined** [comment]
Also the text is not selectable. That means I can't copy and paste the path of the '.shims' into my explorer. If that's a drawback of the fancy new Windows design, please give me a Windows XP-era menu.
Non-selectable text in system messages, option menues, error messages is literally worse than cancer.

**Comment by vegardlarsen** [comment]
Note that this text (for Adobe Reader), was written for the previous versions of MaxTo. The text itself will change when we launch 2.0.0.

Details about shims will be documented in the new documentation; which you can edit in this repository (but probably its best to wait until we get properly started on it ourselves).
