### ISSUE TITLE
2.0.0 elevation mystery

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#244]
Should tell me, wether the program has elevation or not. It doesn't. I click it, it restarts and I'm not sure if it even worked. 
![image](https://user-images.githubusercontent.com/23729465/42761279-595f551c-890d-11e8-9c0c-b0410a4ad771.png)

**Comment by vegardlarsen** [comment]
Should be an easy fix to add a text that states the current setting. In my mind the presence of the "Enable elevation" button should indicate that it is currently not elevated, but it doesn't hurt to be explicit.

**Comment by vegardlarsen** [comment]
I have fixed this issue and it will be in the next release.
