### ISSUE TITLE
2.0.0 Recipe Creation screen weird button layout

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#246]
It's not really clear which buttons do what here. I didn't immediately see what to do here.
I was really thrown by the eccentric positions and the lack of labels on the button.
Why reinvent the wheel instead of doing things in a way, that everybody understands immediately?

![image](https://user-images.githubusercontent.com/23729465/42761743-aad05cb0-890e-11e8-962d-5592314d70b1.png)

**Comment by vegardlarsen** [comment]
Agreed. The buttons are temporarily placed there until I can figure out a better way to place them that makes sense. Hopefully we will get to this by 2.0.0 final.

**Comment by vegardlarsen** [comment]
Closed by mistake. :)

**Comment by vegardlarsen** [comment]
I think this will be a lot better:

![image](https://user-images.githubusercontent.com/436508/46612485-f4191580-cb10-11e8-9129-9c19886ae6b7.png)

Will be in the next release.
