### ISSUE TITLE
2.0.0 region-line helpers should be snappable

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#247]
People who buy screen-dividing software are often the type who want the pixels to be EXACTLY right. The guidelines are really sweet and the golden ratio marker a nice touch. In version 1 I found hitting the right pixels one of the biggest pain points. I wish I could snap onto these very helpful markers. Maybe make them snappable, if the cursor moves the border within 20 pixels of the edge, where they appear?

![image](https://user-images.githubusercontent.com/23729465/42762399-92523896-8910-11e8-9943-280fc3e16bff.png)

**Comment by vegardlarsen** [comment]
I want this to happen, and I tried to make it happen. The control we use (WPF's GridSplitter) does not support snapping, and I don't know of any way to make it support it. Therefore, this request will not make it into 2.0.0 final.
