### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by jordan9095** [digitalcreations/MaxTo#250]
After the most recent windows update, MaxTo crashes immediately after I launch it.

**Comment by maneskiold** [comment]
I have the same problem. Can't launch it as of today. Tried reinstalling but didn't help.

It's the 2.0 preview that I have problems with.

**Comment by vegardlarsen** [comment]
I apologize for the slow response, I am currently on paternity leave.

@maneskiold There should be a `maxto.log` file in `%AppData%\MaxTo` that you can take a look at or paste here for debugging.

@jordan9095 The older version is trickier to figure out, as we don't have any logging. I am hoping the feedback from @maneskiold may help trace down what this is.

Are any of you on Windows Insider releases?

**Comment by maneskiold** [comment]
This is the log file, and it's today Aug 24th it started not working, but I see some exceptions on the 23rd as well, but no idea what they mean ofc :)

[maxto.log](https://github.com/digitalcreations/MaxTo/files/2320023/maxto.log)

**Comment by maneskiold** [comment]
Some progress. I uninstalled and removed the old %appdata%\maxto and reinstalled the 2.0 preview, and now it seems to be working again. The log file said something about problems running in elevated. Maybe that's what causing problems? 

Working for me again now anyway.

**Comment by jordan9095** [comment]
2.0 works for me but only on my main display. I'm not on a windows insider release.

**Comment by jordan9095** [comment]
I'm still having trouble launching the older version of MaxTo after the new Windows update. Is there any way I can get a refund if it is no longer being supported or updated?

Thanks

**Comment by maneskiold** [comment]
I think contacting them on support@maxto.net is the best way to ask about refunds. 

I got the preview working etc anyway, don't think I had to do anything special except removing all config files as stated in my previous post. Haven't tried the old version again.

**Comment by jordan9095** [comment]
2.0 has too many problems for me lol and don't really want to deal with all the bugs right now. I don't have the most traditional monitor setup (two 34" 1440p ultrawides and 27" 1440p traditional monitor) & it causes 2.0 to go haywire. I need software like MaxTo to work efficiently and is well worth the cost if it works. I actually found an old download link for a version from 2015 and it is working the best out of any of them so far. Go figure

**Comment by vegardlarsen** [comment]
@jordan9095 It should still be supported, but this is not something that a lot of people are having issues with. We are working full steam on the preview releases, which should work well on Windows 10 (I am running it right now).

If you can get me a crash report from the previous releases I can take a look (they should be stored as `Exception_*.zip` files in the `%ProgramFiles%\MaxTo` folder). Feel free to send those to support@maxto.net for privacy reasons.

**Comment by vegardlarsen** [comment]
I am assuming this is the same problem as in #236 and #260. Those issues have been fixed in 2.0.0-beta.2, which will be out on Monday.

**Comment by jordan9095** [comment]
My issue was with the older stable version, not the 2.0 beta

**Comment by vegardlarsen** [comment]
I apologize, you are of course correct. However, we will probably not be making any large updates to the legacy versions, all development is focused on the new, preview releases. I suggest you try them out to see if it solves your problem.
