### ISSUE TITLE
Chrome wan't to delete MaxTo

### ISSUE THREAD

**Issue by jeff38100** [digitalcreations/MaxTo#251]
Incompatibility with chrome. Lot of people need an 2018's version.

![capture](https://user-images.githubusercontent.com/8981941/44620430-576a2380-a894-11e8-8144-59f99f4fe3a9.PNG)

Thx

**Comment by vegardlarsen** [comment]
Which Chrome version is this?

PS! I apologize for the slow response time, I have been on paternity leave.

**Comment by jeff38100** [comment]
Hi,

Congratulations ! My twins born a few months ago too.

My computer was infected by a virus. I have reset it and all work well now.

No problem for the moment

Thanks for your questions.

**Comment by vegardlarsen** [comment]
Congratulations to you too :)

In the case of a virus, I am going to close this issue. :)
