### ISSUE TITLE
Assigned monitor numbers don't match what windows assigns to them

### ISSUE THREAD

**Issue by SphinxJ** [digitalcreations/MaxTo#252]
Been having an issue that is mainly caused during a restart of the computer. I am using three monitors, 2-1-3 from left to right, and when I reboot my computer, MaxTo assigns them different numbers almost every time, currently 2-3-1. The issue I have with that is I use different profiles for my left and right monitors that now keeping getting switched up when I log into windows.

Are there any settings I can change to prevent the miscommunication between windows and MaxTo? Thanks.

**Comment by vegardlarsen** [comment]
@SphinxJ Is this in the preview versions (see issue #220)? If this happens in version 2017.7, we may not get a chance to fix it, but in the preview version (2.0 and up) we probably will.

**Comment by SphinxJ** [comment]
This is happening in version 2017.7.0.0.

So should I upgrade to version 2.0 then?

**Comment by vegardlarsen** [comment]
I would recommend you at least try it and let me know what happens there. We have changed a lot about how monitor numbering works, so the experience should be better, but it is still alpha quality, so you may experience crashes. If you still experience issues in 2.0, please do let me know, and I will investigate in more detail.

**Comment by vegardlarsen** [comment]
Did this solve your issue, @SphinxJ?

**Comment by vegardlarsen** [comment]
(closing until told otherwise)

**Comment by SphinxJ** [comment]
I have not changed software versions yet, but the issue has seemed to resolve itself from what I can tell. Thanks.
