### ISSUE TITLE
Always wrong regions sizes

### ISSUE THREAD

**Issue by GrishaevPavel** [digitalcreations/MaxTo#258]
Hi. I have problems with regions sizes, both on previous version and on beta 2.
I can't set sizes accurately. I have 4k monitor and want to set 1920 x 1080 at the center-bottom.
First I see, that regions editor shows wrong monitor size (2px smaller), then I select 1920 x 1080, but as a result I have another rectangle. Then regions editor shows different sizes.
It looks like you save another units, not pixels, but show pixels to me. If you want relative units, you can do:
1) save config in pixels (!!!), not percents or smth else;
2) calculate relative sizes from saved pixels, if another monitor sizes appeared;
I can't believe that there is no ability to save settings exactly, without loss.

**Comment by GrishaevPavel** [comment]
problem screenshot - [https://www.screencast.com/t/MsGhrHuWMefL](url)

**Comment by vegardlarsen** [comment]
Thank you for this report. I will investigate.

There is some math involved here, in removing the size of any painted borders, and this can vary based on the monitor DPI. In some cases you'll end up with half pixels which can cause rounding errors.

Because of the way the controls work, we can currently only save the region sizes as fractions; and calculate pixels from there.

**Comment by GrishaevPavel** [comment]
I have TV 49 inch, pixel size is normal, not "retina" like. And it is strange that I see 1920 in editor, close it, open again and see 1917 for example. And even If there are controls issue, if we have number allready on screen, exactly these number must be saved without recalculation to relative. Somehow you show these pixels, so you have a variables set, and can save them exactly to a file.

**Comment by GrishaevPavel** [comment]
After this all this regions will be in pixels without recalculation. But now I measure a window and it is not that numbers I saw in editor. So editor is not correct.

**Comment by GrishaevPavel** [comment]
I need it, because of huge TV, and I am a developer, so window size exactly 1920 is very important, not 1918 :)

**Comment by vegardlarsen** [comment]
We are making some enhancements to how this works in 2.1.0-beta.2, which will be in beta soon.
