### ISSUE TITLE
MaxTo 2.0.0 beta1 no alternate region template?

### ISSUE THREAD

**Issue by dannythegreat** [digitalcreations/MaxTo#259]
Hello,
I have updated my MaxTo to 2.0.0 beta1 version, but I don't find the "alternate region template and the shortcuts" why?
This feature were helpful yet. Please re-add.

Thank you

**Comment by dannythegreat** [comment]
I answer my selft:

> Alternate regions will not be coming back. It is now extremely simple to load presets by assigning them to hotkeys. The additional complexity of having multiple regions applied at once made this one an easy choice to remove.

**Comment by tommy1e23** [comment]
But the alternate region hots key really cool and very useful.

**Comment by vegardlarsen** [comment]
@dannythegreat Great that you found that answer. 
@tommy1e23 In which ways do loading presets using hotkeys seem less useful to you?

**Comment by tommy1e23** [comment]
> @dannythegreat Great that you found that answer.
> @tommy1e23 In which ways do loading presets using hotkeys seem less useful to you?

The previous version, I can simply hold ALT and Shift to move windows to fill the present.
Now I need to use the shortcut to change the present profile and move the windows.
Or can you add a new shortcut like this feature?
