### ISSUE TITLE
Window should move in the indicated direction even when it starts out not on grid

### ISSUE THREAD

**Issue by timkay** [digitalcreations/MaxTo#26]
When a window is snapped to the grid, it always moves in the right direction. The right arrow moves it to the next tile to the right, etc. However, if a window is not on the grid, no matter what key I press, the window always moves to the upper-left tile. It's no big deal, as I can hit arrow keys to position it, but it would be nice if it started out moving in the right direction.

**Comment by vegardlarsen** [comment]
I was mistaken when I wrote my last comment. MaxTo already works this way. A window placed on top of the border between two regions moves to the left region if you do Ctrl+Windows+Left, and to the right region if you do Ctrl+Windows+Right.

**Comment by timkay** [comment]
MaxTo does not do it properly. The window often moves in the wrong
direction, until it is snapped to a predefined region.

**Comment by vegardlarsen** [comment]
After trying this a few more times, I found a scenario where it can be reproduced. I'll make sure it gets fixed.

**Comment by vegardlarsen** [comment]
I have found and eliminated the bug. The algorithm used to use the edges of the region underneath the window as its base of operation. Meaning that if the center of the window was over a region, that region was effectively skipped. Now it instead uses the window's edges, and therefore it works properly.
