### ISSUE TITLE
2.0 Beta on RemoteDesktop fails to remember regions and no alt-layout option.

### ISSUE THREAD

**Issue by smallscript** [digitalcreations/MaxTo#261]
I just tried upgrading to v2 beta. I access my machine through remote-desktop 95% of the time. It worked "great" with v1.0; and I depended on the "TWO" layout settings (primary-layout and alt-layout) for productivity.

v2 beta only remembered 1 of 6 monitor settings.
I also could-not find the alt-layout option.
The installer crashed when I uninstalled and tried to re-install. The error-script had "squirrel-script/installer"  complaining about something.

**Comment by vegardlarsen** [comment]
First; the alternative layouts are now gone. Instead we recommend that you create recipes that load region presets. This lets you have more than two alternates; you can basically have as many as you want.

What do you mean that the beta only remembered "1 of 6 monitor settings"? Are you regions disappearing after you set them?

**Comment by vegardlarsen** [comment]
Can you copy the "Monitor details" from a few of the monitors in here, so I can have a look?

**Comment by smallscript** [comment]
Yes, later. I actually uninstalled it and re-installed the older version so I could keep working.

**Comment by smallscript** [comment]
And yes, the settings on only the primary monitor were remembered. All the other 5 were not retained, even when I saved the layout with a name.

**Comment by vegardlarsen** [comment]
I can only speculate until I get your monitor info, but I suspect that the remote monitors get the same "id" for some reason.

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback. And I suspect this has been fixed by other bug-fixes we've made.
