### ISSUE TITLE
Paid version: Stable - keeps prompting on every startup about upgrading

### ISSUE THREAD

**Issue by smallscript** [digitalcreations/MaxTo#262]
I have a license.

I am using the stable version.

I tried the beta and, as per other issue posted, it does not work properly for me.

I have no option to stop Stable from prompting on startup.

If I select update it opens WebBrowser and (MaxTo itself) quits [not activating].

It is very-undesirable behavior :-(.

**Comment by vegardlarsen** [comment]
I have disabled the automatic prompt for updates for everyone on the server side. Please let me know if you keep receiving these.
