### ISSUE TITLE
Maximizing doesn't work properly when only one region

### ISSUE THREAD

**Issue by Sawtaytoes** [digitalcreations/MaxTo#263]
v2.0.0-beta1

When I only have one region, I'd like to maximize to the full window. As it is right now, I have to hold `[CTRL][SHIFT]` when maximizing to get the window to get a normal maximization. I remember it only doing that partial maximize in v1 when I had more than one region, but maybe I'm wrong.

![image](https://user-images.githubusercontent.com/3948069/47600097-8e86af00-d981-11e8-9868-37da27e9eab4.png)

vs

![image](https://user-images.githubusercontent.com/3948069/47600100-99d9da80-d981-11e8-9168-e0e828c982bc.png)

**Comment by vegardlarsen** [comment]
You are right. If a monitor has not been divided into regions, MaxTo should allow normal maximization. I will fix this before 2.0.0 goes final.

**Comment by vegardlarsen** [comment]
This has been fixed and will be in 2.0.0-beta.3.
