### ISSUE TITLE
Config settings to memorize active/passive mode

### ISSUE THREAD

**Issue by colthreepv** [digitalcreations/MaxTo#267]
HI, I am using maxto version 2.0.0-beta1

There is no config settings to make permanent the active/passive mode selectable from the tray Icon.
It would be very handy for me to have it passive 100% of the time

It's there a plan to implement it?

**Comment by kjkc-gar** [comment]
Agreed. I leave mine in passive and just use hotkeys to movie windows. The loss of this is slightly annoying, as I have to disable Active every time I bounce one of my boxes.

**Comment by vegardlarsen** [comment]
There are no current plans to add this back, at least not before 2.0 goes final. Can you write a bit about what you use passive mode for?

**Comment by colthreepv** [comment]
Sure: my screens are configured with some regions, so trying to maximize an app will maximize it inside a region (using Active mode)

Using Passive mode it's more flexible, I can maximize to full screen, ignoring regions using WIN + FWDUP, otherwise if I want an app to abide it's screen regions I can use WIN + NUMPADS

**Comment by colthreepv** [comment]
Any update on this feature? will it be released only on final? Seems a perfect recipe for bugs imho

**Comment by vegardlarsen** [comment]
Thanks for poking me about this. This will not happen until after 2.0, meaning 2.1 at the earliest. We are currently trying to track down bugs in 2.0 to get it out for a final release.

I think of this as a two-part feature:

- active/passive mode as it was in earlier releases (the implementation is currently different)
- allowing toggling active/passive with a command (e.g. from a recipe)

**Comment by colthreepv** [comment]
pinging the devs to put this in the [2.1 milestone](https://github.com/digitalcreations/MaxTo/milestone/11)

I have seen there is another related "passive mode" hotkey issue #270, I hope adding this one won't be much additional work

**Comment by vegardlarsen** [comment]
This and #270 is basically the same work item, so I am closing this issue. :)
