### ISSUE TITLE
Regions change when disconnecting monitor

### ISSUE THREAD

**Issue by joddm** [digitalcreations/MaxTo#268]
I use MaxTo on a laptop usually connected to an external monitor. I have set up my regions on the external monitor, and only one region on the laptop screen (whole screen). When I disconnect the laptop from the external monitor, all the regions from the external monitor are transferred to the laptop screen.

**Comment by vegardlarsen** [comment]
Thank you for getting in touch. Can you get me the monitor information for each of your monitors? You can find it when you are changing your regions; there is a button labelled "Monitor details".

Also, it would be very helpful to know what your "Monitor identification" setting is?

**Comment by joddm** [comment]
I don't see the monitor details button? Running 2017.7.0.0

**Comment by vegardlarsen** [comment]
I apologize for the confusion here. I assumed you were running 2.0.0-beta.1, which is out now. This problem should be fixed there (but we have many other bugs).

Please feel free to test out the beta version to see if this solves your problem.
