### ISSUE TITLE
Predefined region for maximizing windows

### ISSUE THREAD

**Issue by thenoctus** [digitalcreations/MaxTo#272]
![image](https://user-images.githubusercontent.com/29714922/48304407-14107000-e4e7-11e8-98f1-6d91703a19c4.png)

I'm a crypto trader, but I think this could be a useful feature for any type of trader (and potentially a market you could specifically market to ;) )

I have my set up with 8 chart windows on the left and 2 trading terminals on the right.  It is great to see all the charts at once in small form on the left to see how multiple setups are developing.  When honing in, I make the window larger manually, I have a hotkey set to maximize it to the entire monitor (as you can see I have a double wide) which is nice, but cuts off the two trade terminals on the right.  It would be perfect to have it just maximize to a predefined space, in this instance the area that of the 8 panes on the left.

**Comment by vegardlarsen** [comment]
Thank you very much for your feedback.

So what you want here is to be able to create a keyboard shortcut that will expand your window in a direction? Given you have a window in your rightmost region, pressing the "Expand left" hotkey would first expand to fill the two rightmost regions, and for each consecutive keypress would expand to the next vertical line to the left?

Did I understand you correctly?

**Comment by thenoctus** [comment]
There's a hotkey to maximize a window and then restore it to the places in the layout.  When working I want to not maximize, just make one of the windows bigger but leave part of the screen with my window.

**Comment by GeezerAl** [comment]
Similar for me. I want three or 4 windows, but I want to adjust every dimension sideways, up, or down. Right now, all I know how to do is based upon your pre-defined, and that is not convenient. Yes, hotkeys are also great. But the flexibility to totally design my monitor areas is what I really want.

**Comment by vegardlarsen** [comment]
OK, after re-reading this a few times I finally understood what you want to do. You need a hotkey that would move a window into a "region" that covers the leftmost 8 regions?

While I can very well see the usefulness of this; I don't see how this can be configured easily. Do you have a suggestion about how this could work from a setup standpoint?

**Comment by vegardlarsen** [comment]
We do have `expand` and `contract` commands now in [version 2.1.0 (currently in preview)](https://maxto.net/release/beta). These should help you on the way.
