### ISSUE TITLE
Unable to install MaxTo 2.0.0-beta2

### ISSUE THREAD

**Issue by bojordan** [digitalcreations/MaxTo#275]
Attached is the SquirrelSetup.log file:
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/2578509/SquirrelSetup.log)

Note that the file path mentioned in the DirectoryNotFoundException exists:

> 2018-11-13 15:15:49> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\rojordan\AppData\Local\MaxTo\packages\.betaId'.

**Comment by vegardlarsen** [comment]
@bojordan Thank you for reporting this. The error message you highlighted is actually harmless in itself; it has to do with Squirrel beta versions, not MaxTo beta versions. Basically it is complaining that you don't have MaxTo installed from before, so there is nothing to upgrade.

The last entry in the log concerns me more:

> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote server returned an error: (404) Not Found.

However, it appears to be a warning and I believe MaxTo itself did install itself successfully. My guess is that you will find the installed files in `C:\Users\rojordan\AppData\Local\MaxTo\app-2.0.0-beta2\`.

However, it may be that MaxTo crashed after the install. If that is the case; can you check `C:\Users\rojordan\AppData\Roaming\MaxTo\maxto.log`?

**Comment by bojordan** [comment]
It does look like it's crashing: [maxto.log](https://github.com/digitalcreations/MaxTo/files/2581634/maxto.log)


>2018-11-14 08:20:45 [MaxTo.Core@2.0.0.331] [Information] Found startup task with incorrect definition. Recreating task.
2018-11-14 08:20:45 [MaxTo.Core@2.0.0.331] [Fatal] Exception occured during startup
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.DeleteTask(String Name, Int32 flags)
   at Microsoft.Win32.TaskScheduler.TaskFolder.DeleteTask(String name, Boolean exceptionOnNotExists)
   at MaxTo.Core.Settings.LoginRegistrationService.Register()
   at MaxTo.Core.Settings.LoginRegistrationService.InitializeAsync()
   at MaxTo.Core.Settings.AsyncInitializer.<InitializeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.MainForm.<OnLoad>d__20.MoveNext()

**Comment by vegardlarsen** [comment]
You can fix this by uninstalling the previous version of MaxTo. If you already have uninstalled it and this error still occurs; you can delete the Task Scheduler entry called "MaxTo" and try again.

This error has been fixed for the next beta release, which I had hoped to put out today but I am at home with a sick child. 🤒

**Comment by bojordan** [comment]
Thanks @vegardlarsen - indeed, uninstalling the previous version allowed the install to succeed.

Hope your little one feels better!
