### ISSUE TITLE
Crashing after start

### ISSUE THREAD

**Issue by Derden234** [digitalcreations/MaxTo#28]
Love this tool but:
- Change system tools to show icon in tray. Doesn't show after reboot. I have application set to start when windows starts.
- Manually start application. Works for a minute or so, then crashes and shuts down.
- Then I try to manually restart and it either stays it is already running (which is not) or runs again to repeat crashes. 

Windows 7 Ultimate. 
16 GB memory
i7 Quadcore. 
3x 2560x1080 displays (LG um55)
Machine is a fresh install but has been patched. 
Running Norton internet security but have this application set to "allow" in firewall.

Thank you

**Comment by vegardlarsen** [comment]
Exception report for my reference:

```xml
<?xml version="1.0"?>
<SerializableException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ExtendedInformation>
    <HResult>-2147024809</HResult>
  </ExtendedInformation>
  <Message>Win32 handle that was passed to Icon is not valid or is the wrong type.</Message>
  <Source>System.Drawing</Source>
  <StackTrace>   at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at MaxTo.Native.SystemWindow.get_Icon()
   at MaxTo.RegionHighlightForm.set_EmulateWindowWindow(IntPtr value)
   at MaxTo.MainForm.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</StackTrace>
  <TargetSite>Void .ctor(IntPtr, Boolean) @ System.Drawing.Icon</TargetSite>
  <Type>System.ArgumentException</Type>
</SerializableException>
```

**Comment by vegardlarsen** [comment]
This will be fixed in the next release.
