### ISSUE TITLE
Hard to read Settings window against dark backgrounds

### ISSUE THREAD

**Issue by AaronLieberman** [digitalcreations/MaxTo#285]
The frosted glass doesn't work very well when overlaid against dark backgrounds. 

![image](https://user-images.githubusercontent.com/8040502/48634491-7bf90780-e97a-11e8-8340-24d6fe1a811b.png)

**Comment by vegardlarsen** [comment]
Completely agree. Putting this on my todo-list.

**Comment by vegardlarsen** [comment]
This is how it will look in beta.4 (black background halfway down, translated to Norwegian).

![image](https://user-images.githubusercontent.com/436508/49040681-8a89bf00-f1c3-11e8-9b81-263e9b4c0453.png)
