### ISSUE TITLE
WHAT!?

### ISSUE THREAD

**Issue by pinkyfloo** [digitalcreations/MaxTo#291]
Ok, so I downloaded the app from the official page coming from a Youtube Video as I was looking for a Mac's Magnet App substitute for W10, the interface wasn't the same that I got on my download, however, I downloaded the "setup" (WHY would you call something "Setup" when it is not a Setup but the program itself...) started using the program and then I thought "Oh my downloads folder has got many setups, I'm gonna cleean that!" as I've just reinstalled my programs, as I recently bought this computer, so cleared every exe file from downloads... aight? then I try to maximize a window oh scrap it goes real maximized, I go to taskbar and as soon as my mouse touches MaxTo icon it vanishes, then after not being able to find anything on start menu I go redownload the "setup" and oh scrap it shows an error... in which it says it attempted to modify (WHY FOR GOD'S SAKE) on other programs folders, like Discord, which is a chat app... like just why?? I mean now I don't know if I want a solution to run this scrap or just want an explanation of what is this setup tryna do sneaking inside other programs folders and maybe get rid of it...
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/2626402/SquirrelSetup.log)

**Comment by vegardlarsen** [comment]
Hi there,

and thanks for writing. I'll try to address each point separately.

- It is a setup file, you just don't get the annoying prompts. If you run it, MaxTo installs itself to your computer.
- If the MaxTo icon moved or disappeared, it is most likely behind the up arrow that Windows introduces. Sometimes new programs will be shown for a little while, and then moved by Windows to "unclutter" the notification area. You can drag MaxTo back to the notification area if you'd like.
- The Squirrel installer, which we use, is also the same software that lots of other software (including Discord) uses. This is why when you open the Squirrel log file, you can see messages from all of these other programs as well. We do not modify these programs at all.
- Your Squirrel log file seems to indicate that MaxTo was already running when you tried to install it the second time.

Note that the version you downloaded is a beta release, and the stable release can be [downloaded from here](https://maxto.net/release) (version is 2017.07).
