### ISSUE TITLE
Explorer window needs two grabs to allow snapping

### ISSUE THREAD

**Issue by Mrfuyu** [digitalcreations/MaxTo#292]
**Describe the bug**
Newly opened explorer window can't be sized by MaxTo on the first grab. If I release it and grab again it works.

**To Reproduce**
1. Start explorer.exe
2. Grab it
3. Additionaly press shift
4. Drag on a MaxTo preset area
5. Nothing happens

Note: Also the window isn't transparent on first drag.

**Expected behavior**
Snap window to MaxTo area on first drag (and make it transparent on drag).

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.0-beta3

**Additional context**
No log entry is created.

**Comment by Mrfuyu** [comment]
Here is an example:

![buggy_maxto](https://user-images.githubusercontent.com/14253537/49407713-c8558d00-f759-11e8-8f99-cb724c666da3.gif)

**Comment by vegardlarsen** [comment]
Does this also happen after a system reboot?

**Comment by Mrfuyu** [comment]
Yes.

**Comment by vegardlarsen** [comment]
Does this also apply for new explorer windows, or just the first one you try it with?

**Comment by Mrfuyu** [comment]
For all new explorer windows.

**Comment by Mrfuyu** [comment]
The Problem is gone for me with v2 final release.
