### ISSUE TITLE
Can't switch from regions

### ISSUE THREAD

**Issue by SkyfoxDonbeulo** [digitalcreations/MaxTo#293]
Hi,
setting up 2 different regions and saving them. When i load a preset and apply, nothing will change. Allways the origin region is active.  

- Windows version 10 (1809)
- MaxTo version 2.0.0 beta 3

Hope anyone can help me...

**Comment by vegardlarsen** [comment]
Hi, I may have misunderstood you, but nothing should visibly change when you click Apply. You will need to start moving your windows around to see the changes. Try holding Shift while you drag a window to preview your regions, or maximizing a specific window.

**Comment by vegardlarsen** [comment]
Closed due to inactivity.
