### ISSUE TITLE
Beta 2 missing fit all to closest region

### ISSUE THREAD

**Issue by shaymdev** [digitalcreations/MaxTo#294]
In Beta 2 I'm not able to find a way to achieve the original functionality of fitting all windows into their nearest region. Is this still possible and I'm just not finding it?

**Comment by vegardlarsen** [comment]
Thanks for reporting this. This feature is currently not available in the betas, and will probably not be ready for the 2.0.0 final release. I am tagging this so I remember to put it back in. :)

**Comment by shaymdev** [comment]
Thanks for the update. Bummer that it's not supported. I'll keep my eye out
for it.

**Comment by vegardlarsen** [comment]
I have implemented this and it will be in version 2.1.0.
