### ISSUE TITLE
Unable to use Elevation Mode

### ISSUE THREAD

**Issue by srbs73** [digitalcreations/MaxTo#296]
As most of the apps I want to arrange are running in Admin mode, I wanted to enable Elevation Mode, however MaxTo just repeatedly crashes and doesn’t enable.  I can therefore on manage apps running in Normal mode.

Tried right clicking on MaxTo Icon to initially run in Admin mode but it immediately crashes with “Unrecoverable error”. Log file for this time:
![image](https://user-images.githubusercontent.com/45626734/49511423-039fab00-f883-11e8-85e2-12cd05fee2b3.png)
[Error log.txt](https://github.com/digitalcreations/MaxTo/files/2648665/Error.log.txt)

Expectation is it can be configured to always start as Admin and manage apps in admin mode.

Running Windows 10 and MaxTo version 2.0.0-beta3

**Comment by srbs73** [comment]
Hi there, here you go: 5d3c3c2f5fe94d71bd459f345c0b0b47

**Comment by vegardlarsen** [comment]
After a bit of looking, I think this may be an issue with "Start on logon". Can you try disabling that setting in your `config.json` file, and then deleting the "MaxTo" task in Task Scheduler?

**Comment by srbs73** [comment]
I don’t have a task in Task Scheduler for maxto and config.json already has start on logon disabled:

{
  "$schema": "https://maxto.net/config.schema.json",
  "language": "en",
  "startup": {
    "startOnLogon": false,
    "runElevated": true
  },
  "updates": {
    "enabled": true,
    "channel": "Beta"
  },
  "behavior": {
    "snap": {
      "to": [
        "Screen",
        "Window"
      ],
      "distance": 10
    },
    "transparentWindowsWhenMoving": true
  },
  "shims": {
    "toggled": {}
  },
  "license": {
    "firstStart": "2018-12-05T10:59:32.1173118Z"
  },
  "recipes": [
    {
      "name": "Move window left",
      "hotkey": "Windows+NumPad4",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Left"
          }
        }
      ]
    },
    {
      "name": "Move window up",
      "hotkey": "Windows+NumPad8",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Up"
          }
        }
      ]
    },
    {
      "name": "Move window right",
      "hotkey": "Windows+NumPad6",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Right"
          }
        }
      ]
    },
    {
      "name": "Move window down",
      "hotkey": "Windows+NumPad2",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Down"
          }
        }
      ]
    },
    {
      "name": "Swap window left",
      "hotkey": "Windows+Control+NumPad4",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Left",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Swap window up",
      "hotkey": "Windows+Control+NumPad8",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Up",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Swap window right",
      "hotkey": "Windows+Control+NumPad6",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Right",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Swap window down",
      "hotkey": "Windows+Control+NumPad2",
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Down",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Center window",
      "hotkey": "Windows+NumPad5",
      "ingredients": [
        {
          "command": "window:center",
          "parameters": {}
        }
      ]
    }
  ],
  "monitor": {
    "idSelection": "SerialNumber",
    "virtualDesktop": false
  },
  "errorReporting": {
    "anonymityLevel": "MachineIdentifier",
    "enabled": true
  },
  "presets": [
    {
      "type": "split",
      "splits": {
        "orientation": "Vertical",
       "distance": 0.5,
        "child1": null,
        "child2": null
      },
      "name": "Two-way vertical"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.5,
        "child1": null,
        "child2": null
      },
      "name": "Two-way horizontal"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.694473409801877,
        "child1": null,
        "child2": null
      },
      "name": "General Office"
    }
  ]
}

**Comment by vegardlarsen** [comment]
If you open the log file when you receive that crash report, what does it say?

**Comment by vegardlarsen** [comment]
I can confirm that this issue exists; and that the error message should not have been shown. This will be fixed for beta.4.
