### ISSUE TITLE
Monitor missing serial number

### ISSUE THREAD

**Issue by sytone** [digitalcreations/MaxTo#299]
**Describe the bug**
When getting monitor properties on the region screen the serial is missing for one of my monitors. 

**To Reproduce**
1. Go to Chane Regions
2. Click on Monitor Detailsl

**Expected behavior**
All monitors should have a serial number?

**Screenshots**
Friendly name: LG ULTRAWIDE WQHD(Display Port_8bit)
Device name: \\.\DISPLAY1
Location identifier: \{61CC07AC-E861-11E8-B839-A794A0DB1531}\0000
Serial number: 
DPI (dots per inch): 96×96
Resolution: 3440×1440 @ 0, 0
Working area: 3440×1400 @ 0, 0

**System information:**
 - Windows version: 10 - 1803
 - MaxTo version 2.0.0-beta3

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment]
@sytone Thank you for your report. 

Unfortunately, not all monitors publish their serial number through the [EDID information](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data) accessible in Windows. Therefore we cannot provide a serial number for all monitors. When this is the case, we end up generating a unique string for the monitor. We have [details on this in the documentation](https://maxto.net/documentation/configuration/monitor-identification).

I am closing this issue as there is nothing we can do about it.
