### ISSUE TITLE
Multiple types of recipe triggers

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#301]
As it stands today, MaxTo only supports triggering recipes using hotkeys or from the command line. We want to support other kinds of trigger events for recipes, here are some examples:

### Events supported

- [x] Monitor
  - [x] Connected (`monitor:connected`)
  - [x] Disconnected (`monitor:disconnected`)
  - [x] Details changed (`monitor:changed`)
- [x] MaxTo 
  - [x] Started (corresponds to Windows logon, `maxto:started`)
  - [x] Regions changed (`maxto:regions_changed`)
- [x] Window events
  - [x] Maximized (`window:maximized`)
  - [x] Placed in region (`window:placed`)
  - [x] Restored (`window:restored`)
  - [x] Moved (`window:moved`)
  - [x] Opened (`window:opened`)
  - [x] Activated (`window:activated`)
- [x] Virtual desktop
  - [x] Changed (`virtualdesktop:changed`)
  - [x] Created (`virtualdesktop:created`)
  - [x] Deleted  (`virtualdesktop:deleted`)
- [x] Windows events
  - [x] Desktop locked (`windows:locked`)
  - [x] Desktop unlocked (`windows:unlocked`)
- [x] Network events (filter by network name, adapter name and possible SSID)
  - [x] Network connected (`network:connected`)
  - [x] Network disconnected (`network:disconnected`)

### Other items

- [x] User interface support for editing triggers (this is a big one).
- [x] Prevent infinite loops when doing stupid things like loading presets as a response to "regions changed".

The configuration syntax will be something like:

```json
{
  "name": "Load regions",
  "triggers": [ 
    { "type": "hotkey", "hotkey": "Windows+Alt+R" },
    { "type": "startup" },
    { "type": "monitor:connected", "monitor": "\\\\.\\DISPLAY1" }
  ],
  "ingredients": [ {} ]
}
```

Note that this is a feature that we will look at after 2.0.0. Suggestions for other events are appreciated.

**Comment by thewavelength** [comment]
I am not sure if this is covered by "Monitor connected/disconnect", so I'm adding it: when closing the lid of a laptop, it should be recognized as an event.

**Comment by thewavelength** [comment]
Another idea might be a "Window opened" or "Application opened" event so I can automatically put e. g. Excel always to a specific region without using a hotkey.

**Comment by vegardlarsen** [comment]
@thewavelength Not sure if we can capture the "closed lid" event, as we would have very little time to do something about it before Windows goes to sleep. I will keep this in mind.

"Application opened" or "window opened" is definitely a good idea. :)

**Comment by thewavelength** [comment]
I can totally close my lid and the monitor on my laptop goes inactive, and still the external monitor keeps alive. This depends on how a user sets his power options in Windows.

This is what I thought of that use case. I agree that doing something before Windows goes to sleep doesn't make much sense.

**Comment by vegardlarsen** [comment]
This has been implemented, with all the events listed in the first post, and will be in version 2.1.

**Comment by thewavelength** [comment]
Awesome list of events! This makes MaxTo so much more powerful. Can't wait to use this.

Does "monitor:changed" cover the lid open/closed stuff?

**Comment by vegardlarsen** [comment]
Maybe? :)

If the monitor is disconnected when you close the lid, those events should work well. I haven't tested (didn't develop this on a laptop).

**Comment by thewavelength** [comment]
How am I supposed to use the filter, e. g. to detect which monitor is being connected/configuration has changed? There is no documentation I could find on this.

**Comment by vegardlarsen** [comment]
The filter supports the following special identifiers:

- `$primary`
- `$all`
- `$current` - the monitor containing the foreground window
- `$next` - the next monitor from `$current`
- `$previous` - the previous monitor from `$current`

Besides those values, you can identify a monitor by (exact match):

- its number
- its friendly name (e.g. `C49RG9x`)
- its serial number (see the Monitor details in the change regions screen)
- its device name (a path of the form `\\.\DISPLAY1`)
