### ISSUE TITLE
MaxTo is already running...

### ISSUE THREAD

**Issue by SkyfoxDonbeulo** [digitalcreations/MaxTo#303]
Hi there,

i have installed MaxTo Version 2.0.0.beta4. After closing and restarting MaxTo i got this message: "MaxTo is already running, you should find it in the notification area" (see screenshot maxto_error.jpg). But there is no Icon and no MaxTo-Task is running. Cannot restart MaxTo. But if i start the setup file, the program is running and an icon will apear. After closing Maxto (no task is running) and restarting the same message pops up.

Running Windows 10 Version 1803
MaxTo 2.0.0.beta4

[maxto20181207.log](https://github.com/digitalcreations/MaxTo/files/2656888/maxto20181207.log)
![maxto_error](https://user-images.githubusercontent.com/45536194/49643291-9a9c6c80-fa15-11e8-9474-318ce084785a.JPG)

**Comment by SkyfoxDonbeulo** [comment]
Hi,

when i start the file "MaxTo.Core.exe" from the directory "%appdata%\local\MaxTo", then the error occurs. If i change the directory to "%appdata%\local\MaxTo\app-2.0.0-beta4" the programme starts without any errors. Normaly the Link is set to "%appdata%\local\MaxTo".

**Comment by nshtg** [comment]
That workaround is not working for me.

**Comment by vegardlarsen** [comment]
This has been fixed for beta.5.

**Comment by vegardlarsen** [comment]
Beta.5 is now available on the website. If you are experiencing this bug, auto-update will not work. You will have to download and run the installer again.
