### ISSUE TITLE
MaxTo won't start (because it's already running - but it's not)

### ISSUE THREAD

**Issue by Doomnometron** [digitalcreations/MaxTo#304]
Error Message
_MaxTo is already running, you should find it in the notification area._

No icon in the notification area, no MaxTo.exe process.

![image](https://user-images.githubusercontent.com/45730384/49695637-47095a80-fb9e-11e8-9265-966014806596.png)

2.0.0-beta3

**Comment by synesisinc** [comment]
Same issue here

**Comment by DropdeadFredd** [comment]
Same issue.

2018-12-11 07:45:43 [MaxTo.Core@2.0.0.359] [Information] Logger setup (online logging: True, process #17300)
2018-12-11 07:45:44 [MaxTo.Core@2.0.0.359] [Information] MaxTo is already running. PID 17276. Exiting.

Windows 10 Pro Version 1809 (OS BUild 17763.134)

Tried an uninstall/re-install, MaxTo works until reboot, on reboot it fails to start and issues the above error when trying to start it manually.

**Comment by vegardlarsen** [comment]
This is the same issue as #303. See that issue for a workaround.

**Comment by DropdeadFredd** [comment]
Thanks

Changing the 'Target' to: %appdata%\Local\MaxTo\app-2.0.0-beta4\MaxTo.Core.exe and 'Start In' to: %appdata%\Local\MaxTo\app-2.0.0-beta4 worked for me.

Changed in both the Desktop Shortcut and the Scheduled Task.

**Comment by Doomnometron** [comment]
Worked for me too. Thanks.

**Comment by ianelletson** [comment]
I am getting this issue as well. I'll try the workaround.

**Comment by vegardlarsen** [comment]
Beta.5 is now available on the website. If you are experiencing this bug, auto-update will not work. You will have to download and run the installer again.
