### ISSUE TITLE
Command: expand/contract in direction

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#306]
The `window:expand` command would take the current size of the window, and expand one edge in one direction until it finds either a window border, a region border or a screen border. It would make window snapping accessible to keyboard users.

Suggested parameters:

- **Window**: Which window to target. Default to foreground window.
- **Direction**: Which direction to move. Also controls which edge is moving.
- **To**: Which edges to consider. Same as in snapping; window, region, screen or any combination.

The `window:contract` command would have the same parameters, but work in reverse (not sure if the Direction should be flipped).

We need to find available shortcut keys for this feature; it would require 8 combinations, preferably of directional keys. I am thinking Windows+Shift+NumPad2/4/6/8 for expand and Windows+Control+NumPad2/4/6/8 for contract.

**Comment by jteris** [comment]
What is the expected release date of the 2.1.0 release?

**Comment by vegardlarsen** [comment]
I'm sorry, we don't have that information yet.

**Comment by rayzorben** [comment]
Please consider having this part of the UI as well (when holding shift). If I have 

`1      |         2
------------x-
3       |         4
`

When I move the window (with shift) to within 10/20/30 pixels of the centerline, it should snap to both regions, for example, if I move the window near the 'x' it will snap to regions 2 and 4.

**Comment by yacoob** [comment]
I take it this is not yet released? Will this functionality be available to use via UI in recipes?

**Comment by vegardlarsen** [comment]
@yacoob It is in preview. See [our releases page](https://maxto.net/release/beta).

It is available in recipes, yes. :)
