### ISSUE TITLE
MaxTo doesn't start 

### ISSUE THREAD

**Issue by tomstachura** [digitalcreations/MaxTo#307]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by tomstachura** [comment]
After a reboot, MaxTo doesn't start even though it's configured to auto start. On top of that, when I try to run it manually, it says it's already running, but there is no icon in the notification area and shortcuts don't work and there is no process in the task manager for maxto.

**Comment by esg-roger** [comment]
Same.
Same after a uninstall/reboot/clean install. (It launches after installation but stops working on next boot).
Manually running MaxTo.Core.exe results in a dialog stating "MaxTo is already running, you should find it in the notification area." (I don't)
Running it *again* sometimes results in a dialog stating "MaxTo encountered an unrecoverable error the last time it ran..."
Attaching logfile.
[maxto.log](https://github.com/digitalcreations/MaxTo/files/2677449/maxto.log)

**Comment by MacMcDell** [comment]
Same. I can't start maxto or close maxto.exe.. I see the process start to tell me its already running but then after clicking ok on the alert window, maxto.core.exe disappears from the details/processes. its getting a but frustrating. I can deal with restarting it if someone knows a way to do that but for the life of me I cannot see the process that is blocking it.

**Comment by vegardlarsen** [comment]
This is the same as issue #303, which I fixed yesterday. There is a workaround in there. The fix will be in beta.6, which will go out today or on Monday.

**Comment by vegardlarsen** [comment]
Beta.5 is now available on the website. If you are experiencing this bug, auto-update will not work. You will have to download and run the installer again.
