### ISSUE TITLE
Recipe ingedient settings not properly loaded into UI

### ISSUE THREAD

**Issue by jmc-comitas** [digitalcreations/MaxTo#308]
**Describe the bug**
After saving a recipe ingedient. eg. Load Preset, or Highlight Region, the "Monitor" or "Preset" settings are not loaded and appear to be unset. Upon inspection of the config.json file, they do appear to be saved, and hotkeys using them do work.

**To Reproduce**
1. Create a recipe
2. Add a "Load preset" ingredient
3. Select a monitor and preset.
4. Save the recipe.
5. Return to the main settings menu with the back button.
6. Re-enter the recipes dialog, select the recipe just created.
7. Select the "Load preset" ingedient
8. The settings appear to be unset, although they are set and still work (verified in config.json). Also happens with the "Highlight regions" ingredient

**Expected behavior**
The existing settings should be properly loaded into the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/19182833/49987172-a8507580-ff72-11e8-8865-1dba19c12eb2.png)

**System information:**
 - Windows 10 Build 1803
 - MaxTo version 2.0.0-beta4 (also beta3, did not try/use before beta 3)

**Additional context**
There are no related errors or information in the MaxTo log regarding this issue.

**Comment by jmc-comitas** [comment]
This is still happening to me, as well as my colleagues that use v2, as of beta7.

**Comment by vegardlarsen** [comment]
Thank you for the nudge. I will be looking into this issue, and hopefully have a fix before version 2.0.0 goes final.

**Comment by vegardlarsen** [comment]
This issue has been fixed for 2.0.0-beta.8, which I will release in a little while (it is building now).

**Comment by jmc-comitas** [comment]
Thanks. Can confirm it is now fixed in beta8.

**Comment by vegardlarsen** [comment]
Thanks for the confirmation! 👍
