### ISSUE TITLE
Remote App window is not recognized

### ISSUE THREAD

**Issue by lolimov** [digitalcreations/MaxTo#309]
We want to use the program to divide one or more remote apps into the designated areas.
The program does not recognise the remote app window, when i am dragging it with the shift key.
Is there any way to make it work?

**Comment by vegardlarsen** [comment]
What kind of remote desktop application are you using? What app is not recognized?

**Comment by vegardlarsen** [comment]
What happens if you hold Shift while you move this window around? Does MaxTo pick it up then?

You may very well be right here, because it is a remote window, MaxTo depends on the remoting software to send the right signals to Windows for it to be possible to do what MaxTo does.

Which version of MaxTo and Windows are you running locally?

**Comment by lolimov** [comment]
If I hold shift and move the window around MaxTo cant find the predefined areas. Basically nothing happens.
I tried the latest stable version of MaxTo and were running it on windows 7 x64.

**Comment by surfdude764** [comment]
I have a similar issue with a remote Citrix session (Citrix Workspace app): When I put the remote session in a window mode, it can be maximized to a tile by holding the Shift key. Though I can't maximize it to this area, then it switches to my complete monitor again. And as long as it isn't maximized, it doesn't pick up the hotkeys.

I did see this issue: https://github.com/digitalcreations/MaxTo/issues/270, but I'm not sure what is meant by 'active' and 'passive' here and if it applies to my issue described?

**Comment by vegardlarsen** [comment]
I am not entirely sure if this is fixable or not. I am going to have to find one of these pieces of software and get a test version of them set up.

@surfdude764 The linked issue (#270) is not related.

**Comment by surfdude764** [comment]
Hi,

first of all I fixed issue #270 for my case. For Citrix it is a registry setting to accept all special keys.

I think the full screen issue can also be reproduced with another remote desktop setup. Had the same with VMware Horizon which was basically RDP. Or VNC will probably behalve the same.

If you could fix this, you would finally make my 4k setup usable the way I want.

Waiting for your next response,

Mark

**Comment by vegardlarsen** [comment]
My conclusion here is that this will be unsupported in MaxTo unless we can find a good workaround.

You may (in some implementations of this kind of remote desktoping) have success with using the hotkeys for moving the windows around.
