### ISSUE TITLE
Command to change settings

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#311]
It would be very beneficial to be able to change settings from the CLI.

Suggested syntax (not sure if our current console parser can handle this, though):

```console
maxto config set behavior.transparentWindowsWhenMoving false
```

I have to decide if it makes sense to use JSONPath for this (prepending `$.` to every query), or if we should use the internal representation instead of the JSON representation when setting these settings. In the latter case, we need some other parsing to navigate POCO objects.

**Comment by thewavelength** [comment]
@vegardlarsen You probably want to close this.
