### ISSUE TITLE
maxto window move /window "Notepad" /Monitor "\\.\DISPLAY3" dosn't work

### ISSUE THREAD

**Issue by coreyspeed** [digitalcreations/MaxTo#313]
Maxto to is not moving my windows to another display, this feature will be really useful to me if this works correctly. 

First, one maximum the window on the screen that notepad is on, this was DISPLAY1

C:\Windows\System32>maxto window move /window "Notepad" /Monitor "\\.\DISPLAY4"
Success: Moved 'Untitled - Notepad' (handle: 0xA314A) to (-1920,0,0,1080).

C:\Windows\System32>maxto window move /window "Notepad" /Monitor "\\.\DISPLAY2"
Success: Moved '' (handle: 0x0) to (0,0,0,0).

C:\Windows\System32>maxto window move /window "Notepad" /Monitor "\\.\DISPLAY3"
Success: Moved '' (handle: 0x0) to (0,0,0,0).

C:\Windows\System32>maxto window move /window "Notepad" /Monitor "\\.\DISPLAY3"
Success: Moved '' (handle: 0x0) to (0,0,0,0).

C:\Windows\System32>

**Comment by vegardlarsen** [comment]
Thanks for this report. I see a few things that are wrong here. 

- Monitors named in this fashion should be `\\.\DISPLAYx` (note the extra slash at the start)
- The window may not be found unless you use the exact title, which may be what is happening here. Try `"Untitled - Notepad"` instead.

Currently, the move command is intended to move a window into a region, not to a different monitor. I can see the usefulness of that possibility though, and I think the syntax you are using seems to be the correct way to do it.

There are caveats when moving a window to a different monitor. I am assuming that moving the window to a monitor without placing it in a region will keep its current size and relative position on the new monitor. That means that the window may be placed partially outside the new monitor; in which case we need to limit both the size and position of the window to stay inside.

**Comment by coreyspeed** [comment]
I always did have the \\ GitHub seems to have removed that, 

![image](https://user-images.githubusercontent.com/6229625/50769087-b3997700-127a-11e9-876f-053feb8b8889.png)

**Comment by coreyspeed** [comment]
the last move maximized the window did not move the program

**Comment by coreyspeed** [comment]
Works if you specify a region, I need a full-screen region then I guess, we have 3 x TV Screens that display on wallboard, we have to manually move the browser windows to each of the defined screens each day, 

Could you let me know how to address web browser's? as we have two firefox windows, can you move tabs ?

**Comment by vegardlarsen** [comment]
If you just need to maximize the window completely to another monitor, try `maxto window maximize /Window "Untitled - Notepad" /Monitor "\\.\DISPLAY2"` instead.

**Comment by vegardlarsen** [comment]
MaxTo cannot currently move things inside browsers, it can only address individual windows (not tabs).

**Comment by vegardlarsen** [comment]
This issue has been fixed for 2.0.0-beta.7, due out tomorrow.
