### ISSUE TITLE
Load presets as a shortcut

### ISSUE THREAD

**Issue by hobbyhoarder** [digitalcreations/MaxTo#315]
Currently, switching to a different region involves clicking in dockbar, selecting Change regions, loading a preset and then confirming it. It simply takes too long if I want to quickly switch to a different region when I open or close a window. Using shortcuts works, but only if you're using a region or two. It's hard to remember all the shortcuts if you have 6+ presets.

A visual selection would be much better and something similar is already implemented when you press the "Load presets" button. That kind of visual selection menu for the presets would be perfect if I could assign it to a shortcut, similar like alt-tab works in Windows.

**Comment by BillionJothi** [comment]
Second this - a shortcut to the load menu possible, which immediately applies to selection. Without having to go into the splitting UI screen. Possible just a copy of the load menu that auto applies the present & which can be enabled/opened using a shortcut.

**Comment by vegardlarsen** [comment]
This is coming in the next 2.2.0 release. You'll be able to trigger the select preset window from a recipe, and if you select a preset it will be immediately applied to that monitor. You'll also be able to pick which monitor it shows up on. The default keyboard shortcut will be Ctrl+Win+E.
