### ISSUE TITLE
Must exit, restart for recipe changes to take effect

### ISSUE THREAD

**Issue by KentuckyFreudChicken** [digitalcreations/MaxTo#317]
**Describe the bug**
Any edits I make to a recipe require a full exit and restart of the program to take effect.

**To Reproduce**
1. Modify any recipe (add, change, remove ingredient -- they all cause same effect)
2. Save updated recipe
3. Trigger recipe with hotkeys
4. Note that the recipe which was loaded before your updates is what plays. The updates didn't take effect.
5. Exit MaxTo
6. Start MaxTo back up, try the recipe again using hotkey, and note that the updated recipe now plays.

My Example: I changed a recipe (and then saved the changes) from opening notepad (%WinDir%\Notepad.exe) to opening any other program and, until I exited and restarted MaxTo, the hotkey for that recipe would still open Notepad, not the updated target. After exit/restart, the hotkey now triggers the updated target program.

**Expected behavior**
Edits to recipes will immediately take effect.

**System information:**
 - Windows version: Win 10, ver. 1809
 - MaxTo version: 2.0.0-beta6

**Comment by vegardlarsen** [comment]
Sorry for the slow response time on this. I can verify that I have been able to reproduce this, and will look into it before 2.0 goes final.

**Comment by vegardlarsen** [comment]
I found the fix for this quite easily, and this will be fixed for the next beta release (or final release if we think we are ready).

**Comment by KentuckyFreudChicken** [comment]
Thank you -- you're the best!

**Comment by vegardlarsen** [comment]
This fix is out today in beta 8. Have a good weekend!
