### ISSUE TITLE
Monitor Naming / Numbering for Monitors

### ISSUE THREAD

**Issue by chefbenjamin** [digitalcreations/MaxTo#319]
**Is your feature request related to a problem? Please describe.**
All my monitors ( 6 of them) are called Generic Monitor. 

**Describe the solution you'd like**
Need a way to leverage of the numbering in windows or give monitors a name or number.

**Comment by thewavelength** [comment]
Suggestion: like with the "Highlight regions" recipe, it might be easier to have a button to highlight the selected monitor.

**Comment by repentsinner** [comment]
Yesss! Having multiple "Generic PNP Monitor"s doesn't help much in recipes.

**Comment by vegardlarsen** [comment]
Here is a preview of what is coming version 2.1 (for a new command called Cycle presets, but all monitor selectors will get this experience).

![image](https://user-images.githubusercontent.com/436508/58709319-34881500-83ba-11e9-960b-6b1972b2264e.png)

**Comment by vegardlarsen** [comment]
Closing this issue as this has been implemented for version 2.1.
