### ISSUE TITLE
Can not install beta version

### ISSUE THREAD

**Issue by dehghani-mehdi** [digitalcreations/MaxTo#320]
Hello,

**Describe the bug**
I like MaxTo and I want to test new version and help _hopefully_ (it's lovely btw), but I could not install it.

when I run installer (_I tried MSI and EXE_), no window shows up, I have to close installer via task manager.

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.0-beta8

**Additional context**
Is there any log in this case?

Thanks.

**Comment by vegardlarsen** [comment]
You can [read this page of the documentation](https://maxto.net/documentation/troubleshooting) to find any relevant log files.

**Comment by vegardlarsen** [comment]
Because we haven't received any follow up or log files, there is unfortunately nothing I can do about this. Closing this issue.

**Comment by dehghani-mehdi** [comment]
Okay, I tried beta10 and it works, so no need to put more info here I guess.
