### ISSUE TITLE
Visual Studios 2017

### ISSUE THREAD

**Issue by BrianHayes33** [digitalcreations/MaxTo#321]
Visual Studios 2017, windows dont snap to region.  instead they always snap and maximize to the screen.
I have several studios open and would LOVE to have this work with VS.

**Comment by bojordan** [comment]
Need to elevate if running VS as admin.

**Comment by vegardlarsen** [comment]
@bojordan is right, you need to elevate MaxTo if you want it to work with other elevated programs. However, Visual Studio should work right out of the box (and does on my machine).

Does MaxTo work OK with other programs on your machine?

**Comment by BrianHayes33** [comment]
That was the issue!  thanks!  my companies policy was keeping it from launching Elevated.  once I got them to allow that, its perfect.  Thanks again.  This tool has been a God send for my development career.

**Comment by vegardlarsen** [comment]
Good to hear. I am closing this issue as it appears to not be a bug in MaxTo. :)
