### ISSUE TITLE
Iterate/load presets using one hotkey (+ using mouse wheel?)

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#323]
**Is your feature request related to a problem? Please describe.**
Remembering preset hotkey shortcuts is hard.

**Describe the solution you'd like**
Having one general hotkey that can be used to automatically activate the next preset. To show which one is active then, it would be nice if the regions are highlighted then. It should be "endless", meaning if the last preset is reached, it should start with the first one.

**Describe alternatives you've considered**
An alternative would be to have one hotkey assignable and using the mouse wheel to then quickly switch to the desired preset.

**Comment by vegardlarsen** [comment]
Good idea! :)

I am leaving these open until we have finished 2.0 final, at which point we will look at when we will get to the different feature requests.

I think this would fit nicely under 2.1, which will be a general expansion of recipes.

**Comment by thewavelength** [comment]
Will this idea land in 2.1?

**Comment by vegardlarsen** [comment]
You can do this in 2.1.0-beta.1 using the "Cycle presets" command. There is a UI bug in beta.1, so if you try to change the recipe after making it, all the checkboxes will be gone. This has been fixed for beta.2.

Mouse wheel support is not included.
