### ISSUE TITLE
Focus on regions

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#324]
**Is your feature request related to a problem? Please describe.**
Setting window focus using ingredients is currently only possible to a specific window or an order.

**Describe the solution you'd like**
It should be possible to select a region which then gets the focus (whatever window is on the top of the stack in that specific region).

**Additional context**
Often the specific windows in a region change. Still I want to use one hotkey to give the current window in a specific region the focus.

**Comment by vegardlarsen** [comment]
I like this idea. We could extend this with `Monitor` and `Region` flags similar to the `move` command.

**Comment by curciel** [comment]
I trying MaxTo right now, the only thing Im missing is to be able to rotate between windows in the same region.

**Comment by fatherofinvention** [comment]
This feature would be incredibly useful for power-users who want to move quickly around regions without taking their hands of the keyboard. Please add it! By the way, great product. :)

**Comment by vegardlarsen** [comment]
I have implemented this for version 2.1.0-alpha.2. :)
