### ISSUE TITLE
"crash any app mode"

### ISSUE THREAD

**Issue by anders55j** [digitalcreations/MaxTo#325]
**Describe the bug**
After a while MaxTo makes any app crash. Even Notepad. Restart of MaxTo helps.

**To Reproduce**
1. Use the computer for a while, like 2-3 days.
2. Hopefully you notice that an app crashes just because you moved it 
3. Start notepad
4. Try to move it just a bit
4. Notepad crashes. And also any other app you try to move.

**Expected behavior**
No crashes

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.0-beta9 (I think I've seen it on beta4 and forward but I never tested earlier betas)

**Additional context**
[maxto20190128 - Copy.log](https://github.com/digitalcreations/MaxTo/files/2804298/maxto20190128.-.Copy.log)

**Comment by vegardlarsen** [comment]
Thank you for the report. Unfortunately the log file doesn't tell me much else than that we lost a connection to one of the sub-processes that make up MaxTo.

When this happens the next time, can you try checking the memory usage of the remaining MaxTo processes (and checking which MaxTo processes are running)? I suspect there may be some sort of memory leak if this only happens after multiple days.

**Comment by anders55j** [comment]
I don't think MaxTo itself crashes, but any window I try to move does. And the errors in the log is probably from when I close down MaxTo to restart. They appear on a normal exit as well, but I will try to be better on checking the clock next time.
![2019-01-29 18_31_45-process hacker](https://user-images.githubusercontent.com/17651291/51934980-2ecaf480-2405-11e9-912a-6878316e5f1f.png)

**Comment by vegardlarsen** [comment]
@anders55j Have you been able to reproduce this with later versions of MaxTo?

**Comment by anders55j** [comment]
I'haven't updated manually for a while, but MaxTo 2 does self-update nowadays, right? I've got RC1 and it certainly got into this "crash-mode" last weekend. 

A few times I got the impression that high overall CPU usage on the computer triggered the bug. I believe VLC is rather CPU hungry when being started and that is when I use MaxTo to position it. But then I tried a heavy CPU loaded newly restarted computer without being able to reproduce it.

**Comment by vegardlarsen** [comment]
@anders55j Is this still an issue on your machine with the latest releases?

**Comment by anders55j** [comment]
Due to the crashes I haven't used it for a while. I will give it another try, but I need to give it some runtime to see if it is still there. I have new monitors as well so things have changed. I'll be back...

**Comment by anders55j** [comment]
No problems for 14 days now. Thanks for the reminder, I'm now able to use MaxTo again.
