### ISSUE TITLE
Constant CPU utilization of 7% without moving any windows. Can this be fixed?

### ISSUE THREAD

**Issue by Andy-KU7T** [digitalcreations/MaxTo#326]
see my screen shot. I cannot afford to waste up to 20% of my CPU on MaxTo. Is there anything you can do here?
![maxtocpuutilization](https://user-images.githubusercontent.com/45279749/52062242-ffaba480-2524-11e9-82f6-418ca6fcd347.png)

**Comment by vegardlarsen** [comment]
@Andy-KU7T Any update on this?

**Comment by Andy-KU7T** [comment]
I killed the MaxTo process but then obviously the app does not work anymore. It just runs with high cpu utilization sometimes.

Do you have some logging/tracing somewhere that I can share with you that may help to figure out what caused this?

Andreas

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by vegardlarsen** [comment]
@Andy-KU7T Which version of MaxTo are you running? My assumption above was that you were running a 2.0 beta version, if you are running 2017.07 instead the case would be different. And in that case I would advice you to try out the 2.0 beta instead.

**Comment by Andy-KU7T** [comment]
Done that now. It seems much less CPU intensive. Great.

Thanks
Andreas


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rserbitar** [comment]
I still ahve this problem with verison 2.1.5. Constnatly using 7% CPU. Thats not good.

**Comment by vegardlarsen** [comment]
@rserbitar Can you make a screenshot of Task Manager? Anything in your log files that would indicate what MaxTo is doing?

**Comment by rserbitar** [comment]
[
![maxto](https://user-images.githubusercontent.com/8320468/100975778-d6079e00-353e-11eb-8c04-6ec455bbeca0.PNG)
](url)

**Comment by rserbitar** [comment]
Ah, seems like ive been running 2.1.4 still. It was updated to 2.1.5 but I did not restart, yet. Restarting with 2.1.5 solved the issue.

**Comment by vegardlarsen** [comment]
@rserbitar Great! :)
