### ISSUE TITLE
Move settings from primary monitor to secondary, if first one has been disabled

### ISSUE THREAD

**Issue by asRIA** [digitalcreations/MaxTo#33]
If I will disable first monitor, the settings will be applied to secondary monitor (snapping zones) what is not comfortable especially when second monitor has different ratio thou.

Probably MaxTo should recognize monitors by some unique id rather that system index. 

Problem is highlighted if somebody is working on laptop and will close a screen with connected secondary monitor.

**Comment by vegardlarsen** [comment]
I am aware of the issue, and it will be fixed at some point. However, it requires a significant rewrite of certain parts of the system, and so it may take a while before this issue is fixed.

**Comment by vegardlarsen** [comment]
This has been fixed in the 2.0.0 preview versions, see #220.
