### ISSUE TITLE
Wrap functionality not implemented in MaxTo 2.0.0

### ISSUE THREAD

**Issue by charlesjeon89** [digitalcreations/MaxTo#330]
**Describe the bug**
MaxTo window movement does not wrap around. For an example, if I divided windows in [1-2-3] and move windows to the right, the window becomes stuck at 3, whereas MaxTo version 1 used to move it back to 1. The same applies to moving windows in any direction.

**To Reproduce**
1. Move windows to the end of region
2. Try moving in the same direction
3. Window doesn't move (because it doesn't wrap around)

**Expected behavior**
In [1-2-3] region setup, moving the window right at pos 3 should move window back to 1.

**System information:**
Windows 10 MaxTo version 2.0.0 beta 6

**Comment by vegardlarsen** [comment]
This is the same as #214. Closing this one. :)

PS! We will do this at some point.
