### ISSUE TITLE
I have installed .net framework 4.7.2556.0, but MaxTo tried to download it

### ISSUE THREAD

**Issue by dehghani-mehdi** [digitalcreations/MaxTo#331]
I will post more info for issue #320 after this one.

**Comment by vegardlarsen** [comment]
@dehghani-mehdi I think you are confusing the file version of the .NET Framework with the published versions. I believe file version 4.7.2556.0 corresponds to .NET Framework 4.7.1, but MaxTo requires 4.7.2.
