### ISSUE TITLE
Edit regions size by typing

### ISSUE THREAD

**Issue by dehghani-mehdi** [digitalcreations/MaxTo#332]
Hello,

I just tried new version and it's great, nice job.

**Is your feature request related to a problem? Please describe.**
I asked about that long ago. I was hoping to see that in new version. using mouse is good, but I think is not enough. is it possible to add this ability to MaxTo in new version?

**Describe the solution you'd like**
Change region size by typing exact numbers, not just using mouse.

Thanks.

**Comment by vegardlarsen** [comment]
This is not something that we will do at this point. The interactions between the different regions make this very difficult.
