### ISSUE TITLE
Add EYEFINITY-like capability

### ISSUE THREAD

**Issue by Tom999Hall** [digitalcreations/MaxTo#333]
I think it would be nice, if MaxTo could natively join multiple monitors into one huge desktop - (without having to use AMD's "Eyefinity"), and then allow this huge desktop to be split

**Comment by vegardlarsen** [comment]
Thank you for your request. This is not something that is within our realm of possibility. Eyefinity is implemented at the video driver level. Re-implementing this would require writing video drivers that are as good as AMD, nVidia and Intel's drivers. MaxTo is a one-man show, so this effort by itself makes this something we won't consider. (I have a bunch of other objections to this as well).

Why would we re-implement a features such as AMD Eyefinity or nVidia Surround when you can use these features from your video driver?

**Comment by Tom999Hall** [comment]
Thanks for the why-not explanation

-Tom
 


Sent from Mail for Windows 10
