### ISSUE TITLE
beta 10: wrong monitor resolutions detected in triple screen setup

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#334]
the reality:
My monitors are set up in a row, from left to right it is monitor:
A, B, C
Monitor A is 3840x2160, 60Hz, scaling 150%
Monitor B is 1920x1080, 144Hz, scaling 100%
Monitor C is 1920x1080, 60Hz, scaling 175%
The taskbar is only visible on monitor B.
Monitor B is the main monitor.

what MaxTo shows:
When going thru the first-time setup to set regions it shows:
A 2560x1440
B 1920x1050
C 1997x617

I don't really want to deal with that and stopped further testing the software.
Should multi-monitor, high-res, high-refresh-rate setups with different scaling already work?
Could you inform me, when it does? I don't want to start working with/testing this
program, if it's not going to get the most basic thing (for my use-case, anyway) right.

**Comment by vegardlarsen** [comment]
Doesn't it show both the scaled and unscaled resolutions? Like this:

![image](https://user-images.githubusercontent.com/436508/52563278-36c16600-2e01-11e9-8844-2d1fee0066b9.png)

The resolutions you write seem to be correct to me according to your scaling settings. (Except you mistyped 1097px)

How do you hide the taskbars? Any special program besides what Windows allows by default?

Which Windows version are you on?

**Comment by davidermined** [comment]
no it does not. It shows only one number. 
Yep, I did mistype 1097 px.
I am not using any special programs, beside the Windows setting.
I am on the latest Windows 10.
This is what it looks like.
Some more info about my monitors.
Note, that Windows gives each monitor a name, whereas MaxTo refers
to all monitors as "generic monitor". Something's wrong here.
![howitlookslike](https://user-images.githubusercontent.com/23729465/52882227-49240280-3167-11e9-9ab6-62f0dfd9aeba.PNG)
![monitorinfopng](https://user-images.githubusercontent.com/23729465/52882228-49240280-3167-11e9-8e5c-0173638376c6.PNG)

Is the expected behaviour, that all my areas have to be redone, should I ever change resolution, scaling or the size of the windows taskbar?

**Comment by davidermined** [comment]
It would be good, if there is a hint, that the resolution shown is with the taskbar subtracted.
It is really jarring, when you see weirdo numbers, that you don't recognize as being related to the resolution of your monitor. Even the example screenshot looks super broken and confusing.

**Comment by vegardlarsen** [comment]
I just realized what probably causes this. In beta.10 the UI process is missing a manifest. It was present in beta.9. 

Can you try downgrading to beta.9 (you'll need to uninstall, reboot, and then install the previous release). If I am right this has already been fixed for the next release.

**Comment by davidermined** [comment]
Installed "beta.9". Now it shows the correct monitor resolutions without confusing me with scaling stuff, I don't care about. I guess, that's good.

**Comment by GeorgePetropoulos** [comment]
The problem still exists. I am in trial but if this is not resolved I will just find another solution

**Comment by vegardlarsen** [comment]
@GeorgePetropoulos Which version are you running?

**Comment by GeorgePetropoulos** [comment]
I am using the latest I think.
Just downloaded two days ago.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GeorgePetropoulos** [comment]
@vegardlarsen I am using the latest I think.
Just downloaded a few days ago.

**Comment by vegardlarsen** [comment]
@GeorgePetropoulos Can you please check in Settings, About to see which version you are running?

PS! I am currently on vacation, responses may be slow.

**Comment by GeorgePetropoulos** [comment]
2.0.1

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vegardlarsen** [comment]
@GeorgePetropoulos Sorry for the slow response time. I've been away on vacation. You should uninstall the current version of MaxTo, and try downloading and installing [version 2.1.0-beta.2 from our website](https://maxto.net/release/beta).
