### ISSUE TITLE
Comand line trigger recipe not working

### ISSUE THREAD

**Issue by KrisKind75** [digitalcreations/MaxTo#336]
**Describe the bug**
On the homepage it is indicated that the comand `maxto recipe "Notepad on the side"` will launch a recipe. It does not work.
Also the command is not listed in the comand list when typing `maxto`

**To Reproduce**
1. Open cmd.exe
2. Type maxto recipe "name of recipe"
3. Nothing happens

**Expected behavior**
Launch the predefined recipe 

**System information:**
 - Windows version: 10
 - MaxTo version 2.0 beta 10

**Comment by vegardlarsen** [comment]
You are right. This was left over from a preview of the website, and the functionality itself is not ready yet, and won't be ready until version 2.1. I am removing it from the website.

We do however intend to support this syntax in the future though.

**Comment by KrisKind75** [comment]
> 
> 
> You are right. This was left over from a preview of the website, and the functionality itself is not ready yet, and won't be ready until version 2.1. I am removing it from the website.
> 
> We do however intend to support this syntax in the future though.

Looking forward to it!
Thanks
