### ISSUE TITLE
AppCrash while moving Child window to region in Passive mode

### ISSUE THREAD

**Issue by beauw** [digitalcreations/MaxTo#34]
While dragging an application subwindow (I was dragging a child window of FlameRobin) while in passive mode and holding the 'Shift' button; the Window snaps to the correct region followed by MaxTo crashing and displaying an error dialog with the message: "The application has crashed and it will now be dismissed.  A bug report has been sent to the developer. We apologize for the inconvenience."

**Comment by vegardlarsen** [comment]
@beauw Thanks for reporting. I haven't seen the crash report show up here yet, but if you want you could e-mail me (address on the website) the file "Exception_<something>.zip" file from `C:\Program files (x86)\MaxTo`.

**Comment by vegardlarsen** [comment]
I believe this could be due to a bug in how MaxTo handled windows without an icon. I am unable to reproduce this with my local build of MaxTo.

@beauw If you want to try a private build, e-mail me and we can double-check if the problem has disappeared on your end.

**Comment by beauw** [comment]
Hi Vegard,

I would be happy to test this out here.  My trial period has expired
though, would it be possible to test this out before buying a license?

Thanks,

Beau

**Comment by vegardlarsen** [comment]
@beauw Since my comment I have released a new version with this bug fix included. If you upgrade to 2013.02 it should hopefully work. If you don't have a license for that release, e-mail me privately (address on website).
