### ISSUE TITLE
Compatibility list should show whether something has been disabled

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#343]
Like the entry "Adobe Acrobat Reader" should be red, instead of blue, after I disabled the workaround.
Because I know I'm gonna have to check this, after it auto-updates, because I have not enough faith yet, to assume it wouldn't overwrite the setting.

The whole thing is confusing anyway. From my perspective, disabling the setting is my workaround to MaxTo being difficult/conservative/complying with security blabla.
So I'm turning something "on" instead of "off".
I'm really glad, that I don't have do "shims.xml"-stuff anymore.
That was super aversive.

**Comment by vegardlarsen** [comment]
I agree that there should be some sort of indication from the overview if a shim has been disabled. I'll look into adding this for 2.0. I'm not sure as to how to formulate a sentence that doesn't come out confusing with regards to the disabling of shims. Does "The shims you disable are stored in your user settings." make sense here?

The Adobe Reader shim is special, because the default settings in Adobe Reader causes a crash if MaxTo runs without its shims. So it is more that Adobe Reader is being weird.

**Comment by davidermined** [comment]
actually I mistakenly assumed, that the shims-thing was done already by clicking the button here.
Having this documented right in the program, instead of having to google this and reading it on GitHub is better, I guess.
But why can't MaxTo just edit the bloody shims itself? The fact, that the user has to deal with that is still terrible. Like I don't even know what the hell "shims" is supposed to mean.
Don't you see a problem with asking the user to do something so obscure, weird and annoying?
Like you can use your program properly, if you do this quest and talk to some Swedish dragon first.
Then some people might not even know how to interpret %ProgramFiles%, because they've never seen that expression. It's a power-user thing to know, but using the PDF reader that everybody uses is not.
Can't you at least make step 2 a clickable link, so that when I click on the path it opens the explorer window or it just opens the shims for me?

**Comment by vegardlarsen** [comment]
I think there is some confusion as to what you are seeing here. MaxTo does control the shims, and we can update them without requiring a MaxTo upgrade.

A shim is basically a way for us to tell MaxTo that program X does not support method Y that is normally used by MaxTo to achieve some goal. MaxTo will disable some functionality just for program X if that program is running. If the shim hadn't been loaded, the end result would be that program X would crash (or misbehave).

To try and explain to the end user what is happening, a shim can also contain a description of what is happening. This is basically just formatted text, and we present it both in the application and on the website.

PS! The explanation for the Adobe Reader shim will be changed once version 2.0 becomes final. The explanations are shared between the versions. When version 2.0 final is released the explanation will be more along the lines of "make these changes in Adobe Reader, then come back here and disable this shim".

**Comment by vegardlarsen** [comment]
This has been fixed for 2.0.0-rc.2.
