### ISSUE TITLE
Startup should give me a reason to care

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#345]
In "Startup" there's a nice setting to enable elevation.
But there's no reason given, whether I should or should not do that.
What's the point, exactly?
It makes me uncertain, whether I should or shouldn't do it.
Which is a bad feeling and aversive.

**Comment by vegardlarsen** [comment]
Do you have a suggestion as to what we should write here to concisely describe this feature better than we currently do?

**Comment by davidermined** [comment]
No, because I don't know why elevating MaxTo is advantageous.
Because the program never told me and I don't know or care enough about obscure Windows permission settings. Most people don't either. 
Not like Windows ever tells you, why there's a permission system in the first place. 
Something, something security blabla that wastes time of the day, by calling an invisible elevation prompt that has the preternatural ability to hide behind open Windows or start minimized. 
The permission system in Windows sucks and is a bad user experience.
Making me deal with, it is a small cost. In attention and general goodwill towards all living beings.
There should be a reason given, when and why paying that cost is necessary.
That makes it cheaper. Might make it cathartic to read something like:
"Windows is stupid sometimes and disables this or that feature. Elevating it, fixes that."

**Comment by vegardlarsen** [comment]
We should probably become better at linking to the documentation. Here is [background material](https://maxto.net/documentation/configuration/startup).

**Comment by davidermined** [comment]
"needed for making MaxTo work with other elevated programs" would suffice
as a hint, for me anyway. Having the description that most people, who
actually care about all the settings and then a link explaining UAC would
be good. Though the hint was all I was missing, really.

**Comment by Gubith** [comment]
If the setting is important enough to exist, it is important enough for a brief description.

**Comment by vegardlarsen** [comment]
I've changed the descriptive text for this setting:

> This setting lets you control whether Maxto runs elevated or as a normal user. When running as a normal user, MaxTo cannot interact with programs running with elevated permissions.

This will be in 2.1. Translations pending. :)
