### ISSUE TITLE
some weird error message appeared

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#346]
just leisurely moved the settings window around
no idea what that's all about

![image](https://user-images.githubusercontent.com/23729465/53297774-8b160e00-3823-11e9-92f2-f9a7443e4824.png)

**Comment by davidermined** [comment]
the details field:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Native.MaxToWindowOperations.MoveToRectangle(Rectangle region, Boolean isMaxtomized)
   at MaxTo.Companion.MessageHandlers.MaximizeWindowMessageHandler.ActInternal(String name, Message message)
   at MaxTo.Companion.MessageHandlers.WindowMessageHandlerBase.Act(Message message)
   at MaxTo.Companion.MessageHandlers.WindowMessageHandlerDispatcher.Dispatch(Message message)
   at MaxTo.Companion.Hook.HookController.MessageSourceOnWindowMessage(Object sender, Message message)
   at MaxTo.Core.Native.HiddenWindowMessageSource.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MaxTo.Companion.x86
    Assembly Version: 2.0.0.456
    Win32 Version: 2.0.0.456
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/MaxTo.Companion.x86.exe
----------------------------------------
MaxTo.Core
    Assembly Version: 2.0.0.456
    Win32 Version: 2.0.0.456
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/MaxTo.Core.EXE
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.7.1.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Serilog.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Serilog.Sinks.Debug
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Serilog.Sinks.Debug.DLL
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 2.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Serilog.Sinks.File.DLL
----------------------------------------
Serilog.Sinks.Raygun
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Serilog.Sinks.Raygun.DLL
----------------------------------------
Mindscape.Raygun4Net4
    Assembly Version: 5.5.2.0
    Win32 Version: 5.5.2.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Mindscape.Raygun4Net4.DLL
----------------------------------------
Mindscape.Raygun4Net
    Assembly Version: 5.5.2.0
    Win32 Version: 5.5.2.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Mindscape.Raygun4Net.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3282.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Caliburn.Micro
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Caliburn.Micro.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Reflection.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll
----------------------------------------
DigitalCreations.Rett
    Assembly Version: 1.0.31.0
    Win32 Version: 1.0.31
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/DigitalCreations.Rett.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Newtonsoft.Json.DLL
----------------------------------------
VirtualDesktop
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/VirtualDesktop.DLL
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/NuGet.Squirrel.DLL
----------------------------------------
Squirrel
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/Splat.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MahApps.Metro.IconPacks.Modern
    Assembly Version: 2.3.0.4
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/david/AppData/Local/MaxTo/app-2.0.0-rc1/MahApps.Metro.IconPacks.Modern.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by vegardlarsen** [comment]
Definitely a bug. I'll look into what happened here.
