### ISSUE TITLE
MaxTo turns window transparent for no reason, even after exiting it

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#348]
see title
![image](https://user-images.githubusercontent.com/23729465/53297926-0bd60980-3826-11e9-843f-6b892f80d7ed.png)

**Comment by vegardlarsen** [comment]
Can you consistently reproduce this with new apps? How?

**Comment by davidermined** [comment]
probably not. Long ago, don't know how I managed.
Just playing around absent-mindedly. Can be closed, probably.
If I notice it again, I'll reopen.
