### ISSUE TITLE
Does not start on logon when elevation enabled

### ISSUE THREAD

**Issue by bojordan** [digitalcreations/MaxTo#349]
MaxTo 2.0.0-rc1 doesn't automatically start on logon for me. This is not new to 2.0.0-rc1 (sorry for not reporting earlier). To be best of my memory, automatic start began to fail when I enabled elevation.

**Comment by samusaran** [comment]
This happens to me as well, but I have UAC disabled, so I can't actually enable or disable elevation.

**Comment by vegardlarsen** [comment]
Can you check your MaxTo logs ([here's how](https://maxto.net/documentation/troubleshooting)) and see if you receive any sort of exception.

My guess is that a previous version of the startup task is present (from the previous version of MaxTo), and may need to be removed manually. If that is the case; open Task Scheduler, and manually delete the task called "MaxTo" (maybe in lowercase).

![image](https://user-images.githubusercontent.com/436508/53549506-9bd0c780-3b34-11e9-89d4-eba63eb7c6a7.png)

**Comment by vegardlarsen** [comment]
This appears to be the same as issue #347. Closing this as duplicate.

**Comment by khongi** [comment]
I removed the old task ![maxto_old_task](https://user-images.githubusercontent.com/11983684/53552432-9d51be00-3b3b-11e9-9561-bfd23d91f7b3.jpg)

Seemed like something wrong with the path. Then I started MaxTo, it recreated the task, but after restart still no MaxTo. Same problem.
![maxto_new_task](https://user-images.githubusercontent.com/11983684/53552884-ad1dd200-3b3c-11e9-96ae-1c8a1870af74.PNG)

I checked the error code and looks like if you remove the `file:\` part from Action\Start in (optional) 
![maxto_task_startin](https://user-images.githubusercontent.com/11983684/53553216-6a102e80-3b3d-11e9-9bb4-53171f3948e8.PNG)

Then the task runs successfully.

![maxto_task_successful](https://user-images.githubusercontent.com/11983684/53553222-6f6d7900-3b3d-11e9-8404-4306aa7d19c6.PNG)
