### ISSUE TITLE
Crash when used with Skype

### ISSUE THREAD

**Issue by Twelve-60** [digitalcreations/MaxTo#35]
Not sure if this is a skype-related, high-dpi-related or otherwise, but whenever using Maxto it crashes when used with Skype (not the app version) with the shift hotkey. Fortunately works with most other applications though.

I'm running Windows 8.1 64bit at 2560x1600.

All the system hook diagnostics fail if that is of any help.

**Comment by vegardlarsen** [comment]
@Twelve-60 Thanks for reporting this. If all of the diagnostics fail, I would recommend rebooting before trying again. If the Skype issue is still present (and the diagnostics pass), I'll try to have a look into what is happening.

**Comment by vegardlarsen** [comment]
After trying to reproduce this for a while, and since I haven't heard anything more from @Twelve-60, I am concluding that this was a transient issue on your machine.

**Comment by Twelve-60** [comment]
Sorry, I didn't get back to you.

This is still occurring for me, system hook diagnostics always fail even after reboot.

Is there any way I can supply data for you?

**Comment by vegardlarsen** [comment]
@Twelve-60 Here is a [private build](https://dl.dropboxusercontent.com/u/12591686/MaxToSetup-Twelve-60.exe). Let me know when you have downloaded it so I can remove it. To install you will need to uninstall your current version of MaxTo, then install this (they have the same version number, so won't install unless you uninstall first).

**Comment by Twelve-60** [comment]
I have downloaded and installed, but am getting the same issue and diagnostic results. Anything I need to do?

**Comment by vegardlarsen** [comment]
Are you running the latest version of Skype (7.0.0.102)?

Skype is a 32-bit application. Are other 32-bit applications working with MaxTo? A good test subject is Windows Media Player (Start, Run, "wmplayer").

**Comment by Twelve-60** [comment]
Correct, 7.0.0.102. Windows Media Player works as expected.

**Comment by vegardlarsen** [comment]
I'm afraid I have no idea what is causing it then. I am just now preparing a new release to go out, so a fix for this won't make it in this release.

Do you have any other software that may be interfering with MaxTo, or does anything remotely related to window management?

**Comment by Twelve-60** [comment]
That is a shame :( Does MaxTo auto-update?

I can't think of anything that would be interfering, especially since Skype is the only application thus far to have the problem.

**Comment by vegardlarsen** [comment]
Unless you've turned it on in the options, MaxTo will notify you of new updates, but it won't update itself. I'll keep trying to figure out what could be happening here, but so far I have no ideas.
