### ISSUE TITLE
Span multiple regions

### ISSUE THREAD

**Issue by jteris** [digitalcreations/MaxTo#351]
Is there any way to span a window across two regions? Easy example...if the monitor is split into 4 equal regions so if you had a 2x2 grid with the following regions:
     1     |    2   
--------|--------
     3     |    4 
I need the ability to still have all 4 regions but be able to span across regions 2/4 and 1/3 while other times have individual windows in grids 1-4.

**Comment by vegardlarsen** [comment]
At the moment, no.

However, we are working on commands called `expand` and `contract`, which will allow you to do what you say using keyboard shortcuts. See issue #306.

**Comment by loneboat** [comment]
+1 for this. So far it's the only gap I've run across using MaxTo!
