### ISSUE TITLE
Windows can't be moved to a different monitor if on same virtual desktop

### ISSUE THREAD

**Issue by heystenner** [digitalcreations/MaxTo#358]
**Describe the bug**
I have tree monitors installed. When I use a recipe to move a window to a specific monitor AND to a specific virtual desktop, it _only_ works, if I am on a different virtual desktop. If I'm on the _same_ virtual desktop, the window won't move.

**To Reproduce**
- Set up the recipe as seen below:
![grafik](https://user-images.githubusercontent.com/47742121/54074009-de5d7700-428d-11e9-9072-6b2dfcbf9a76.png)
- I go to virtual desktop no. 3 (the target desktop to move the window to)
- I hit the assigned key binding. (no other app uses this binding afaik)
- Nothing happens.

**Expected behavior**
The window is supposed to move to another monitor.

**System information:**
- Windows 10 Version 1803 build 17134.590
- MaxTo version 2.0.0-rc2

**Additional context**
`2019-03-09 17:12:30 [Core@2.0.0.470] [Information] Executing recipe '"Auf Desktop 3"' with 1 ingredients

2019-03-09 17:12:35 [Core@2.0.0.470] [Information] Recipe '"Auf Desktop 3"' executed successfully.

2019-03-09 17:12:51 [Core@2.0.0.470] [Information] Executing recipe '"Auf Desktop 3"' with 1 ingredients

2019-03-09 17:12:52 [Core@2.0.0.470] [Information] Recipe '"Auf Desktop 3"' executed successfully.

2019-03-09 17:13:01 [Core@2.0.0.470] [Information] Executing recipe '"Auf Desktop 3"' with 1 ingredients

2019-03-09 17:13:35 [Core@2.0.0.470] [Information] Recipe '"Auf Desktop 3"' executed successfully.`

Squirrel* : none

**Comment by vegardlarsen** [comment]
Thank you again for this report. If you run this on the command line, it would actually hang indefinitely:

```
maxto window move /VirtualDesktop 1 /Monitor "\\.\DISPLAY1"
```

I have fixed this now, so that we do not attempt to move a window between virtual desktops if the virtual desktop corresponds to the desktop you want to move the window to.

This fix will be in the next release.

**Comment by heystenner** [comment]
Hey @vegardlarsen thank you, I'm looking forward to it.
