### ISSUE TITLE
Tiled windows following resized regions

### ISSUE THREAD

**Issue by hultqvist** [digitalcreations/MaxTo#361]
**Is your feature request related to a problem? Please describe.**
Sometimes a window needs more space, but at the same time I want the other windows to stay tiled.

Related to #117 but with a different solution suggested.
**Describe the solution you'd like**
1. Hotkey for quick region editing:
Pressing this hotkey will open the region editor.
Pressing it again will save and close.

2. After regions are saved, all tiled windows should be resized to match the new region locations.

**Comment by vegardlarsen** [comment]
I think bringing back an equivalent of "Fit all windows to regions" as a command (we had that in 2017.07 and earlier). 

We are already planning some stuff for [version 2.1](https://github.com/digitalcreations/MaxTo/milestone/11) that could help here; being able to trigger a recipe on region changes, and then running this new "fit all windows" command would be helpful.

I am tagging this for 2.1, and will use this for implementing the "fit all windows to regions" as it used to be.

**Comment by gsunjka** [comment]
👍 That's great.    

I have a workflow like this:
I have set up multiple regions with two panes e.g. 1/2-1/2, 2/3-1/3, 3/4-1/4. If I want to have more space in one window, I switch the region from 1/2-1/2 to 2/3-1/3 with a keyboard shortcut. It would save a lot of time, if the two windows in the region would change size automatically after switching the region.

**Comment by vegardlarsen** [comment]
"Fit windows to regions" has been implemented as a command for version 2.1.0, and therefore I am closing this issue. :)
