### ISSUE TITLE
rc2 no way to access shims.xml

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#364]
tells me to go to %programfiles% and open the MaxTo-folder.
There is none.
![image](https://user-images.githubusercontent.com/23729465/54430833-07b25300-4725-11e9-8b4d-3fbee6b99789.png)

**Comment by vegardlarsen** [comment]
@davidermined This explanation was originally written for 2017.07, and will be updated once MaxTo 2.0.0 is final.
