### ISSUE TITLE
rc2 context menu key doesn't open menu in Tray Setting

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#365]
I'm forced to use the mouse to access MaxTo-settings. That is bad. All other entries in my Tray are happy to accept the context-menu button in lieu of the right mouse click. Just MaxTo doesn't.

**Comment by vegardlarsen** [comment]
Do you mean the context-menu button on your keyboard? How do you set the keyboard focus to an icon in the notification area?

**Comment by davidermined** [comment]
windows+b

Am Fr., 15. März 2019 um 13:34 Uhr schrieb Vegard Andreas Larsen <
notifications@github.com>:

**Comment by vegardlarsen** [comment]
Unfortunately, this is not something we can fix at this point in time. We use [a library](https://bitbucket.org/hardcodet/notifyicon-wpf) to create the notification area icon, and that library does not support activation through that key. It could be possible to submit an issue with them, but the last time they accepted an external change was in 2016.

I evaluate this as a very low-priority issue, as I suspect very few people navigate the notification area in this way.
