### ISSUE TITLE
(optional) default recipes without numPad

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#366]
I mean, just a set of them as an option, that I could quickly get for all the defaults. 
I would like to really try the preset recipes and I'm pretty sure the default stuff would serve all my needs, but I don't have convenient numpad at the moment. 
Many ergonomic keyboards forego having a numPad, and ergo-obsessed people are probably a part of the MaxTo userbase.
And besides, even if did, I rarely use it, so I'm never quite sure if numLock is on or off.
Makes it a bit unfriendly.

**Comment by vegardlarsen** [comment]
Check out [the release notes for 2.0.0-rc.3](https://maxto.net/release/beta), released less than an hour ago:

> This release candidate contains a large change to how MaxTo uses keyboard shortcuts. We can now override any system hotkey, so we have changed our default hotkeys:
>
> - Move windows using Windows + arrow keys
> - Swap windows using Windows + Alt + arrow keys
> - Center window on the monitor using Windows + Alt + C
> - Maximize to monitor using Windows + Alt + M
