### ISSUE TITLE
windows+up-arrow no longer maximizes window

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#369]
instead the window moves between unregioned state and the last region, I think.
Or something similarly weird, sometimes it switches between two regions and the unregioned state.
Since "window+up-arrow" is not a declared recipe, it is not for MaxTo's to screw with at all.
I want to complement the existing windows shortcuts, not replace them all.
(small chance, some key is stuck. I'll restart system to confirm)

**Comment by davidermined** [comment]
Restart didn't help (also killed all other things, that might modify key-input).

If this is intended behaviour, well...... wut?! Why?!
This isn't documented anywhere. Ain't a recipe and there is nowhere else to look.
But if it is not and you can't reproduce it:
This might be, because I have a strange keyboard layout, where the arrow-keys have an fn-function?
Gaming Keyboards like screwing around with that area of the keyboard to give some extra functionality. In my case it's a Lenovo Legion Y720.
It happens on my external keyboard, too though. This is just a guess.

https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.notebookreview.com%2Fwp-content%2Fuploads%2Fsites%2F2%2FLenovo-Legion-Y720-keyboard-669x501.jpg&imgrefurl=http%3A%2F%2Fwww.notebookreview.com%2Fnotebookreview%2Flenovo-legion-y720-review%2F&docid=wUu33MqZoBcdGM&tbnid=QsGmxx9Cp0pdDM%3A&vet=10ahUKEwjU2q6mroThAhWATRUIHQMmDe8QMwhDKAMwAw..i&w=669&h=501&bih=1158&biw=2194&q=lenovo%20legion%20y270%20keyboard&ved=0ahUKEwjU2q6mroThAhWATRUIHQMmDe8QMwhDKAMwAw&iact=mrc&uact=8#h=501&imgdii=QsGmxx9Cp0pdDM:&vet=10ahUKEwjU2q6mroThAhWATRUIHQMmDe8QMwhDKAMwAw..i&w=669

**Comment by vegardlarsen** [comment]
@davidermined We did change this in rc.3, and this has been a very requested feature from several people. Win+arrow keys moves the window to the region in the direction of the arrow key. You can always change the default hotkeys to something of your liking.

There are simply to few shortcut keys available for us unless we override the Win+arrow keys combination, or resort to using the numpad by default.

**Comment by davidermined** [comment]
so.....
Ah, nvm. I just saw that rc3 got online today. Guess my testing round got
kinda outdated :(

Am Fr., 15. März 2019 um 15:53 Uhr schrieb Vegard Andreas Larsen <
notifications@github.com>:

**Comment by davidermined** [comment]
I'm on rc3 now.
I deleted all the recipes that use two keys only. Default Windows behaviour is still overriden.
Do you mean to say, I have to create a recipe for each shortcut, that does exactly what the shortcut usually does?

**Comment by vegardlarsen** [comment]
@davidermined Unfortunately, we do not have a nice experience to allow you to "reset settings" partially. The easiest way to reset the settings (and get the new defaults), is to exit MaxTo, delete `%AppData%\MaxTo\config.json`, and then start it again. This will not loose your monitor regions, but it will loose any presets and other keyboard shortcuts you may have.

**Comment by davidermined** [comment]
I uninstalled. I deleted all configs in %appdata%. And in local. Then reinstalled rc3.
Then deleted all two-key shortcuts. And normal Windows-behaviour returned.
So that worked out.
Except for windows-up. That's still doing strange MaxTo things, I didn't agree to.
This shoudn't be an old config-thing, anymore.
Oversight?
![image](https://user-images.githubusercontent.com/23729465/54530849-324e1700-4984-11e9-99c7-ba6c73ec65c5.png)

**Comment by vegardlarsen** [comment]
Not an oversight, but something we haven't been able to differentiate. 

Windows+Up on a default Windows installation maximizes the window (the exact same way as if you had clicked the maximize button using the mouse), and we cannot differentiate between a Windows+Up maximize and a mouse click maximize.

**Comment by davidermined** [comment]
never used the mouse-click maximize thing in the old MaxTo either. I think
I could disable that.
Yeah, passive mode did that. I loved passive mode.
Could there be a checkbox that turns it off? Did I miss it?
Cause I won't see myself using it, otherwise. Kinda a big deal.
(unless I can set a recipe to emulate what the shortcut does anyway)

Am Mo., 18. März 2019 um 14:59 Uhr schrieb Vegard Andreas Larsen <
notifications@github.com>:

**Comment by vegardlarsen** [comment]
Windows+Up has always been like this, even in previous versions of MaxTo.

We do not currently support passive mode in 2.0. We are considering bringing it back.

**Comment by davidermined** [comment]
Please.
Never got into active mode usage.
Seemed to be in the way, instead of complimenting existing muscle memory.
Especially now that windows 10 let's you easily quarter.
