### ISSUE TITLE
I can't install the software do to multiple errors (error loading 64 bit max to

### ISSUE THREAD

**Issue by apextools** [digitalcreations/MaxTo#37]
says error loading 64 bit max to
says wont work on my machine
to download and install updates from microsoft for C++ 2012 x 64
when installed reboot computer and max to will work
i go here: http://www.microsoft.com/en-us/download/details.aspx?id=30679
directs me to microsofts site to download some updates
all them installed but one
i get this error on the microsoft download file
vcredist_arm.exe is not a valid win32 application
so it does not let me complete the install to be able to use the program
what should i do?

**Comment by vegardlarsen** [comment]
@apextools You do not need the `vcredist_arm.exe`, you only need `vcredist_x64.exe` and `vcredist_x86.exe`. The installer should have set this up for you. Also the link to the download seems to be wrong, [this is the one you need](http://www.microsoft.com/en-us/download/details.aspx?id=40784).

I will double check that that error message links you to the correct download.

**Comment by apextools** [comment]
Thank you that new link did the trick and I got the software to install. 

But now the main reason i bought it was to be able to split regions for trading charts

when i maximize ie chrome etc.. it snaps to the region but I can not get the chart to snap it always takes the full screen. I use ninjatrader.com (free to download here for testing) http://www.ninjatrader.com/download-registration.php Do you have any ideas on how I can get it to work?

**Comment by apextools** [comment]
reboot of computer fixed it (windows 7)

**Comment by vegardlarsen** [comment]
@apextools Good to hear. I am keeping this open until I have fixed the link in the app.

**Comment by yrio** [comment]
The link in the app's message box still points to Visual C++ Redistributable for Visual Studio 2012 Update 1. (not for Visual Studio 2013)

![capture](https://cloud.githubusercontent.com/assets/9688834/6056708/593e05b0-ad47-11e4-8ca1-9be6a27da88f.PNG)

**Comment by vegardlarsen** [comment]
@yrio As we haven't released a new version since this bug was opened, that is still the case, yes.

**Comment by apextools** [comment]
Yed
