### ISSUE TITLE
MaxTo shortcut shouldn't just start the service RC3

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#371]
(this is actually a different issue from the silent setup)

As a naive and innocent user, I expect to enter "windows-key", type "MaxTo" and then have something I can interact with open. Same for the MaxTo shortcut.
Not the service to wordlessly start after having to answer a "this thing does changes, Windows is concerned about"-user prompt to answer.
Which is odd anywway, since Windows is ok with having it run on startUp.
As a very innocent user, who still thinks that hiding the taskbar is not a completely broken windows feature, it might evade my attention completely, that the service actually started.
The problem with the prompt specifically, is that you expect it during the setup, so this makes me think I accidentally clicked the setup again (and sometimes programs actually name their setup in that way and the Windows search finds them and that just spells trouble).
Then I also don't expect it to tell me that MaxTo is already running. I kinda knew that already, I wanted to go to the options to configure MaxTo.
If I had my taskbar routinely hidden, I might even get angry at that point, because no, obviously MaxTo isn't running already, because I can't find any sign of MaxTo.
("start program, then look in he tray bar for the program" is not instinctual behaviour for good-natured Windows users, and they get kinda less good-natured, when they get confronted with frustrating weirdness)

Usually a shortcut behaves differently and users expect that.
Going thru the tray icon via right Mouseclick as the only path to settings isn't sufficient, nor is it obvious.
It's way too Ninja.

addendum: also some Windows power-users experience Windows as a wonderful, productive flow of complete and utter control.......... and then some unexpected bullshit happens, that gives them screaming fits. Be nice to us, yeah :)

addendum 2:
Installed RC3. I noticed just now, that it tells me to look for MaxTo in the notification area.
But...... Windows users just don't have time for reading prompts, tbh. They're strongly conditioned to regard them as spam, that's in their way. Ok,ok,ok,next,next,next,install. That's Windows.
So, still unhappy about it not just opening settings.

**Comment by vegardlarsen** [comment]
Previous versions opened the change regions screen when you tried to run a second instance, as I don't think opening the settings is appropriate. We may do that here as well. Another alternative is to have the current instance pop up a notification "bubble" that points to the application icon.

We are thinking about this. If you have any good suggestion as to what we could show instead, I would be happy to hear them.

**Comment by davidermined** [comment]
Logitech G Hub opens settings when clicking the shortcut. So does
RescueTime.
It's understood that those services run in background doing things. That
you only open them by shortcut (or by tray option) to modify the "doing
things"-part,
not to start the service, which is usually auto-start anyway.

I'd want the shortcuts to open the Settings, but also I want there to be a
very ovbvious way to open the screen "change region" from the settings.
The "notification area" context menu shouldn't be what you have to use to
get all the functionality. It's good if it has all of it, it's bad if it
has all of it alone.
Because..... depending on your scaling settings, monitor size and DPI, this
icon might be tiny and the notification area is just fumbly. Especially if
you have to use your mouse.
Especially if people use "hide taskbar".
More paths, more chances of people finding what they want.
Also I think, that there should be a link from "change region screen" to
open "settings", as well.
Same principle.

Am Mo., 18. März 2019 um 10:43 Uhr schrieb Vegard Andreas Larsen <
notifications@github.com>:
