### ISSUE TITLE
Grouping regions and Expand to Group and then Return to original position

### ISSUE THREAD

**Issue by wbochar** [digitalcreations/MaxTo#373]
An example layout:

![MaxtoRequest](https://user-images.githubusercontent.com/2974227/54443421-f6fae080-4716-11e9-9917-d030c4127c8c.jpg)

It would be amazing to have the ability to create grouped regions (and floating regions) that could be added to list of window positions. 

Often with the above config it would be useful to expand to 2/3 the screen briefly to do editing or commands then drop it back to its original position. Also, the ability to assign a unique id to the groups. Like ALT-WIN-1 though 9 for the groups and ALT-WIN-0 to return to its previous position. The ability to also toggle on/off the groups (in config panel) from the common NUM-WIN-LEFT etc would also be useful.

**Comment by vegardlarsen** [comment]
We are working on something similar, called [expand/contract](https://github.com/digitalcreations/MaxTo/issues/306). It would basically allow you to set up shortcuts that would expand a window edge in the direction you choose.

We are thinking it would Windows+Shift+arrow keys, and pressing e.g. Windows+Shift+Left would expand the left edge of the active window to the next region edge, window edge or monitor edge. Consecutive presses would move it further in that direction.

I am hoping we will be able to add "expand vertically/horizontally/all directions" as an option here.

I am closing this issue as I think it is basically the same thing as what we are already working on.
