### ISSUE TITLE
not "natural windows behaviour", 2.0.0

### ISSUE THREAD

**Issue by DavidGretzschel** [digitalcreations/MaxTo#374]
That would be, if I could when having used the windows-right to half-screen a window, then used windows-down to give it the right lower quarter:
Also, windows-up with this setting doesn't actually reliably maximise the window either.
(observed with the snipping-tool window, post-snip)
Sometimes it decides to do random bs, as well. (sometimes it takes up maximum vertical, but only 4/5 of the horizontal of the screen; then windows-up toggles in between those states; ain't nothing to do with regions either, I haven't set any)
With normal Windows-shortcuts, I could actually use "windows-up" to assign the window to the upper right quarter.
Don't know what a good alternative description would be. But anything that's correct would be better than the current. (I admit, that: "It'll do unpredictable non-sense." is an awkward thing to write.)
I have a really hard time predicting, what MaxTo does and don't want to use it in this state. 
I need to know, that the same action yields the same results every time and that what already worked very well, doesn't get overwritten.

![image](https://user-images.githubusercontent.com/23729465/54688506-06669900-4b1e-11e9-8c3f-40f463365001.png)

**Comment by davidermined** [comment]
I know, this relates to "passive mode" not being implemented somehow. But this is a false description nevertheless.

**Comment by davidermined** [comment]
https://www.dropbox.com/s/cbmm97bt72qmszh/2019-03-20-1447-30.mp4?dl=0

Here's a video where I just press "windows-up" over and over, that has nothing to do with "natural windows behaviour" or maximization.

**Comment by davidermined** [comment]
ibn4: I did delete all config for MaxTo before installing the new version.

**Comment by vegardlarsen** [comment]
@davidermined Windows+Up on default Windows installations actually do different things based on the context. 

- If the window is in half-split screen, Windows+Up will move it to the top quarter of the monitor.
- If the window is in quarter-split screen, and on the bottom, Windows+Up changes it to half-split.
- If the window is in quarter-split-screen, and on the top, Windows+Up **maximizes the window**.

That final point there is where MaxTo will intercept and force it into a region, because MaxTo intercepts all maximize events, and this event is no different from any other method you may use to maximize the window (double-click title-bar, click maximize button, drag to center top of screen and release).

We are aware of this issue, we don't think it is possible to fix it; it may just end up being one of those quirks you have to live with if you decide not to use MaxTo's default shortcut keys.

**Comment by davidermined** [comment]
oops, sorry. Deleted it by accident. Here you go:
https://www.dropbox.com/s/cbmm97bt72qmszh/NONSENSE.mp4?dl=0

**Comment by davidermined** [comment]
to be fair, I haven't given MaxTos default shortcut keys more than half a look.
This might be workable. I'm not thrilled, when window management software asks me to
trow out deeply ingrained habits. But I'll give it a shot, maybe I'll make it work somehow,
maybe even like it.

**Comment by davidermined** [comment]
point still stands though, don't call it "natural windows behaviour".
Don't lie. It's evil. And people will shout at the monitor, when stuff is broken all of a sudden
without any warning.

**Comment by Reapsert** [comment]
I have been using the older, more classic version of maxto for a while now. But recently somehow a maxto update was forced onto me and now all of a sudden the software completely sucks for my natural usage. 

Shift draging onto regions works, but there are only one set of regions, where are the settings for alternate regionss that I LOVED?! 

And even when using windows+up does not really maximize a window. Some times it does not work at all even though a window is in a top quarter, and when it does "work" it is not really maximized but a minimized window scaled to fit the screen. This results in ugly borders and messes up some programs, not even mentioning trying to close a program with the cursor in the top right of a window just accidently rescaling the window instead. 

You had such an amazing, easy and simple software that I would gladly have paid the double amount for. And now you have ruined it for me. If you do not fix the behaviour or release older versions for download then I will sadly just have to find a new program that works more like yours did before...
