### ISSUE TITLE
Page Up missing

### ISSUE THREAD

**Issue by pettijohn** [digitalcreations/MaxTo#376]
Running 2.0.0 (stable). 
In setting, recipes, change keyboard shortcut, I see that I can select PageDown but not PageUp. 
Expected result: Page Up an option in the list.
Actual result: Page Up not present.

**Comment by vegardlarsen** [comment]
You are right; the name is wrong. You'll find PageUp right next to PageDown, under the name "Prior".

The names are gotten directly from an internal list by Microsoft (called `System.Windows.Forms.Keys`), so we didn't have to localize all the keys we use. However, in that list, some keys have multiple names, so Prior and PageUp have the same value, and in this case Prior just happens to come before PageUp in the list.

We did this as a shortcut so we could get 2.0 out the door as quickly as possible.

We will create our own list and try to get localized names for the next release.

**Comment by pettijohn** [comment]
Thanks! That solved it for me!

**Comment by vegardlarsen** [comment]
This issue has been closed because we have fixed it for version 2.1.0, where the key names are localizable.
