### ISSUE TITLE
MaxTo behaves as an U instead of an O on a 4 monitor setup, also unpredictable; 2.0.0

### ISSUE THREAD

**Issue by DavidGretzschel** [digitalcreations/MaxTo#377]
I don't really have software to capture 4 montiors at once, so bear with me here:

(picture for illustration of monitor layout)
I would like to use the "win+arrow"-recipes to navigate my "centered" window from monitor to monitor in clockwise fashion. Starting from monitor 4. This will not work, even though I will have pressed windows + down, right, up, left. At win+left it goes from monitor 3 back to 2, instead of from 3 to monitor 4 again.
Then I will do the same in counterclockwise direction from monitor 3.
down, left, up works and I am now on monitor 4. However windows+ right, which I expect to bring me to monitor 3 to complete the rotation actually brings me diagonally to monitor 2.

Monitor 2 is my "main display". I also ensured that the mouse can do the same movement, i.e. that there aren't "virtual gaps of air" between any of the monitors.

![image](https://user-images.githubusercontent.com/23729465/54824207-8883c880-4caa-11e9-86a1-6ad4b8c41299.png)

**Comment by davidermined** [comment]
this is a fresh MaxTo install using default and unchanged recipes

**Comment by davidermined** [comment]
also deleted the %appdata% folders, roaming and local first

**Comment by vegardlarsen** [comment]
Can you get me the monitor details for each of these monitors? You can find this information when you are looking at the change regions window, but you will have to do it for each monitor separately.
