### ISSUE TITLE
Recipe feature: cycle through regions

### ISSUE THREAD

**Issue by pettijohn** [digitalcreations/MaxTo#379]
I currently set up a few keyboard shortcuts for recipies, WIN+F1, WIN+F2, etc, that each load a region preset and then highlight the regions for 1000ms. There is a lot of repetition in setting these up.

Feature request is to be able to have that in one recipe where executing it repeatedly cycles through a set of region presets. I envision the UI being a new ingredient "Cycle Presets," and I can click checkboxes next to the presets I want to include when cycling. Possibly also drag & drop to reorder the sequence.

**Comment by vegardlarsen** [comment]
Thank you for this request. I think this ingredient makes sense. I am queuing this up for the work we'll do for 2.1, and it will be more thoroughly reviewed/examined once I get started.

**Comment by vegardlarsen** [comment]
This work is being completed today for version 2.1. Here is a snapshot from my testing (I've since fixed the spelling error).

![image](https://user-images.githubusercontent.com/436508/58556750-07523000-821d-11e9-870e-f2733bf656c0.png)
