### ISSUE TITLE
Cannot Install MaxTo : Failed to correctly acquire vcredist_x86.exe

### ISSUE THREAD

**Issue by elmezie** [digitalcreations/MaxTo#38]
When trying to install MaxTo , I get the following error everytime.

I have installed both the x86 and x64 Visual C++ Redistributable Packages for Visual Studio 2013 .
I have rebooted the computer several times, I have uninstalled and tried to reinstall maxTo several times as well.  Any ideas?

I am running

Windows 8 Pro with Media Center
Latest version of MaxTo ( Problem occurs with previous versions as well )
I do have windows firewall disabled

![maxto](https://cloud.githubusercontent.com/assets/6753827/5750845/2e0ab350-9c0f-11e4-893b-47c230b74497.png)

**Comment by vegardlarsen** [comment]
@elmezie It seems the checksum of the files has changed on Microsoft's server. A lot of customers have reported this lately. 

Until I can fix this in the installer, please download `vcredist_x86.exe` and `vcredist_x64.exe` [from here](http://www.microsoft.com/en-us/download/details.aspx?id=40784) and install them before running MaxTo's setup.

**Comment by elmezie** [comment]
Hello, 

I have also tried installing those both and uninstalling them and re-installing them and reboots.  Still no luck, when I run the install I get the same error unfortunately.

**Comment by vegardlarsen** [comment]
I have just now (a few minutes ago) uploaded a new version that fixes this issue. It seems Microsoft uploaded a new version of this file without giving it a new URL, which MaxTo's setup interpreted as an error in the download.

I committed the cardinal sin of not updating the version number of MaxTo, so everyone who needs this gets it with their previous license, and they don't get update notifications for a version which only fixes something in the installer. So, if you are experiencing this problem for a version downloaded after January 15th 2015, please let me know.

**Comment by elmezie** [comment]
One more question, where I can download the fixed version?  I downloaded the newest one listed on the website ( Version 2014.12 - Released Wednesday, 03 December 2014 ) and that seems to give me the same error.

**Comment by nishbish** [comment]
I just downloaded the trial version today and i have this problem after getting vcredist_x86.exe and vcredist_x64.exe.

**Comment by vegardlarsen** [comment]
@elmezie @nishbish The fixed version simply replaced the 2014.12 version. So downloading the latest release should be enough. It may be that I have botched something when I tried to fix this. I will investigate this further this weekend, but in the meantime you can try [downloading MaxTo directly](https://maxtostorage.blob.core.windows.net/releases/MaxToSetup-2014-12.exe) or using the workaround I posted above.

**Comment by begna112** [comment]
I downloaded the version u linked here and it still didnt work. also installed the C++ redistributables myself and no luck either. windows 8.1 64-bit. I get errors on opening maxto as well saying that 32bit and 64 bit couldnt load.

**Comment by statix1** [comment]
Came here to see if this issue was known; Using latest version of Maxto downloaded from website 
- Windows 8.1 pro 
- Downloaded the two files and installed prior and reboot; no luck 

Otherwise a very cool program

**Comment by vegardlarsen** [comment]
I am at a loss for what could be causing this. It had one very clear-cut reason, which should have been fixed with the latest release. I will be looking further into this tonight.

**Comment by statix1** [comment]
Quick question for the other users; Does the application actually work? I noticed that the main functionality of the application worked but it the errors were the only annoying thing that popped up at the beginning

Also I don't know if it helps but I noticed by Windows 8 kept deactivating and removing all my user settings. I had to reenter my key every time and then it would happen again. Ever since I uninstalled the problem went away. Not sure if it was related.

**Comment by elmezie** [comment]
Good catch @statix1 , It didnt even cross my mind to continue the installation.

It will eventually completely the installation , If I hit yes to continue installation and keep hitting yes for the next 5 or so times the error pops up.

However once it's installed it seems to run fine.

**Comment by gcstul** [comment]
Same deal. No luck.
Uninstalled everything, Loaded the Microsoft items, then the software and validation code.
I can make the regions, but nothing moves to the regions.

**Comment by statix1** [comment]
@gcstul Try pressing Ctrl+winkey and left and right arrow keys. Maxto does not replace the default Winkey+arrow combination it uses a seperate combination for itself. Took me a few min to realize this.

**Comment by gcstul** [comment]
That worked. They are where I want them to go, but that is just like using the windows method.
I was wanting true seperate windows where I could see the full window just as if it were the whole monitor, just smaller and 4 to a screen.

**Comment by statix1** [comment]
@gcstul If i understand your question correctly, you will need to draw those regions. You can split them into four regions and then maximize them into your four little 'fences'

**Comment by gcstul** [comment]
When I maximize in the four little regions, I hold alt and click maximize on the #2 monitor, It just makes it as large as the monitor. (32")

**Comment by gcstul** [comment]
On monitor #1, I only have split into two "horizontal fences", it seems ok.??

**Comment by gcstul** [comment]
Scratch that. The only think the "sizes" correctly on either screen is Microsoft Word.

**Comment by begna112** [comment]
It works sporadically for me as well. Never on windows explorer or some other programs. Does occasionally on others like mirc.

**Comment by vegardlarsen** [comment]
@begna112 @gcstul If MaxTo does not work with a single program, a reboot may be required. Also, continuing installation without getting the proper pre-requisites installed may be what is causing your issues. For MaxTo to work properly, you [NEED these pre-requisites installed](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (`vcredist_x64.exe` and `vcredist_x86.exe`). 

If MaxTo works with some windows and not others, this will probably be because some part of it is misbehaving, and then usually only 32-bit or 64-bit software will be affected. On newer Windows installations, most software is 64-bit (including explorer), but older versions of Word may be 32-bit.

**Comment by nishbish** [comment]
I managed to get it working this morning after uninstalling and re-installing.  I'm very happy with it and will be buying a license soon.

Just have a suggestion for future versions. When resizing a window and decreasing its width for example, would it be possible for the windows that were snapped next to the resized window to remain snapped and expand in to the space where the first window was occupying?

**Comment by vegardlarsen** [comment]
@nishbish Not to reveal too much, but I am thinking about how this can be done... :wink:

**Comment by szarouski** [comment]
>For MaxTo to work properly, you NEED these pre-requisites installed (vcredist_x64.exe and vcredist_x86.exe).

Thanks, that worked. I'm going to play a bit with the program and buy it when trial ends.
