### ISSUE TITLE
Window snapping not working

### ISSUE THREAD

**Issue by josezulu** [digitalcreations/MaxTo#380]
**Describe the bug**
Window snapping doesn't work, even when I have the setting turned on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Notepad.
2. Make it a small window, ~1/3 of the monitor size.
3. Open another Notepad.
4. Make it a small window, ~1/3 of the monitor size.
5. Put them side to side.
6. Move either of them around, no snapping.
7. Resize horizontally one of them back and forth to meet the other window edge, does not snap.

**Expected behavior**
It should snap like version 2017.07.

**Screenshots**

**System information:**
 - Windows 7.
 - MaxTo version 2.0.0

**Other**
You can reproduce the issue with Internet Explorer.

**Comment by vegardlarsen** [comment]
Does this issue also happen after rebooting your machine?

**Comment by josezulu** [comment]
I just run the following tests:

**A) Reboot: MaxTo loads automatically the last region preset used**
-window to monitor edge: snapping works
-window to regions: snapping works
-window to windows: snapping does not work

**B) Load a different region preset**
-window to monitor edge: snapping works
-window to regions: snapping works **but to the previous region!**
-window to windows: snapping does not work

**C) Reboot**
-Same as scenario A above.

**D) Load a different region preset**
-Same as scenario B above.

**My conclusion**
-snapping to monitor edge: works always.
-snapping to regions: only works to the region preset loaded upon reboot.
-snapping to window: never works.

Notes:
-I have "Active" selected, I'm not sure whether that setting does anything currently.
-To test this I used Chrome, Sublime Text and Windows Explorer.
-I have all three snapping options enabled.
