### ISSUE TITLE
Region naming and reset app positions

### ISSUE THREAD

**Issue by gingerrunner** [digitalcreations/MaxTo#383]
When writing a recipe, what is the naming convention for regions? For 2x1, top and bottom, left and right are fairly obvious.  But what if you have lots of regions, how are they identified?

Also, I want to create a script that resets the position of my favorite apps in my favorite positions - usually for when changing presets when docked or not. How can I achieve this if some but maybe not all of the apps are running? I.e. Launch if not running. And finally, if I have 2 instances, how to make sure both go in to the same region.

**Comment by vegardlarsen** [comment]
Thanks for writing. There really isn't a naming convention per se; as regions aren't named. You can give coordinates in pixels, percents, etc, to target any region currently at that point.

We currently do not support "launch if not running", but this is actually a very good idea. 

Ensuring two windows go into a region, could be done if you have different titles for the two windows that you know in advance. We could perhaps support a "all windows from a process", that could work?

**Comment by gingerrunner** [comment]
Thanks for the quick reply.

Let me know if & when you add a "launch if not running" option to the app, or if you can think of an alternative (such as writing a separate script that does it then calling that app from MaxTo?).

Can you give an example for the region coordinate suggestion + syntax. I will upload an example region setup, could you explain the region data I would need to use to target those regions?

All windows from a process option would work. In fact, what is the syntax for targeting a running app to a region? Is is the process name? I don't get the correlation of naming in the drop down menu versus running processes.

![2019-03-30](https://user-images.githubusercontent.com/49098209/55277884-6528d100-52db-11e9-83f4-75639b7dbdb5.png)

**Comment by vegardlarsen** [comment]
You can target an application through either its window title or its window class. The window class is something the application decides itself, but it may not be totally unique. The window title may change depending on what document you have open, which can also be an issue.

To target your regions, I would use something like:

- center left
- 50%, 50%
- 85%, 5% (85% from the left, 5% from the top)
- 85%, 30% (85% from the left, 30% from the top)
- bottom right
- top right

Does that help?

**Comment by gingerrunner** [comment]
Yes, thanks, the regions syntax worked for me.

I am still struggling with the other topic because of the challenges with the title/process.

I think my use is case is likely to be a common one - i.e. when docking or undocking, or switching between profiles, or even just if I move windows around regions, I just want to simply "reset apps to default windows positions". I like to have chrome in one region, slack in another, spotify in another etc., always the same apps in the same positions.  Is there any way to achieve this simply through the cmdline or the recipes?

**Comment by vegardlarsen** [comment]
There is, but it isn't as straight-forward as you would like, and features are coming to make this easier. See e.g. #301 for something that is coming in version 2.1.0.

If you want to assign this to a hotkey today, I'd recommend creating a recipe with multiple "Move window" ingredients. For each command, use these parameters:

- Set `Window` to the window title
- Set `Region` to one of the texts I provided below to target the regions.
- Leave the rest blank

I think that should work well for you.

**Comment by gingerrunner** [comment]
out of interest, what is the ETA on 2.1.0? I still don't have a solution for this issue and it would be good to have an indication of when it might it might be coming along..... thanks

**Comment by vegardlarsen** [comment]
ETA is unknown at this point. We have (and have had) some pressing issues in regards to payment processing on our website (SCA/PSD2 for those in the know), then enabling license renewals on the website, and finally coordinating on issue #415 with Microsoft. I'm afraid I don't know what to tell you.

**Comment by vegardlarsen** [comment]
@gingerrunner 2.1.0 is now in alpha.

**Comment by vegardlarsen** [comment]
@gingerrunner We did add "idempotent launch" in issue #498. It is in [the 2.1.0 previews](https://maxto.net/release/beta). In 2.1.0-beta.1 we also added support for partial matches for window titles, so you can add wildcards (e.g. "* - Notepad" to target any Notepad window on a US English machine).
