### ISSUE TITLE
New Demo Install & Setup

### ISSUE THREAD

**Issue by PappaSmurf** [digitalcreations/MaxTo#387]
**Describe the bug**

I have install MaxTo onto a Windows10 64bit Version and I am having the following issues

The monitor is an Acer ET430K (3840x2160@60Hz) which I have split into 4 different equal areas.

When I run 3 copies of Remote Desktop and place a Desktop into each area ( Upper Left, Upper Right and Lower Right ) I want to put the Main Screen into the Lower Left but I do not know how to do this.  Also I would like to reset the Resolution in each area to 1920x1080.

Is there something in the directions that I missed?

**Comment by vegardlarsen** [comment]
@PappaSmurf I am not entirely sure I see the problem here. You can use the "Quarters" preset, and once it has been loaded and you have clicked "Use regions", whenever you maximize a window it should go into the region beneath the mouse cursor.

You can also move the windows around using Windows+arrow keys to place them where you want. Does that help?

**Comment by PappaSmurf** [comment]
Hello, I have started up MaxTo, Clicked on Change Regions then Load Presets selected Quarters and finally checked Use Regions.  When I try to maximize one of the three Remote Desktops nothing happens other than it maximizes the Remote Desktop to full screen size and does not place it into one of the Quarters.
However, I found that if I select one of the Remote Desktops and use the Windows Key + an Arrow Key it does place the Remote Desktop into one of the quarters and I can use the Windows Key + an Arrow Key to move it to the location that I want.
Still, it does not resize the screen in the Region so that I can see the full screen.
And how do I place the main desktop into the fourth region.
PappaSmurf

**Comment by PappaSmurf** [comment]
Also, when I exited each of the Remote Desktops, set MaxTo to Not Active, I was left with the following screen.
![MaxTo_1](https://user-images.githubusercontent.com/5560374/55508859-fcfa2800-5617-11e9-980e-bdd69cf70a87.JPG)

**Comment by vegardlarsen** [comment]
When you connected to the remote machines, did you do this?

![image](https://user-images.githubusercontent.com/436508/55558768-15884200-56ed-11e9-832d-67ab010cc448.png)

I think Bad Things(tm) happens to RDP if you try to force it to move when in full screen. Setting the monitor size should bring it out as a normal window; and most connections [can be resized on the fly if you change some settings](https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/smart-resizing.html).
