### ISSUE TITLE
Regions keep changing size.

### ISSUE THREAD

**Issue by Draylynn** [digitalcreations/MaxTo#389]
**Describe the bug**
Regions aren't saving correctly and are changing size without help from the resizer.
This bug keeps resetting my resolution.txt files that record HUD feature locations in certain applications, quite annoying.

**To Reproduce**
Create Template: 840x|1500x|1500x.
Load Template: 842x|1499x|1499x.
Change Regions > Apply; 846x|1497x|1497x.
Change Regions > Apply; 849x|1495x|1496x.
...Etc.

**Expected behavior**
A created template should load the same way it saved.
Regions should only actively change via the region-changing drag bars.

**Screenshots**
NA

**System information:**
 - Win10
 - MaxTo 2.0.1

**Additional context**
NA

**Comment by vegardlarsen** [comment]
This issue is the same as #382. We are aware of this issue, and are working on it. I am closing this issue, but discussion can continue in #382.
