### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by will1792** [digitalcreations/MaxTo#39]
I have installed latest version(2014-12) on Windows 8.1(64-bit). It gave errors about vcredist but I installed them seperately and installation gives no error now. Still I have some issues.

1. When I do Options -> Diagnostics -> Run self-test, only Keyboard shortcuts(64-bit, Elevated 32-bit, Elevated 64-bit) are green-checked. I guess it should be all checked, shouldn't it?
2. Window snap does not turn off even it is unchecked in options.
3. Some windows gets bigger and bigger when I drag them. I found Line(messenger) and KakaoTalk(messenger) do this.
4. It reacts a bit slow. For example, window snap does not work sometimes and it is fixed when I release mouse button and drag it again. Also, aligned window should come back to its original size but sometimes they come back slowly.

Any suggestion? TIA

**Comment by vegardlarsen** [comment]
1. Does windows maximize to their region? If so, this can safely be ignored.
2. This could very well be a bug, I will have to examine it more closely.
3. These tools may be doing something strange when you resize them. I believe Line is already on our compatibility list that is supposed to prevent this, but I may be mistaken.
4. I have heard reports of these slowness issues, but I have never been able to reproduce them to figure out what is going on. Are you running any software in the background that may be conflicting with MaxTo?

**Comment by will1792** [comment]
1. Windows do maximize to their region.
2. I have two computer with Windows 8.1 and both have the same issue. Snap range option works well but other options do not work.
3. I read the issue about Line and adding a line in 'shims' file prevent Line to behave like that, but KakaoTalk still behave weird.
4. I'd say I don't have many programs running background. I have Kaspersky running on one computer and Avast Anti-virus running on the other, and both have TeamViewer running. I think I was running Internet Explorer, Xshell and Microsoft Excel when I got the issue.

**Comment by vegardlarsen** [comment]
@will1792 You can add a similar line for KakaoTalk. Just find the name of the executable (without the .exe ending) and add it in a similar way.

**Comment by statix1** [comment]
Hey Ive seen how quickly you respond to tickets and its pretty impressive and the  dedication is admirable. Keep up the good work!

**Comment by gcstul** [comment]
Same issues. No fix.

**Comment by vegardlarsen** [comment]
I have confirmed that the fixed I mentioned above works, and this will ship in the next release.
