### ISSUE TITLE
Work only on specific monitor(s)

### ISSUE THREAD

**Issue by AkazaRenn** [digitalcreations/MaxTo#390]
**Is your feature request related to a problem? Please describe.**
Yes, since there are still bugs on it affecting the user experience I would like to avoid them as much as possible.

**Describe the solution you'd like**
Add an option in settings allowing user to choose the monitor(s) that will be affected by this software.

**Describe alternatives you've considered**
Maybe... try fixing bugs faster?

**Comment by vegardlarsen** [comment]
@AkazaDorian Thank you for your feedback. MaxTo should not affect window maximizations on monitors where there are no regions set up?

**Comment by AkazaDorian** [comment]
@vegardlarsen Like [Offset when dragging a maxmized window down](https://github.com/digitalcreations/MaxTo/issues/338), and [Firefox doesn't keep its original window size after it's reduced to the taskbar](https://github.com/digitalcreations/MaxTo/issues/339) when I turned on the `Show tab previews in the Windows taskbar` option for Firefox.

**Comment by vegardlarsen** [comment]
I will investigate this in more detail. We haven't tested with that feature enabled in Firefox.

**Comment by AkazaDorian** [comment]
@vegardlarsen As a temporary fix, maybe the scheme could be changed to be a real "no effect" on monitors with no regions? (like uncheck the "Active" option)

**Comment by vegardlarsen** [comment]
@AkazaDorian That should already be the case.

**Comment by AkazaDorian** [comment]
@vegardlarsen Doesn't look like based on the behavior on bug (https://github.com/digitalcreations/MaxTo/issues/338)[Offset when dragging a maxmized window down]

**Comment by vegardlarsen** [comment]
This issue no longer happens in version 2.1.0. I don't know why exactly that is, but I am closing this issue.
