### ISSUE TITLE
Compatibility with Razer Synapse 3

### ISSUE THREAD

**Issue by RedeemerXy** [digitalcreations/MaxTo#392]
**Describe the bug**
MaxTo is preventing Razer Synapse 3 from working correctly. Most clicks in the Synapse window do not have any effect when MaxTo is running on the system. 

**To Reproduce**
1. Have MaxTo and Razer Synapse v3 working on the system in the background (started with Windows)
2. Open Synapse from the system tray icon
3. Move the Synapse window at least once by click dragging (this is where the faulty behaviour seems to hook in)
4. With a Razer device like a mouse or headset connected, click on the device and try to switch between any of the tabs in the top row by left clicking on them
5. none of those clicks have any effect

**Expected behavior**
MaxTo not interfering with Synapse functionality.

**System information:**
 - Windows version: 10
 - MaxTo version: 2.0.1, but also reproduced on 2017.07
 - Razer Central version: 7.3.11.110
 - Razer Synapse version: newest available update of v3 at the time of this report

**Comment by vegardlarsen** [comment]
Can you try adding an entry to the `%LocalAppData%\MaxTo\shims.json` file? It should be something like this:

```json
{
    "id": "razer_synapse",
    "descriptions": {
      "en": {
        "title": "Razer Synapse 3",
        "subtitle": "This subtitle intentionally left blank",
        "description": "This description intentionally left blank"
      }
    },
    "iconUrl": null,
    "url": null,
    "canDisable": true,
    "defaultEnabled": true,
    "ignore": false,
    "disableSubclassing": true,
    "disableSnapping": false,
    "disableTransparency": false,
    "useMoveWindow": false,
    "emulatesMaximize": false,
    "windowClasses": [],
    "processes": [ "<insert here>" ]
  }
```

Note that under `processes`, where it says `<insert here>`, you need to insert the process name of the file running. You can find that in Task Manager, on the Details tab. It is the name of the executable without the ".exe" extension. So if you can find `Razer_Synapse3.exe`, you'll need to insert `Razer_Synapse3` here.

Restart MaxTo and the affected program, and let me know if that works?

**Comment by RedeemerXy** [comment]
Yes, that did the trick!
I added the entry with the process "Razer Synapse 3" and now the mouse clicks have the proper effect again, thank you!

**Comment by vegardlarsen** [comment]
Great to hear. I will be adding this to the default compatibility shims when I get back from Easter vacation.

**Comment by vegardlarsen** [comment]
This is now a default shim (has been for some time, actually).
