### ISSUE TITLE
Windows 10 Virtual Desktops - HOW?

### ISSUE THREAD

**Issue by lucasdelamper** [digitalcreations/MaxTo#393]
I am using Virtual Desktops on Windows 10 and want to use different regions for different desktops.
When I set the regions in any desktop, they seem to be applied to all desktops.

The doc says that what I want can be done but fails to explain how to.

Please let me know and/or improve the doc.

Thanks

**Comment by vegardlarsen** [comment]
Thank you for the feedback on this. In the Settings window, under Monitor, check "Use different regions on each virtual desktop". I will update the documentation now (but it won't be updated until the next time we deploy the website).

**Comment by lucasdelamper** [comment]
I already set that flag. But then still the same regions apply to all
desktops. The question was and is: how to set other regions for a specific
desktop?

Thanks

Lucas

**Comment by vegardlarsen** [comment]
@lucasdelamper Sorry for the slow response on this, we are currently all on Easter vacation here.

You just need to switch to the virtual desktop you want to change the regions for, then open the "Change regions" window.

**Comment by lucasdelamper** [comment]
Oh. This is so weird. I'm sure this what what I tried, but every time my
regions were the same in all desktops.

I tried again and now it does work...

Thanks and I hope you can still enjoy your vacation

Lucas

**Comment by vegardlarsen** [comment]
Great to hear you got it to work :)
