### ISSUE TITLE
Remove a  Region Preset

### ISSUE THREAD

**Issue by DaePrice** [digitalcreations/MaxTo#397]
I can't seem to find a way to remove a preset. Am I missing something? I may have made too many presets....

**Comment by josezulu** [comment]
The only way I found to remove presets is to edit the "config.json" file in my user data folder "AppData\Roaming\MaxTo".

First I closed the program, then made a backup of the config file, then modified the config, then started the program.

**I don't know if this will work for you, IT MAY BREAK THINGS, so USE AT YOUR OWN RISK !!!** :)

**Comment by DaePrice** [comment]
Yeah, I found that route myself, and should have clarified in my original post. I can see how making profiles deletable would ALSO need to patch recipes dependent on them. 

Lucky me, i do feel comfortable editing the .json file. I removed the profile reference in the recipe using it, closed the app, deleted the lines in the config.json, then restarted MaxTo. It worked like a charm, but I wouldn't say it should be standard practice. It would be good to warn less technical users before creating lots of regions. This clarification need is similar to the "elevate MaxTo" issue. Just a little more clarification on whats going on and why will help answer some questions, and add to an already amazing program.

**Comment by vegardlarsen** [comment]
Sorry for the slow response on this; Easter vacation just ended here in Norway. Removing region presets is definitely coming.

@josezulu Correct. You don't even have to close MaxTo, it will reload the config file when it changes.

@DaePrice You are right; but what would happen is that recipes will be left in an invalid state. A bad thing for sure; but it will present an error message when the recipe is run.

**Comment by vegardlarsen** [comment]
This was actually implemented in 2.1.0-alpha.2. :)

**Comment by refactorsaurusrex** [comment]
> This was actually implemented in 2.1.0-alpha.2. :)

@vegardlarsen Can you clarify this? Is there a way to remove a preset from the UI? Or do you have to remove it directly from the config file?

**Comment by vegardlarsen** [comment]
@refactorsaurusrex When you have the edit regions window open, do this:

![image](https://user-images.githubusercontent.com/436508/76396773-1e13de80-637a-11ea-843b-cf4f30c39a7f.png)

Then you'll see this:

![image](https://user-images.githubusercontent.com/436508/76396819-3552cc00-637a-11ea-88de-b2d19c0ac295.png)

**Comment by refactorsaurusrex** [comment]
Ah, I totally missed that this is an alpha feature. I'm on the stable release. Thanks for the response!
