### ISSUE TITLE
CLI command for getting currently active regions preset name

### ISSUE THREAD

**Issue by Nodacode** [digitalcreations/MaxTo#399]
### **[Description]**
I am using a custom launcher program which runs batch files to switch to other presets, starts certain applications linked to the selected preset and moves windows to predefined regions in this preset. Being able to get the name of the active preset I could dynamically label my launcher and avoid loading a preset if it is already active by querying the name beforehand.

The json file for the currently active preset is not of much help because it is missing the name of the configured preset (*`"name": null`*). Could you please make this be carried over from *config.json* when activating a preset in a future release.

Comparing the active json file with a preset defined in *config.json* woud be doable but cumbersome. I think CLI enhancements would be the right way to go.

### **[Feature reqeust]**
It would be very handy to have a CLI command to get the name of the currently active regions preset.

And while we are at it, getting the file path of the currently active preset would also be very nice and getting the names of all configured regions presets would be another bonus. 
Enhancing the already implemented highlight CLI command to highlight certain regions presets without activating them would also be a nice enhancement.

Something like ...

*Usage:*
> `maxto regions active {name|path}`
> `maxto regions presets`
> `maxto regions highlight [name]`

*Examples:*

> **[Command]**
> `maxto regions active name`
> **[Output]**
> `MyDevRegions`

> **[Command]**
> `maxto regions active path`
> **[Output]**
> `C:\Users\<UserName>\AppData\Roaming\MaxTo\Monitor\<SystemName>\<MonitorName>\<ID>\0000\3440@96x1440@96.json`

> **[Command]**
> `maxto regions presets`
> **[Output]**
> `MyDevRegions`
> `MyMultimediaRegions`
> `MyResearchRegions`
> `MyWorkRegions`
> `Quarters`
> `Two on the left`
> `Two on the right`
> `Ultra-wide three-way`

> **[Command]**
> `maxto regions highlight MyMultimediaRegions`
> **[Result]**
> *Preset 'MyMultimediaRegions' will be highlighted in a preview without needing preset to be active.*

Thank you very much!

**Comment by vegardlarsen** [comment]
Thank you for this thought-out suggestion. Most of this makes sense to add.

Action items as I see them:

- [ ] Loading a preset also copies over the name.
- [ ] Editing regions directly should reset the name to `null`
- [ ] Add `regions active` command to echo out the name
- [ ] Add a way to list all the presets (not sure if this is going to be a separate command)

**Comment by vegardlarsen** [comment]
This may have been more involved than I initially assumed; many machines have multiple monitors, and we would in that case need to list active regions for each monitor. I am also thinking of adding a flag to the CLI application that would ensure JSON output for any command, that could help in this situation.

**Comment by vegardlarsen** [comment]
This will not be completed for 2.1.0. There can be multiple active presets at once (on different monitors), and we haven't really made the commands system for querying information.

If this is something we are going to do in the future, it would involve a larger rethinking of how commands work.
