### ISSUE TITLE
Gadgets don't work if....

### ISSUE THREAD

**Issue by curtis1757** [digitalcreations/MaxTo#40]
Gadgets don't work if 'Start with Windows' is checked in Options.  With this checked when Windows 7 x64 restarts my Gadgets (Clock and Calendar in upper left corner of screen) do not appear.  I saw the Info pop-up for this option that said "Do not check this unless the program files have been put in a permanent folder!"  Not sure what this means since Maxto installation installed itself in C:\Program Files (x86)\MaxTo  which is a permanent folder, right? (what folders are not 'permanent'?)

Great program from the little I have used it so far, but would be really nice to be able to have Gadgets work  when the 'Start with Windows' is checked.

Thanks!

**Comment by vegardlarsen** [comment]
@curtis1757 My guess is that this can be solved by editing the `shims.xml` file in your `C:\Program files (x86)\MaxTo` folder, and adding a single line under the `<ignore>` tag:

```xml
<process>sidebar</process>
```

This will cause MaxTo to avoid interacting with the process that supplies the gadgets, and hopefully that will cure this problem.

If this indeed works, please let me know so I can fix this for the next release.

**Comment by curtis1757** [comment]
Vegard,

Yes!  That fixed the problem.  I will now be buying MaxTo.

I recently got a new LG UltraWide monitor so I am checked out using MaxTo to divide up my screen into three vertical sections with the middle section about 75% of the screen for my main work area, the far right is just Gadgets and the far left is all my desktop icons.  I understand I think pretty well what MaxTo is doing and realize what I'd like it to do may not be possible... but what I would really like is to only have windows show up in my middle main  window and not be able to move or have Windows 7 place windows in my left/right side windows (unless I use the Modifier key).  Can MaxTo be setup to do that?

Thanks!
Curtis
  ----- Original Message -----

**Comment by vegardlarsen** [comment]
Technically, what you are asking for is doable, but MaxTo does not support it at this time. Since moving the window is so quick (especially using the shortcut keys), I don't think I will prioritize this.

**Comment by curtis1757** [comment]
I understand....  the short keys can do a lot, but the behavior I'm looking for is where the left/right side windows are 'protected' and if I moved a window say off to the right when the windows right edge hit the left edge of my MaxTo right window the window being moved would behave the same as if I was moving a window (when not using MaxTo) and the right edge went beyond the desktop/monitor right edge, which it simply goes off the screen and does not change the size of the window.  Using MaxTo I'd like the window being moved to look like it was 'sliding under' the 'protected' window.

Even without the above feature... MaxTo gets me closer to the effect I want (which is like how the Gadgets pane worked in Windows XP)

Thanks again!
Curtis
  ----- Original Message -----
