### ISSUE TITLE
Size of regions

### ISSUE THREAD

**Issue by jumpingjackflash5** [digitalcreations/MaxTo#401]
Why can't I set the region size smaller than 145-148px when doing two vertical splits in version 2.0.1? It would be useful for me since I need small borders on the sides of the screen, approximately 100-120 px. I knot that the window control occupy some space but I needn't to use windows there, I primarily need the main window in the centre to be limited in width.

Jan

**Comment by vegardlarsen** [comment]
@jumpingjackflash5 Windows has a minimum window size that MaxTo adheres to. We cannot safely create smaller regions than this. We will be introducing padding/margin support at some point to help with the use case you are describing.

**Comment by jumpingjackflash5** [comment]
Thanks for explanation.
