### ISSUE TITLE
Regions do not fit the monitor resolution

### ISSUE THREAD

**Issue by TagoriaTar** [digitalcreations/MaxTo#402]
My monitor has a resolution of 2560x1080 and use three regions
400x1038 (left)
1759x1038 (center)
400x1038 (right)
Most of the times there is 1 pixel missing(!),
400+1759+400 is not 2560

Windows 10,
MaxTo 2.0.1

**Comment by vegardlarsen** [comment]
Thank you again for your feedback. This is also the same as issue #382 as far as I can tell. :)
