### ISSUE TITLE
Reopen MaxTo Region Settings changes the regions each time

### ISSUE THREAD

**Issue by TagoriaTar** [digitalcreations/MaxTo#403]
My monitor has a resoution of 2560x1080 pixel.
When i set 3 regions parallel with these width 380, 1800, 380 and
save this settings. Then reopen the regions and the width has changed.
If you do that in a loop you will have these region width...

380, 1800, 380
382, 1797, 382
384, 1793, 383
386, 1789, 395
388, 1786, 386
390, 1782, 388
and so on..

Windows 10
MaxTo 2.0.1

**Comment by vegardlarsen** [comment]
Thank you for your feedback. This is the same issue as #382. I am closing this one, as we only need one to track each issue.
