### ISSUE TITLE
Error running MaxTo combined with Enpass

### ISSUE THREAD

**Issue by calxibe** [digitalcreations/MaxTo#410]
For each click you do in Enpass you wil need to click "Ok" on this error about 10-15 times:

![image](https://user-images.githubusercontent.com/30157044/57804270-914cc400-775a-11e9-8fbe-715ceb27d4ce.png)

1. Download "Enpass Password Manager" from Microsoft Store
2. Start Enpass
3. See error

System information:
 - Windows version: 10 Enterprise (Last update in Windows Insider Program: Slow ring)
 - MaxTo version: 2.0.1

Additional context:
Either maxto.log or SquirrelSetup.log contains any related information to this issue.

**Comment by vegardlarsen** [comment]
Thank you for the feedback. I don't get this error on my machine with Enpass version 6.0.6 (322) ; that may mean that there is something strange going on.

Can you check if your copy of MaxTo has downloaded the compatibility shims? It should happen automatically on startup, but them missing on your machine may be a issue. Check under Settings, Compatibility. If there is a list of programs there; the list is working as it should.

**Comment by calxibe** [comment]
That is the exact same version I’m running of Enpass on two machines with this issue.
I have many compatibility shims, but none for Enpass.

I tried installing MaxTo at my laptop now, and it does not give the error. So my guess would be that this issue is related to running the Insider Program (next release of Windows 10).

**Comment by vegardlarsen** [comment]
I am assuming your Windows version is build 1905? If so, this appears and #415 could very well have the same root cause?

**Comment by calxibe** [comment]
The problem in #415 looks the same, and I also run a version of May Update (insider program uses another build number series, current build is 18362, but this problem have also been on previous builds of may update).

If it will be helpfull to help you troubleshoot i could give you a TeamViewer inside working hours?

**Comment by vegardlarsen** [comment]
Thank you for the offer. Most times this doesn't really help, because for me to figure out what is happening I have to hook up a debugger and have MaxTo's source code available. I have started upgrading my work computer to the slow insider ring, and I'll give this another try on Monday. :)

**Comment by calxibe** [comment]
Hopefully you find a solution to this small issue soon, because it makes MaxTo unusable in my situation where Enpass is a must have...

**Comment by vegardlarsen** [comment]
Did you try reinstalling Enpass after updating to Windows 10 1903?

**Comment by calxibe** [comment]
Nope, but it surly fixed the problem :)
