### ISSUE TITLE
Expand window to multiple regions

### ISSUE THREAD

**Issue by JesusTheHun** [digitalcreations/MaxTo#411]
Hello, I'm new to MaxTo. I'm a user of MacOS windows manager named _Spectacle_, and I came across your software when looking for a solution for my PC.

I understand we can change regions settings, save & load presets.
I use a very large screen, 5120x1440.

Sometimes I simply want a window to occupy two regions of my screen.

Let's pretend I divide my screen in 12 regions, over two rows, so 6 columns.

I send a window in the top left corner, and then I can extend the width of the window, pressing the same shortcut multiple times, "expand to right region" or "expand to bottom region".
This way I can make two windows occupy half the screen - expanding right twice, therefore using 3 regions - or a third of the screen - expanding right once, using 2 regions. Then I can expand bottom, therefore using 6 or 4 regions.

This is way more flexible than regions presets, which are useful if you need a very specific setting, but not so much if you need quick organization.

**Comment by vegardlarsen** [comment]
Hi there @JesusTheHun. This feature was finished a couple of days ago, and will be in version 2.1. See #306.  :)

**Comment by JesusTheHun** [comment]
Looks like you gonna have a new customer very soon :)
