### ISSUE TITLE
Windows maximize only

### ISSUE THREAD

**Issue by wcatlan** [digitalcreations/MaxTo#412]
Seems the regions are ignored and when I Shift-move a window, it shows a white box maximized to fill the screen, not any region, no matter where i move the window. This is for all three monitors.

Maxto version:
v 2.0.1

Monitor details for main monitor:

Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY4
Location identifier: \{C116F7FF-7828-11E9-B9F1-9CB6D093D628}\0000
Serial number: LYWAA0034208
DPI (dots per inch): 96×96
Resolution: 1920×1080 @ 0, 0
Working area: 1920×1040 @ 0, 0

**Comment by vegardlarsen** [comment]
Seems like very strange behavior. Do all your monitors have the same DPI scaling?

**Comment by wcatlan** [comment]
No - One monitor (the laptop's built-in 13" monitor) is set to 150% with 144x144 dpi (as opposed to 96x96):

Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY1
Location identifier: \{B8610922-2337-11E9-B9CB-CACDB09B02BA}\0000
Serial number: 
DPI (dots per inch): 144×144
Resolution: 1920×1080 @ -1920, 0
Working area: 1920×1020 @ -1920, 0

Third monitor is same as main:

Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY5
Location identifier: \{C116F7FF-7828-11E9-B9F1-9CB6D093D628}\0001
Serial number: LYWAA0034208
DPI (dots per inch): 96×96
Resolution: 1920×1080 @ 1920, 0
Working area: 1920×1040 @ 1920, 0

There are only ever three monitors at one time, but i switch between home and work rigs (three monitors at home as well), so that may explain some of the naming for the DISPLAYs.

**Comment by vegardlarsen** [comment]
Can you try disabling the built-in monitor (which has different scaling), then restart your computer (this step is important), and see if the problem goes away?

**Comment by wcatlan** [comment]
I tried disabling the built in monitor using Device Manager. The icon in DM showed the monitor to be disabled, but truthfully, when I rebooted, the icon showed the monitor disabled but it was still functioning. In any case, it did not have any effect on the issue.

**Comment by vegardlarsen** [comment]
Disabling the monitor in Device Manager only disables its driver; and the monitor may still work afterwards. If you go into Display Settings and change it so the monitor is not active, that should work better.

**Comment by wcatlan** [comment]
I cannot find where / setting to make monitor "not active" in Display Settings.

**Comment by wcatlan** [comment]
Of course - just found option to "Disconnect Display" under Multiple Displays dropdown. Will try that, with reboot.

**Comment by wcatlan** [comment]
I selected Disconnect Display on the built-in monitor and after the monitor briefly came up during reboot, it then disconnected, as expected.  It did not impact the issue.  Same behavior.

**Comment by vegardlarsen** [comment]
OK, this sounds very strange. Can you try to capture a screenshot of this while it is happening (pressing PrintScreen will take a screenshot of your entire desktop, and you should be able to Ctrl+V it directly here), and a separate screenshot of your regions?

**Comment by wcatlan** [comment]
![image](https://user-images.githubusercontent.com/42011807/58191695-208f3580-7c8d-11e9-974d-87eee76bd5df.png)

![image](https://user-images.githubusercontent.com/42011807/58191862-706dfc80-7c8d-11e9-8063-3cdeb98feca9.png)

**Comment by wcatlan** [comment]
When I go back into "Change Regions" there is no indication that my regions were set - do you think that has something to do with it? I am also running in trial mode.
![image](https://user-images.githubusercontent.com/42011807/58194353-47506a80-7c93-11e9-9726-2966fbfc8bf9.png)

**Comment by vegardlarsen** [comment]
That absolutely has something to do with it; and I have a strong suspicion that this will have been fixed for you in version 2.1 when it comes out. There is a bug in 2.0.1 which causes issues when the monitor identifier MaxTo uses has more than one consecutive backslash in it. Can you wait and pay attention to when we release a 2.1 beta?

For now a workaround is to save your regions as a preset, and create a recipe that loads the preset using a hotkey. Then you can press the hotkey on startup, and your regions will be loaded.

I am adding this issue to the 2.1 release.

**Comment by wcatlan** [comment]
Sure..will look forward to future release.  Will have time to try workaround tomorrow.  Note - the display names do not have consecutive '\\' they have '\.\' ..not sure how they get those names - i didn't do anything explicit that i know of to pick those names; just a straight Win 10 system.

**Comment by vegardlarsen** [comment]
Those are the monitor "device names" that Windows supply, and they really are named `\\.\DISPLAY1` (it looks like a UNC network path, where the `.` means the local machine). I am pretty sure this will be fixed for you in 2.1.
