### ISSUE TITLE
Hyper-V Manager and virtual window not compatible

### ISSUE THREAD

**Issue by serkanozt** [digitalcreations/MaxTo#413]
App seems quite enough for daily purposes but I noticed that when I try to maximize Hyper-V windows, maximizing do not recognize regions and always maximizes full screen.

I do not know if it is a bug but it will be better for me to use MaxTo without this issue.

Thanks

**Comment by serkanozt** [comment]
Both of them.

**Comment by vegardlarsen** [comment]
Hyper-V Manager runs under `mmc.exe`, which runs as an elevated process. This means that running MaxTo elevated solves this issue.
