### ISSUE TITLE
Can I configure that new windows do not open maximized?

### ISSUE THREAD

**Issue by Andy-KU7T** [digitalcreations/MaxTo#414]
All works, except when I open Outlook attachments. PDF, Excel, etc open up maximized across all regions. Is there a way to configure it to always go to a specific region?

**Comment by vegardlarsen** [comment]
MaxTo should be able to intercept these windows, even when they open as maximized. Have you done anything specific to make the windows open maximized by default? This is not default Windows behavior as far as I can tell.

Or are you describing a situation where MaxTo does not intercept a maximize event?

**Comment by vegardlarsen** [comment]
Closing this issue due to lack of response from customer.
