### ISSUE TITLE
Failed to restart MaxTo as elevated program

### ISSUE THREAD

**Issue by boniboni** [digitalcreations/MaxTo#416]
I set MaxTo to restart elevated in order to make the elevated processes and windows to obey my recipes. After this, MaxTo doesn't startup properly. MaxTo.Core.exe process is running ("Maxto is already running, you should find it in the notification area"), but it is not running properly. User Account Control is not disabled. I'm running a local administrator account. User Account Control is set to "never notify", but the problem persistent even when UAC is fully up. According to the log the problem seems related to some kind of permission settings. The problem persists even when I try to uninstall and reinstall MaxTo. This is a production machine, with a full Visual Studio installation and many kinds of frameworks and programs and it seems that I don't have any kind of similar problems with permissions with other programs, so this problem seems elusive to me and related to some very specific way in which MaxTo depends on permission settings.

[maxto20190525 - Copy.log](https://github.com/digitalcreations/MaxTo/files/3219949/maxto20190525.-.Copy.log)

**System information:**
 - Windows version: Windows 10 x64 1903 (build 18362.116)
 - MaxTo version: latest stable

**Comment by boniboni** [comment]
Found the culprit: Secondary Logon service was disabled.

**Comment by vegardlarsen** [comment]
Was there any specific reason you had Secondary Logon disabled in the first place?

The error code in your log file (`Could not register startup task after setting changed.`) can maybe be remedied by manually deleting the the task called "MaxTo" in Tash scheduler, but it may just recreate it with the wrong rights again.

**Comment by boniboni** [comment]
It seems that https://www.reddit.com/r/TronScript/ (a script to remove Windows bloatware and disable Windows telemetry) wrongfully disabled that service. It was entirely my fault because I used the most aggressive version of the script. Setting Secondary Logon back to "Manual" eliminated the problem with MaxTo trying to run elevated.

**Comment by vegardlarsen** [comment]
OK, good to hear. I'd never heard of that service being disabled for legitimate reasons. :)

But very good that we now have this documented for Google. 👍 

Closing this issue as the culprit has been found.
