### ISSUE TITLE
Windows Key Interrupting

### ISSUE THREAD

**Issue by IsaacElenbaas** [digitalcreations/MaxTo#417]
**Describe the bug**
Many people press key combos in order and then release all at once. For some reason, MaxTo does actions on release (which I see the reasoning for, but still not standard). Thus, using anything with the Win key and releasing all at once opens the start menu and the action is ignored.

**Expected behavior**
An action.

**System information:**
 - Windows version: 10
 - MaxTo version: 2.0.1

**Additional context**
A quick AHK script to delay Win key release works well enough for me, but an option would be nice (I assume the default won't be changed, it makes sense).

**Comment by vegardlarsen** [comment]
You are right; there used to be a reason we triggered hotkeys on key up instead of key down; but I cannot see that reason anymore. I am going to have to test this a bit more thoroughly, but I will look at changing this for version 2.1.

**Comment by IsaacElenbaas** [comment]
I was thinking if one has Win+Alt as well as Win+Alt+A or something, or to prevent conflicts with existing program hotkeys, which is why I'd lean toward an option vs changing. There was definitely a reason at some point, as it's the opposite of the long-time standard. The trouble is just that the Windows key and start menu stop anything from happening if released before the program notices.

**Comment by vegardlarsen** [comment]
I don't think this should be an option as this is an issue where it is extremely difficult for the end user to make an informed decision. We need to decide on a default that makes sense here.

Windows seem to attach their hotkeys to key-down events, and I am thinking it makes sense that we do the same to preserve the feel people have in Windows.

I have made this change and it will be in version 2.1.
