### ISSUE TITLE
Setting for Default Taskbar Action

### ISSUE THREAD

**Issue by IsaacElenbaas** [digitalcreations/MaxTo#418]
**Is your feature request related to a problem? Please describe.**
Clicking the taskbar opens a menu where you can disable MaxTo, change regions, open settings, and exit. The demo shows it opening the change regions automatically.

**Describe the solution you'd like**
Disabling or exiting seems like a rare use case. Make that menu the right click action (which it already is) and change the left to regions by default.

**Comment by khongi** [comment]
Left click (or double click) to change regions would be useful without the menu appearing. You can double click to change regions now but then the menu appears and disappears twice, which is not the most elegant behavior for such a common use case.

**Comment by vegardlarsen** [comment]
I have looked at this, and I wasn't aware of the menu appearing while double-clicking. I have changed it so "change regions" only appears on double-click, and the menu only appears on right-click. Left-click then does nothing.
