### ISSUE TITLE
Slack application no longer respects MaxTo region

### ISSUE THREAD

**Issue by NicholasConrad** [digitalcreations/MaxTo#420]
Slack application no longer respects MaxTo region

Noticed for the first time yesterday. Other applications still respecting MaxTo as expected.

**System information:**
Windows 10 build 18898.1000
MaxTo 2.0.1

**Comment by NicholasConrad** [comment]
Uninstalling and reinstalling maxto seems to have resolved the issue.

**Comment by vegardlarsen** [comment]
Great to hear. :)
