### ISSUE TITLE
Cannot find "Enter" key in the recipe

### ISSUE THREAD

**Issue by rustamsh** [digitalcreations/MaxTo#421]
**Describe the bug**
Cannot assign "Enter" key with a recipe

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Recipes' and pick an existing recipe or create a new one
3. Try to assign an "Enter" key

**Expected behavior**
I would like to be able to assign an "Enter" key with modifiers. An existing "Execute" or "Select" doesn't work as "Enter" key

**System information:**
 - Windows version: 10 Pro
 - MaxTo version 2.0.1

**Comment by vegardlarsen** [comment]
You are absolutely right. If you want to do this manually you can edit the `config.json` file directly and the writing e.g. `Windows+Control+Enter` should work fine.

I am adding this for version 2.1.

**Comment by vegardlarsen** [comment]
I have fixed this issue for version 2.1.
