### ISSUE TITLE
This program is active on my desktop but does not work at all.  I have windows 10, it is up to date.

### ISSUE THREAD

**Issue by Jkipe** [digitalcreations/MaxTo#423]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by Gubith** [comment]
Setup regions.  If its not working, make sure there is a region loaded.

**Comment by Jkipe** [comment]
I set up regions....
I also uninstalled and it will no longer re-install since windows update

Jarred Kuiper | Home Loan Advisor
Stewardship | moneywellrooted.com<http://moneywellrooted.com/>
Call | Text | Fax 602.777.3443<tel:602.777.3443>
NMLS#1196786<tel:1196786>

**Compliance Disclosure** Your actual rate, payment, and costs could be higher. Get an official Loan Estimate before choosing a loan. The contents of this message may be confidential. If you are not the intended recipient, do not disseminate, disclose, copy or use this message without the permission of the author. Nothing contained in this message, or in any attachment, shall satisfy the requirements for writing, and nothing contained herein shall constitute a contract or electronic signature. If this message is received in error, please delete it immediately.


On Jun 4, 2019, at 9:19 PM, Gubith <notifications@github.com<mailto:notifications@github.com>> wrote:


Setup regions. If its not working, make sure there is a region loaded.

**Comment by vegardlarsen** [comment]
In these cases a reboot may be necessary. If the problem persists after a reboot, please let me know.

**Comment by Jkipe** [comment]
As mentioned, it will not install even after a computer restart
[cid:image001.png@01D51BB7.141C45E0]

Jarred Kuiper | Home Loan Advisor
Stewardship | moneywellrooted.com
Text | Call  602.777.3443
NMLS#1193786
**Compliance Disclosure** Your actual rate, payment, and costs could be higher. Get an official Loan Estimate before choosing a loan. The contents of this message may be confidential. If you are not the intended recipient, do not disseminate, disclose, copy or use this message without the permission of the author. Nothing contained in this message, or in any attachment, shall satisfy the requirements for writing, and nothing contained herein shall constitute a contract or electronic signature. If this message is received in error, please delete it immediately.
[1][20]

**Comment by vegardlarsen** [comment]
OK, I thought you had got it installed. Can you get me the setup log file? There should be a button to open it when the setup fails to install.

PS! I'd recommend going directly to Github to answer, as every time you reply to the e-mail directly it will expose your e-mail address to everyone.

**Comment by Jkipe** [comment]
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/3262389/SquirrelSetup.log)

**Comment by vegardlarsen** [comment]
According to the log, MaxTo is already installed on your machine. It should be in the notification area (next to the clock), sometimes "hiding" behind the small up-arrow.

The error in the log indicates that MaxTo is already running, and that it couldn't remove the files because they were in use. If this is still the case, rebooting your machine and trying to install again should help.

**Comment by vegardlarsen** [comment]
Closed due to lack of response.
