### ISSUE TITLE
Regions not set on startup

### ISSUE THREAD

**Issue by Gubith** [digitalcreations/MaxTo#424]
MaxTo loads on boot but with no regions are set.  Load region required on every boot.

It does load regions automatically for different resolutions (set by loading profiles in Displayfusion).  

Windows 10 64 Pro 1803  (17134.799) 
MaxTo 2.01

Prolly Microsoft's fault.

**Comment by Gubith** [comment]
Never mind, it seems to be working now that I posted about it.   Maybe adjusting things while testing fixed something.

**Comment by vegardlarsen** [comment]
This could very well be one of the known bugs in MaxTo 2.0.1; my guess is fiddling with the "Monitor identification" setting fixed this for you. We are fixing this for 2.1.
