### ISSUE TITLE
Not working for normal Users on Terminal Server

### ISSUE THREAD

**Issue by ia3654** [digitalcreations/MaxTo#426]
**Describe the bug**
Application does not work for normal users on Terminal Server.

**To Reproduce**
1. Login as admin
2. Start install mode
3. Install MaxTo
4. Resume to execution mode
5. Login as normal user
6. Wait for link to MaxTo appear on desktop, then start it
7. Click next, choose 30 day test license, click configure regions
8. Configure some regions, click on use regions
9. Now the window should close, but it doesn't. 
Edit: I can close the window using alt-f4 and the icon also appears in the tray. When I open the region configuration again the region is still correctly displayed.
But it's not working, windows still maximize to full screen.

**Expected behavior**
Ideally the app should be configured once by the admin and then auto start for all users.
But maybe terminal server is not supported? I did not find any information about this.

**System information:**
 - Windows version: Server 2008 R2
 - MaxTo version: 2.0.1

**Additional context**
In the logfile one error appears:
2019-06-07 18:27:57 [Core@2.0.1.499] [Error] Could not register startup task during startup.
System.UnauthorizedAccessException: Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 (E_ACCESSDENIED))
   bei Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   bei Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   bei Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition)
   bei MaxTo.Core.Settings.LoginRegistrationService.CreateTask()
   bei MaxTo.Core.Settings.LoginRegistrationService.Register()
   bei MaxTo.Core.Settings.LoginRegistrationService.InitializeAsync()

**Comment by vegardlarsen** [comment]
Sorry for the slow response on this, it slipped quite far down my inbox over the long weekend.

I think there are some misconceptions here:

- MaxTo is installed separately per user. You need to [use the MSI installer to install it on a terminal server](https://maxto.net/no/documentation/installing/msi). The MSI installer will install MaxTo separately to each user account on login.
- If you want to do a global install, you'll need to use the ZIP archive and do the installation manually. You can control [where MaxTo stores its configuration](https://maxto.net/no/documentation/configuration/location) if you want it to be shared between users, but all users will need write access to it, and conflicts will probably occur when you have multiple users. This is not currently a supported configuration.
- I don't think the error message is related to what you are describing, but it indicates that MaxTo did not have access to make changes to the startup task (in Task Scheduler). This is probably not a big deal.

**Comment by vegardlarsen** [comment]
Closing issue due to lack of response. Feel free to reply.
