### ISSUE TITLE
Does not run in Windows 10 1903

### ISSUE THREAD

**Issue by cmendozalugo** [digitalcreations/MaxTo#427]
**Describe the bug**
The app stopped running and started causing errors in the system consistent with applications that are not prepared for the new version of Windows 10.

I uninstalled the app and then downloaded the installer again. It does not finish installing since the error appears again.

**To Reproduce**
1. Download de Windows 10 installer
2. Run the installer
3. See the error

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: 10 v 1903
 - MaxTo version 2.01

**Comment by mswulinski** [comment]
Ditto

**Comment by digitalchet** [comment]
Having the same issue here where the installer fails.

**Comment by vegardlarsen** [comment]
Can you get me the installer log files?

My guess is that this is the same issue the installer "always" has, which is that MaxTo is already installed and running, and the installer tries to delete the app directory. Windows won't let it since MaxTo is running.

To solve this issue:

1. Disable "Start MaxTo on logon" if it was enabled.
2. Restart Windows.
3. Install now.

**Comment by cmendozalugo** [comment]
Thanks mswulinski. I updated today to the latest version and the installer worked just fine now.

**Comment by digitalchet** [comment]
Actually, I did try the installer after a reboot that appears to have fixed the issue.

**Comment by mswulinski** [comment]
Since 1903 install though I get a ton of these errors with various pieces of software, Skype being the most common. 
![image](https://user-images.githubusercontent.com/27841432/59447917-1ebf1a80-8dd2-11e9-834a-b668efa00bba.png)

**Comment by vegardlarsen** [comment]
@mswulinski These issues can most of the time be resolved by reinstalling the program that crashes. I am not sure what causes it, but issue #415 covers this.

**Comment by cmendozalugo** [comment]
@mswulinski I had the same issue and, as commented by @vegardlarsen, it was corrected by uninstalling the app and reinstalling it.

**Comment by digitalchet** [comment]
I get these incessantly whenever I run iTunes on Windows (don't judge me! ;P ). It's gotten to the point where I have to exit out of MaxTo, start iTunes, and relaunch MaxTo. 
I've tried the uninstall-reinstall, and uninstall-reboot-reinstall to no effect. There's definitely something in 1903 that messes with the way MaxTo works.

**Comment by vegardlarsen** [comment]
Closing this as it should really be in #415.
