### ISSUE TITLE
Multimonitor feature request

### ISSUE THREAD

**Issue by bjornsol** [digitalcreations/MaxTo#429]
**Is your feature request related to a problem? Please describe.**
I’m currently working with a 4 monitor setup with two levels and monitors of both orientations. When I want to maximize a window on my portrait monitor (where I’ve not set up any zones) my instinct is “Win + Up”. With MaxTo this sends the window to on of the lower zone on the monitor above and I need to additionally use “Win + Down” to get it back to, and maximized, on the portrait monitor. 

**Describe the solution you'd like**
I’d like to enable a specific key combo that explicitly states that I want to change monitors on the active window, and if I’m using the normal key combos (win + arrow) it will only move the window around on the current monitor.

**Describe alternatives you've considered**
None

**Additional context**
Maybe a fringe case with regard to monitor configuration, but I believe it should be possible to limit cross monitor movement.

**Comment by vegardlarsen** [comment]
@bjornsol First let me apologize for the slow reply on this. It needed some thinking through. :)

I think you can do this (partly) already. You'll need to set up a recipe that uses the "Move window" command, and only specifying the Monitor attribute. When "Move window" is run without setting a direction, it will move the window to the specific monitor (and try to maintain the coordinates). 

If you want to additionally maximize it to cover the entire monitor, add another "Maximize window to screen" command. 

If you instead want it to go into a region, you can add another "Move window" command, this time setting the Direction to None, and not setting any of the other parameters, in which case it will move the window into the closest region, or you can specify a region by using the Region parameter.

In the next version this will also support special properties, such as "Next monitor" and "Previous monitor", so you can do this properly.

**Comment by bjornsol** [comment]
@vegardlarsen No problem on the reply lag :)

I checked out your suggestions and it works well. Thanks!
Also found that windows 10 has a built in shortcut (I think), giving Win+Shift+Right/Left the function of moving the active window to the next monitor within the windows monitor numbering system :)

**Comment by vegardlarsen** [comment]
What, I didn't know about this shortcut! That's awesome! :)
