### ISSUE TITLE
taskbar lost active app highlights W10

### ISSUE THREAD

**Issue by ferryperry** [digitalcreations/MaxTo#431]
**Describe the bug**
all taskbar icons are un-highlighted. Normally the open apps are highlighted.

**To Reproduce**
1. Being on the desktop, I expect to see highlights of the active app
2. I use several virtual desktops, same  on all
3. Maxto works fine in all other respects

**Expected behavior**

**Screenshots**
Taskbar looks like all apps are inactive, not much to show here.

**System information:**
 - Windows version: build 17763.557 version 1809
 - MaxTo version 2.0.1

**Comment by ferryperry** [comment]
Dunno what happened, the highlights are back, although I did reïnstall, it did not return right away. I do have a new monitor with some calibration issues, it being a TV. 

Let's just forget this issue with my apologies.

**Comment by vegardlarsen** [comment]
OK :) Just commenting to let you know I read it :)

**Comment by ferryperry** [comment]
Sorry, I am extremely happy with the functionality of MaxTo to the extend that such a bug in my use case was very unforunate.

Aaaand now it’s back, while typing this …

Flabbergasted, maybe still more later, first finding out what’s going on…

Kind regards,

Fer

Verzonden vanuit Mail voor Windows 10

Van: Vegard Andreas Larsen
Verzonden: maandag 17 juni 2019 15:12
Aan: digitalcreations/MaxTo
CC: ferryperry; State change
Onderwerp: Re: [digitalcreations/MaxTo] taskbar lost active app highlights W10(#431)

OK :) Just commenting to let you know I read it :)
