### ISSUE TITLE
Intel XTU window not compatible

### ISSUE THREAD

**Issue by greggguru** [digitalcreations/MaxTo#432]
Intel's Extreme Tuning Utility will open as an empty windows frame where not even the title bar has content. Sometimes XTU will appear to be working correctly but it isn't possible to interact with the UI. I believe Intel isn't using standard Windows windows.

I added this to the shims.json file to resolve the issue.

```
{
    "id": "xtu",
    "descriptions": {
      "en": {
        "title": "Intel Extreme Tuning Utility",
        "subtitle": "Prevent empty window frame, allow mouse clicks.",
        "description": "Intel Extreme Tuning Utility (Intel XTU) offers the state of the art in overclocking. It is a comprehensive set of tools to tune, test and monitor your system. If MaxTo is active, XTU will display an empty window and/or mouse clicks will not be registered. This shim disables subclassing XTU windows."
      }
    },
    "iconUrl": "https://maxto.net/assets/shims/cmd.png",
    "url": null,
    "canDisable": true,
    "defaultEnabled": true,
    "ignore": false,
    "disableSubclassing": true,
    "disableSnapping": false,
    "disableTransparency": false,
    "useMoveWindow": false,
    "emulatesMaximize": false,
    "windowClasses": [],
    "processes": ["PerfTune"]
  }
```

I reused an existing icon and didn't look into what each of the options actually do, but this has worked for me. If I should create a pull request, I will do so.

-Gregg

**Comment by vegardlarsen** [comment]
@greggguru Can you check if this works with `disableSubclassing: false` and `disableTransparency: true` instead? I am adding this now, but I can quickly change this later if just disabling transparency works.

**Comment by vegardlarsen** [comment]
Shim should now be active and available. [Link](https://maxto.net/no/shim/intel_xtu)

**Comment by greggguru** [comment]
> @greggguru Can you check if this works with `disableSubclassing: false` and `disableTransparency: true` instead?

@vegardlarsen Confirmed that changing those two options is effective also, thank you! My original shim description mentions disabling subclassing so you'll have to update that too.

You are awesome!

-Gregg

**Comment by vegardlarsen** [comment]
Thanks for the feedback. I'll update the compatibility shim now, and it should roll out with the next automatic update.

**Comment by vegardlarsen** [comment]
Took me a while, but I updated it now. :)
