### ISSUE TITLE
Provide "Alternative Region" functionality again within the new recipes system

### ISSUE THREAD

**Issue by menthughes** [digitalcreations/MaxTo#434]
I'm a big fan of MaxTo but I've been using the 2-year-old version ever since the update to 2.0+. I routinely make use of the Alt regions (Main region has two large columns; alt region sub-divides these, so I can easily mix-and-match). Changing recipes means extra keystrokes that slow things down considerably.

Can "Alt" functionality not be re-introduced for cases where two recipes exist? I want to be on board with the new versions but cannot work with the new method at the moment! Thanks.

**Comment by vegardlarsen** [comment]
@menthughes We have no plans regarding re-introducing alternate regions. We will however provide a solution that we think will make life a lot easier in version 2.1: [Expand/contract window edges](https://github.com/digitalcreations/MaxTo/issues/306), which lets you quickly expand a window to fit multiple regions.

Do you think that would solve some of your problems?

**Comment by menthughes** [comment]
That feature certainly sounds useful - but I don't think it'll come close to replicating the functionality that Alt regions had. I know that going back (from a UI perspective) to the full Main/Alt regions isn't desirable - but the shortcut keys were what made it useful.

![Monitors](https://user-images.githubusercontent.com/52197082/60085993-37b0bf80-9732-11e9-99aa-aead8f6a2126.png)

In the 2017 version, I can freely place any window as either a full height or half-height window with just a couple of keystrokes. The Expand/Contract Window Edges feature could replicate some of that (assuming the second window layout was chosen) but would mean being able to arbitrarily chose which edge of the window was moved in which direction - with keystrokes? I mean.... presuming you moved a new window to the right (which will end up at top right or bottom right - probably predictably, but still) how easy will it be to then move it to the other window? So - I create a new window - move it to the right and it ends up Top Right (for instance) - but I want bottom right. I then have to cycle through full height followed by bottom right?

I'm absolutely not knocking the idea - if you've used it then I perhaps the experience is more fluid.

**Comment by vegardlarsen** [comment]
We would have to provide some sort of guidance with regards to this, but it actually feels quite nice to use. We don't know what the actual shortcut keys will be yet, but it will likely involve directional keys (left, right, up, down) and a modifier key to switch between expand and contract.

The goal is to get the user to think about it as "I want to expand this window by moving its top edge" when you press the up shortcut.

Does that makes sense?
