### ISSUE TITLE
Program Specific Functionallity

### ISSUE THREAD

**Issue by bjornsol** [digitalcreations/MaxTo#436]
I use multiple programs with multiple windows that I like to have in different tile layouts. Meaning that one zone layout will work perfectly for one program, while messing up the workflow for a different one.

Would it be possible to define zones on the monitor that are only active for windows from one or more specific programs in addition to a default zone layout? By doing this one could specialise the zones to fit each programs workflow.

For example one program would have a three collumn system with narrow ones on the sides and a wide one in the middle, while another program would have a 2x2 equal tile setup. In addition the default can be a 1x2 equal tile setup.

**Comment by vegardlarsen** [comment]
Technically there isn't anything wrong with doing this the way you state here, but user interface-wise there would be a lot that can go wrong and be misunderstood.

We will provide a few tools in version 2.1 that will make scenarios like this easier:

- a new trigger for recipes that fires when a window opens (with an optional filter title)
- a place command for recipes that lets you place windows completely freely
- support for WinSplit-like grid-splitting as part of recipes (this is pretty cool)

That makes it possible to have a recipe that says "whenever I open Notepad, make it 1024x768 pixels and put it at 0,0".

Does that solve your issue?

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback.
