### ISSUE TITLE
Change focus hotkeys are missing

### ISSUE THREAD

**Issue by raabf** [digitalcreations/MaxTo#44]
You are already able to move windows to other tiles through `Control` + `Windows` + Arrow Keys. But you are not able to change the focus of the windows. Only using `Alt` + `Tab` is annoying, since  one of the advantages of tiled window manager is to improve that without using the mouse. This is a quite basic feature of a tiled window manager

You should provide a change focus hotkeys in the same way as moving windows. I recommend to use `Windows`+ Arrow Keys to do that. For that you have to overwrite the standard assignment of Windows of these keys:

 + `Windows` + `Up`: maximize window
 + `Windows` + `Down`: minimize window
 + `Windows` + `Left`: maximize on half left of the screen
 + `Windows` + `Right`: maximize on half right of the screen

You need none of these keys if you use MaxTo, so they can be reassigned.

**Comment by vegardlarsen** [comment]
I believe the Control+Windows+PageUp/PageDown keyboard shortcuts (by default) does this. Correct me if I am mistaken.

**Comment by raabf** [comment]
no sorry you misunderstand me.
I do not mean changing between windows in the *same* tile/region. I mean changing focus of windows in *different* tiles. Actually you had to use `Alt`+ `Tab` or grabbing the mouse for changing the focused tile and window. The way I have proposed would be much faster and targeted.
