### ISSUE TITLE
Grabbing Firefox window by its title bar resize the window to a small size

### ISSUE THREAD

**Issue by terrybr** [digitalcreations/MaxTo#440]
**Describe the bug**
When I move Firefox window using a "recipe" to a region, and then move the window to another screen by grabbing the Firefox window by its title bar, the window is resized to a very small size when I start dragging. 

**To Reproduce**
1. Put the Firefox window to a region by using a "recipe"
2. Click on the Firefox window's title bar and start dragging
3. The Firefox window resize to a very small window

**Expected behavior**
The Firefox window size should be its previous size before it was put in a region using a "recipe"

**System information:**
 - Windows 10 Pro
 - MaxTo version 2.01

**Comment by vegardlarsen** [comment]
- Which version of Firefox is this? 
- Does the issue persist even after a reboot?
- Which commands are in your recipe?

**Comment by terrybr** [comment]
- Firefox Quantum 68.0 (64-bit)
- Yes, it does.
- Windows Key + ALT + Right

**Comment by vegardlarsen** [comment]
@terrybr By commands I mean what are the ingredients of the recipe? The hotkey doesn't tell me much. Is this the "Swap window right" command that comes with MaxTo by default?

**Comment by terrybr** [comment]
@vegardlarsen Sorry, it's the "Move window left" mainly.

**Comment by vegardlarsen** [comment]
This behavior is no longer present in MaxTo 2.1.0-beta.1. Closing issue.
