### ISSUE TITLE
In Windows 1903 launching spotify desktop app causes maxto to crash

### ISSUE THREAD

**Issue by jacobedonahoe** [digitalcreations/MaxTo#442]
**Describe the bug**
In Windows 10 version 1903, spotify desktop app crashes on launch if MaxTo 2.0.1 is running

**To Reproduce**
1. Install/launch MaxTo 2.0.1
2. Install/launch Spotify desktop app
3. Observe Crash and error message

**Expected behavior**
I expected the Spotify app to launch without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/7757934/60975915-56968080-a2f2-11e9-9bf8-04769e6c8091.png)

**System information:**
 - Windows version: [10 version 1903]
 - MaxTo version [2.0.1]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. 
[maxto20190710.log](https://github.com/digitalcreations/MaxTo/files/3377890/maxto20190710.log)

**Comment by vegardlarsen** [comment]
Thanks for your report. This is the same issue as #415. I am closing this issue as a duplicate. See workaround in #415.
