### ISSUE TITLE
Add compatibility shim for iZotope RX 7

### ISSUE THREAD

**Issue by chrishunt** [digitalcreations/MaxTo#443]
**Describe the bug**

When attempting to move the [iZotope RX 7 Audio Editor](https://www.izotope.com/en/products/repair-and-edit/rx.html) with MaxTo, the windows shrinks to a tiny size and becomes unresponsive. RX 7 must be killed and restarted.

**To Reproduce**

1. Start MaxTo
2. Open RX 7
3. Move RX 7 to a MaxTo region using keyboard shortcut
4. RX 7 shrinks to tiny size and becomes unresponsive 

**Expected behavior**

It's expected that RX 7 will be moved to the specified region and continue to be responsive.

**Screenshots**

### Before invoking MaxTo

![before](https://user-images.githubusercontent.com/65323/61010459-8fa31500-a333-11e9-9de9-094e02fd5dc1.jpg)

### After invoking MaxTo

![after](https://user-images.githubusercontent.com/65323/61010461-916cd880-a333-11e9-8fd9-3ed3e840990a.jpg)

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1

**Additional context**

I've added the following entry to `shims.json` to keep the audio editor from crashing. This works great for me, but I'm opening an issue here as well because it seems as though MaxTo overrides `shims.json` on a regular basis and we need to either allow folks to specify their own shims or we need to add this upstream. Thanks much!

Please note that the image URL is on my dropbox, so feel free to grab that and move to `https://maxto.net/assets/shim/` 😆 

```json
{
  "id": "izotope_rx7",
  "descriptions": {
    "en": {
      "title": "iZotope RX 7",
      "subtitle": "RX 7 cannot be moved or resized by MaxTo.",
      "description": "Designed specifically for the demanding needs of music and post professionals, RX 7 is the industry standard audio repair tool used on movies and TV shows. This compatibility shim disables MaxTo for all of the RX 7 windows."
    }
  },
  "iconUrl": "https://www.dropbox.com/s/nt0bp19jy8dueze/rx7.png?raw=1",
  "url": "https://www.izotope.com",
  "canDisable": true,
  "defaultEnabled": true,
  "ignore": true,
  "disableSubclassing": true,
  "disableSnapping": true,
  "disableTransparency": true,
  "useMoveWindow": false,
  "emulatesMaximize": false,
  "windowClasses": [],
  "processes": [
    "iZotope RX 7 Audio Editor",
    "iZotope RX 7 Advanced Audio Editor"
  ]
}
```

**Comment by vegardlarsen** [comment]
Thank you for this, I will make sure to add this once I am back from vacation.

**Comment by vegardlarsen** [comment]
I've finally published this and it should appear shortly in shim updates to MaxTo.

@chrishunt Sorry for the wait!

**Comment by chrishunt** [comment]
Thanks @vegardlarsen
