### ISSUE TITLE
Maxto: Installing without admin

### ISSUE THREAD

**Issue by Linkege** [digitalcreations/MaxTo#446]
Hello,

Wasn't sure where to ask this, so this was the best I could find. I hope that is OK. 

I just wanted to make sure Maxto can be ran as a "portable" program. EG if I install on a USB I can run it on a windows PC with the USB in it etc? I would love this for work but need to go through a million steps to get anything installed on my PC. 

Thank you,

**Comment by vegardlarsen** [comment]
That should work just fine, use the [ZIP archive](https://maxto.net/documentation/installing/zip). You may need to [redirect your configuration file](https://maxto.net/documentation/configuration/location) to be stored on your USB drive as well, if you can't save things to `%AppData%`.
