### ISSUE TITLE
Regions Swapping After Screen Timeout

### ISSUE THREAD

**Issue by axisfx24** [digitalcreations/MaxTo#448]
**Describe the bug**
Every time my computer screen times out and goes to sleep or I lock the screen, the regions are swapped around to other monitors or the regions are just reset. All of my windows are moved over to the primary monitor and have to be moved back over to the secondary monitor. Regions that were set up on the secondary monitor move over to the primary and vice versa. This is with all applications, it does not appear to be app specific.

I have 2 4k monitors and this has happened for a couple of years, on previous versions as well. This could be with a laptop screen and secondary monitor or multiple external monitors only. But i just started to use a second monitor and MaxTo again, hoping this would be resolved.

The app is not crashing or having any other issues it seems. 

**To Reproduce**
1. Lock the computer or allow it to timeout and turn the screen off.

**Expected behavior**
For the regions to not be reset.

**System information:**
 - Windows version: 10 c1809
 - MaxTo version: 2.0.1

**Comment by vegardlarsen** [comment]
Have you tried changing monitor identification in the settings to any other setting? Can you copy the "Monitor details" for all your monitors here?

**Comment by axisfx24** [comment]
I have tried swapping the identifiers around. I have tried both number and properties.

Should I expect, after a screen timeout, for my windows to appear back on the separate monitors in their correct positions?

Here are the details of my monitors:

Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY1
Location identifier: \{6A295DAF-ACD6-11E9-BEE7-BC0745C01B86}\0000
Serial number: 
DPI (dots per inch): 96×96
Resolution: 3840×2160 @ 0, 0
Working area: 3840×2120 @ 0, 0

Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY2
Location identifier: \{6A295DAF-ACD6-11E9-BEE7-BC0745C01B86}\0001
Serial number: 
DPI (dots per inch): 96×96
Resolution: 3840×2160 @ 3840, 0
Working area: 3840×2120 @ 3840, 0

**Comment by vegardlarsen** [comment]
I believe I can solve this problem with a private preview release of MaxTo 2.1 for you. Please get in touch with me via the support e-mail address to receive it, and reference this issue.

**Comment by axisfx24** [comment]
Thank you for your response and update for my issue! I have installed the preview release and that seems to have solved the regions from swapping. 

But I am seeing a similar issue as #450, with windows resized and all seemingly loading onto the primary after an unlock. I don't think #450 had dual monitor setup though.

**Comment by vegardlarsen** [comment]
OK, good to hear that your initial problem has been solved. No solution for (or local reproduction of) #450 yet.

I am closing this issue as it has been solved for version 2.1.
