### ISSUE TITLE
Compatibility with surface pro tablet mode

### ISSUE THREAD

**Issue by SergeFranceschino** [digitalcreations/MaxTo#449]
In tablet mode on "Microsoft Surface Pro" most windows do not display and the display remains stuck on the Start menu. When MaxTo is uninstall everything works fine again.

**Comment by vegardlarsen** [comment]
Most definitely a bug. I am assigning the 2.1 milestone to this, but depending on difficulty I may need to postpone this a bit.

My best guess for a solution to this is to disable MaxTo functionality when the computer is in tablet mode.

**Comment by vegardlarsen** [comment]
Some research on this subject.

- [Events that we can listen to](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/continuum)
- [.NET mapping](http://msdn.microsoft.com/en-us/library/microsoft.win32.systemevents.userpreferencechanged.aspx)

However, the links appear to indicate we need a reference to the UWP stuff, so we may need to do something different to not break compatibility with older versions of Windows.

**Comment by vegardlarsen** [comment]
Some more research uncovered [this article](https://devblogs.microsoft.com/oldnewthing/?p=93815), which can probably be considered the definite source material on this subject.

The problem, which I was not aware of until now, is that tablet mode is per monitor, not system-wide.

That means we need to be able to disable regions and window subclassing for windows once they are put on a specific monitor. This is complicated quite a bit by not owning a single device capable of tablet mode.

**Comment by SergeFranceschino** [comment]
Hello,
https://github.com/microsoft/PowerToys
works very well.

**Comment by vegardlarsen** [comment]
Because we want to maintain backwards compatibility for Windows 7, 8 and 8.1, we cannot support this at this point. We will be revisiting this for version 3.
