### ISSUE TITLE
Windows are usually incorrectly sized

### ISSUE THREAD

**Issue by altano** [digitalcreations/MaxTo#450]
**Describe the bug**
When applications are maximized they frequently have an incorrect, 1px gap around them:

![image](https://user-images.githubusercontent.com/1009/61845621-ef7fdc80-ae58-11e9-8d9e-e7c265882dfa.png)

When I minimize the application and restore it the gap is SOMETIMES gone. Here I maximize the window and the gap remains, then I minimize+restore and the gap is gone:

![2019-07-24_21-30-34](https://user-images.githubusercontent.com/1009/61846212-1d662080-ae5b-11e9-9376-3a64b5322395.gif)

Lastly, when I close and re-open an application the window position is usually even worse, increasing the gap further. I have to restore and then maximize the app to get it to go back to having just a 1px gap.

**To Reproduce**
1. Create regions.
1. Center any app in any region and maximize
1. Window has 1px gap

**Expected behavior**
I would like the window to fully fill its region and I do NOT want to see my background leaking in between windows.

**Screenshots**
See above

**System information:**
 - Windows version: 10 (v1809)
 - MaxTo version: 2.0.1

**Additional context**
n/a

**Comment by vegardlarsen** [comment]
Sorry for the slow response time on this, I have been away on vacation.

- Is this a high-DPI (4K) monitor or a regular 96 DPI monitor? 
- Can it be reproduced only with specific programs (such as VS Code in your example), or does the same thing happen with e.g. Notepad?
- Does this only happen when maximizing to regions using the maximize button, or does it also happen when using Shift+drag or when using a recipe?

**Comment by altano** [comment]
No worries about the response time.

> Is this a high-DPI (4K) monitor or a regular 96 DPI monitor?

High-DPI but not 4K. It's an LG 5K2K (5120x2560) ultrawide

> Can it be reproduced only with specific programs (such as VS Code and Spotify in your example), or does the same thing happen with e.g. Notepad?

I can reproduce with Spotify, Firefox, and Explorer. I can't easily get at Notepad on my system but Notepad2 does NOT reproduce the issue.

> Does this only happen when maximizing to regions using the maximize button, or does it also happen when using Shift+drag or when using a recipe?

Both

Lastly, it looks like I left out a very important detail in my original report: when a window has an accent border (e.g. Explorer) windows look right when they have focus and wrong when they don't have focus. Windows that never have an accent border (e.g. VS Code) always look wrong. Does this have something to do with the Windows 10 accent border?

**Comment by thewavelength** [comment]
I can confirm this behaviour. For me this happens e. g. with the WhatsApp Web Microsoft Store App.

Coincidence or not, I don't know: I also have a ultra widescreen (3840x1600) with 125% scaling.

**Comment by vegardlarsen** [comment]
After having investigated this for a while, it does not appear that we can solve this in any good way. If we ignore the "invisible accent border" and size windows 1px larger in 3 directions, we'll get overlapping windows which looks really weird when the focus changes. I am closing this as won't fix, unless something changes in regards to API support on Windows' end.
