### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by FxCatalyst** [digitalcreations/MaxTo#453]
There is no bug. 

I'm just trying to get this thing started and I'm not a coder of any sort. 

I have the regions configured, I think. 

Then, I expected to be able to map various windows to each region using a click-and-drag. But, when I do this, it is as if no regions were set-up at all. The only time I can see the monitors being regionalised is when I click on 'settings' in MaxTo. 

I have been throwing CPUs through the window since about 1994, so I'm not a complete imbecile. However, the lack of 'typical retail' 'Getting Started' or 'Tutorial' documentation (videos? gasp!) means that even though I bought this product and was excited to use it, I'm basically stuck and have done nothing. 

Also: I sent a request to a SUPPORT email address that went unanswered. 

I established a GitHub account just for this! 

Would anybody please be willing to help me here on this? I'd like to use MaxTo. 

Thank you.

**Comment by vegardlarsen** [comment]
Hi there @FxCatalyst, I haven't seen any e-mails from you to the support address, but it could have been blocked by spam filters (it happens).

After setting up your regions, and clicking "Apply regions", the regions should be available for use. And either of the following should work:

- clicking a maximize button should put the window in the region underneath the mouse
- holding Shift while moving a window should highlight the regions. Hold Shift until after you've released the mouse button
- hitting Windows+arrow keys should move the windows around quickly.

In some rare cases it may require a reboot of your computer after installation.

**Comment by FxCatalyst** [comment]
Could we possibly do a screen share? I can't replicate what you're saying
at all.

I use Zoom and TeamViewer.

Thank you.

Rick

**Comment by vegardlarsen** [comment]
I am closing this issue as we are now in touch via e-mail.

**Comment by FxCatalyst** [comment]
Thanks. I'll review Github shortly.
