### ISSUE TITLE
Windows freezes and slows for a long time with the Windows 10 capture function.

### ISSUE THREAD

**Issue by treasurej** [digitalcreations/MaxTo#458]
**Describe the bug**
Windows freezes and slows for a long time with the Windows 10 capture function.
Window Key + Shift + S

After exiting MaxTo, the capture function works fine.

**System information:**
 - Windows version: 10 Pro
 - MaxTo version: 2.0.1

**Comment by vegardlarsen** [comment]
Hi,

and thank you for getting in touch. This is actually a duplicate of #386, which has been fixed for the 2.1 release. I am therefore closing this issue.
