### ISSUE TITLE
Hot keys for recipes stop working after windows update

### ISSUE THREAD

**Issue by gabeng** [digitalcreations/MaxTo#461]
**Describe the bug**
I reviewed previous bug reports where error messages appeared after a windows update. In my case, however, there is no error message. The hot keys for the recipes simply stopped working. The issue appeared after a windows update to Windows 10 Pro 1903 build 18362.295.
Just noticed that the hot keys `Windows + arrows (righ/left)` still seem to work. The num pad keys do not.

**To Reproduce**
This issue persists even after re-install of MaxTo. I have no option to roll back the windows update at this time.

**Expected behavior**
I would like the hot keys to continue functioning.

**Screenshots**
n/a

**System information:**
 - Windows version: Windows 10 Pro 1903 build 18362.295
 - MaxTo version 2.0.1

**Additional context**
Log file attached.
[maxto20190830_report.log](https://github.com/digitalcreations/MaxTo/files/3558805/maxto20190830_report.log)

**Comment by vegardlarsen** [comment]
Does this persist after a reboot of the machine as well? Did this start after making some changes to the configuration file?

The supplied log file contains no useful information to help solve this, unfortunately. Maybe if you could send your `config.json` file I'll be able to figure out what has happened?

**Comment by gabeng** [comment]
Yes, the issue persists after reboot. Already re-installed Maxto as well. No, I did not make any changes to the config file. Cleaned out the config after re-install and had to re-create it. Thanks for looking into this.
[config.zip](https://github.com/digitalcreations/MaxTo/files/3560137/config.zip)

**Comment by gabeng** [comment]
When closing the application, some error messages appear in the log. Not sure if this is expected. I am attaching the log file.
[maxto20190831_report.log](https://github.com/digitalcreations/MaxTo/files/3562397/maxto20190831_report.log)

**Comment by vegardlarsen** [comment]
@gabeng Yes, we know of the errors, and it shouldn't really affect anything (which is why I haven't invested time into trying to fix it).

If Windows+(Left|Right) works, does it still go to MaxTo regions, or is this the Windows "Aero Snap" half-screen functionality?

**Comment by gabeng** [comment]
You are right, the Windows+(Left|Right) did not work with MaxTo - it was Aero that had stored the positions. After a reboot, hotkeys with MaxTo do not work at all.

**Comment by vegardlarsen** [comment]
@gabeng Does this still happen with [the 2.1.0 previews](https://maxto.net/en/release/alpha)?

**Comment by vegardlarsen** [comment]
I am closing this issue due to lack of feedback.
