### ISSUE TITLE
Option to reverse shift behavior when maximizing windows

### ISSUE THREAD

**Issue by watermarkhu** [digitalcreations/MaxTo#462]
When dragging a window, holding down _shift_ enables the snapping of the window to the set region. Not holding down _shift_ has the normal behavior. 

However, when maximizing a window, the effect of _shift_ is opposite compared to during dragging. Now, holding down _shift_ has the normal behavior of maximizing to full screen, and not holding down _shift_ maximizes the window to the set region. 

It would be great to have the option to reverse the behavior of shift during maximize.

**Comment by vegardlarsen** [comment]
This makes sense, and previously we had "Passive mode" that did this (it was removed with version 2.0). We've had multiple requests for this to come back, so we will probably do that at some point.

**Comment by gregmac** [comment]
Related #328

**Comment by vegardlarsen** [comment]
Passive mode will be back in 2.1.0-beta.2! However, that only applies to maximize events at this time.

I want to tie the behavior you list here to passive mode, so the behavior of dragging windows and maximizing windows align. That would be a breaking change, and therefore must wait until 3.0.

I am therefore closing this issue, and will revisit this in 3.0.
