### ISSUE TITLE
Hotkey D9?

### ISSUE THREAD

**Issue by frm1001xplrr** [digitalcreations/MaxTo#467]
There are hotkey characters D0-D8 for numerical characters 0-8, but 9 is missing???

I fell like this is more of a bug, but surely it can't be, right? There must be some reason for this...

What gives?

Best
F1X

**Comment by vegardlarsen** [comment]
It is probably because I can't count. :)

We've already fixed this for 2.1 (along with properly localizing the names). I am closing this as fixed for 2.1.
