### ISSUE TITLE
Allow half-maximize (similar to how it functions in W10)

### ISSUE THREAD

**Issue by baalimago** [digitalcreations/MaxTo#468]
**Is your feature request related to a problem? Please describe.**
When using W10 snap features, it's possible to first windows+left to maximize a window to the leftmost container, and then if windows+up is pressed, the application window gets halved once more (becoming a quarter of  the screen). This functionality is great!

**Describe the solution you'd like**
An implementation much like the one which exists in w10. 

The main reason why is that the partition could be used both as a quarter and a half, but by only defining it as a half. In the current version of maxto, either a quarter partition needs to be used, or a half partition. My suggestion is that a half partition could be used, and then there should be a hotkey/recipe/functionality which  maximizes the window to half of this partition.

I hope my explanation is making sense, this functionality would give the best of both worlds. For more context, try using the windows 10 window manager, press windows left on a unmaximized window to make it fill half the screen, then press windows-up/down and you'll see what I mean.

**Comment by vegardlarsen** [comment]
@baalimago I apologize for letting this sit without an explanation, sometimes issues do slip between my fingers and I only discover them after trying to reach Inbox Zero.

I think that you would be well served with the new "Cycle position" command in 2.1.0-alpha.2, which let you use "WinSplit Revolution"-style keyboard shortcuts to split the monitor. It is a different way of working compared to MaxTo's normal flow, but I think it may work for you.
