### ISSUE TITLE
Applications that do not snap to a region

### ISSUE THREAD

**Issue by tomingoglia** [digitalcreations/MaxTo#469]
I'm currently running in the default Ultra wide 3 way region setting. The below applications do not honor the regions. I'm using the Windows key and arrows or dragging to the region at the top of the screen. The default Windows regions (50% split left and right) do work for these applications, however. 

- Microsoft Teams (one computer)
- Windows Command Prompt (multiple computers)
- Windows PowerShell (elevated permissions)
- VS Code
- Notepad++

To follow up on this. The problem seems to be pretty random :-( Today VS code won't snap to a region along with Teams and Notepad++. I'd love some ideas on why this is happening. I'd really like to purchase this product but it seems to be a headache for some of the apps that I use all of the time. The more odd thing is that some of these work on my other computer. So...is it really a compatibility with the program or something else going on?

A bit more here. The windows that don't snap also don't become transparent when you drag them. 

Anyone home here?

**Comment by Ribesg** [comment]
Same issue with TeamSpeak3

**Comment by vegardlarsen** [comment]
Sorry this has taken me so long to answer, @tomingoglia. It must have slipped by.

There could be multiple reasons a program misbehaves with MaxTo, usually if they misbehave in the exact same manner it has the same cause.

If the windows do not become transparent, it means that subclassing isn't working. This can fail e.g. just for 64-bit apps (because we have to run 32-bit and 64-bit apps separately). It would be interesting to see if all the apps that fail share a bitness. You can inspect this using Task Manager, under the Details tab. Right-click the column header, and choose "Select columns". Set a checkmark for "Platform", and then find the application in the list to see its bitness.

**Comment by tomingoglia** [comment]
Thanks for the response. Unfortunately my trial expired and I didn't feel comfortable paying for the product when I couldn't get support. I have no way to test it now.

**Comment by vegardlarsen** [comment]
@tomingoglia Contact me on the support e-mail with a link to this case and I'll see what I can do.

**Comment by aalear** [comment]
I can reproduce this with Visual Studio 2019 - it doesn't become transparent and doesn't snap to regions. It used to when I first installed MaxTo 2.0 (about two or three weeks ago, I think? not entirely sure), but then something seemingly broke somewhere and it doesn't behave anymore.

**Comment by vegardlarsen** [comment]
@Ribesg TeamSpeak 3 will be fixed in the next release; see #481.

@aalear Strange to hear this issue with VS, I'm using it daily with MaxTo, never had an issue. A reboot may be necessary to clear it up.

**Comment by aalear** [comment]
@vegardlarsen I suspected that me RDP'ing into the machine might have been affecting things, so it took a while before I finally had a chance to do a clean reboot. Unfortunately, doesn't look like it helped.

I did some experimenting with the settings and it looks like VS positions within the regions when MaxTo is running with elevated UAC privileges, but not without.

**Comment by vegardlarsen** [comment]
@aalear Are you running Visual Studio as administrator? If that is the case, it should say "Microsoft Visual Studio (Administrator)" as the window title?

MaxTo can only work across the "elevation boundary" if it itself is running elevated. That could be the explanation for why VS didn't obey regions until after you elevated MaxTo.

**Comment by aalear** [comment]
@vegardlarsen Aha, that was it. Interestingly enough, VS is running as administrator despite the fact that the shortcut isn't marked as such, but... that's a mystery for another day. Thanks for you help!
