### ISSUE TITLE
Version 2015.02 Error writing to file

### ISSUE THREAD

**Issue by szarouski** [digitalcreations/MaxTo#47]
![maxto1](https://cloud.githubusercontent.com/assets/911388/6096991/56c91958-af79-11e4-9231-44fede22da0a.png)
![maxto2](https://cloud.githubusercontent.com/assets/911388/6096992/56cc72b0-af79-11e4-86e0-d9d6802b065c.png)
And when running programm
![maxto3](https://cloud.githubusercontent.com/assets/911388/6097005/fea28f92-af79-11e4-8619-24d16bba3fba.png)

**Comment by szarouski** [comment]
That happened while I was installing update on existing installation. I uninstalled program, then rebooted computer to get rid of dll file and installed 2015.02 without any issues. Feel free to close the issue.

**Comment by vegardlarsen** [comment]
Strange. I'm going to close this, and hope this was a fluke on your machine. If anyone else sees this issue, feel free to chime in here.
