### ISSUE TITLE
Internal server error when logging in to maxto.net

### ISSUE THREAD

**Issue by dzieciou** [digitalcreations/MaxTo#474]
**Describe the bug**
When trying to log in through maxto.net I'm getting 

> "We encountered an error: Internal Server Error. We've logged this error with request ID |be8a579b-4e0c0ca40007f502.."

**To Reproduce**
1. Go to maxto.net
2. Try to log in.

**Expected behavior**
I should be logged in.

**Screenshots**

![2019-10-01 14_27_34-Error - MaxTo](https://user-images.githubusercontent.com/7452788/65961868-c468c900-e457-11e9-8524-7fb310fda923.png)

**System information:**
 - Chrome 77

**Additional context**

**Comment by heathcates** [comment]
I'm having the same issue. 

I am also not able to register using the updated code if that connection is of any help.

**Comment by vegardlarsen** [comment]
@heathcates @dzieciou We tried deploying an update to the website earlier today, and it seems to not have gone to plan. I have rolled it back now, and these issues should be gone now. Can you please check if that is the case?

**Comment by heathcates** [comment]
> @heathcates @dzieciou We tried deploying an update to the website earlier today, and it seems to not have gone to plan. I have rolled it back now, and these issues should be gone now. Can you please check if that is the case?

I'm in now, thanks for the quick reply.

**Comment by dzieciou** [comment]
Thanks, it works well now.
