### ISSUE TITLE
Compatibility issues with latest version MaxTo.Hook.x64.dll

### ISSUE THREAD

**Issue by bradydonald** [digitalcreations/MaxTo#475]
Multiple software components complain about MaxTo:
LocalBridge.exe - Bad Image C|;\...\MaxTo.Hook.x64.dll is either not designed to ruinon Windows or contrains an error. Try installing the program again.

This is stable build and windows build Win 10 Pro v1903 OSbuild 18362.388

Also uninstall and re-installing does not fix the issue. Have to quit MaxTo lo launch or run certain programs.

**Comment by vegardlarsen** [comment]
Have you seen issue #415? There is a workaround that will stop this issue completely on your machine.

I am closing this as a duplicate. :)

**Comment by bradydonald** [comment]
Just read it but I resolved the issue by:

Uninstalling
Searching the machine after rebooting for any Maxto occurrences and
deleting all files manually - uninstaller doesn't seem to remove all traces
of the program.
Rebooting
Installing fresh

No problems since then so I'm not convinced this is an issue with the
windows build but some combination of both.

Great program btw. Love how est I it is to use.

**Comment by Xairoo** [comment]
LocalBridge.exe belongs to `Microsoft.MicrosoftOfficeHub``
Well, that bug steels lifetime.
