### ISSUE TITLE
Allow users to specify exempt programs.

### ISSUE THREAD

**Issue by SethG911** [digitalcreations/MaxTo#479]
**Is your feature request related to a problem? Please describe.**
Yes, Adobe XD is currently causing error dialogs to appear due to MaxTo.

**Describe the solution you'd like**
Allow users to be able to add their own list of programs to the exempt list.

**Describe alternatives you've considered**
Closing MaxTo to avoid the error dialogs while using Adobe XD.

**Additional context**
None.

**Comment by vegardlarsen** [comment]
@SethG911 Is this the same error message as in #415?

**Comment by sambedingfield** [comment]
![image](https://user-images.githubusercontent.com/13186243/67474056-b6b7f500-f64b-11e9-893d-44917392714d.png)

Yeah, same error message when Adobe XD and MaxTo are running at the same time. It's been like this for a few weeks now and is really frustrating! I have error reporting on, but if there's anything I can help with diagnosing further, please let me know.

**Comment by vegardlarsen** [comment]
@sambedingfield If that is the case, see the e-mail you just received (if you are a paid customer), or the workaround in issue #415.

I am closing this issue because it would appear that it is the same issue.

@SethG911 Please do let me know if it is not.

**Comment by sambedingfield** [comment]
Just seen the email and can confirm - deleting the following file:
`C:\Users\XXXXXX\AppData\Local\Packages\Adobe.CC.XD_XXXXXX\LocalCache\Local\MaxTo\app-2.0.1\MaxTo.Hook.x64.dll`

 ...took 30 seconds and instantly fixed the issue without losing any data.

Much appreciated guys. MaxTo is the best!
