### ISSUE TITLE
Crash report: a time log

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#48]
Maxto has been crashing quite frequently, ever since I updated it from the 2011 version 3 days ago. @vegardlarsen, if you don't mind, may I keep a crash-log here?
- 2015-02-09 10:03:50, crashed while trying to move a "Sumatra PDF" window.
- 2015-02-09 12:48:18, crashed while switching to Sumatra PDF.'
- 2015-02-09 15:38:34, crashed while switching to Vim (or expanding Vim to full string).
- 2015-02-09 16:38:13, crashed while trying to maximize MS Excel, 2013.
- 2015-02-09 19:30:00, crashed while trying to maximize Vim. Maxto had already successfully moved the Vim window to the
  next screen. It crashed when trying to maximize the window.
- 2015-02-10 10:02:01, crashed while trying to move Firefox Window.
- 2015-02-10 11:42:47, crashed while trying to maximize Firefox. Moving around worked.
- 2015-02-10 16:29:03, crashed while waking up from sleep/screen-saver.
- 2015-02-11 10:50:09, crashed while maximizing the firefox window, after moving it to another screen.
- Getting worse. Crashed three times in a minute, silently. Twice with Firefox and once with Vim.  2015-02-16 17:42:58

**Comment by vegardlarsen** [comment]
@llinfeng Could you check to see if there are Exception_<something>.zip files in your MaxTo folder, and if that is the case, e-mail them to me? I have seen no crash reports being reported automatically in a few days.

**Comment by llinfeng** [comment]
@vegardlarsen, no `.zip` file had been found in `c:\Program Files (x86)\MaxTo\`, the default directory.

Anywhere else should I look into?

**Comment by vegardlarsen** [comment]
Do you get the "MaxTo has crashed and a bug report has been sent to the developers" message? Or does it crash in a different way?

**Comment by llinfeng** [comment]
I think so. Will confirm this upon next crash.

**Comment by vegardlarsen** [comment]
When this happens, before starting MaxTo again, check again for the Exception.zip files. MaxTo deletes them if it thinks they are sent successfully, but I am not receiving them here.

**Comment by llinfeng** [comment]
Here goes the error message vomited by the crash report: 
````
Files that help describe the problem:
  C:\Users\llinfeng\AppData\Local\Temp\WERA537.tmp.WERInternalMetadata.xml
  C:\Users\llinfeng\AppData\Local\Temp\WERBAAB.tmp.appcompat.txt
  C:\Users\llinfeng\AppData\Local\Temp\WERBABC.tmp.hdmp

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
````

Screenshots follows: 

![2015-02-10_115933](https://cloud.githubusercontent.com/assets/5890407/6131766/50b7ab70-b11c-11e4-8784-f68d5853848d.png)
![2015-02-10_115941](https://cloud.githubusercontent.com/assets/5890407/6131767/52ce44be-b11c-11e4-94ee-43552923a587.png)

After clicking "yes", nothing happened.

**Comment by vegardlarsen** [comment]
Ah, this crash report is going to Microsoft, so I won't see it. Can you grab those files listed and e-mail them to me?

**Comment by llinfeng** [comment]
I have searched over the root directory at which Maxto is deployed and here goes the search result: No Zip file found at this directory. 
![2015-02-10_120033](https://cloud.githubusercontent.com/assets/5890407/6131797/8aff4ebe-b11c-11e4-99a2-c44c2281650b.png)

Will email those files to you in a minute.

**Comment by llinfeng** [comment]
I had only found the first file mentioned in the error report. Here goes the content. 

https://www.dropbox.com/s/4puo7hv0ui2ehnv/WERA537.tmp.WERInternalMetadata.xml?dl=0

**Comment by vegardlarsen** [comment]
Unfortunately that file didn't tell me anything useful. Try to see if you can grab any of the other two files. By the way, which version of Windows are you running?

**Comment by llinfeng** [comment]
I am running Windows 7 Ultimate. Here goes a different error message, which might be what you are looking for. 
![2015-02-10_162756](https://cloud.githubusercontent.com/assets/5890407/6136808/e57223ec-b141-11e4-8e42-a877f093b855.png)

**Comment by llinfeng** [comment]
Hi @vegardlarsen, any idea why Maxto keeps crashing? It crashed twice this morning within 30 minutes. Anything you would like me to provide? What follows is another file that I fetched.

https://www.dropbox.com/s/kt2a5y8fu51xm29/temp.hdmp?dl=0

**Comment by vegardlarsen** [comment]
@llinfeng Are you certain you are running the 2015.02 release? Could you check the about dialog?

Whenever the last error message you posted a screenshot of appears, there should be Exception.zip-files, could you look again?

**Comment by llinfeng** [comment]
Ok, I found those in the recycle bin. Here goes the link to the two files I have found: 
https://www.dropbox.com/s/yuxuwcetn1jybpb/Exception_130680773245915171.zip?dl=0

https://www.dropbox.com/s/n646bawmccl5q0g/Exception_130682563894382902.zip?dl=0

I am running 2015.2 
![2015-02-13_103826](https://cloud.githubusercontent.com/assets/5890407/6189939/7b2e2620-b36c-11e4-8011-3acafe22c9e7.png)

**Comment by vegardlarsen** [comment]
@llinfeng The attached crash reports seem to be the exact same issue as in #49. Can you take a look at the build I provided there, to see if it fixes the problem?

Crash report for reference:
 
```xml
<?xml version="1.0"?>
<SerializableException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ExtendedInformation>
    <HResult>-2146233079</HResult>
  </ExtendedInformation>
  <Message>Process has exited, so the requested information is not available.</Message>
  <Source>System</Source>
  <StackTrace>   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at MaxTo.CompatibilityShimsManager.ProcessIdentifier.MatchesWindow(ISystemWindow window)
   at MaxTo.CompatibilityShimsManager.WindowIdentifierCollection.Contains(ISystemWindow window)
   at MaxTo.CompatibilityShimsManager.TagWindow(ISystemWindow window)
   at MaxTo.MainForm.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</StackTrace>
  <TargetSite>Void EnsureState(State) @ System.Diagnostics.Process</TargetSite>
  <Type>System.InvalidOperationException</Type>
</SerializableException>
```

**Comment by llinfeng** [comment]
Do I need to uninstall the previous installation?

**Comment by vegardlarsen** [comment]
Yes. :)

**Comment by llinfeng** [comment]
@vegardlarsen, something worse happened. Now the program dose not "crash", it just stops working silently. No error message would be sent and the icon should still be dock at the notification area. It quits/stops without any notice!

I guess I am unable to send you any log file for debugging this time.

**Comment by llinfeng** [comment]
Hi @vegardlarsen, the newly provided build will quit silently on my machine.

**Comment by llinfeng** [comment]
Newly found pattern: the new build will silently exit when I get back and forth with remote access.

**Comment by llinfeng** [comment]
@vegardlarsen: new bug patter
Crashed silently while trying to maximize firefox, as always. However, Maxto also hides the entire firefox window. Such an active window is not visible anymore.

Any thought?

**Comment by llinfeng** [comment]
@vegardlarsen, it may be a pattern now: silent quit occurs when trying to maximize the window using `Win + Enter`. I am running a Win 7 OS.

**Comment by vegardlarsen** [comment]
That makes sense. Can you try to provoke it a few times to figure out if that really is the issue? I'll look into it the next time I am doing work on MaxTo.

**Comment by llinfeng** [comment]
The silent crash occurs mostly when I try to expand the window to full screen. If this is hard to debug, implementing the following feature would be a life-saver: 

Currently, when I move a maximized window from one screen to another, that window will cease to be maximized. As long as you could make the maximized window remain maximized, I think the silent crash would occur less often.

**Comment by vegardlarsen** [comment]
I'm afraid I don't understand. Are you dragging the window (it will restor its previous size when you start dragging) or moving it using keyboard shortcuts (it will move into the available region)?

The crash happens when you press Win+Enter?

**Comment by llinfeng** [comment]
I am not dragging the window, but shifting the window across screens (4 of them), from left to right, using the hotkey for *Movement*. The "shifting" works fine. Maxto will crash silently when I try to maximize the window (upon pressing Win + Enter, i.e. *Maximize to monitor*).

Does this make sense?

**Comment by llinfeng** [comment]
Maybe something new this time. I tried the new build on my Windows 8.1 machine and here goes some "debug" window, which I have no clue how to proceed.

Additionally, upon this crash, the window/process that lead to the crash would *vanish* when maximized, using the normal "maximization" button on the right corner at the top. I fell like Maxto does not like me.

Any solution? I think I have provided enough error reports that I would just like to have an old version running for now. I would be happy to test out the possible new builds. 

Thank you anyway.
![untitled picture](https://cloud.githubusercontent.com/assets/5890407/6274157/66a9fb94-b843-11e4-8a6d-2cfcdc3caa9c.png)

**Comment by vegardlarsen** [comment]
Thanks @llinfeng. It really seems MaxTo does not thrive on your machine. That latest bug report is a problem with NBug, which is the library we use internally to report crashes in MaxTo. It looks like it can't properly serialize an error report, so deleting any `Exception_<something>.zip`-files (after you've e-mailed them to me) from the MaxTo folder should get rid of that error. I'll be looking into what is causing it.

I am stumped as to why you are experiencing so many crashes on your machine, but I will look into every error report and try to solve them. Thanks again.

**Comment by llinfeng** [comment]
Hi @vegardlarsen, here is one more guess: that my installation of the "new build" (as of the one you provided in #49) may not have been fresh. So, apart from the following directory
`````
c:\Program Files (x86)\MaxTo\
`````
Are there any directory that MaxTo is writing onto? I do see that all my key-mappings are kept. I would doubt if the silent crashes are caused by the conflicts in the files that are left-over.

This may explain why I am the only one who has been experiencing the problem with the new build.

By the way, things gets really worse for me now. 
* For the 2011 build, key mappings stopped to work. MaxTo will not exist nor refresh. I was also *unable* to move the windows around using the original windows key-bindings;
* After uninstalling the 2011 build and re-install the "new build", it should have "silently quit" after 2 seconds upon a new start. This happened to Vim.

I am really expecting a solution badly.

Thank you all the same.

**Comment by llinfeng** [comment]
New pattern: MaxTo inactive upon start. Icon does not vanish, but had also been inactive. Hovering the mouse over the icon in the notification area will trigger the display of name tag for "Maxto". However, right-click does not trigger anything. Nor had all the hot-keys defined internally through the "Options" work for MaxTo.

**Comment by llinfeng** [comment]
Additionally, these are the *three* processes that are running while the icon remain inactive.
![untitled picture](https://cloud.githubusercontent.com/assets/5890407/6415461/394b8746-be6d-11e4-8a1e-944048a1a468.png)

I don't think it would be normal to have both 32 and 64 bit processes running at the same time is a good idea. Since MaxTo is small enough, would you mind passing me a 32-bit only build?

**Comment by vegardlarsen** [comment]
Just to let you know, I am reading all your posts, I just don't have a working theory yet.

MaxTo runs all these processes on purpose. The 32-bit subprocess only deals with 32-bit processes, and the 64-bit subprocess only deals with 64-bit processes. It has to work that way.

MaxTo has a settings file underneath `%localappdata%\Digital_Creations_AS`, if you delete the folder (may be more than one) there, all your settings (except your license key) will disappear.

If MaxTo crashes, it may not work correctly again until after you have rebooted. I don't know why, but when developing MaxTo I quite frequently have to reboot because Windows couldn't handle the sudden termination.

I will be looking at the Win+Enter problem, but unfortunately I have been really busy this week.

**Comment by llinfeng** [comment]
Hi @vegardlarsen, no problem. I understand. Take your time in fixing the bug.

In the mean time, I have deployed the following key-mappings in AHK to help battle the crashing of MaxTo. Hope this would be helpful for whoever is experiencing the same problem. (Script written in AHK, to be downloaded from: http://ahkscript.org/)
````
;; Mapping for multiple pressing!
i := 0
^!m::
i := ++i
SetTimer,T0,500 ;0.5秒,两次热键之间不超过这个时间就被记录
Return
T0:
        if i>1 ;大于1时关闭计时器
        SetTimer,T0,Off
				if i=1
						send ^!m
        if i=2 ;按两次时...
            Process,Close,MaxTo.exe
        if i=3 ;.....
            run C:\Program Files (x86)\MaxTo\MaxTo.exe
        if i=4 ;.....
            MsgBox,pressing for 4th time in a roll.
        if i>5
        {
            MsgBox,长按住RAlt不放
            sleep 4000  ;这里如果是别的命令,需要延时4秒防止长按键时多次触发
            i := 0
        }
        i := 0 ;最后把记录的变量设置为0,于下次记录.
Return
````
That is, pressing `Ctrl+Alt+M` for twice within 0.5 second will trigger the termination of `MaxTo.exe`. (Upon silent crash, such process will keep running.)

Pressing `Ctrl+Alt+M` for three times in a roll (within 0.5 second) will trigger the start of Maxto.

As of now, recusing a "crashed" Maxto had become less demand and could be done within several seconds. So, this becomes less bothering as before. (Well, I would easily be pissed off when asked to use the mouse to do repeated work.)

**Comment by vegardlarsen** [comment]
Can you try this out with the 2.0.0 preview releases we just put out? See #220 for details.

I have a suspicion that this will stop happening with those releases.

**Comment by vegardlarsen** [comment]
Closing because of lack of feedback.
