### ISSUE TITLE
Moving windows - super slow movement - unusable experience

### ISSUE THREAD

**Issue by andre-holivia** [digitalcreations/MaxTo#480]
**Describe the bug**
When I simply move a window (drag from the title bar), there is like a smoothing effect which makes the movement of the window unbearably slow. It is like there is a smoothening effect imposed by MaxTo which is just not keeping up with the speed of the hand. This is very visible slow

**To Reproduce**
Install Maxto
Drag any window

**Expected behavior**
When I am moving windows either bring up the grid to snap into or move fast based on where my drag movement stops

**Screenshots**
Cannot provide a screen shot. Hapy to share a video if given an email to send to

**System information:**
- Windows 1903, Build 19008.1 (started on earlier builds)
 - MaxTo version 2.0.1

**Additional context**
It is not a crash. It is a situation where the product makes UX impossible

**Comment by vegardlarsen** [comment]
Can you [check your log files](https://maxto.net/documentation/troubleshooting) for anything happening during this behavior?  Does the issue happen with all apps, or just specific ones?

**Comment by nickallevato** [comment]
I see this happen when I drag the actual MaxTo window. 
feels like transparency related, but I'm only speculating.

**Comment by jdunham22** [comment]
I saw this for the first time today, I'll report back if I can isolate it.

**Comment by bmspcsd** [comment]
I have this problem as well, but only on the actual MaxTo window. Regular program windows move normally but the MaxTo window seems to have a maximum speed that it will not exceed. Interestingly it remembers every action and carries them out, just slowly. For instance if I grab the MaxTo window and drag it quickly around the screen and then let go, it will move in that pattern but very slowly. I am on 1903 Build 18362.418 and MaxTo 2.0.1

**Comment by lucaslink** [comment]
> I have this problem as well, but only on the actual MaxTo window. Regular program windows move normally but the MaxTo window seems to have a maximum speed that it will not exceed. 
Exact same behavior for me as well.

**Comment by uxchamp** [comment]
I have the same issue. On version 2.0.1. This issue is only with MaxTo Settings window. Can't drag it around the desktop.

**Comment by vegardlarsen** [comment]
After investigating this quite a bit, this is related to using `Window.DragMove` from WPF to allow moving the window by clicking on points we control. The "correct" way of doing this Win32-style, is to respond to `WM_NCHITTEST` messages with `HTCAPTION` for the correct areas, but because of how our windows are currently created this is not a possibility.

We are looking into ways we can get around this.

**Comment by vegardlarsen** [comment]
I have managed to fix this issue, and the fix will be in 2.1.0-alpha.4.
