### ISSUE TITLE
Windows have stopped snapping to regions

### ISSUE THREAD

**Issue by JDoetsch85** [digitalcreations/MaxTo#482]
This morning, Chrome has stopped snapping to the regions.  It's the only app that I've noticed that has this behaviour, and it had been working fine prior to today.

Reproduce:

Open Chrome
Drag to region
Click maximize or double-click top of window to snap
Window fills entire space instead of desired region

I'm nearing the end of my 30 day trial, and I was considering purchasing but now I'm not so sure I'll continue.  Any assistance would be appreciated.

**Comment by vegardlarsen** [comment]
Unfortunately Chrome broke something in their latest update. See issue #476 for what we are doing about it. I am closing this issue as a duplicate.
