### ISSUE TITLE
Latest version of chrome breaks the docking feature

### ISSUE THREAD

**Issue by capslockoff** [digitalcreations/MaxTo#483]
**Describe the bug**
Please install the latest version of Chrome and the window no longer fits within a region of Maxto.
Version 78.0.3904.70 (Official Build) (64-bit)

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment]
Please see issue #476. Closing this as a duplicate.
