### ISSUE TITLE
windows reverting back to 'pre maxto' size after 'clicking off' then 'clicking back on' the window

### ISSUE THREAD

**Issue by nickallevato** [digitalcreations/MaxTo#487]
windows 10
maxto alpha

I filed a previous bug report; all conditions are the same.

**Comment by vegardlarsen** [comment]
I have identified this issue in 2.1.0-alpha.1, and the fix for this issue will be in 2.1.0-alpha.2. Thank you for letting us know.

**Comment by nickallevato** [comment]
thanks man
appreciate you allowing my loosey-goosey tickets too
