### ISSUE TITLE
'Regions' are ignored by Chrome version 78.0.3904.87

### ISSUE THREAD

**Issue by dukeduck1984** [digitalcreations/MaxTo#488]
**Describe the bug**
Just updated Chrome to version 78.0.3904.87 and found out that the MaxTo regions no longer work for Chrome, and Chrome only.

**To Reproduce**
1. Update the Chrome to version 78.0.3904.87
2. Click maximize button on Chrome window bar.
3. Chrome ignores the regions set by MaxTo and the window just maximized to full screen size.

**Expected behavior**
Chrome window should have maximized to the region size.

**System information:**
 - Windows10 release 1903
 - MaxTo version 2.0.1

**Comment by vegardlarsen** [comment]
Please see issue #476 which has a fix for this issue. Closing this as it is a duplicate.
