### ISSUE TITLE
Crash after few minutes of usage

### ISSUE THREAD

**Issue by nigi10** [digitalcreations/MaxTo#49]
After updating I get a crash after a few minutes of usage. I am also developing in visual studio so it might be a problem with some windows that are being debugged or something. I will send you the exception zips by email.

**Comment by vegardlarsen** [comment]
@nigi10 Thank you for the report. It appears a process disappeared while MaxTo was examining it. Were you by any chance terminating the debugging session in VS when this happened?

Where you doing anything in particular when this crash occurred?

Crash dumps for my reference:

```xml
<?xml version="1.0"?>
<SerializableException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ExtendedInformation>
    <HResult>-2146233079</HResult>
  </ExtendedInformation>
  <Message>Process has exited, so the requested information is not available.</Message>
  <Source>System</Source>
  <StackTrace>   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at MaxTo.CompatibilityShimsManager.ProcessIdentifier.MatchesWindow(ISystemWindow window)
   at MaxTo.CompatibilityShimsManager.WindowIdentifierCollection.Contains(ISystemWindow window)
   at MaxTo.CompatibilityShimsManager.TagWindow(ISystemWindow window)
   at MaxTo.MainForm.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</StackTrace>
  <TargetSite>Void EnsureState(State) @ System.Diagnostics.Process</TargetSite>
  <Type>System.InvalidOperationException</Type>
</SerializableException>
```

```xml
<?xml version="1.0"?>
<Report xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <GeneralInfo>
    <CLRVersion>4.0.30319.34209</CLRVersion>
    <DateTime>10.02.2015 08:46:54</DateTime>
    <ExceptionMessage>Process has exited, so the requested information is not available.</ExceptionMessage>
    <ExceptionType>System.InvalidOperationException</ExceptionType>
    <HostApplication>MaxTo.exe</HostApplication>
    <HostApplicationVersion>2015.2.0.0</HostApplicationVersion>
    <NBugVersion>1.1.2.0</NBugVersion>
    <TargetSite>Void EnsureState(State) @ System.Diagnostics.Process</TargetSite>
  </GeneralInfo>
</Report>
```

**Comment by nigi10** [comment]
It could very well be that I terminated a debugging session when this crash
happened. I will try to see if the crash appears again during debugging.

2015-02-11 9:24 GMT+01:00 Vegard Andreas Larsen <notifications@github.com>:

**Comment by nigi10** [comment]
Again had the same crash. It happened during compilation so I am pretty
sure there was no process stopped (at least none with a window ... there
might be test cases running as a post build step)

2015-02-11 9:29 GMT+01:00 Nicholas Pleschko <lordnigi@gmail.com>:

**Comment by vegardlarsen** [comment]
I am going to set up a try-catch around this area and will send you a private build once I get the time. Would be interesting to figure out exactly what is happening though.

**Comment by nigi10** [comment]
That would be perfect, thanks! I agree it sounds like an interesting case
to investigate further. If I can help you in any way let me know.

2015-02-11 13:48 GMT+01:00 Vegard Andreas Larsen <notifications@github.com>:

**Comment by vegardlarsen** [comment]
I've created a custom build with this problem fixed. You can [download it here](https://dl.dropboxusercontent.com/u/12591686/MaxToSetup-issue49.exe).

This build has the same version number as the currently released version. If you want to install it, you first have to uninstall the current version, and then install this, as the setup will not let you overwrite with identical versions.

Please let me know if this solves the crashing issues.

**Comment by nigi10** [comment]
Perfect, thanks! I will install it and test it.

2015-02-13 8:26 GMT+01:00 Vegard Andreas Larsen <notifications@github.com>:

**Comment by nigi10** [comment]
Just had another crash with the new version. Seems to be a similar one. The
report is attached.



2015-02-13 8:35 GMT+01:00 Nicholas Pleschko <lordnigi@gmail.com>:

**Comment by vegardlarsen** [comment]
@nigi10 Can you please send the report via e-mail to me personally. E-mails sent to Github do not include attachments.

**Comment by nigi10** [comment]
Ups, sorry. I didn't even realize these emails go through github. Will send
you an email with the attachment.

2015-02-13 16:00 GMT+01:00 Vegard Andreas Larsen <notifications@github.com>:

**Comment by vegardlarsen** [comment]
New crash report below

```xml
<?xml version="1.0"?>
<SerializableException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ExtendedInformation>
    <HResult>-2147024809</HResult>
  </ExtendedInformation>
  <Message>Process with an Id of 1872 is not running.</Message>
  <Source>System</Source>
  <StackTrace>   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at MaxTo.Native.SystemWindow.get_Process()
   at MaxTo.CompatibilityShimsManager.ProcessIdentifier.MatchesWindow(ISystemWindow window)
   at MaxTo.CompatibilityShimsManager.WindowIdentifierCollection.Contains(ISystemWindow window)
   at MaxTo.CompatibilityShimsManager.TagWindow(ISystemWindow window)
   at MaxTo.MainForm.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</StackTrace>
  <TargetSite>System.Diagnostics.Process GetProcessById(Int32) @ System.Diagnostics.Process</TargetSite>
  <Type>System.ArgumentException</Type>
</SerializableException>
```

It seems this is crashing with different exceptions with the same cause. I am looking into it now, new build coming shortly.

**Comment by vegardlarsen** [comment]
OK, that was fast, even for me.

[New build here](https://dl.dropboxusercontent.com/u/12591686/MaxToSetup-issue49-take2.exe). Same as last time, need to uninstall before installing.

**Comment by nigi10** [comment]
Awesome :) installing it now.

2015-02-13 17:15 GMT+01:00 Vegard Andreas Larsen <notifications@github.com>:

**Comment by vegardlarsen** [comment]
@nigi10 Any crashes yet? :)

**Comment by nigi10** [comment]
:) Sorry I am not using MaxTo on the weekend. Will report back next week ;)
Thanks again for the quick support!

2015-02-13 20:46 GMT+01:00 Vegard Andreas Larsen <notifications@github.com>:

**Comment by llinfeng** [comment]
Hi @nigi10! It seems that we are suffering from the same bug now. 

Any luck with the new build? It crash/exit without noticing every now and then, at a frequency of twice an hour.

**Comment by nigi10** [comment]
No crashes so far. Looks like it is fixed.
