### ISSUE TITLE
new windows upgrade dll errors everywhere.....

### ISSUE THREAD

**Issue by Chiraza** [digitalcreations/MaxTo#490]
upon rebooting after windows upgrades Version	10.0.18362 Build 18362 dll errors loads will try and post some pictures as soon as I reboot again.

**Comment by Chiraza** [comment]
![Annotation 2019-11-08 110810](https://user-images.githubusercontent.com/57492085/68491151-4ba81a00-0218-11ea-9358-2e49a5b2cd9c.jpg)

**Comment by vegardlarsen** [comment]
Please see issue #476, with a working workaround. Closing this issue as a duplicate. @Chiraza
