### ISSUE TITLE
NoMachine client does not maximize properly

### ISSUE THREAD

**Issue by RobvanB** [digitalcreations/MaxTo#491]
When maximizing the NoMachine (https://www.nomachine.com/)  client in a region, the left side of the window 'drops off', it cuts off the left side of the window.
I can manually make it show properly by resizing it. It does 'snap' to the corner then.

**To Reproduce**
1. Drag NoMachine client to certain region
2. Click 'maximize' on the window border

**Expected behavior**
It should properly maximize and show the full window in the region

**Screenshots**

How it should look (note Linux taskbar is visible now on the left)
![correct](https://user-images.githubusercontent.com/118380/68514910-241f7480-024d-11ea-8ca0-81213ee45b86.png)

How it looks when I hit the maximize button (note the left side of the window gets cut):
![wrong](https://user-images.githubusercontent.com/118380/68514919-2bdf1900-024d-11ea-9643-976d297ebc7d.png)

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1

**Additional context**
N/A

**Comment by vegardlarsen** [comment]
Do you have different DPI scaling settings on two monitors, so that the NoMachine window partially extends into the monitor to the left?

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback.
