### ISSUE TITLE
How to set background wllpapers ro regions created with MaxTo?? Thanks.

### ISSUE THREAD

**Issue by kpl1949** [digitalcreations/MaxTo#493]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vegardlarsen** [comment]
@kpl1949 MaxTo does not actually create separate "monitors" for each region, so you cannot set background images separately per region. MaxTo itself does not deal with background images at all. We have no plans to do so either; so I am closing this issue.

As a suggestion, you can probably create your own background images with outlines of your regions on them, but I don't think this is something MaxTo itself should do.
