### ISSUE TITLE
Add idempotent option to Launch ingredient

### ISSUE THREAD

**Issue by bmspcsd** [digitalcreations/MaxTo#498]
Splitting this out from #496 

Please add an option to the current Launch command so that programs are not launched if they are already running. Preferably if they are already running, this option would just "restore" them to the screen or bring them to the foreground. This way a Recipe can be created which lays out a workspace with a certain set of programs, and the Recipe will simply arrange the programs if the programs are already running when the Recipe is executed, rather than start new instances of each program.

**Comment by vegardlarsen** [comment]
I have implemented this for the next release. I am adding a `/SkipIfAlreadyRunning` flag to the existing launch command. It will only skip launching if the exact same executable is already running.
