### ISSUE TITLE
Since a few days the program asks me to enter again my licence key. When I go on your website to copy it, have an error message.

### ISSUE THREAD

**Issue by alexandrebesset** [digitalcreations/MaxTo#501]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment]
Can you please elaborate on which error message you are receiving?

**Comment by alexandrebesset** [comment]
Error

We encountered an error: Internal Server Error.
Go to home page <https://maxto.net/en>

We've logged this error with request ID |783abce6-41433a0593686bab..
[image: Computer illustration showing a Microsoft Surface Studio]
C:\> wget https://maxto.net/ --2019-11-18 09:34:18-- https://maxto.net/
Resolving maxto.net (maxto.net)... 10.14.108.56 Connecting to maxto.net (
maxto.net)|10.14.108.56|:443... connected. HTTP request sent, awaiting
response... 500 Internal Server Error 2019-11-18 09:34:18 ERROR 500:
Internal Server Error. C:\>

**Comment by vegardlarsen** [comment]
@alexandrebesset And what where you doing as you received this error?

**Comment by alexandrebesset** [comment]
I was trying to find my serial key on your website.

**Comment by vegardlarsen** [comment]
Can you instead contact me on the support mail address so we can resolve this privately? You'll find it under Settings, About in the app.
