### ISSUE TITLE
Eliminate 1 pixel gap between regions.

### ISSUE THREAD

**Issue by desjani** [digitalcreations/MaxTo#506]
Every window seems to have a one pixel wide gap between regions, allowing the wallpaper/other windows to show through. Screenshot attached. 
![2019-11-26 10_49_04-](https://user-images.githubusercontent.com/45343386/69659099-be97fa00-103a-11ea-8ce9-354dbade52b7.png)

**Comment by vegardlarsen** [comment]
Thank you for your report. Which version of Windows and MaxTo are you running? Does the problem persist after a reboot? Is it valid for all programs (e.g. Notepad)? Do you have any sort of DPI scaling turned on? Do you have multiple monitors, and is the DPI scaling different between them?

**Comment by Fonta** [comment]
I have a 49" super ultra wide screen and have my settings like 1/4, 2/4, 1/4. I also have a few pixels gap between the windows. as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/6190791/76017956-c27fc600-5f1f-11ea-8a1a-497d2ff48f30.png)

**Comment by vegardlarsen** [comment]
@Fonta Do you have any sort of DPI scaling turned on? Do you have multiple monitors, and is the DPI scaling different between them?

**Comment by Fonta** [comment]
Hi, I'm on 100%, no other monitors.

![image](https://user-images.githubusercontent.com/6190791/76091169-52278200-5fbd-11ea-87cc-092bd31a777c.png)

**Comment by vegardlarsen** [comment]
After having investigated this for a while, it does not appear that we can solve this in any good way. If we ignore the "invisible accent border" and size windows 1px larger in 3 directions, we'll get overlapping windows which looks really weird when the focus changes. I am closing this as won't fix, unless something changes in regards to API support on Windows' end.

See also #450 (which is basically the same issue).
