### ISSUE TITLE
Help - LocalBridge.exe - Bad Image error

### ISSUE THREAD

**Issue by timbochung** [digitalcreations/MaxTo#507]
I've tried reinstalling Max.To several times + updating Windows to no avail.  Suggestions?

Thanks,
Tim
![Capture](https://user-images.githubusercontent.com/58309121/69827931-9dc0d780-11e7-11ea-97c1-53a758563053.PNG)

**Comment by vegardlarsen** [comment]
This is unfortunately a known issue. See issue #415, which contains a workaround and more information.
