### ISSUE TITLE
LocalBridge.exe - Bad Image

### ISSUE THREAD

**Issue by fixafone123** [digitalcreations/MaxTo#509]
I am getting the following error message, mostly when Office products start but I also get it at random times: [Error Message](https://wustl.box.com/shared/static/e8qdv0z33jrs3d8amy7fi7ywxak6g2yx.png)

I am running version 2.0.1

Thanks!

**Comment by vegardlarsen** [comment]
Hi @fixafone123. This is a known issue after upgrading your Windows version. Please see #415 for a workaround until Microsoft can fix this issue. I am closing this issue as a duplicate.
