### ISSUE TITLE
Maximizing to "main display" wherever start the "Maximize to monoitor" motion.

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#51]
I have a multi-monitor setup and have just noticed that the issue is prevailing with maximizing to full screen from the
"extended screens". 

The following usually happens when I call the "maximize to the screen" action: 

1. When I initiate the action at a "extended screen", the current active window gets maximized to the main display. 
2. I would have to move the window back to the previous screen and redo the maximization again.

Going back and forth to and from the "main display" screen usually gets the window to be expanded to the right screen.

I would doubt if this should be the normal behavior, though.

**Comment by vegardlarsen** [comment]
I have reproduced the problem on my machine, and have worked out a fix that should prevent this from happening in the next release.

**Comment by llinfeng** [comment]
Great! Thank you!
