### ISSUE TITLE
Error message displayed repeatedly - LocalBridge.exe - Bad Image

### ISSUE THREAD

**Issue by Sunny-Engineer** [digitalcreations/MaxTo#511]
**Describe the bug**
A pop up dialog box is displayed 100's of times an hour with the message:
LocalBridge.exe - Bad Image

![2019-12-04_11h41_16](https://user-images.githubusercontent.com/36799802/70162494-bc155000-168b-11ea-95b2-52007954bb53.png)

**To Reproduce**
It just happens...

**Expected behavior**
It should not happen.

**Screenshots**
See Attached

**System information:**
 - Windows version: [Windows 10 Pro - Build 18362.476
 - MaxTo version [e.g. 22] 2.0.0.451

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment]
Please see issue #415, which contains a fix and an explanation. I am closing this issue as a duplicate.

Also, please update your MaxTo version to 2.0.1 (it doesn't fix this issue, but it does fix other issues).
