### ISSUE TITLE
can't install .net framework 4.7 or higher

### ISSUE THREAD

**Issue by rabbit61319** [digitalcreations/MaxTo#512]
Hi, running wins 10 pro.

Installation shows complete for .net framework.

I install Maxto and it asks me to download .net framework again.

Need assistance.

**Comment by vegardlarsen** [comment]
MaxTo requires .NET Framework 4.7.2 or higher. If it isn't installed, it will attempt to install that version. You can manually download version 4.7.2 [from here](http://go.microsoft.com/fwlink/?linkid=863265).

Please do let us know if that help.

**Comment by rabbit61319** [comment]
I did install it. When I do Maxto setup again, it will ask me to down .NET again.

**Comment by vegardlarsen** [comment]
Can you please share with me your setup log? [Details about how to find it is here](https://maxto.net/documentation/troubleshooting).

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback.
