### ISSUE TITLE
Irritating error message keep reoccuring after reinstallation - Windows 10 [NOT FIXED] Error status 0xc000012f

### ISSUE THREAD

**Issue by mja09006** [digitalcreations/MaxTo#513]
Need a solution to this annoying error message. I pay for this service. It keeps reoccurring. I already tried uninstalling and reinstalling software. Happens randomly every 10 minutes or so. Closing window prompts it to open 5 more times.
![MaxTo Error Message Windows 10](https://user-images.githubusercontent.com/52556927/70284646-b0f91780-1792-11ea-8054-8a99c97dd0d9.png)

**Comment by vegardlarsen** [comment]
@mja09006 Please see this issue for an explanation and a fix: #415.

Basically you need to Reset or re-install Microsoft Office 365, because of a bug in Windows. I am closing this issue as a duplicate.
