### ISSUE TITLE
Installer priviliges issue, can't install

### ISSUE THREAD

**Issue by b4ckup** [digitalcreations/MaxTo#514]
I just downloaded the trial installer. When I try to run it, the UAC pops up to confirm admin privileges for the installation process **twice**. After the second time grating privileges it says **Installation failed. Please re-run this installer as a normal user instead of "Run As Administrator"**. I did not run it as administrator, the executable itself needed the privileges so UAC popped up automatically. Not granting privileges in the UAC stops the installation process as well. So atm can't install MaxTo.

Win 10 Version	10.0.18362 Build 18362

**Comment by vegardlarsen** [comment]
@b4ckup Thanks for writing. Which version of MaxTo are you downloading? The installer should not require administrator access. Can you get me the installer log ([details here](https://maxto.net/documentation/troubleshooting))?

**Comment by b4ckup** [comment]
Product Version of the installer says 2.0.1. 
Unfortunately no log is written, most likely because the installation fails before logging is set up

**Comment by vegardlarsen** [comment]
This sounds very strange to me, as the installer should not require admin privileges under any circumstances that I am aware of. 

- Is the installer digitally signed by Digital Creations AS?
- Where did you download it from?
- Is the file `%LocalAppData%\SquirrelTemp\SquirrelSetup.log` empty on your machine?

**Comment by b4ckup** [comment]
- yes it is signed by Digital Creation AS
- I did download it from [https://maxto.net/en/release/2.0.1/download](https://maxto.net/en/release/2.0.1/download)
- there is no Directory **%LOCALAPPDATA%/SquirrelTemp**
- there is also not SquirrelTemp directory in the LOCALAPPDATA of my admin account
- in fact there is no SquirrelTemp directory in %LOCALAPPDATA% for any of my accounts
- it might be relevant that I am on a windows user that has admin privileges
  
If this is some strange one time error you don't have to bother fixing. I just filed this issue to let you know, because an installation bug can maybe cost you some users and some potential licensing revenue.

**Comment by b4ckup** [comment]
LOL I just came across [this stackoverflow thread ](https://stackoverflow.com/questions/20096706/how-does-windows-decide-whether-to-display-the-uac-prompt) and it says installer detection is done via filename. So I renamed the file from Setup.exe to something else and now it's working. Maybe consider renaming your installer to **MaxToSetup.exe**, this worked for me. This is a good idea anyhow so people know which installer they downloaded earlier.

**Comment by vegardlarsen** [comment]
I don't understand how that particular rename to `MaxToSetup.exe` would help (although it is obvious that it did for you), because of this requirement:

> Filename includes keywords like "install," "setup," "update," etc.

Thank you for figuring this out. We will in some manner rectify this.

**Comment by vegardlarsen** [comment]
The build process has been adjusted, and starting with 2.1.0-alpha.4 this naming convention will be followed.
