### ISSUE TITLE
not work with a computer running Windows 10 on the domain controller

### ISSUE THREAD

**Issue by widmann-it** [digitalcreations/MaxTo#515]
Hello, 
maxto does not work with a computer running Windows 10 on the domain controller. As a normal user !!  

I am installing maxto (No matter if 2.0 / 2.01 /Alp 1 /Alp 2) - the computer asks for administrator rights and then the message https://i.imgur.com/WeBqxym.png However, there is no icon in the task bar.

**Comment by vegardlarsen** [comment]
@widmann-it Thank you for reporting this issue. 

- As a sanity check, is the MaxTo icon hidden by the up arrow?
- Does the problem still occur after a reboot?
- Are you running a domain controller on the Windows 10 machine, or is the Windows 10 machine connected to a domain?

**Comment by widmann-it** [comment]
The Domaincontroleler runs on a different computer - A reboot does not help at all.
No log file is written either

**Comment by vegardlarsen** [comment]
Are there any processes running that start with `MaxTo.`? Which processes? What happens if you end all of those processes, and then start MaxTo again?

**Comment by widmann-it** [comment]
Ares no processes are shown,

**Comment by widmann-it** [comment]
Hello, 
I have reinstalled the computer with the same result. 

The user is a normal user without administrator rights. After the installation maxto could call once. The regions were also displayed. But on both screens the regions were not adjustable differently. Thereupon I let maxto run as administrator - with the result that it does not work anymore

[maxto20200305.log](https://github.com/digitalcreations/MaxTo/files/4292520/maxto20200305.log)

**Comment by vegardlarsen** [comment]
There is an exception that has crashed MaxTo two times in the log file:

```
2020-03-05 11:41:29 [Server@2.0.1.499] [Fatal] Unhandled exception "UnauthorizedAccessException" at "   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.Threading.EventWaitHandle..ctor(Boolean initialState, EventResetMode mode, String name, Boolean& createdNew, EventWaitHandleSecurity eventSecurity)
   bei MaxTo.Core.EventWaitHandleFactory.For(String name)
   bei MaxTo.Server.Program.<Main>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MaxTo.Server.Program.<Main>(String[] args)"
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "MaxTo-9644" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.Threading.EventWaitHandle..ctor(Boolean initialState, EventResetMode mode, String name, Boolean& createdNew, EventWaitHandleSecurity eventSecurity)
   bei MaxTo.Core.EventWaitHandleFactory.For(String name)
   bei MaxTo.Server.Program.<Main>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MaxTo.Server.Program.<Main>(String[] args)
```

I am uncertain what causes it. Can you try updating to [version 2.1.0-alpha.3](https://maxto.net/release/alpha)?

From the logs it also appears as if MaxTo is set to start as administrator, but that access was denied (either by you or the system settings).

**Comment by vegardlarsen** [comment]
@widmann-it Are you still experiencing this problem? 

From looking at this; this can be either of two things:

1. A timing issue.
2. A rights issue, where the normal user account does not have access to the elevated user's tokens. 

Can you please get back to me with some details about your setup, specifically user rights and how you elevate?

**Comment by widmann-it** [comment]
The problem still exists - even under the current alpha version. As an administrator everything runs fine. Only as a normal user not. There is always the message that the program has already been started. After 5 to 10 attempts the program is loaded without error message but I can't save regions

**Comment by vegardlarsen** [comment]
@widmann-it Could there be "remnants" of MaxTo running as admin when you are starting the normal version? Can you check to see if there are any MaxTo processes running (using Task Manager, under Details) before you start the normal process?
