### ISSUE TITLE
"Move window down" recipe miss hotkey assignments in MaxTo 2.1.0-alpha2

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#516]
**Describe the bug**
"Move window down" recipe miss hotkey assignments in MaxTo 2.1.0-alpha2.

**To Reproduce**
1. Fresh install MaxTo 2.1.0-alpha2.
2. Go to recipes
3. Select recipe "Move window down"
4. Select Hotkey in menu
5. See error that no key is assigned

**Expected behavior**
Should work, like "Move window left".

**Screenshots**
[711](https://user-images.githubusercontent.com/1430997/70838098-ec38bd80-1e06-11ea-8a6c-a113587f4de4.png)

**System information:**
 - Windows version: 10 build 18362.535
 - MaxTo version 2.1.0-alpha2

**Comment by vegardlarsen** [comment]
It appears that "Down" is simply missing from the list of possible keys. We will fix this.

**Comment by thewavelength** [comment]
Is it possible to differentiate between Return (below Backspace) and Enter (Numpad) and to add those two options as hotkey?

**Comment by vegardlarsen** [comment]
@thewavelength Unfortunately not. At the level we are listening for hotkeys, they are represented as the same value ([`VK_RETURN` from the documentation](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)).

**Comment by vegardlarsen** [comment]
This has been fixed and will be in 2.1.0-alpha.3.
