### ISSUE TITLE
Hotkey overview missing in MaxTo version 2.1.0-alpha2

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#517]
**Describe the bug**
Hotkey overview missing in MaxTo version 2.1.0-alpha2. There is no simple overview anymore which hotkeys are assigned to which recipes. One starts to forget hotkeys here and then. The list from version 2.0.x was incredible useful.

**To Reproduce**
1. Fresh install MaxTo 2.1.0-alpha2.
2. Go to recipes
3. See missing hotkeys in overview list

**Expected behavior**
![713](https://user-images.githubusercontent.com/1430997/70838193-679a6f00-1e07-11ea-9ce9-237c9ee32727.png)

**Screenshots**
![712](https://user-images.githubusercontent.com/1430997/70838191-61a48e00-1e07-11ea-9ad2-5d406f98c71a.png)

**System information:**
 - Windows version: 10 build 18362.535
 - MaxTo version 2.1.0-alpha2

**Comment by vegardlarsen** [comment]
I agree that this would be useful to display (more useful than the current subtitle), so I'll work on getting this to show more useful information.

It was removed because we now have multiple trigger types, and we'll need to account for all of them.

**Comment by vegardlarsen** [comment]
![image](https://user-images.githubusercontent.com/436508/77825579-75e86e80-710a-11ea-9515-5da41b0aef23.png)

I've just implemented these changes, along with creating summaries of the most common (and useful) parameters to the triggers and ingredients. It does take up a bit more vertical space, but I think it strikes a nice balance between readability and density.

Will be in 2.1.0-alpha.4.
