### ISSUE TITLE
Some hotkeys throw an error in log

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#518]
**Describe the bug**
Using some hotkeys is without effect because an Exception is thrown.

**To Reproduce**
1. Register Recipe with Hotkey `WIN + ALT + Numpad0`
2. Use it

**Expected behavior**
Should work.

**System information:**
 - Windows version: 10 Pro 1903
 - MaxTo version 2.1.0-alpha2
- Ultra-wide monitor (3840x1600 with 125% Scaling)

**Additional context**
[MaxTo-extract.log](https://github.com/digitalcreations/MaxTo/files/3972639/MaxTo-extract.log)

Maybe this is related to #516?

**Comment by vegardlarsen** [comment]
Using the same hotkey as above no longer crashes in internal builds, so I assume this has been fixed as a side effect of #516. Closing, but please re-open if this should happen after 2.1.0-alpha.3.
