### ISSUE TITLE
Won't install (or do anything) on Vista SP1

### ISSUE THREAD

**Issue by simplyeffectiveweb** [digitalcreations/MaxTo#52]
Im on Vista SP1 (yes, I know), and Maxto installation is not working. As follows:

    Downloaded from Maxto site (Maxtoseetup-2015-02.exe)
    Running program results in nothing (as in nothing happens, no dialgue boxes, no errors shown)

This is without question a Maxto installation issue. I use a variety of software and test others. So software gets installed with reasonable frequency. (and system admin is done to virus check, windows updates, etc). Sometimes threads like this seem to get diverted by semantics (just saying). Even today two other programs installed fine.

I'm not going to go further with debugging this because these situations normally result in a circle of obvious Windows questions and trying stuff that go nowhere. I'm happy my system works and won't change it for this program (no offence intended, just the way Windows makes people think). However, If a solution or update becomes available, I'll happily try again,

**Comment by vegardlarsen** [comment]
I'm downloading a Vista SP2 build now, and I'll install it in a VM for testing to figure out what is happening.

**Comment by vegardlarsen** [comment]
I haven't yet determined if this is the case, as I am still downloading the installer of Vista, but it seems .NET Framework 4.5 is not supported on Windows Vista SP1. You need SP2. This could very well be what is stopping the installer. [Details](http://www.microsoft.com/en-us/download/details.aspx?id=30653)

**Comment by vegardlarsen** [comment]
The next version of the installer will block installation attempts from Windows Vista SP1 or lower. I'll be updating the website shortly as well. My suggestion: update to SP2 (or even better Windows 8.1)! :)

**Comment by simplyeffectiveweb** [comment]
Yep you'r right. I'm a .NET dev(ish) and if 4.5 is required it won't work on anything pre-Vista SP2. Thanks for looking into this.
