### ISSUE TITLE
config.json not written on first start when not changing settings

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#520]
**Describe the bug**
Even though only starting MaxTo 2.1.0-alpha2 on a fresh installation and clicking through the "register product" or "use 30-day trial" and applying a region seems to work, no `config.json` is written. This causes MaxTo forcing one to go through the process again on every start. Only changing something in the settings causes MaxTo to write the configuration file.

**To Reproduce**
1. Fresh install MaxTo 2.1.0-alpha2 with removing old version (and config files) before
2. Start MaxTo, not changing settings
3. Close MaxTo
4. See that no `config.json` file is present
5. Start MaxTo to realize you have to go through first initialization screen again

**Expected behavior**
`config.json` should be written in all scenarios to avoid the user having double the work.

**System information:**
 - Windows version: 10 Pro 1903
 - MaxTo version 2.1.0-alpha2
- Ultra-wide monitor (3840x1600 with 125% Scaling)

**Additional context**
I tested this on two different machines with the same system configuration. Same behaviour.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. I have made the necessary changes and they will be in 2.1.0-alpha.3.
