### ISSUE TITLE
Expand window to region next to it

### ISSUE THREAD

**Issue by ebelanger** [digitalcreations/MaxTo#522]
**Is your feature request related to a problem? Please describe.**
I have an ultrawide monitor with 3 regions mostly for centering the "main" window I focus on.  Depending on the application, I would like to expand the window to the left or right region to optimize the space used.

**Describe the solution you'd like**
The behavior would be similar to swapping windows with their neighbors, but instead will maximize the window with the other region, spanning 2 regions.  Doing this multiple times would continue expanding the window to regions.

I would probably add 2 new options to the "move window" ingredient, one to maximize into the target region and one to minimize away from the region.

**Comment by vegardlarsen** [comment]
@ebelanger This feature is actually in version 2.1.0-alpha.2. Look at the "Expand edge" and "Contract edge" commands. I am closing this issue as we already have it :)
