### ISSUE TITLE
MaxTo 2.0.1 stable conflicting with windows GameBarFT.exe

### ISSUE THREAD

**Issue by tauCete** [digitalcreations/MaxTo#526]
![maxto and gamebarft error](https://user-images.githubusercontent.com/23044275/71757276-54e4ea00-2e49-11ea-9aa3-d5eb93932a4c.png)

MaxTo seems to keep running most times the popup crash message happens, but sometimes I need to restart maxto manually.  image of the error message is attached.  This happens when MS word is launch consistently.

**Comment by vegardlarsen** [comment]
@tauCete This is an instance of issue #415. Please see that issue for instructions. `GameBarFT.exe` seems to be related to Xbox, so resetting those packages in Windows should help.

I am closing this issue as a duplicate.
