### ISSUE TITLE
Install prevented due to .NET version

### ISSUE THREAD

**Issue by MavriGata** [digitalcreations/MaxTo#530]
I am attempting to install and get the error regarding .NET version 4.7.2 is required.  

I looked at the files under Microsoft.NET/Framework64/v4.0.30319
The DLL files say that the version is 4.7.2556

It is a work computer so I do not have admin rights to update .NET

Log file attached.

[maxto20200122.log](https://github.com/digitalcreations/MaxTo/files/4100132/maxto20200122.log)

**Comment by vegardlarsen** [comment]
@MavriGata I am not sure that file version is actually .NET Framework version 4.7.2.

[Microsoft's guidance on determining the version of .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) is quite detailed, can you try out their instructions and see?

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback.
