### ISSUE TITLE
Avid Media Composer 2019 conflicts with MaxTo

### ISSUE THREAD

**Issue by Froentin** [digitalcreations/MaxTo#531]
**Describe the bug**
When MaxTo is executed on windows 10 Pro, Avid Media Composer 2019 can't be fully launched. It craches at "Initializing OpenGL effects".

**To Reproduce**
1. Let MaxTo executed.
2. Click on Avid Media Composer 2019.
3. Wait the initialisation of the software.
4. At the "Initializing OpenGL effects" loading, software crashes.

**Expected behavior**
I'm expected no crash of Avid Media Composer 2019

**System information:**
 - Windows version: 10 pro (build : 1903 ; version 18362.592)
 - MaxTo current version up to date (27.01.2020)

**Comment by vegardlarsen** [comment]
Can you get me the name of the running process? You'll find it in Task Manager, under Details.

**Comment by vegardlarsen** [comment]
I can not reproduce this locally with Avid Media Composer downloaded and installed as of today. Closing issue.
