### ISSUE TITLE
Display Windows 10 Virtual Desktops side by side

### ISSUE THREAD

**Issue by inovitae** [digitalcreations/MaxTo#532]
**Is your feature request related to a problem? Please describe.**
I just bought an ultra wide screen (49") and I would like to see the Virtual Desktops side by side on the same screen. Like this I could e.g. share one of the two virtual desktops and continue working on the other...

**Describe the solution you'd like**
Being able to show 2 or more Windows 10 Virtual Desktops on the same screen

**Describe alternatives you've considered**
A split screen is of course already available but when screen sharing like in Skype it would try to share the whole screen not the area

**Comment by vegardlarsen** [comment]
I like this idea, but at the moment it is not technically possible to do. Microsoft has a very limited API surface for their virtual desktops (so small that it is actually inadequate for what MaxTo does currently, and we have resorted to using undocumented APIs). I have spoken to the devs working on the virtual desktop feature at Microsoft (this was a good while ago), and they did not have plans to extend the API surface.

Therefore, I am closing this issue as it just isn't possible to do.
