### ISSUE TITLE
too many errors in simplified Chinese in the software

### ISSUE THREAD

**Issue by le0d0** [digitalcreations/MaxTo#533]
I like this softeware a lot, but simplified Chinese translation has too many errors. I am chinese, i can help you correct it.
If you need my help, send me a email: `<email removed>`

**Comment by vegardlarsen** [comment]
Thank you for the feedback. We used a professional translation company for this translation. It is however up for modification at https://maxto.net/translate. Feel free to fix any issues you find with it and it will be included in the next update.

PS! I've removed your e-mail address from this public forum.

**Comment by le0d0** [comment]
Thanks, glad to know that.

Vegard Andreas Larsen <notifications@github.com> 于 2020年1月30日周四 下午5:03写道：
