### ISSUE TITLE
Incompatible with Windows Terminal

### ISSUE THREAD

**Issue by TMily** [digitalcreations/MaxTo#534]
**Describe the bug**
Incompatible with Windows Terminal

**To Reproduce**

when maxto runing Windows Terminal crash

**System information:**
 - Windows version: Win10 1909 18363.592
 - MaxTo version: 2.1.0A3
 - Windows Terminal version: 0.8.10261.0 from MSStore

**Additional context**

Application  Error Event:

> 错误应用程序名称: WindowsTerminal.exe，版本: 0.8.2001.26001，时间戳: 0x5e2e5240
错误模块名称: InputHost.dll，版本: 10.0.18362.387，时间戳: 0x1217c36e
异常代码: 0xc0000409
错误偏移量: 0x0000000000041a73
错误进程 ID: 0x37ac
错误应用程序启动时间: 0x01d5d8ce8abcecf5
错误应用程序路径: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
错误模块路径: C:\Windows\System32\InputHost.dll
报告 ID: 1b13bfdf-f337-497d-bbe0-7bb9f7c8819b
错误程序包全名: Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe
错误程序包相对应用程序 ID: App

Windows Error Reporting:

> 故障存储段 1633211405700529229，类型 5
事件名称: MoBEX
响应: 不可用
Cab ID: 0
问题签名:
P1: Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 0.8.2001.26001
P4: 5e2e5240
P5: InputHost.dll
P6: 10.0.18362.387
P7: 1217c36e
P8: 0000000000041a73
P9: c0000409
P10: 0000000000000007

**Comment by vegardlarsen** [comment]
Thank you for your report. We have [added Windows Terminal to our compatibility shims list](https://maxto.net/en/shim/windows_terminal).

Can you in MaxTo's Settings, go into Compatibility and click "Check for updates"? The afterwards, restart Windows to make sure all changes have taken effect?

Please do let me know if this solves the problem on your machine.

**Comment by TMily** [comment]
new compatibility shim work well thanks
