### ISSUE TITLE
Maximized window isnt "real maximized"

### ISSUE THREAD

**Issue by GronbergInfo** [digitalcreations/MaxTo#536]
Hi.
I just found this software today after buying a samsung 49" ultra wide screen 5120x1440 screen.

When i maximize a window into the region (works as expected).

For windows, at first it gets the maximized icon windows 10 draws, but then it changes to restored icon, but the window is maximized to my region.

But windows gets a resize cursor in the top or bottom, this causes me to resize the window instead of selecting a tab in firefox (latest)

Is it possible to get the maximized windows not getting this 1-2 px edge?

**Comment by vegardlarsen** [comment]
That's the monitor I just got for my home office. Great monitor! :)

The problem about letting the window become "maximized" (in that it gets a restore button), is that it will screw up the window borders of the window, which is really ugly. Quite simply, allowing the restore button to show triggers a whole bunch of other stuff that you don't need. I remember I experimented with this back when I initially made MaxTo, so I am a little short on details of exactly what happened.

That means that unfortunately I don't think this is possible to do.
