### ISSUE TITLE
Very Weird Error Popping Up all of a sudden

### ISSUE THREAD

**Issue by gte619n** [digitalcreations/MaxTo#537]
**Describe the bug**
After the latest Windows Update, I get this error message popping up time after time.

![image](https://user-images.githubusercontent.com/223900/74480113-54933200-4e7e-11ea-88f9-a3e250484f6e.png)

**Comment by nevilex** [comment]
Same issue. Started happening after latest major Windows 10 update yesterday.

**Comment by vegardlarsen** [comment]
Long answer: see #415 for a full explanation.

Summarized: re-install Dell Update and run the PowerShell snippet from that issue as admin.
