### ISSUE TITLE
Full Screen Mode Inside the Region

### ISSUE THREAD

**Issue by IvanChernyshov** [digitalcreations/MaxTo#538]
Hello,

I prefer to use some applications in the fullscreen mode; however, there is no way to restrain them to a specific area. It would be great to see this feature in MaxTo.

Many thanks for the great tool!

**Comment by vegardlarsen** [comment]
Thank you for the request. This is one of our most requested features (see e.g. #388, read more there for details), but it is very difficult to do, and therefore we have postponed it for a long time.

I am closing this issue as it is a duplicate.
