### ISSUE TITLE
Since restartr today big error....

### ISSUE THREAD

**Issue by dexnetz** [digitalcreations/MaxTo#539]
app version: 2.0.1
![image](https://user-images.githubusercontent.com/20894177/75150262-4d80e500-5704-11ea-8bb7-9c928b6bb332.png)

**Comment by dexnetz** [comment]
this is my little problem, this msg comes somtimes 10 times, in a min.

**Comment by vegardlarsen** [comment]
Please see #415. There is a specific note towards the end of that thread on how to fix LocalBridge.exe errors.

I am closing this as a duplicate.
