### ISSUE TITLE
Steam Client not recognized

### ISSUE THREAD

**Issue by Fracture98** [digitalcreations/MaxTo#54]
I've had problems with the Windows Steam client before with windows managers, so it's clearly doing something funky.

Snap to region doesn't work with this particular app, though Windows snap to screen edge does work.

Not a huge problem, but it'd be nice to have it recognized.

(Bought a license within my first 60 seconds of the trial :-) )

**Comment by vegardlarsen** [comment]
Good to hear that you like the app.

I'll probably end up adding Steam to an ignore list of some sort in the next release, so you'll be notified why it is happening.

**Comment by vegardlarsen** [comment]
So this is a hard nut to crack, apparently. Steam does not respond to window messages, and even with inspector tools I cannot get any information about the Steam window. This means that I won't even be able to add Steam to MaxTo's ignore list, as we can't even get the name of the process running it. I will look into ways in which we can enumerate processes instead of enumerating windows, but I suspect if you can't get hold of its window, you can't get hold of its process either.

**Comment by Fracture98** [comment]
Well, don't worry about it too much. A few interesting things I've noticed - it does respond to CTRL-Windows-Left/Right/Up/Down - sometimes ;-)

It also seems to be responding to some drag to edge commands and maximize to region.

The only thing I've changed is turning off all checkboxes in Options/Windows Snap/Snap to.

I have my secondary monitor divided vertically, then the left region divided once horizontally. I am able to Ctrl/Win/Left to move Steam to the small region, and Ctr/Win/Down to drop it to the other small region. If I try Ctr/Win/Right, it refuses to return to the half-screen region (though there is a bit of 'flashing').

Anyway, I'd be fine if you drop this to low priority. It's working 'well enough' for the amount I move this particular app. If you're curious, I could probably whip up some screen recordings to show you how it's reacting.

**Comment by rappo** [comment]
I know this is a 2 year old request, but it affects me as well. I would love to be able to control Steam with MaxTo.

**Comment by vegardlarsen** [comment]
Unless Steam changes how it operates, this appears to be impossible to fix from our end.

**Comment by rappo** [comment]
@vegardlarsen fair enough. To your previous point, you can try reporting the issue here: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by vegardlarsen** [comment]
This is no longer relevant. The Steam client now works well with MaxTo. Closing this issue.
