### ISSUE TITLE
Error message when running MaxTo & Spotify

### ISSUE THREAD

**Issue by tfp1** [digitalcreations/MaxTo#541]
MaxTo Version: 2.0.1 
Spotify Version: 1.1.27.472.gf6574b97 (Microsoft Store version)

# Steps to Reproduce
1. Launch MaxTo
2. Launch Spotify
3. Observe error message

# Alternative Steps
1. Launch Spotify
2. Launch Maxto
3. Select the spotify window
4. Observe error message

![](https://p193.p3.n0.cdn.getcloudapp.com/items/KouW4xy2/Image+2020-03-07+at+8.56.27+AM.png?v=16efb0eb3ffa95de5b2cf477743235e9)

**Comment by vegardlarsen** [comment]
On my phone, but please see issue #415 for workaround.
