### ISSUE TITLE
Error with MaxTo.hook.x64.dll on recent Windows build

### ISSUE THREAD

**Issue by soleroitsolutionsltd** [digitalcreations/MaxTo#542]
**Describe the bug**
Error with MaxTo.hook.x64.dll on recent Windows build - reported as invalid 0x000012f

**To Reproduce**
Launch MaxTo

**Expected behavior**
Application working without error message

**Screenshots**
https://i.imgur.com/vhYxEvE.jpg

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 2.0.1]

**Additional context**
Happening will all our machines...

**Comment by vegardlarsen** [comment]
Thank you for writing. This is a version of issue #415. Please see that issue for a workaround (the workaround for LocalBridge.exe is different from most other programs).

Closing this issue as a duplicate.
