### ISSUE TITLE
Breaks Assetto Corsa Launcher

### ISSUE THREAD

**Issue by d3relict** [digitalcreations/MaxTo#544]
**Describe the bug**
Interferes with Assetto Corsa Launcher, which tries to create a full screen window, but fails (gets resized), then repositions and the application crashes

**To Reproduce**
1. Install Assetto Corsa
2. Start the game
3. Sometimes a race needs to be started and exited

**Expected behavior**
Game window allowed to enter full screen dimensions

**Screenshots**
did not make any yet

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1

**Additional context**
n/a

**Comment by vegardlarsen** [comment]
@d3relict I think this can be fixed with a compatibility shim. Can you get me the name of the process (with MaxTo not running)? You'll find it in Task Manager, under Details.

**Comment by d3relict** [comment]
hey @vegardlarsen, if i understood you correctly, the name of the process is AssettoCorsa.exe. it also launches acs.exe which is the simulation part, it had no issues so far, but might be good to add as an exception as well. in case i missed your meaning, please help me find the info you are looking for :)

**Comment by vegardlarsen** [comment]
That was correct. Can you try opening Notepad (or any other text editor you may prefer), and open the file `%LocalAppData%\MaxTo\shims.json` (that is a valid file path, even though it may not look like it).

In that file, copy and paste in this snippet near the end:

```
  {
    "id": "assetto_corsa",
    "descriptions": {
      "en": {
        "title": "Assetto Corsa",
        "subtitle": "Prevent crashes",
        "description": ""
      }
    },
    "iconUrl": null,
    "url": null,
    "canDisable": true,
    "defaultEnabled": true,
    "ignore": false,
    "disableSubclassing": true,
    "disableSnapping": false,
    "disableTransparency": false,
    "emulatesMaximize": false,
    "windowClasses": [],
    "processes": ["AssettoCorsa"]
  }
```

You'll need to look at the structure of the file, insert a comma at the correct place, and then save the file. Afterwards; you need to restart both MaxTo, and then try launching Assetto Corsa again.

If that doesn't work (it will), you can try setting `disableSubclassing` to `false` and `ignore` to `true` instead.

Please let me know how this works out, so I can add it to the official set.

**Comment by d3relict** [comment]
thanks, it worked perfectly, now i have proper fullscreen without crashes and/or unwanted resizing.
also thank you for the info, now i can provide better reports in case i have other issues, and give you the proper json object to fix it :)

**Comment by vegardlarsen** [comment]
Thank you for your report. I have added this to the official shims list, and it will be automatically reloaded the next time you start MaxTo. :)

Closing issue.
