### ISSUE TITLE
SETTING - [x] Enable Default Window Maximize Function

### ISSUE THREAD

**Issue by BlackOpzFX** [digitalcreations/MaxTo#546]
**Is your feature request related to a problem? Please describe.**
Nope. Not a problem just a request.

**Describe the solution you'd like**
Maxto allows me to use it without touching the keyboard UNTIL I need to maximize the window. A setting that enables the default maximize icon/action would allow you to use the program for the majority of the day without using the keyboard. During the day I switch and maximize apps constantly and it always interrupts my flow to have to reach for the keyboard when I could just click the maximize (I LOVE the double-click to space dock so I wouldn't miss it).

**Describe alternatives you've considered**
1) Adding a [x] Enable Default Window Maximize Function
2) Allow Recipes to use Mouse Buttons (without required key input)

**Additional context**
LOVE the program. The only ways I can think to improve it are....
1) Mouse Maximize
2) Hotkey to overlay the region lines and allow them to be adjusted in a LIVE view so you can actually see what will be revealed by the resized windows.

**Comment by vegardlarsen** [comment]
@BlackOpzFX MaxTo should intercept maximize events triggered by the mouse. Clicking the maximize button should normally force a window into its own region. Holding Shift while clicking the button should let it maximize normally.

You should also be able to drag and drop windows while holding Shift, to quickly preview the regions and drop a window directly into it. Are you not seeing this functionality?

Recipes using mouse buttons are not currently on our roadmap; but we may rethink that at some point.

**Comment by BlackOpzFX** [comment]
I wanted to avoid touching the keyboard. In any event I found a hack. I'm using x-mousebutton to turn a mouse wheel click into the keyboard-combo to execute the 'Maximize' for me. Works Perfectly and now I dont even have to mouse to then click the maximize icon. Click Scroll Wheel. Done.

https://www.highrez.co.uk/downloads/XMouseButtonControl.htm

**Comment by BlackOpzFX** [comment]
As far as the window region redraw I meant... Why switch to a diff screen to adjust the window borders? Why not overlay those line onto the LIVE screen (not a grey background) and allow adjustment while the window contents resize in real-time. Because the adjustment lines are a different screen it can be hard to make fine adjustments since it you're slightly 'off' you have to readjust on the grey screen again, check, adjust, check, adjust...

**Comment by vegardlarsen** [comment]
@BlackOpzFX In regards to the "Change regions" screen, we are evaluating different options here. The main complaint we've had here is that you can't see underlying window edges, so we will work to change this. Most likely this is something we'll look at for version 3.

I am closing this issue then, as far as I can see you have found workarounds for your main points?
