### ISSUE TITLE
Enhancement Request - Top/bottom border adjustment

### ISSUE THREAD

**Issue by madmann26** [digitalcreations/MaxTo#547]
**Is your feature request related to a problem? Please describe.**
Not really an issue. When you snap regions into place, the bottom border conflicts with the Windows taskbar. 

**Describe the solution you'd like**
It would be nice to have an adjustment for that.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by vegardlarsen** [comment]
@madmann26 Are you saying that the "Change regions" window overlaps with the Windows taskbar, so that you can no longer see the taskbar?

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback.
