### ISSUE TITLE
Regions do not take into account Taskbar's size

### ISSUE THREAD

**Issue by lusham** [digitalcreations/MaxTo#550]
I'm using horizontal split for two regions and on one of my two laptops (both are used with the same external monitor) the Windows Taskbar is not taken into account and windows are cropped when moved to regions.

See that on the screenshot there is no status bar for MS word and Chrome is cut as well. 

![image](https://user-images.githubusercontent.com/32714850/80010201-fad46700-84c1-11ea-9e89-5df9697cf87c.png)

If I change the height of the Taskbar windows are redrawn correctly:
![image](https://user-images.githubusercontent.com/32714850/80011417-c1046000-84c3-11ea-84cc-4a3c21be24e1.png)

However, it happens again in the next move to the region:

![image](https://user-images.githubusercontent.com/32714850/80011500-db3e3e00-84c3-11ea-8899-c4f745db0c0f.png)

This is annoying for apps like MS Word and Visual Studio where you don't see the status bar and is a blocker for messaging apps like Telegram or Whatsup Web (in a browser) because the area where you type and send a message is not visible.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. I can see from your screenshots that something is wrong here; but I am not entirely sure what it is.

I am able to reproduce this locally after some fiddling:

1. Place Notepad in a full-height region
2. Resize taskbar to be taller
3. Place Notepad in the same region.

I am investigating.

**Comment by vegardlarsen** [comment]
Thank you for letting me know about this issue. I believe I have been able to fix this for version 2.1.0-beta.1. Please watch out for that release shortly.

**Comment by vegardlarsen** [comment]
@lusham Was this issue fixed for you in 2.1.0-beta.1?

**Comment by lusham** [comment]
@vegardlarsen, I could not reproduce it for some time already so it seems fixed. Thanks!
