### ISSUE TITLE
2.1.0-alpha4 Certain applications do not snap to regions

### ISSUE THREAD

**Issue by roosmsg** [digitalcreations/MaxTo#551]
Explorer and certain other applications do not snap to regions. They disappear instead. It's like they minimize without any animation. Upon reopening the application, the app window appears resized and in the top left corner of the screen. Snapping seems to work for other applications.

Applications I have tested and do not work:
- Explorer.exe
- Outlook Office 365
- Notepad++
- MS Internet Explorer

Applications I have tested and do work:
- Chrome
- Notepad
- Evernote
- Sublime Text
- Spotify
- MS Edge

System information:
 - Windows version: 10
 - MaxTo version: 2.1.0-aplha4 

Things I have tried to solve the problem:
- Reset config
- Reinstall
- Reboot

**Comment by vegardlarsen** [comment]
@roosmsg Thank you for your report.

When you say "snap to regions", are you using drag while holding Shift, click to maximize or keyboard shortcuts?

Does the problem still exist after rebooting?

**Comment by roosmsg** [comment]
I use Shift when I try to snap to regions. Click to maximize sometimes does work, but not always (for the same applications I have mentioned above).

The problem still exists after rebooting. 

Perhaps I should mention that I keep the window transparency behavior off, as that has never worked properly for me.

**Comment by vegardlarsen** [comment]
While you are snap-dragging, do you see a preview window indicating where the window will be placed?

**Comment by roosmsg** [comment]
I see no preview window for those particular applications. 

The problem exists from 2.1.0-alpha2 and up. 2.1.0-alpha1 works as expected (with preview window).

**Comment by roosmsg** [comment]
Just did a clean install of Windows 10 Pro on another pc. Using 2.1.0-beta1, the problem persists.

**Comment by vegardlarsen** [comment]
I am unfortunately unable to reproduce this. I've tried on Windows 10 build 1909 and 2004, and it works with all the software on your list. I have seen instances where e.g. 64-bit applications wouldn't work, while 32-bit applications worked, but that isn't the case here. There is a good mix between 64- and 32-bit apps on both lists.

**Comment by roosmsg** [comment]
Just build a new pc. Did another clean install of Windows and boom... same problem. Does it have something to do with my version of Windows? NL-NL?
![Knipsel](https://user-images.githubusercontent.com/19514981/81320597-bc2dd780-9091-11ea-9836-e3b042f19d73.PNG)

**Comment by vegardlarsen** [comment]
@roosmsg Thank you for being thorough on this. It should not be a problem with your version of Windows, especially not your language settings. This is the latest, stable version of Windows 10, and it should work just fine with MaxTo.

Have you tried with the 2.1.0-beta.1 release? I don't believe it contains any changes that may affect this, but it is worth a try. 

Just to be clear, what you are seeing is the following:

1. You open an affected application.
2. You move that window while holding Shift.
3. When you release the mouse button, the window disappears?

**Comment by roosmsg** [comment]
Those steps you describe are exactly what happens. Step 4: I reopen Windows Explorer (same as choose previous window size) and the window appears resized in a previous region. That's usually the top left corner of the screen.

I was going to comment with the text below, but then I restarted MaxTo a couple times and noticed all my problems had gone. I keep testing and report back here when I notice anything different.
> I am on 2.1.0-beta.1 right now and notice a few new things:
> 
> 1. the issue also occurs when I click the top bar to maximize, but only on the second time I do this.
> 2. the preview window (indicating where the window will be placed) does not function properly. Nothing shows up for the affected applications. Other applications work fine.
> 
> Windows transparency still doesn't function properly, so that's turned off.

**Comment by vegardlarsen** [comment]
@roosmsg I think I have managed to isolate (and fix) this problem. I am building it now, but if you send me an e-mail at support@maxto.net, I'll be able to send you a private build that will hopefully solve your issues.
