### ISSUE TITLE
MaxTo forgets configured region preset after restart

### ISSUE THREAD

**Issue by sauer-m** [digitalcreations/MaxTo#552]
**Describe the bug**
After a System restart the saved region preset is present but not active. It needs to be activated in the region settings after the software is closed and opened again.

**To Reproduce**
1. create a template in the region settings.
2. save as preset.
3. restart software.
4. the preset is no longer active but choosable from the preset list.

**Expected behavior**
It would be helpful if the created preset is saved as default and active as soon as the software starts (e.g. on startup of OS).

**System information:**
 - Windows version: [Win 10 1809]
 - MaxTo version [2.0.1]

**Additional context**
log attached:
[maxto20200426.log](https://github.com/digitalcreations/MaxTo/files/4535444/maxto20200426.log)

**Comment by vegardlarsen** [comment]
Can you try to use the 2.1.0-alpha.4 preview release to see if this problem goes away? [Downloads are here](https://maxto.net/release/alpha).

If you are unwilling to try preview software, the problem can be fixed by changing your monitor identification in the settings to "By number".

**Comment by sauer-m** [comment]
Wow, that was quick, thanks.
Yes, that solved the problem.
The Beta is very laggy (unresponsive and slow) on my System. Also the language setting doesnt work (Software is in german despite I choosed english).

I will also try to change the monitor identification in the current stable.

**Comment by sauer-m** [comment]
Seems to I'm not able to deinstall the current beta. The uninstaller cant find "update.exe" in "C:\Users\%user%\AppData\Local\MaxTo\"
Therefore I also cant install the stable release.

**Comment by sauer-m** [comment]
using the 2.1.0-alpha.4 preview release solved the problem, as well as changing the monitor identification in the settings to "By number".

**Comment by vegardlarsen** [comment]
@sauer-m Yes, there are some missing translations for the preview releases. See [maxto.net/translate](https://maxto.net/translate) to help out. I see German is currently at 59%.

**Comment by sauer-m** [comment]
I will have a look. What I was meaning was: 
Language is set to "english" but displayed language is german.

**Comment by sauer-m** [comment]
Hm, so Im back in stable version 2.1.0 as the beta messed up my windows. Changing the display detection settings to "By Number" didnt work. After e restart the reagion settings are gone, unfortunately :/

**Comment by vegardlarsen** [comment]
What happened in the beta that "messed up your windows"?

**Comment by sauer-m** [comment]
The window-transparency changes with every move of a window. As far as I remember even if maxto is closed.(See screens attached).
Sometimes I also get this Net framework exception (attached).
Also, during installation my sistem get really slow and laggy. Last time it was a pain to uninstall MaxTo beta. I cloudnt run the uninstaller because files were missing.
I make further investigations when I have time again.
![grid_snap_error](https://user-images.githubusercontent.com/16384794/81384170-90eacd00-9111-11ea-9b80-e2b66619a731.png)
[grid_snap_error.txt](https://github.com/digitalcreations/MaxTo/files/4597665/grid_snap_error.txt)
![grid_snap_framework error](https://user-images.githubusercontent.com/16384794/81384177-92b49080-9111-11ea-9914-ff2a1cee8e0a.png)
![menu_error](https://user-images.githubusercontent.com/16384794/81384181-934d2700-9111-11ea-9e2f-1ab9aa3c6cfc.png)
![transparency2](https://user-images.githubusercontent.com/16384794/81384182-934d2700-9111-11ea-92b3-fb193d9ed440.png)
![transparency3](https://user-images.githubusercontent.com/16384794/81384187-93e5bd80-9111-11ea-9cd5-a7ec10bb5373.png)
![transparency4](https://user-images.githubusercontent.com/16384794/81384189-947e5400-9111-11ea-8e5d-76639413c8ba.png)

**Comment by vegardlarsen** [comment]
Could you please send me your log files from when these crashes happen (either here or at support@maxto.net)? The errors do not appear to have been logged to our online crash reporting. You can find your log files by hitting Win+R, typing `%AppData%\MaxTo` and look for files ending in `.log`.

I am looking into the crash data you sent over in regards to the .NET Framework exception.

**Comment by vegardlarsen** [comment]
After examining the crash you sent above, I think I need the log files to determine what is happening. I know it may be a long shot asking this, but were you doing anything special at the time the exception showed up?

```
System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "RegionHighlightForm".
   bei System.Windows.Forms.Control.CreateHandle()
   bei System.Windows.Forms.Form.CreateHandle()
   bei System.Windows.Forms.Control.get_Handle()
   bei MaxTo.Companion.MessageHandlers.DragWindowMessageHandler.ActInternal(String messageName, Message message)
   bei MaxTo.Companion.MessageHandlers.WindowMessageHandlerBase.Act(Message message)
   bei MaxTo.Companion.MessageHandlers.WindowMessageHandlerDispatcher.Dispatch(Message message)
   bei MaxTo.Companion.Hook.HookController.MessageSourceOnWindowMessage(Object sender, Message message)
   bei MaxTo.Core.Native.HiddenWindowMessageSource.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by sauer-m** [comment]
Im a bit busy right now, so im only able to send you the current logfile without further tests.
I attached you the whole folder. Maybe the display information help you as well.
[MaxTo.zip](https://github.com/digitalcreations/MaxTo/files/4598130/MaxTo.zip)


Due to your second question. I couldnt remember but guess not. Maybe there was an open explorer window, maybe also spotify.
As Im temporarily using another software to get my desktop splitted every test is disabling the software installing MaxTo, testing, and reverse. So I need a bit of free time to support you with this.

**Comment by vegardlarsen** [comment]
This issue with the transparency, should be OK in version 2.1.5. Please feel free to ping me @sauer-m if this is still an issue.
