### ISSUE TITLE
ninjatrader shim

### ISSUE THREAD

**Issue by Vlion33** [digitalcreations/MaxTo#553]
**Describe the bug**

when i open ninjatrader (from ninjatrader.com) all sets up ok but if i enlarge a chart window that chart locks up and subsequently have to shut down whole trading system to get it to work again

i am using windows 10 pro with latest maxto version 2.0.1 i have a full purchased version

i have read through documentation trying to figure out how to make a shim or something around it so that maxto will not affect this specific platform...any info on how to create a shim to avoid a program would be very useful to know how to do this in a fairly simple way.

thank you for any help...

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment]
@Vlion33 Have you tried NinjaTrader using [the 2.1.0-beta.1 preview](https://maxto.net/release/beta)?

**Comment by Vlion33** [comment]
the beta version fixed all those issues... thank you!
