### ISSUE TITLE
Windows resize issues using 2.1.0-beta1

### ISSUE THREAD

**Issue by marcosqlbi** [digitalcreations/MaxTo#555]
When I try to resize windows using 2.1.0-beta1, I’m not able to get the size I want, MaxTo is interfering with a regular resize operation and I have to disable it to be more productive.

1. Go on a monitor where the area is splitter in 4 identical rectangles
2. Open Notepad (or any other windows application) and move it on that screen
3. Resize Notepad trying to enlarge the size - during the movement the window is reduced and I'm not able to get the proper size

The resize operation should work without interference.
By disabling MaxTo everything returns back to normal.

 - Windows version: 10.0.18363 Build 18363
 - MaxTo version 2.1.0-beta1

**Comment by vegardlarsen** [comment]
@marcosqlbi sent me the following GIF of what happens, and gave me permission to share it here.
![ezgif com-optimize](https://user-images.githubusercontent.com/436508/81388348-79631280-9118-11ea-994a-df2a8b78d3ef.gif)

I have confirmed this bug, and am working on figuring out what exactly is causing it.

**Comment by vegardlarsen** [comment]
I have located and fixed this issue. It will be in the next release (beta.2).

**Comment by marcosqlbi** [comment]
Thanks!
