### ISSUE TITLE
Applications crashing when moving screens to different square

### ISSUE THREAD

**Issue by spectrumitteaam** [digitalcreations/MaxTo#556]
**Describe the bug**
When moving an appliction (word,excel) to another location on the monitor the appliction (word,excel) will crash. MaxTo doesn't seem to crash or store any logs about the crashing

**To Reproduce**
1) Open application
2) Move to different part of the screen

**Expected behavior**
Application window being moved to correct spot

**System information:**
 - Windows 10 1909
 - MaxTo version 2.0.1

**Additional context**
This is happening on a Surface Studio. Happens more frequently with our phone system Fuze. User will try to move a phone call to the other screen and the phone app will crash and disconnect the call.

**Comment by vegardlarsen** [comment]
@spectrumitteaam Thank you for your report. Which version of Office are you running? I just tested this here, and I can see no problems with Word or Excel 2019.

Is this an issue that happens after a while, or are there specific situations where it occurs?

I also downloaded Fuze to test it, however I do not have an account or a meeting that I can join, so I could only test it on the welcome screen. On that screen, everything seems to work with MaxTo as it should.

**Comment by spectrumitteaam** [comment]
@vegardlarsen Office 2016. The user says it happens until he restarts his computer and then it's fine for 2-3 days then everything starts acting up. I know that's not much help but I will try and see if I can figure out the problem. Thanks for your help.

**Comment by vegardlarsen** [comment]
@spectrumitteaam That makes it quite a bit harder to debug. However, I will have a try at reproducing this (and hopefully fixing it).

**Comment by vegardlarsen** [comment]
@spectrumitteaam Can you try this with MaxTo 2.1.0-beta.1, [downloadable from here](https://maxto.net/release/beta)?

**Comment by spectrumitteaam** [comment]
Yes. I will let you know thanks.

**Comment by vegardlarsen** [comment]
@spectrumitteaam 2.1.0-beta.2 is now available from the same location. I suggest trying that instead.

**Comment by vegardlarsen** [comment]
As we have no updates from @spectrumitteaam, I am assuming this has either been solved or is no longer an issue. Closing this issue.
