### ISSUE TITLE
Windows 7: Crashes every time I lock my screen

### ISSUE THREAD

**Issue by AsaAyers** [digitalcreations/MaxTo#56]
When I get up from my machine I use `<Windows>+L` to lock my screen. Every time I return and unlock I get the following and I have to start MaxTo again.

![screenshot_030115_122211_pm](https://cloud.githubusercontent.com/assets/324999/6431911/95c2ecde-c00d-11e4-9181-3bf6db53d3b2.jpg)

It doesn't provide me with any info, so I'm not clear if a bug report is really being sent or who it may be sent to.

**Comment by vegardlarsen** [comment]
Hi Asa, thanks for writing.

Unfortunately that bug report hasn't reached me. For some reason bug reports that happen on my machine are reported, but I have yet to receive a single report from a customer.

Anyhow, if this happens again, please look in `C:\Program files (x86)\MaxTo` for any files called `Exception_<something>.zip`, and e-mail them to me at support@maxto.net.

I will try to have a look at this tonight, but if it doesn't happen on my machine it will be difficult to track without the exception report.

**Comment by vegardlarsen** [comment]
Closing this as this was resolved with @AsaAyers via e-mail. Same issue as #49.
