### ISSUE TITLE
Can no longer resize windows properly while MaxTo is running

### ISSUE THREAD

**Issue by NicholasConrad** [digitalcreations/MaxTo#560]
Window resizing exhibits unusual and undesirable behavior. Exiting MaxTo restores window resizing function.

Examples of unexpected behaviors:

1) Dragging the window boarder with the resizer icon active instead of dragging the edge of the window (increasing the window size), drags the entire window (at the same, or close to the same size).

2) Dragging the window edge with the resizer icon active can make the window 'jump' to unexpected locations on the screen (possibly related to a 'snap' function?).

3) Dragging the window edge with the resizer icon active may results in the window disappearing from all monitors, such that even win key + arrow will not make it reappear as with normal windows placed outside of the visible screen area. 

Troubleshooting steps:

Closed and re-started MaxTo - No effect on issue
Restarted PC - No effect
Uninstalled and reinstalled MaxTo - No effect
Tested with both windows and Maxto window snapping on and off - same behavior in both cases

Exit MaxTo - Expected window resizing behavior restored

Win 10 Pro V1909 Build 18363.836
MaxTo V2.1.0-beta1

**Comment by vegardlarsen** [comment]
I believe we have fixed this issue for version 2.1.0-beta.2, see issue #555. Does that sound like the same issue to you?

**Comment by NicholasConrad** [comment]
Yes, this is the same issue! Sorry, I searched under open tickets before posting my bug report, I didn't think to include closed tickets too. I apologize for the duplicate issue.
