### ISSUE TITLE
Constantly get Could not execute recipe

### ISSUE THREAD

**Issue by takeoffeh** [digitalcreations/MaxTo#562]
**Describe the bug**
Very frequently when running recipes I get "Could not execute recipe"  Object reference not set to an instance of an object.

**To Reproduce**
I have my SurfaceBook 15" connected to a docking station with two other monitors connected to that.  I do undock and redock my machine occasionally.  I haven't found what causes it all the time, but I do find that I have to rebuild my recipes and re-attach keyboard shortcuts once it happens because it doesn't seem to fix itself.

I have a simple recipe to maximize the active foreground window within the current monitor.  Hooked up Windows+Alt+M as the keyboard shortcut.

Screenshot below of both the recipe and the error I get when running it.  It'll run for a while and work fine, but then something happens - either locking and unlocking computer or undocking and redocking it and somewhere there it'll stop working.  I've tried doing a maxto service restart and that generally won't fix it either

**Screenshots**

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1
![maxto_1](https://user-images.githubusercontent.com/27126254/82267623-282dfc80-992a-11ea-9937-fbc116e5870e.png)
![maxto_error](https://user-images.githubusercontent.com/27126254/82267633-2bc18380-992a-11ea-9716-5db0f1b5baa7.png)

**Comment by vegardlarsen** [comment]
Can you please try this again on [version 2.1.0-beta.1](https://maxto.net/release/beta)? I believe this has been fixed there.

**Comment by takeoffeh** [comment]
Seems much better in the 2.1.0-beta.  Thanks!
