### ISSUE TITLE
Maxto doesn't seem to build monitor dictionary until you Apply Regions through UI

### ISSUE THREAD

**Issue by takeoffeh** [digitalcreations/MaxTo#563]
**Describe the bug**
Trying to apply regions using command line fails until you apply regions through UI

**To Reproduce**

1. 1. Restart maxto using maxto service
2. 2. using command line apply regions - maxto regions apply /Monitor [SerialNumber] /Name [regionName]
3. 3. Command line gives error The given key was not present in the dictionary.
4. 4. Right-click maxto icon, select Change Regions menu
5. 5. Click Apply regions (don't have to set them)
6. Run the same command from step 2 - now it works

Something in the "Apply Regions" through the UI seems to build the monitor dictionary.  One of the main advantages of maxto is being able to run a batch file and set everything how I want without having to interact with the UI.  It's a total pain to launch that everytime there's an issue and then go back and run everything

Screenshot of my command window

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1
![maxto_cmd](https://user-images.githubusercontent.com/27126254/82268241-c078b100-992b-11ea-93a2-04fc6bc286c6.png)

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment]
Thank you for reporting this. After testing, this issue does not occur in version 2.1.0-beta.1, which you can [download from here](https://maxto.net/release/beta). Please do try and update to that version and let me know if it is still an issue for you.
