### ISSUE TITLE
Cycle presets recipe

### ISSUE THREAD

**Issue by roosmsg** [digitalcreations/MaxTo#564]
**Describe the bug**
The Cycle presets recipe does not remember the presets it should cycle through.

**To Reproduce**

1. Create new recipe
2. Give it a name
3. Add ingredient: Cycle presets
4. Choose default monitor
5. Presets: check all
6. Add trigger: Hotkey
7. Save recipe
8. Close settings
9. Press hotkey * an error message pops up or nothing happens *
10. Reopen the recipe in settings * all presets are forgotten *

**System information:**

Windows version: Win 10 1909
MaxTo version: 2.1.0-beta1

**Additional information**
Load preset recipe works fine.

**Comment by vegardlarsen** [comment]
Thank you for reporting this issue. I have found the cause, and fixed it for the next release. :)
