### ISSUE TITLE
Let region selector close with ESC key

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#565]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The new feature to automatically open the region selector for a new virtual desktop is nice. Sometimes, nothing should be changed. Or it can happen I'm pressing the wrong hotkey and opening the region selector by mistake. Pressing ESC in it should be possible to quickly close it.

**Describe alternatives you've considered**
Could use ALT+F4 but this breaks the flow with my hands.

**Additional context**
None.

**Comment by vegardlarsen** [comment]
This change will be in 2.1.0-beta.2.

**Comment by thewavelength** [comment]
This is buggy. Pressing ESC once works, after that it is impossible to ever open the region selector again until I restart MaxTo.

PS: This is probably not important but it is possible to open the settings UI twice which makes it buggy. Closing the second UI instance also will close the first one. Might be related?

**Comment by thewavelength** [comment]
Also, this is related so I am not opening a new issue, it would be cool to fully control the region selector by keyboard. E. g. pressing L or P to open the presets, navigate in the list with the arrow keys and use Enter to load a preset.

**Comment by vegardlarsen** [comment]
Please open a new issue for the Esc key issue. I don't think we will implement that form of keyboard navigation, we'll try to stick to the Windows guidelines on that.
