### ISSUE TITLE
Shims aren't installed with installer, needs internet access to download

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#566]
**Describe the bug**
[Windows Terminal](https://github.com/Microsoft/Terminal) is crashing immediately upon start when MaxTo 2.1.0-beta1 is running. The same behaviour happens with 2.1.0-alpha1/2/3 as well.

**To Reproduce**
1. Install Windows Terminal via GitHub release or Microsoft App Store (doesn't matter)
2. Start MaxTo 2.1.0-*
3. Start Windows Terminal
4. Experience the crash

**Expected behavior**
No crash.

**Screenshots**
n/a

**System information:**
- Windows version: Windows 10 1909 18363.836
- MaxTo version: 2.1.0-beta1 and 2.1.0-alpha1/2/3
- Windows Terminal version: 0.11.1333.0 and 1.0.1401.0

**Additional context**
There are no entries in the MaxTo log file regarding this crash.

**Comment by thewavelength** [comment]
Additional information: when Windows Terminal is already running before MaxTo is started, it works fine: reacting to shortcuts, snaps to regions etc.

Interesting though: when closing Windows Terminal by hand it needs waaaay longer when MaxTo is running.

**Comment by vegardlarsen** [comment]
I am not able to reproduce this locally, but we've made some fixes in beta.2 that may address this issue. Do you have your shims updated, they should contain a compatibility shim for Windows Terminal?

**Comment by thewavelength** [comment]
How I am supposed to do that? I just extracted the latest beta and let it run, so no set up was running.

**Comment by vegardlarsen** [comment]
You can update your compatibility shims from Settings, Compatibility? There should be an entry for Windows Terminal?

**Comment by thewavelength** [comment]
I'm feeling a bit stupid, ehhh... how?

![1438](https://user-images.githubusercontent.com/1430997/82448836-93064180-9aaa-11ea-9730-2a1f4ec9768e.png)

**Comment by thewavelength** [comment]
Okay... got it. It needs network. I tested it on a computer without network. Mhhmpf. Works now.

Is there a "nice" way to get the shims to a computer without network?

**Comment by vegardlarsen** [comment]
Not really. Ideally it should be bundled with the installer, but that is a bit more difficult than I would like. :)
