### ISSUE TITLE
"Last update" date is broken without internet

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#567]
**Describe the bug**
When using MaxTo 2.1.0-beta1 without internet, the "last update" date is broken.

**To Reproduce**
1. Install MaxTo 2.1.0-beta1 on a machine without internet
2. Go to the compatibility tab
3. "Last updated: 419 years ago"

**Expected behavior**
Better use something like "never"?

**Screenshots**
![1437](https://user-images.githubusercontent.com/1430997/82443230-6ef23280-9aa1-11ea-8108-d947c3ddf2e4.png)

**System information:**
- MaxTo version: 2.1.0-beta1

**Comment by vegardlarsen** [comment]
Fixed for 2.1.0-beta.2.
