### ISSUE TITLE
MaxTo only works on primary desktop in Sysinternals Desktops V2.0

### ISSUE THREAD

**Issue by bwright** [digitalcreations/MaxTo#57]
With sysinternals desktop v2.0 maxto only works on the primary desktop, and not the other 3 desktop environments.

**Comment by vegardlarsen** [comment]
If I understand how Sysinternals Desktop works, MaxTo won't work with it. MaxTo runs on the desktop where it is started (as any program does). You can't move a program between desktops; starting the same program on a different desktop actually starts a new instance of the desktop. There is no communication between programs running on the different desktops.

MaxTo relies on being able to communicate with the programs it works with. You may be able to start MaxTo again on each new desktop, but it will most likely not work. MaxTo has a built-in functionality that will only let it run once. It could be that this will stop you from running multiple copies across desktops, I simply don't know.

If you manage to start MaxTo again on a second desktop, please let me know how it works out.

**Comment by vegardlarsen** [comment]
After having examined how MaxTo prevents multiple executions of itself, I believe you can simply start a new instance of MaxTo in each extra desktop to remedy this issue.
