### ISSUE TITLE
Add "Current Window" to window selection in ingredients

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#572]
**Is your feature request related to a problem? Please describe.**
When adding some ingredients, e. g. "minimize window" or "Fit to region" either I can select all windows by not entering a search mask or only specific one. What if I want to apply an ingredient to the current window (that one that has the focus) only?

**Describe the solution you'd like**
There should be an additional filter to select the focused window.

**Describe alternatives you've considered**
No ideas.

**Comment by thewavelength** [comment]
Like it is in "Maximize to monitor" or "Center window"

**Comment by vegardlarsen** [comment]
I have fixed this for 2.1.0-beta.3.
