### ISSUE TITLE
Add "Mouse click" ingredient

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#573]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Moving a mouse is already possible. It should be possible to artifically invoke a mouse click. It would be best to let the user decide for how long the click should go or - even better - let the user decide to invoke only "mouse button down" and/or "mouse button up" for better automation possibilities.

**Describe alternatives you've considered**
An alternative could be using AutoHotKey instead of MaxTo for this. I totally understand if this request exceeds the capabilities MaxTo should have in your vision.

**Additional context**
I need this feature to select an input field in an application which is not automatically focused even when focusing the window of that given application.

**Comment by thewavelength** [comment]
When doing this, adding key down and key up should probably be easy as the same API functions can be used, just for other virtual keys.

**Comment by vegardlarsen** [comment]
I am not entirely sure how I feel about this idea, it does make sense, but it would be a very difficult way of automating tools.

It would make more sense to add a sort of "keypresses script"; however, then we'd basically be AutoHotkey.

I am closing this issue as an idea, but we may revisit this later.
