### ISSUE TITLE
"Regex" not clickable on "Window title" and "Window class"

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#574]
**Describe the bug**
I can't activate "Regex" for "Window title" nor "Window class". It works for "Process name".

**To Reproduce**
1. Try click "Regex" on either one.

**Expected behavior**
Should be activated.

**System information:**
- MaxTo version: 2.1.0-beta2

**Comment by thewavelength** [comment]
Also, when I click "Regex" on "Process name", change to another ingredient, changing back to the orignal one, alls three "Regex" checkboxes are checked.

**Comment by vegardlarsen** [comment]
I cannot reproduce this. Can you please be more specific about what happens, or export the recipe?

**Comment by thewavelength** [comment]
You can try clicking around on the checkboxes. I just found out it works sometimes, when another checkmark is set. Happens on any ingredient with the Regex option. Sadly I can't give more details as this seems totally random to me.
