### ISSUE TITLE
Error message - Could not execute recipe,  Virtual Desktops are only supported in Windows 10

### ISSUE THREAD

**Issue by mjayuk** [digitalcreations/MaxTo#579]
I've created a recipe which I hoped would allow me to move applications between virtual desktops.  However, when I run it, I receive a notice telling me that Virtual Desktops are only supported in Win 10.

**Describe the bug**

When I try and run the recipe I receive an error message which says:

Could not execute recipe
Virtual Desktops are only supported on Windows 10
MaxTo

**To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

The application in focus should move to next next Virtual Desktop
**Screenshots**

**System information:**
- Windows version: 10 Pro 1909
- MaxTo version: 2.0.1

**Additional context**

**Comment by vegardlarsen** [comment]
Have you had a chance to try this in 2.1.0-beta.2, available from [our website](https://maxto.net/release/beta)?

**Comment by mjayuk** [comment]
2.1.0-beta.2 Install failed.  I've included the log file for you.
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/4674978/SquirrelSetup.log)

**Comment by mjayuk** [comment]
I was able to install after manually deleting the folder: C:\Users\<username>\AppData\Local\MaxTo

I created a Recipe to move the window to a virtual desktop, but I still received the same error message as before - ...only supported in Win 10

**Comment by vegardlarsen** [comment]
@mjayuk I have confirmed and fixed this bug for 2.1.0-beta.3. It was caused by a bug in a library we use.

**Comment by shie-erlich** [comment]
this is still happening for me in 2.1.1 (not detecting that i'm running win10).
is there a workaround for this?

**Comment by vegardlarsen** [comment]
@shie-erlich Which specific Windows version are you running? (Hit Win+R, type `winver` to check)

**Comment by shie-erlich** [comment]
@vegardlarsen windows 10 enterprise, version 2004, build 19041.630

**Comment by QuiteStupidGull** [comment]
@vegardlarsen same problem here.
MaxTo version: 2.1.1
Windows version :  Windows 10 PRO 20H2, build 19042.630

**Comment by vegardlarsen** [comment]
@QuiteStupidGull @shie-erlich Does it go away after updating to 2.1.2 and rebooting?

**Comment by QuiteStupidGull** [comment]
Just updated and rebooted, same problem.
