### ISSUE TITLE
MaxTo crashes repeatedly and none of the system hook diagnostics succeed.

### ISSUE THREAD

**Issue by sflanagan180251** [digitalcreations/MaxTo#58]
I'm able to get the software to work, but after a while, it will crash and I'll have to run it again.  When I run the self-test on the diagnostics panel, the system hook row fails across the row.  This is happening on 2 separate machines, both of which are running Windows 8.1 64 bit.  Are there logs that are created that I can look at to see what is going on?

**Comment by vegardlarsen** [comment]
Hi Sean, I have a suspicion that this may be fixed in an internal build. Can you download and replace MaxTo.exe with [this file](https://dl.dropboxusercontent.com/u/12591686/MaxTo.exe), then start MaxTo again.

It has worked for most people I have talked to via e-mail.

**Comment by sflanagan180251** [comment]
I've installed it on the 2 machines I work with.  I have not yet seen the error that the application has crashed, but it usually takes some time before that happens. 
When I run the diagnostics, however, all 4 columns of system hooks still have x's in them and now the 32-bit keyboard shortcut also has an x.  
The keyboard shortcuts seem to work, at this point, so I'll have to keep an eye on it.

**Comment by vegardlarsen** [comment]
I am closing this then, since I haven't heard about any new crashes from you in a few days. Please feel free to comment here again if you are still experiencing crashes.

**Comment by sflanagan180251** [comment]
No crashes so far, so this should be good.
