### ISSUE TITLE
ESC key only works once to close region selector

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#580]
**Describe the bug**
Pressing ESC in the region selector once works, after that it is impossible to ever open the region selector again until I restart MaxTo.

**To Reproduce**
1. Open region selector
2. Use ESC to close it

**Expected behavior**
Region selector is still usable afterwards.

**System information:**
- MaxTo version: 2.1.0-beta2

**Comment by vegardlarsen** [comment]
I have identified and fixed the root cause of this. Will be in 2.1.0-beta.3.
