### ISSUE TITLE
Software window get black while changing places through shortcut

### ISSUE THREAD

**Issue by brunocantuaria** [digitalcreations/MaxTo#581]
**Describe the bug**
Occasionally, when switching an window from places, using a shortcut, that window turn entirely black.  The MaxTo doesn't crash and the now black window can still be switched from place to place using the shortcut, but it will remain black. The window will also keep working, I can confirm this because any shortcut from the window like saving, pause or playing music, will still occurs. Minimizing, maximizing or even closing MaxTo will not fix the issue, the only way to fix it is closing the window (with Alt+F4 or other mean, because not even the default UI appears), and then reopening the software.

It already occurred with a lot of softwares that I use, so I don't think it may be related to a specific software, but all of them are usually open when the issue happens, because usually when I'm using the computer, I'm using all of them at once: Chrome, WhatsApp for Desktop, Photoshop, Deezer and VSCode (You may assume that all of them are in the latest version, because I always keep them updated, as well as MaxTo).

Sometimes, when this error occurs, an alert message appears related to .Net Framework, saying that an exception occurred with MaxTo. Much more rare, when this error occurs, MaxTo also crashes, so I must restart it and the software which got the black screen.

In two specific situations, I could see that the window didn't really get black, but it was like the window was being printed outside the area it was supposed to be (which is the black screen), in those two cases, I could see a small part of the window's right bottom area in the black screen's top left area.

If I would estimate, I would say that the black screen occurs once at each 30 window changes. Note that, if I repeatedly change the window multiple times  (I tested up to 100 times) the error doesn't occurs, so I guess it may be a memory problem as well.

**To Reproduce**
Unfortunately, I could not detect a specific behavior that triggers this issue. 

**Screenshots**
I'll update a screenshot once this error occurs again.

**System information:**
- Windows version: Windows 10 Version 1909 (Compilation 18363.836)
- MaxTo version: 2.0.1

**Additional context**

[config.json.txt](https://github.com/digitalcreations/MaxTo/files/4691167/config.json.txt) - I saved it as TXT so I can upload it here.
[maxto20200525.log](https://github.com/digitalcreations/MaxTo/files/4691180/maxto20200525.log) - This log file is from 2 days ago, when the error occurred. It also occurred a few minutes before I started this bug report, but when I checked the today's log, it wasn't there, actually it was like the log started after the bug happened (maybe MaxTo is in fact crashing, but reloading automatically?)

**Comment by vegardlarsen** [comment]
Please do update with a screenshot if this problem does occur again. Also, it would be very interesting to see the details of that error message.

I would recommend updating to 2.1.0-beta.2, which is [available from our website](https://maxto.net/release/beta). The error in your log file should be fixed in that release, but I am not sure if that is related to the black window issue.

**Comment by brunocantuaria** [comment]
Ok. It happened again. Check the screenshots:

![black-1](https://user-images.githubusercontent.com/3237812/83178811-71830680-a0f7-11ea-8e24-2d292caab8a1.JPG)
![black-2](https://user-images.githubusercontent.com/3237812/83178808-70ea7000-a0f7-11ea-918e-6ef1a6037a26.JPG)
As you can see at above screenshots, nothing crashed and everything continues to work. I can keep moving windows across areas, even the black ones.

![black-3](https://user-images.githubusercontent.com/3237812/83178813-721b9d00-a0f7-11ea-8d5c-c4f6aad692b0.JPG)
In this last SS, I've discovered that if try to manually increase the "black window", the original window start to becoming being visible, but note that, only the visual is there, the functionality is in the actual place where the visual should be. This means that, when I click the visible close button, nothing happens, I need to click on the spot inside the black area, where the close buttons was supposed to be.

Then, I checked the MaxTo log, but it was without any reference to an error. So, I closed MaxTo, and checked the log again, and the error was there. I'm attaching it below:

[maxto20200528.log](https://github.com/digitalcreations/MaxTo/files/4697518/maxto20200528.log)

I'll update to the beta version and check if this error continues to occur.

**Comment by vegardlarsen** [comment]
Thank you for the update. The errors in your log file happen immediately after MaxTo has requested to exit, so they are unrelated.

I believe this may be resolved in 2.1.0-beta.2, as that version has made some changes to how windows are moved around.

Also, if you get the .NET Framework Exception popup again, I would really love to see the details.

**Comment by brunocantuaria** [comment]
Hi Vegard,

I'm already using the beta 2, the issue didn't happened so far, but I haven't used the computer too much since the update.

Anyway, a new issue appeared with the beta version. When resizing a window, the transparency doesn't turn back to non-transparent. Each resize will make it more transparent, as you can see at attached screenshot. The transparency will only go away after closing and reopening the window.

![ss2](https://user-images.githubusercontent.com/3237812/83334294-dd8e7780-a27b-11ea-824d-eb6d8f37b4a4.JPG)
![ss1](https://user-images.githubusercontent.com/3237812/83334295-de270e00-a27b-11ea-9c83-bcb9d22911e4.JPG)


Turning the transparency option off, will prevent the issue.

I'm attaching the logo as well:

[maxto20200530.log](https://github.com/digitalcreations/MaxTo/files/4706055/maxto20200530.log)
