### ISSUE TITLE
Trying to resize window with mouse behaves incorrectly if MaxTo running

### ISSUE THREAD

**Issue by takeoffeh** [digitalcreations/MaxTo#583]
When running MaxTo, if I try and use the mouse to grab the bottom-right corner of a window to resize it larger or smaller it often jumps around and grows and shrinks the location of the window as opposed to the size - often turning it so small that it's nearly impossible to find or moving the entire window down instead of resizing the window.

**To Reproduce**
1. Have a window that only takes up something like 1/4 to 1/2 your screen
2. Grab bottom-right corner and try to make the window bigger by dragging down and out/right
3. Then make it smaller by dragging up and in/left

**Expected behavior**
Window top left position should remain anchored where it started and only bottom right corner should adjust to change the window size.  Instead the entire window isn't anchored and jumps around all over the place

If I stop MaxTo and do the same thing it works fine.  Start MaxTo and it happens again

**Screenshots**
Captured a video as it's easier to see.  At the beginning of the video I've stopped MaxTo and you can see it behaves as one would expect.  I then start MaxTo and you can see the problem where it jumps all around.  Link to 40 second video as it wouldn't let me attach mp4: https://www.dropbox.com/s/5odiy8ejffuh69q/maxto_window_resizing.mp4?dl=0

**System information:**
Windows 10 Version 1803 (OS Build 17134.1425)
MaxTo version: 2.1.0-beta1

**Additional context**
I do fairly frequently see notices that MaxTo crashed the last time it ran or recovered from an unexpected error.  I've attached a zip with 7 examples from the last week.  After it shows this message it seems to continue running fine, but just in case it's helpful.  I also notice that there's usually two MaxTo windows showing up in my system tray and neither goes away when I hover over them.

[MaxTo.zip](https://github.com/digitalcreations/MaxTo/files/4718712/MaxTo.zip)

**Comment by vegardlarsen** [comment]
This issue should have been fixed in 2.1.0-beta.2. Please see [the release notes](https://maxto.net/release/beta) and issue #555.

Do let us know if the issue persists in version 2.1.0-beta.2.

**Comment by takeoffeh** [comment]
Thank you - this is awesome!  Just installed 2.1.0-beta.2 and haven't seen it since.  Tried searching for it before logging this but couldn't find it.  Sorry for the duplicate.  Appreciate how quick you are on responding to issues.
