### ISSUE TITLE
Single clicking on the window resize bar enables window transparency. Repeated clicks toggle through transparency levels.

### ISSUE THREAD

**Issue by jamesahallam** [digitalcreations/MaxTo#584]
**Describe the bug**
Accidentally single clicking on the window border but not resizing will change the transparency of the window.

**To Reproduce**
1. Any window that's not completely maximised by Windows.
2. Click the border as if you're going to resize the window but don't move your mouse.
3. Window transparency will be enabled.
4. Keep single clicking slowly and the window transparency will loop through 3 levels of transparency but never return to fully opaque.

**Expected behavior**
Transparency should not be changed until the window is moved or resized. It should return to opaque after movement is finished.

**System information:**
Windows: Version 1909 (OS Build 18363.836)
MaxTo: 2.1.0-beta2

**Additional context**
Disabling Window transparency in the settings prevents this from happening.

I can't see anything error related in the logs. Only entry that's generated is

2020-06-05 09:45:13 [CompanionX64@2.1.0.660] [Information] [MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "maxto - Google Search - Google Chrome" (0x"680ae8"), used mouse position to find region "{X=62,Y=0,Width=929,Height=1080}".

**Comment by vegardlarsen** [comment]
We are aware of this issue with Google Chrome. We are looking for ways this can be solved.

**Comment by vegardlarsen** [comment]
I believe I have fixed this for 2.1.0-beta.3. It comes at a cost, however; we will no longer be able to add the transparency to windows that are already transparent. I believe that cost is justified for something that works... :)
