### ISSUE TITLE
Using Snipping in Windows 10 sometimes freezes the screen

### ISSUE THREAD

**Issue by neodraxo** [digitalcreations/MaxTo#585]
When creating a snip from the Win-Shift-S shortcut, the snip selection turns blue and the screen freezes. 

**Describe the bug**
The screen freezes, but the system keeps working (sounds reproduce, tasks continue executing, even Skype calls remain active). The snip will remain on screen, in blue color. Ctrl-Alt-Del triggers the system screen, lock work and you return to login screen. Logging back in returns you to a frozen screen. Task Manager does not load in the first attempt, and only after locking and calling the Task Manager several times (not the same number of times every time) the screen may unfreeze.

**To Reproduce**
1. Activate snip selection via Shortcut Win-Shift-S (I have not tried to reproduce using the Snip app directly)
2. Select a region to snip
3. Bug may show up or not. I've noticed it it shows up the first time doing the Snip after a restart. Then it may not happen again until the system is rebooted, or it may happen after a while.
4. using Print-Screen has not triggered this bug.

**Expected behavior**
Sniping will capture the selection and open the app.

**Screenshots**
Not possible

**System information:**
Version 1909 (OS Build 18363.836
- MaxTo version: 2.0.1

**Additional context**

**Comment by vegardlarsen** [comment]
@neodraxo Can you please confirm my comments above?
