### ISSUE TITLE
Split screen display is not supported in chrome F11 full screen mode

### ISSUE THREAD

**Issue by xjl456852** [digitalcreations/MaxTo#586]
Split screen display is not supported in chrome F11 full screen mode

**Comment by vegardlarsen** [comment]
@xjl456852 MaxTo does not support moving full-screen apps into regions at this time. There are two main reasons:

- There isn't any standard way of "going full-screen" in the same way that there is of maximizing. Basically, every app does it differently, and detecting it in a good way may not be possible.
- There are serious user interface issues regarding how this could be done:
  - There is usually not a taskbar that can be dragged.
  - Windows may be draggable by the entire window, or MaxTo could make them be draggable. But there may be existing functionality tied to this; e.g. a video player may treat click and drag as forward/rewind.
