### ISSUE TITLE
Shift + Snap does not work with Mathematica

### ISSUE THREAD

**Issue by p-Wave** [digitalcreations/MaxTo#588]
**Describe the bug**

When I try to snap a window of Wolfram Mathematica to a region, there is no preview of the space and nothing happens

**To Reproduce**

1. Create regions and apply
2. Open Wolfram Mathematica
3. Hold Shift + Move Windows

**Expected behavior**

A region preview should appear.

**System information:**
- Windows version: Windows 10 1909
- MaxTo version: 2.0.1

**Comment by vegardlarsen** [comment]
Does this happen for other programs as well? Does a simple program such as Notepad work as expected? Does the issue persist after a reboot?

**Comment by p-Wave** [comment]
Hi!
It only happens with Mathematica. Other programs work as expected.
The current beta does NOT have the problem, although that version leads to some significant graphicl lag. Should I report that in another ticket?

All the best

**Comment by vegardlarsen** [comment]
@p-Wave Can you describe the lag in more detail, or maybe record a video of it so I can try to determine if we've seen it before?

**Comment by p-Wave** [comment]
This only occured after installing the beta version and I'm now unable to reproduce the problem.
Therefor I'm closing the ticket.
