### ISSUE TITLE
Recipes should have an ingredient to resize windows to an arbitrary value

### ISSUE THREAD

**Issue by p-Wave** [digitalcreations/MaxTo#589]
**Describe the solution you'd like**
I would like to have an ingredient, that allows me to resize a window to a size of my choosing.

**Additional context**
I wanted to create a recipe, that centers a window and resets the size of the window to e.g. a square.

**Comment by vegardlarsen** [comment]
@p-Wave In version 2.1.0-beta.2, [available on our website](https://maxto.net/release/beta) you can use the `window:size` command for exactly this. :)

From the command line to resize keeping the center in place:

```
maxto window size /Window "* - Notepad" /Size 1024x768 /Origin 50%,50%
```

Or to keep the top left in place:

```
maxto window size /Window "* - Notepad" /Size 1024x768 /Origin "top left"
```
