### ISSUE TITLE
Vanishing windows of normal size.

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#59]
Temporarily, MaxTo will hide those windows that had been restored from Maximization. That is, when restoring from maximized view, the window will vanish and re-maximizing the window will make such window visible. However, such window will be consistently docked at the "Main Display" screen. (The monitor selected through the "Screen Resolution" window). And, such window will vanish when trying to move it to the next screen using the hotkey.

@vegardlarsen: were you able to replicate this? Let me know if the description is unclear.

All the best, 

-Linfeng

**Comment by vegardlarsen** [comment]
I am not sure I do understand. Could you maybe do a screen capture to show me what is going on?

**Comment by llinfeng** [comment]
Let there be two states of windows: normal-sized and maximized-sized. When a window is of "normal size", pressing the shortcut for maximizing the window will bring it to "maximized size", occupying the full range of the screen/monitor.

The problem is that: upon pressing the "maximization" shortcut for a few times, such window will no longer be *visible* in its "normal size" and will only be visible in the maximized view. The odd is: regardless of where the window was located (as of monitors), the visible maximized view shall only be docked at the "primary display".

This becomes a problem when I want to move the window to the next screen given that such problem did occur. For a window that has been docked at the primary screen (i.e. only visible in maximized view), moving it to the next available region will still entail the screen to vanish. Only killing and restoring the process (*.exe) will restore the functionality.

**Comment by AsaAyers** [comment]
I think I'm seeing the same thing. It seemed to be consistent with [Atom](https://atom.io/)... right up until I installed screencapture software. I'll get a recording when I can reproduce it next, but here's what I know.

I max Atom into a region that doesn't take up the whole screen. When I un-maximize the window it gets positioned off screen. I can right click the task bar and select move, then move it back onto the screen. Or I can `ctrl+win+right` and it pops back on screen. I'm also on a laptop where I have a docking station at work and one at home with different monitor configurations. I don't know if this could contribute toward confusing MaxTo about where the window should move to.

**Comment by vegardlarsen** [comment]
I have tried to reproduce this as best I can, but no luck so far. I've even installed Atom, but it behaves just fine on my machine. When MaxTo restores a window, it uses the previously stored position (that MaxTo itself stores when the window was maximized). After looking at the code for a while, I realized that if the stored position was non-existent, it could place the window with a size of 0x0. So in the coming release I have added a check to see if this is the case, or if the new position does not intersect with any of the monitor bounds, the restored window will be placed in the top left quadrant of your primary monitor. If any of you can confirm that this happens in the next release, then I know we are on to something.

**Comment by AsaAyers** [comment]
You might also try `View > Reload (ctrl+alt+r)` in Atom to see if that triggers it. According to [their discussion forums](https://discuss.atom.io/t/atom-moves-on-reload/15377?u=asaayers) it _usually_ un-maximizes the window but leaves it nearly the same dimensions as before, then maximizes when it finishes loading. (or we can wait, that's fine too)

I use reload to build plugins for Atom and that's when this bug is the most noticeable.

**Comment by vegardlarsen** [comment]
I've tried reloading the Atom window quite a few times now, it just doesn't seem to happen on my machine (or my test VM). Until I can find a reliable method of reproducing this, I don't think it will be solved.

And yes, it seems Atom is doing something very strange when you reload. Unless they actually destroy the window and create a new one, I can't see why it should be doing this resizing.

**Comment by llinfeng** [comment]
@vegardlarsen, before closing this issue, could you supply me with "your version of MaxTo"? Mine is still suffering from issue #48.

**Comment by vegardlarsen** [comment]
Did you download version 2015.03, released a few hours ago? #48 is still not fixed (as far as I can tell), as I couldn't figure it out in time. There were quite a few other fixes that I felt were important to release, so I had to make some hard priorities there.

**Comment by llinfeng** [comment]
Good to know that there is a new release. It should be advised to delete-reboot-install, right?

**Comment by vegardlarsen** [comment]
Yes, absolutely. Because of the way MaxTo works, unless you are very lucky, a reboot is required.
