### ISSUE TITLE
Settings window very unresponsive

### ISSUE THREAD

**Issue by eikowagenknecht** [digitalcreations/MaxTo#593]
**Describe the bug**
The MaxTo settings window is responding very slow. E.g. moving or resizing the window feels very sluggish, lagging behind the actual mouse movement for quite some **seconds** sometimes.

**To Reproduce**
Open settings window and move it around using the mouse.

**Expected behavior**
Moves around just like any other window.

**Screenshots**
---

**System information:**
- Win10 2004 Build 19041.329
- MaxTo version: 2.01

**Additional context**

**Comment by vegardlarsen** [comment]
@eikowagenknecht We are aware of this issue, and are trying to resolve it. Unfortunately, we have until now been unable to fully fix this, but it should be better in the 2.1.0-beta.2 release. See issue #480 for details.

We are aiming to fix this completely in version 3.0, with a rewrite of the UI. More details about that will be coming at a later stage.

**Comment by eikowagenknecht** [comment]
Thank you for the reply. I missed that other issue, sorry.

Just switched to 2.1.0-beta2, but it has - as far as I can see - not improved.
