### ISSUE TITLE
Make maximize behaviour configurable

### ISSUE THREAD

**Issue by eikowagenknecht** [digitalcreations/MaxTo#594]
**Is your feature request related to a problem? Please describe.**
I've been trying your software for the whole workday now and love it so far, but windows only maximizing to a small proportion of my screen really really really annoys me because sometimes I just want to make a window fullscreen without having to use some keyboard shortcut.

**Describe the solution you'd like**
Please add a possibility to make the maximize functionality customizable. There need to be only 2 options:
- Fit into nearest region (current behavior)
- Work like it does without MaxTo (maximize fullscreen)

Alternatively, "fit into nearest region" could also be executed only when the shift key is pressed, just like the dragging functionality.

I know this has previously been noted in #486, but since that one was closed, I'll add it here as a feature request.

**Describe alternatives you've considered**
I'm torn between keeping and buying the application and just uninstalling it again because of this maximizing behaviour..

**Comment by vegardlarsen** [comment]
@eikowagenknecht In the latest beta, there is an option in the settings for turning on "Passive mode", which reverses the default behavior, and only forces things into regions while you hold Shift. Would that help in your case?

**Comment by eikowagenknecht** [comment]
@vegardlarsen Thanks for the reply. I just switched to the 2.1.0-beta2 release, but unfortunately this has made things worse.

If I understand correctly, the passive mode should achieve exactly what I want. But it does not work. After switching it on, everything is the same as before. Maximizing windows still fits them into the nearest region. I tried turning passive mode off and on again a few times, but no change.

Also I noticed another thing in the beta: Previously (2.0.1) when I dragged a window around there was a white highlight where the window would be placed, this is gone now and I see no option to activate it again.

Restarting MaxTo did not fix any of this.

**Comment by vegardlarsen** [comment]
Sorry for noticing your reply before now. I have been away on vacation these last few weeks.

It could be that passive mode is a bit buggy, I did test it quite substantially here, but we've received some other reports about irregularities while I was away.

I'll try to look into this more.

**Comment by eikowagenknecht** [comment]
Thanks for looking into this. As of now, I have passive mode enabled, but maximizing windows still fits them into the nearest region. Please contact me if you need further tests / logs etc.

**Comment by vegardlarsen** [comment]
I have been able to reproduce this (on my machine, it only happened when passive mode was set in the settings when MaxTo started, and not if you toggled passive mode in the settings).

I have fixed the bug now, and the fix will be in 2.1.0-beta.4.
