### ISSUE TITLE
Switching to a virtual desktop breaks the program

### ISSUE THREAD

**Issue by p-Wave** [digitalcreations/MaxTo#595]
**Describe the bug**
Switching to the next virtual desktop breaks the ability to open the "Change Regions" screen.
After switching back to the original desktop, the screen is still not available.
Only after restarting MaxTo can I configure the regions again

**To Reproduce**
1. Start MaxTo
2. Open "Change Regions" screen
3. Set desired regions
4. Apply regions
5. Switch to next/different virtual desktop
6. Open "Change Regions" screen
7. Go back to original desktop
8. Open "Change Regions" screen

**Expected behavior**
Item 6 and 8 in the list above should open the "Change Regions" screen.

**Actual behavior**
Item 6 and 8 in the list above do not open the "Change Regions" screen.

**System information:**
- Windows version: Windows 10 1909
- MaxTo version: 2.1.0-beta2

**Comment by p-Wave** [comment]
[maxto_config-and-logs.zip](https://github.com/digitalcreations/MaxTo/files/4906519/maxto_config-and-logs.zip)

**Comment by vegardlarsen** [comment]
We've made some changes for version 2.1.0-beta.3 that may fix this. 

PS! I am currently on summer vacation. Responses may be slow.

**Comment by vegardlarsen** [comment]
@p-Wave Can you try this scenario with 2.1.0-beta.3, which has just been released?

**Comment by vegardlarsen** [comment]
@p-Wave Did 2.1.0-beta.3 fix it for you?

Closing this issue under the assumption it did.
