### ISSUE TITLE
Regions appear in different places after waking up from sleep

### ISSUE THREAD

**Issue by mortenmoulder** [digitalcreations/MaxTo#596]
**Describe the bug**
My setup consists of 2x 2560x1440 and 2x 1920x1080 monitors. When I wake up the PC after sleep, all regions are in the wrong place. One region suddenly appears on 2 monitors, but it's very shallow and very tall.

All my monitors are 100% DPI scaled.

I can fix this in two ways: Restart MaxTo or rearrange my displays and move them back.

**To Reproduce**
1. Put PC to sleep
2. Wake up PC
3. Move windows/programs that are scattered all over the place into my regions, using the hotkey specified in MaxTo.

**Expected behavior**
I would expect it to remember the regions, but it seems like MaxTo sets the regions before the monitors are initialized, or something like that.

**System information:**
- Windows version: 1909 OS Build: 18363.900
- MaxTo version: 2.1.0-beta2 (but I have tried stable as well)

**Additional context**
I have tried to identify my monitors by number, properties, and serial number.

**Comment by vegardlarsen** [comment]
Hi @mortenmoulder, thank you for your report.

If you open the Change Regions window after a sleep, are the strange regions reflected here as well, or is this only when you use the "Fit windows to region" option?

PS! I am currently on vacation, so responses may be slow.

**Comment by mortenmoulder** [comment]
Hi @vegardlarsen 

If I open the Change Regions window after sleep, it appears completely normal. It's like it's happening in this order:

1. PC turns on
2. MaxTo reads the monitor setup, resolution, etc.
3. Monitors adjust according to how Windows 10 has them set up (they blink, turn black, turn back on, and so on)

And then:

1. Right click on MaxTo and select Change Regions
2. Change Regions reads the current windows setup and shows the UI as it should look
3. Cancel changes (none were made)
4. MaxTo now knows the proper window setup, because it was read in step 2

That's my guess to how it works. It's like MaxTo initially reads the window setup at the wrong time.

**Comment by rooby** [comment]
So are the regions wrong or are the windows just not in the regions they were in before?

In my case I have 2 monitors but when my computer wakes everything has been moved to monitor 1 and I have to move them back where they should be.

Does that sound similar to your issue or something different?

**Comment by mortenmoulder** [comment]
Hi @rooby 

Sometimes a single window is moved away and I have to move it back, but I think that's a Windows 10 "issue", because it happens even without MaxTo.

But no, my problem is that regions are simply smaller and in other positions. My 1440p monitor looks like it has a 1080p region. The region is definitely 16:9 and it looks about as small as 1920x1080 is on a 2560x1440 monitor.

I've since creating this issue moved my setup to an even worse setup (in regards to software, at least). 1x 4K monitor, 1x 1440p monitor, and 1x 1080p monitor. So 3 different resolutions (all same 100% DPI scaling though). My regions now appear on the correct monitor, they're just.. smaller and offset. Quite weird.

**Comment by vegardlarsen** [comment]
@mortenmoulder So it appears that this may be a DPI-scaling issue. I assume that if you change anything about your desktop after Windows is awake, MaxTo will pick it up? You can try unlocking your taskbar and resizing (or moving it) to quickly force the regions to re-apply.

**Comment by mortenmoulder** [comment]
@vegardlarsen DPI is the same across all 3 (previously 4) monitors. Nothing has changed except the resolution.

**Comment by vegardlarsen** [comment]
@mortenmoulder Does that trick still solve it?

**Comment by mortenmoulder** [comment]
@vegardlarsen Won't be able to test until I get home, unfortunately.

**Comment by mortenmoulder** [comment]
@vegardlarsen Confirmed that trick solves it. I've tried to mark my regions on this picture, so maybe that gives a better understanding.

Red = Region
Black = Monitor

Not sure where the last 3rd region is.

![image](https://user-images.githubusercontent.com/1304665/89314760-5a720f00-d67a-11ea-829e-8928420b66ec.png)

**Comment by mortenmoulder** [comment]
Still happening.

**Comment by mikeowens87** [comment]
I believe I am dealing with the same bug over here. I'm on a 5120x1440 @ 125% DPI split into 4 sections, and screen locks or sleeping causes each window to move out of place slightly.

**Comment by vegardlarsen** [comment]
@mikeowens87 Can you confirm if you have the exact same versions of Windows and MaxTo as @mortenmoulder?
