### ISSUE TITLE
Auto maximize if moved to monitor with no regions

### ISSUE THREAD

**Issue by mortenmoulder** [digitalcreations/MaxTo#598]
**Describe the bug**
This is both a feature request and a bug report. 2 out of 3 of my monitors have no regions. When I use my WINKEY+Arrow to move an app around, it doesn't maximize the window. Instead it just moves the app to that screen and fills it up, but not maximized. If I then hit the maximize button on the window, it moves the window and maximizes it. Video example: https://i.imgur.com/Fr0RYqb.mp4

I move the window away using WINKEY+Arrow, which is why it appears black for a second. As you can see, I move the window back on the screen with no regions on it, and then I maximize it. But it doesn't maximize it correctly. I have to move it using my mouse and THEN maximize it.

The feature request is literally: If an app is moved to a screen with no regions, automatically maximize it. There should be an option for that.

**System information:**
- Windows version: 1909 OS Build: 18363.900
- MaxTo version: 2.1.0-beta2 (but I have tried stable as well)

**Comment by vegardlarsen** [comment]
This has been fixed for version 2.2.0, and will be in the first preview release we put out.
