### ISSUE TITLE
Mouse to Monitor

### ISSUE THREAD

**Issue by Ndmand501** [digitalcreations/MaxTo#599]
This is a feature or help request.  I have four monitors, and I use two keyboards and two mice to get around the screen real estate.  My setup creates two problems.

1.  Getting the mouse to monitor that I need to use is a challenge.  First you have to find it, then move it.  I would like to be able to have the mouse snap to the monitor or region that I want to use without having to look for it (or look away to hit Ctrl).  A hot-key would be great, such as Alt-4 snaps to monitor four, etc.
2.  Child dialogues often appear on a monitor away from the parent window.  This is especially true for Adobe Acrobat, but it also happens with Excel.  For example, I may be working in Excel on monitor 4, but if I hit Ctrl-F (the find function), the dialogue may appear on monitor #1.  There have been times when I didn't think that Excel responded because the child opened 20 inches away on another monitor.

These problems logically arise from multiple monitors, and at least one competing app seems to solve them.  I just prefer to stay with MaxTo.  I have already tried the recipe thing, but can't get this figured out.  If you have a recipe, please send.

Thanks,
Ndmand501

**Comment by vegardlarsen** [comment]
I apologize for the slow response here; the summer holiday has just ended here in Norway and I've been away.

In version 2.1.0-beta.2 ([available on our website](https://maxto.net/release/beta)), there is a `mouse:position` command, that you can invoke from the command line like this:

```
C:\> maxto mouse position /Position "center, center" /Monitor $next
```

That would move the mouse to the middle of the next monitor. Other supported monitors are `$previous` and just using numbers (1-4).

We are working on better documentation for this.

As for your second case, this is semi-achievable. In 2.1.0-beta.2, you can set a trigger when new windows are opened. You will have to filter the window by its title (e.g. `Find`). You could then use a command to move the window to a specific monitor, but we do not support doing this in relation to its parent window. 

This will move the current window to monitor 3.

```
C:\> maxto window move /Monitor 3
```

When selecting monitors, we also support `$current`, which means the monitor that has the foreground window. In this case however, your window has the foreground focus, so this is not really possible today.

**Comment by vegardlarsen** [comment]
I am closing this issue as I believe I have addressed @Ndmand501's problems.
