### ISSUE TITLE
Unable to make acrobat windows snap to size

### ISSUE THREAD

**Issue by 57thkafka** [digitalcreations/MaxTo#60]
This is the error message that comes up. My monitor is an LG 34um95-p running at 3440x1440 @ 50Hz. This is Acrobat Pro 11.0.10.

I have only had MaxTo since yesterday and have tried numerous programs with it, without any problems. It's a shame because

![maxto error message](https://cloud.githubusercontent.com/assets/11346817/6522210/2a19fd26-c3da-11e4-885d-5d8e2e110498.jpg)

**Comment by llinfeng** [comment]
Reference: #31

**Comment by vegardlarsen** [comment]
@57thkafka Unfortunately, this is a known issue with Acrobat Reader. You can follow the instructions that @llinfeng pointed to, otherwise there is nothing we can do about it.
