### ISSUE TITLE
[Feature] When resizing a full screen window, automatically resize adjacent full screen windows

### ISSUE THREAD

**Issue by ChristopherHaws** [digitalcreations/MaxTo#601]
**Is your feature request related to a problem? Please describe.**
The default Windows Snap feature has a toggle'able feature where adjacent windows will be resized along with the window you are resizing which does not work when using MaxTo.
![image](https://user-images.githubusercontent.com/5934505/90061822-8bb29680-dc9b-11ea-89ff-ffa22c960708.png)

**Describe the solution you'd like**
Add the same ability as the default Windows 10 Snap where windows are resized together.

**Describe alternatives you've considered**
Currently I have to either manually resize each window or modify the regions and re-maximize each window

![image](https://user-images.githubusercontent.com/5934505/90062140-14c9cd80-dc9c-11ea-8f19-967b13c70332.png)

**Comment by vegardlarsen** [comment]
@ChristopherHaws Thank you for the feedback. We are evaluating variations of this that we think are better. I am filing this as an idea that we will revisit for later versions.
