### ISSUE TITLE
LocalBridge.exe - Bad Image: MaxTo causes error dialog

### ISSUE THREAD

**Issue by aslakrin** [digitalcreations/MaxTo#602]
Update is perhaps a strong word since it's a corporate thing, but version is 1909/18363.418.

It runs fine for a while, then anything from 2 to 20 of those dialog boxes need to be clicked away. Still works afterwards too.

![2020-08-21 08_38_54-LocalBridge exe - Bad Image](https://user-images.githubusercontent.com/901730/90860625-9ef3ef00-e38a-11ea-9209-71560c179c0d.png)

**Comment by vegardlarsen** [comment]
@aslakrin This is an instance of issue #415, which is really a bug in Windows, and only happens when you upgrade Windows versions. Search in that issue for the fix (look for the PowerShell snippet).

**Comment by aslakrin** [comment]
Thanks. I didn't understand even one bit of the powershell snippets, but deleted the cached dlls. It would perhaps be useful if MaxTo could detect a windows update and preemptively at least alert the user, but maybe also offer to scan for the problem.
