### ISSUE TITLE
Extremely annoying shifting bug on 2x4k screen

### ISSUE THREAD

**Issue by crankedguy** [digitalcreations/MaxTo#604]
**Describe the bug**
If you divide a 4k screen with 3840x2160 in thirds on virtual desktops, so you have 3 parts with 1280px at first everything seems well.
Then when you switch back and forth in Windows 10 a few times between the virtual desktops the relations start shifting. They start shifting from the first switch and get worse and worse every time you switch, so a fter a few switches you have 1278x1278x1285 which is not 3840 anymore. And the more often you do that the more it is switched to the left.
Extremely annoying.
This is with a dual monitor setup with latest version of Windows 10.

**Expected behavior**
Pixels should stay 3840 in total and should not shift at all

**Screenshots**
https://pasteboard.co/JolHt0s.jpg

**System information:**
- Windows version: 19041.450
- MaxTo version: 2.0.1

Edit : I just saw this happens with every single split that is done, on the first and also on the second monitor. And it happens horizontal AND vertical, so vertical there only remain 2158 pixels after a few switches.
Isn't this the main functionality of the program?? How can this be?

**Comment by vegardlarsen** [comment]
@crankedguy Thank you for the report. Have you tried this in version 2.1.0-beta.3? There are improvements in the preview version in regards to this functionality specifically.

You can [download the preview releases from our website](https://maxto.net/releases/beta).

**Comment by crankedguy** [comment]
@vegardlarsen Thansks for getting back to me. No I did not until now. Is beta in your case considered "safe"? I am on a production system and won't mess anything up which I do not get rid of then.

**Comment by vegardlarsen** [comment]
According to our telemetry, it shouldn't be much worse, but or course the bugs are different. If you are concerned, I would recommend backing up `%AppData%\MaxTo` before updating, so you can go back to your previous settings. For a smooth update, uninstall your current version and reboot before installing the latest release. Please let me know if it works?

**Comment by vegardlarsen** [comment]
@crankedguy Any updates on this?
