### ISSUE TITLE
Task Bar Covering bottom of regions in Windows 10

### ISSUE THREAD

**Issue by psdbrawner** [digitalcreations/MaxTo#606]
I am new to MaxTo (only used it for a few weeks).  I have setup two regions (left and right) on each of my two monitors.  When I maximize a browser or other application to the region, the bottom of the window is behind the taskbar at the bottom of my screen.  I have the taskbar displayed on both screens and I am seeing the issue on both screens (primary and secondary).  If I use the "Maximize to Monitor" feature it correctly displays without the window going behind the taskbar.

I didn't see anywhere that I could indicate the taskbar height or reduce the region's height to accurately avoid the taskbar.

I am running Windows 10 Pro version 2004 OS build 19041.450 with Feature Experience Pack 120.2212.31.0.  I am running MaxTo version 2.0.1.

I appreciate any help you can provide.

**Comment by vegardlarsen** [comment]
MaxTo is supposed to know what the working area of your screen is. It relies on messages from Windows to "update" its knowledge of what these working areas are. If you temporarily move or resize your taskbar, the issue should go away immediately. You will need to right-click in a blank area of the taskbar, and uncheck "Lock the taskbar":

![image](https://user-images.githubusercontent.com/436508/92122678-09ca0f00-edfc-11ea-8ce4-27f1410a405e.png)

Does this issue persist after a reboot? Is there anything you can do to consistently reproduce it?

**Comment by shtirlitsDva** [comment]
Resizing the taskbar bigger and back to small, fixed the problem for us. The values for the working area must have become stale somehow and needed refreshing.

**Comment by vegardlarsen** [comment]
Thank you for the update. I am not sure what causes the values to be out of date. MaxTo is subscribed to all kinds of events that should notify it whenever this changes (e.g. resolution changes, monitors are connected, etc.), and does not cache this value in any way.

If you can think of anything you can do to consistently reproduce this issue, please feel free to comment here and we can re-open this issue.
