### ISSUE TITLE
Max.to fails immediately when Chrome Incognito is opened

### ISSUE THREAD

**Issue by d3relict** [digitalcreations/MaxTo#609]
**Issue description**
Opening Google Chrome in incognito mode will kill Max.to, and will not recover unless it is closed and restarted.

**System information**
Chrome: Version 85.0.4183.83 (Official Build) (64-bit)
OS: Windows 10 Pro, version 1909, build 18363.1016
Max.to: 2.1.0-beta3

**Comment by vegardlarsen** [comment]
@d3relict Thank you for reporting this issue.

Do you get anything in your error log when this happens?

I have tried this myself with the same exact Chrome version, and nothing crashes on my machine.

**Comment by d3relict** [comment]
hey @vegardlarsen thank you for dealing with my issue, unfortunately, the email notification landed in my trash, hence the late reply :(

no error occurs to be specific, it just stops working completely.

i made a quick repro, and it behaves as described:
- start max.to, it asks for elevated permissions, granted
- open chome, observe proper behavior, windows resizing according to regions
- open incognito tab, and the maximised windows no longer respect the regions
- doing anything other than restarting max.to will not fix the issue

**Comment by vegardlarsen** [comment]
Does the problem go away if you set MaxTo to run as a standard user (not elevated)?

**Comment by d3relict** [comment]
tried without elevation, same issue. functionalities cease to work until restart of max.to.

**Comment by d3relict** [comment]
@vegardlarsen anything else i can try?

**Comment by vegardlarsen** [comment]
@d3relict Could this be issue #476 in a new disguise? See [my instructions here](https://github.com/digitalcreations/MaxTo/issues/476#issuecomment-547324294).

It could be that since MaxTo is run as administrator, the registry keys that MaxTo writes to "fix" Chrome is written to a wrong location, and it therefore somehow doesn't work. It is a long shot though.

**Comment by d3relict** [comment]
@vegardlarsen the issue was fixed in the latest 2.1 release, this is safe to close. thanks for your efforts!

**Comment by vegardlarsen** [comment]
Great. Thank you for the update.
