### ISSUE TITLE
Create new preset from frontmost window

### ISSUE THREAD

**Issue by paul-chambers** [digitalcreations/MaxTo#610]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use the dimensions of an existing window to create a new preset. Not really a problem, just an inconvenience, forcing iterative trial and error.

**Describe the solution you'd like**

In its simplest form, another menu option on the tray icon menu to use the frontmost window to initially set the regions. I.e. if I were set up a window with the dimensions and placement I'm looking for, select the item, then I enter the 'change region' UI to save as a new preset 

**Describe alternatives you've considered**

I could find a tool that would tell me the dimensions of a window and enter them manually into MaxTo. But since I don't appear to be able to enter the dimensions numerically, I'm still left tweaking the dividers manually.

**Additional context**

The motivation for this is wanting to set up a video playback window top right with a consistent 16x9 aspect ratio. This avoids the player adding black bars to maintain the video's aspect ratio within a content region that doesn't match.

**Comment by vegardlarsen** [comment]
Thank you for this feedback. There are some quirks around how the region setup works in MaxTo that prevents us from doing this at the moment. Say that you leave a window in the middle of the screen, with space all sides. Depending on how you look at it, that would either generate 5 regions (4 in a spiral around the window, and 1 for the window itself), or 9 regions (4 for each side, 4 diagonnaly, and 1 for the window itself). Any combination of these two is also possible.

I feel that sort of defeats the purpose of MaxTo; and you can achieve something like this in version 2.1.0 (which is currently in preview) without this. We have added a new set of recipe commands (expand and contract window). Once you've placed your main window, you can use those commands to expand other window edges until they align with the main window.  We are working on documentation for these commands.

**Comment by paul-chambers** [comment]
Thinking about it, what I'm looking for is an easier way to set the dimensions of a region, the placement doesn't really matter. Indeed, copying the window's position too would complicate things, particularly if the user has the window close to a screen edge - the regions created would not be useful, perhaps even problematic (e.g. a region 1 or 2 pixels wide/tall). I have a related idea, but will suggest that separately, so it's not buried in comments.
