### ISSUE TITLE
Quick switching between existing presets

### ISSUE THREAD

**Issue by paul-chambers** [digitalcreations/MaxTo#611]
**Is your feature request related to a problem? Please describe.**

Not a problem, a faster, single-step way to achieve something I do frequently that currently requires multiple steps.

**Describe the solution you'd like**

I would like a pull-right menu on the tray icon that lists the custom presets, so that I can switch presets without having to enter 'Change Regions' and load that preset. Bonus points to be able to bind a preset to a hotkey as a 'recipe'

**Describe alternatives you've considered**

None I can think of.

**Additional context**

I have one preset I use for Zoom (have a 4k monitor, with a region sized as 1920x1080 for sharing via Zoom or OBS), another I use for day-to-day work. I find myself switching back and forth often.

**Comment by vegardlarsen** [comment]
Thank you for your feedback. This is an idea that I have considered, and this may be something we look at for 2.2.

I have some ideas here in regards to adding recipes into this right-click menu as well.

I am labelling this as an idea, which is something we regularly go back and revisit.

**Comment by vegardlarsen** [comment]
PS! You can load presets using a hotkey, with the recipes feature. That may be even quicker for you.

**Comment by paul-chambers** [comment]
Thanks, Vergard. Yes, I was reading about recipes earlier, and a submenu that includes recipes would be perfect. It also occurred to me that virtual desktops could help, too.
