### ISSUE TITLE
Optionally snap region boundaries to edges of underlying windows.

### ISSUE THREAD

**Issue by paul-chambers** [digitalcreations/MaxTo#612]
**Is your feature request related to a problem? Please describe.**

I would like the ability for a region to reflect the dimensions of an existing, open window. In my case, it's a media player that I want to size with the correct aspect ratio for the content it is playing.

**Describe the solution you'd like**

I'd like to be able to snap region boundaries to the edges of windows underneath, probably only when a modifier key is held down.

**Describe alternatives you've considered**

I did try to manually enter the displayed window dimensions in the 'change regions' mode, but they're not editable.

**Additional context**

Would probably need adjustment of the degree of blur of underlying windows too, perhaps only when the modifier key is down?

**Comment by vegardlarsen** [comment]
@paul-chambers Thank you for your report. I would like to do this as well, however, the grid resizing control that we use has no support for snap points. If it had, we would allow it to snap to window borders as well as predefined snap-points (1/3, 1/2, etc).

It is definitely something that is on our wish-list of things to do.

It will however not happen on our current roadmap of releases (e.g. 2.1, 2.2). There is a (admittedly small) chance that it may happen in 3.0, as we will be replacing quite a bit of the UI for that release.
