### ISSUE TITLE
Multi user on Windows

### ISSUE THREAD

**Issue by mikelazell** [digitalcreations/MaxTo#616]
I have multiple user profiles on Windows 10 and like to Switch Users quite frequently.

E.g my work profile, my home profile, my wifes profile.

For MaxTo to work I have to remember to close it before switching otherwise it complains it is still running.

Have I missed something simple on setup?

TIA

**Comment by vegardlarsen** [comment]
@mikelazell So you are effectively running MaxTo multiple times on the same machine, under different user accounts that are logged on simultaneously?

This is not something we've tested extensively, so it may be that this is a bug.

**Comment by mikelazell** [comment]
@vegardlarsen Yep that's correct. It seems to be aware of itself across multiple user accounts (thinks it is running) but you cant access it from the other. When running the process manually it freezes setting regions.

**Comment by vegardlarsen** [comment]
This issue has been fixed for 2.1.0-beta.4. MaxTo now allows multiple instances of MaxTo as long as they are in separate sessions.
