### ISSUE TITLE
"Use Regions" button not working

### ISSUE THREAD

**Issue by figgy78** [digitalcreations/MaxTo#617]
Right after starting the application, I am able to change regions, but after a while, if I try to do it again, the buttons stops working and I have to cancel and restart the app to make changes to regions. 

This with or without elevated permissions. 

It's been like this for a year or so. 

Currently I'm on Version 2.1.0-alpha3

**Comment by vegardlarsen** [comment]
@figgy78 Can you try to update to 2.1.0-beta.3, where I believe this issue has been fixed?
