### ISSUE TITLE
MaxTo cannot move the "Gvim" window

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#62]
When I were not able to move the Gvim window: 

1. That there is no longer circulation of windows when it hits the left(right)-most region.
In previous version, a window won't stop at the left most region when being directed to "move left". It will show up at the right-most region. The windows were able to circulate from left to right, seamlessly. Such feature had been removed.

2. Worse though: I cannot move the "Gvim" window after having MaxTo running for a well. All the other windows of other processes are "movable". It is only for the Gvim windows. Strangely, I should still be able to maximize the Gvim window and restore it to normal size.
When trying to combat the second bug in my old way as recorded in #48, such key mappings no longer work. I cannot end the process of `MaxTo.exe`. I should manually restart MaxTo.

@vegardlarsen, were you able to reproduce this?

**Comment by llinfeng** [comment]
Update for this issue: never happened up till no 2015-03-16 11:15:14.

**Comment by vegardlarsen** [comment]
@llinfeng I haven't had a chance to look at this issue yet, but if it was a transient issue, and it doesn't reoccur, it will be very hard for me to figure out what happened.

**Comment by vegardlarsen** [comment]
I am closing this for the reasons mentioned above.
