### ISSUE TITLE
Website 500 Error Trying to Log in

### ISSUE THREAD

**Issue by t-rad679** [digitalcreations/MaxTo#620]
**Describe the bug**
When trying to log in, I got a 500 server error. This occurred with every SSO (I'm pretty sure I used Google initially).

**To Reproduce**
1. Go to maxto.net
2. Click "Log In"
3. Click on any of the SSO buttons.
4. Go through the corresponding login flow
5. See that a red page describing an internal server error is shown

**Expected behavior**
Logged into the MaxTo website

**Screenshots**
![image](https://user-images.githubusercontent.com/4794150/94350371-aeb2c300-001b-11eb-84fa-0fa5e1b8020f.png)

**System information:**
- Windows version: Version 2004 (OS Build 19041.506)
- MaxTo version: N/A

Trying to install app

**Comment by vegardlarsen** [comment]
Thank you for your feedback. I was unable to find what caused this for your account in our logs, but I tried all four SSOs myself just now, and they work for our accounts.

So, not wanting to expose your e-mail address on this public forum, I recommend you e-mail me at support@maxto.net, so we can figure out why this happens to your account specifically?
