### ISSUE TITLE
Windows Close after Reposition

### ISSUE THREAD

**Issue by Archithead** [digitalcreations/MaxTo#625]
Hi All,

Using the current stable MaxTo release. 
Often when I move a window to a different locaiton, the window will snap there and after about a second will disappear. If it does stay, and I try to resize it or move it manually, it will close. Any thoughts?

Michael

**Comment by vegardlarsen** [comment]
@Archithead Thank you for your issue. Does this issue still happen with version 2.1.0-beta.5? The easiest way to update is to set your Update channel to Beta in MaxTo's settings, then restart MaxTo twice.

If this continues to happen using that version, and it is limited to a specific program, we can try adding a compatibility shim, but let's cross that bridge when we get to it.

**Comment by Archithead** [comment]
This issue appears to be happening again on Chrome as well as Windows
Explorer. Moving or resizing kills the app that I am trying to resize or
relocate.

**Comment by vegardlarsen** [comment]
@Archithead Could this be issue #476 in a new form? Does it start working again if you apply the registry fix from that issue? Which specific version of Google Chrome is this?

**Comment by Archithead** [comment]
Here's the chrome build. Version 86.0.4240.111 (Official Build) (64-bit)
I don't think it's the same issue. It happens to Windows Explorer, Bluebeam
Revu, Chrome, Revit and a few others. MaxTo seems to work for a while and
after about an hour starts just closing windows that I attempt to move or
resize. I'll write back with more details and see if I can narrow the start
of the occurrence down to a single program. Windows Explorer seems to be
the consistent culprit right now.

**Comment by vegardlarsen** [comment]
What you are describing sounds to me like a crash in each individual program, but it can very well be caused by MaxTo. Please do get back to me with the details. The log files at `%AppData%\MaxTo` could be helpful to look at around the times a program crashes, but it is unlikely to contain anything useful for these kinds of crashes.

**Comment by Archithead** [comment]
So it looks like it happens if I go to move a program after the computer
sits for a few minutes and goes to sleep. Wake it back up, and it crashes
every program I try to adjust. They will still snap to regions without
crashing, but if I adjust them in any way or resize them, they crash.

**Comment by Archithead** [comment]
Furthermore, exiting and restarting MaxTo repairs this behavior and the
program works normally.

**Comment by Archithead** [comment]
Spoke too soon. It crashed again.

**Comment by vegardlarsen** [comment]
When these crashes start to happen, which MaxTo processes are running on your machine? See in Task Manager, under Details, any process starting with `MaxTo.` is of interest.

**Comment by Archithead** [comment]
So
MaxTo (32 bit)
MaxTo.Companion
MaxTo.Companion (32 bit)
MaxTo.Core
MaxTo.Server

are all running. I'm using a 64x system. Do you think this is causing
issues?

Michael

**Comment by vegardlarsen** [comment]
That appears to be all of the required processes. MaxTo fully supports x64-systems, so that should not be an issue.

Are the programs that start crashing all of the same "bitness"? You can check that again in Task Manager, again under Details, right-click the header and choose *Select columns*, then make sure *Platform* is checked and click OK. Now you'll have an extra column that specifies the platform for every process.

**Comment by Archithead** [comment]
They all appear to be 64 bit programs.

**Comment by vegardlarsen** [comment]
Are your regions properly loaded when the computer comes back from sleep? Opening the "Change regions" screen should show your regions. Does it stop crashing after opening "Change regions"?

Which version of Windows are you running? Are there any other window managers running?
