### ISSUE TITLE
feature request: ctrl-shift/windowskey-shift + mousewheel to scroll between active windows?

### ISSUE THREAD

**Issue by ounrequitedo** [digitalcreations/MaxTo#629]
feature request: ctrl-shift/windowskey-shift + mousewheel to scroll between active windows?
That would be great, thanks.

**Comment by vegardlarsen** [comment]
Thank you for your idea. Active windows would mean "open windows" in this case, right?

This should be doable, I can't see any immediate technical hurdles for doing it, but it is something we will have to file in our ideas folder (basically tagged and closed so we can reference it later).

**Comment by ounrequitedo** [comment]
Yes, thank you!
