### ISSUE TITLE
maxto crashing application all the time

### ISSUE THREAD

**Issue by YammYcoding** [digitalcreations/MaxTo#63]
Hi. I'm on windows 8.1 and this app is crashing here all the time. Takes half hour, 20 minutes, 10 minutes, can last some hours, but at some point it will crash again, and I will have to reopen the app.

Apps running regularly on the computer : chrome, phpstorm, eudora, dreamweaver CC, photoshop CC, outlook and notepad. Also skype, icq, evernote, battle.net.

If you have any way of stack tracing for debugging this, please ask me and I'll give it some tries.

[]s

**Comment by llinfeng** [comment]
I am helpless at the same issue (#48), however, a short script written in AHK helped overcome such crashing problem. BTW, had you installed the new release as of 2015.03?

**Comment by vegardlarsen** [comment]
@YammYcoding Look for Exception_<whatever>.zip files in `C:\Program files (x86)\MaxTo`. If there are any files there, send them to me by e-mail (address in app). This is supposed to be automatic crash reporting, and I've received a few crash reports in the last few days, but nothing that I think could be related to this.

Does this appear to be the same issue that @llinfeng is experiencing in #48? If that is the case, let me know and I'll close this case.

**Comment by YammYcoding** [comment]
I downloaded it this week, so I suppose it's the latest version - 2015.2.0.0.

**Comment by vegardlarsen** [comment]
@YammYcoding Try downloading [this file](https://dl.dropboxusercontent.com/u/12591686/MaxTo-crash-1-per-hour.zip). First exit MaxTo, then extract the downloaded file to `C:\Program Files (x86)\MaxTo`, and then start MaxTo. Please let me know if this fixes your crashing issues.

**Comment by YammYcoding** [comment]
Right, just installed here, let's see =]

**Comment by jdunham22** [comment]
I have been having a similar problem.  I move my laptop often between no attached monitors, one attached monitor (at home) and two attached monitors (at work), and the computer is hibernated often when I commute, not sure if that matters.  I am running Windows 7 Pro 64-bit.  MaxTo runs at startup, but it crashes at least once a day when I remember to restart it.  It didn't do that before the December update.  I will try that file and report back

**Comment by YammYcoding** [comment]
Hmm it seems that the error is gone. It's beeing a few days and the crash didn't happen yet. I guess you can consider it fixed for now, thanks ! =D

**Comment by jdunham22** [comment]
Mine does not seem to crash anymore.  Thanks!

**Comment by YammYcoding** [comment]
Don't forget to tell us when you patch the installer, so we can download it ;)

**Comment by jdunham22** [comment]
MaxTo has not crashed since I installed the fix.  Thanks again!

**Comment by vegardlarsen** [comment]
@YammYcoding The installer was patched as of version 2015.03. So it should have been fixed for a while now.
