### ISSUE TITLE
Your website gives 500 error when trying to get my key

### ISSUE THREAD

**Issue by josesimas** [digitalcreations/MaxTo#632]
I logged in to my account, and when I clicked the line in my licences list (Key and billing history button) I got a 500 error instead of being able to download the key to activate the software.

**Comment by vegardlarsen** [comment]
@josesimas Can you reach out to us privately at support@maxto.net with the e-mail address you used to purchase MaxTo so we can fix that issue for you?

**Comment by vegardlarsen** [comment]
This issue has been resolved privately with @josesimas.
