### ISSUE TITLE
broken link 404 on https://docs.maxto.net/how-to/windows-without-maxto 

### ISSUE THREAD

**Issue by RhinoFox** [digitalcreations/MaxTo#633]
In page: https://docs.maxto.net/tutorial/keyboard
is a link to: https://docs.maxto.net/how-to/windows-without-maxto

That's broken.

**Comment by vegardlarsen** [comment]
Thank you for that. I've fixed it now (by removing the link). I meant to write that how-to, but didn't get to it in time.
