### ISSUE TITLE
Old documentation links redirect to localhost

### ISSUE THREAD

**Issue by manuelhuber** [digitalcreations/MaxTo#637]
**Describe the bug**
When opening an old documentation link like _https://maxto.net/en/documentation/configuration%2Flocation_ it redirects you to _localhost:3000_ instead of the usual 404 page

**To Reproduce**

1. Open https://maxto.net/en/documentation/configuration%2Flocation in your browser
2. It opens localhost:3000

**Expected behavior**
It shows me a 404 page or better yet redirects me to the new documentation

**Comment by vegardlarsen** [comment]
Thank you for reporting this issue. I have fixed it, and it will be deployed shortly.
