### ISSUE TITLE
new WinSplit hotkeys not working

### ISSUE THREAD

**Issue by manuelhuber** [digitalcreations/MaxTo#638]
**Describe the bug**
The new WinSplit hotkeys of version 2.1.0 aren't working. The documentation says they should be working out of the box https://docs.maxto.net/tutorial/keyboard

**To Reproduce**
1. Start MaxTo
2. Select a window
3. Press hotkey ctrl+alt+numpad 1 (with and without numpad enabled)
4. Nothing happens

**Expected behavior**
The window moves to the lower left corner of the screen.

**System information:**
- Windows version: Windows 10, Version 1903
- MaxTo version: 2.1.0

**Comment by vegardlarsen** [comment]
@manuelhuber Did you reset your recipes as outlined in the upgrade e-mail? If you upgraded from version 2.0.1, the recipes for using it doesn't exist. You can do this easily from the *Recipes* tab in *Settings*, by clicking *Restore defaults*, then *For this tab*.

**Comment by manuelhuber** [comment]
Ah, I missed that part in the email - I was looking in the wiki for the answer and didn't find it. I also looked in the wiki how to export recipes but didn't find it. I eventually found the option to export a single recipe but that's quite a laborious process, so I just copied the recipes from the config.json and pasted them after resetting.

From my side, this issue is resolved.

Good follow-up tasks would be to update the wiki:
- The "out of the box" hotkeys are just recipes and if you don't see them you need to reset settings on the recipe tab
- How to export recipes (single & export all)

**Comment by vegardlarsen** [comment]
I've made some changes to the docs (should go live in a few minutes), and added a how-to on exporting and importing.

Search functionality would be great, not quite sure the easiest way to do that as of just now.
