### ISSUE TITLE
Feature Request: openning window of certain filetype at certain region

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#64]
I find that I don't have control of where a window would be opened up. It would be better if MaxTo could enable such subscription of filetype to window-region.

Let me know if if should write more.

All the best, 

-Linfeng

**Comment by vegardlarsen** [comment]
MaxTo knows nothing of "file types". It does know about programs though, but this is a very complex issue.

- How do you identify Microsoft Word?
  - By its window class?
  - By the name of the process?
  - By the title of the window?
- It would seem natural to want to place two windows with Microsoft Word in different regions, but MaxTo cannot distinguish between them correctly. If you go by window title MaxTo would almost never get the placement correctly. If you go by window class or the process name, it would always place Word windows in the same region.

This feature is one of the most requested features of MaxTo, but unfortunately it is a lot more complex than what one might initially think.

**Comment by llinfeng** [comment]
At least AHK handles the problem you've described well. It has two options: `ahk_exe` and `ahk_class`, through which I can call windows of certain type to be activated (that is, to restore from minimized view).

To note, in AHK, there is a `groupadd` method, which could be used to "loop through all the processes" of such attribute. The order in "group" is only determined by the order of "window activation". So, there is definitely a way to distinguish processes that share the same name (or window class).

Additionally, the idea is not to dock windows of certain file-type at a certain **all the time**. That is not necessary nor practical. Currently, MaxTo is behaving wildly, and sometimes stubbornly, when it handles the *initial position* of processes. I have no control of where to look for when I start `Gvim.exe`, for example. Per this request, all I am expecting is that Maxto may gain ability to place the window of a newly started process *at a certain region* **initially**, so hat I can know here to look for such new window. I agree that there is no strong reason for docking the window permanently at one region.

If specifying the initial position of windows of certain type should also be so big an obstacle, may you please **explain how MaxTo decides where to put the window of a newly started process**?

**Comment by vegardlarsen** [comment]
MaxTo does not decide where new windows go. The initial position is up to the program itself and Windows to decide. There are built-in mechanisms in Windows which should remember the last know position.

I am reopening this, and will try to investigate once again how to do this. I'm afraid it will feel to confusing when you have programs with multiple windows that you want to place in different regions.

**Comment by llinfeng** [comment]
So, do you know how to manipulate such "last known position"? I have tried the following: 
1. Move the window to a different region using shortcuts in MaxTo, and then **close** the window.
2. Move the window to a different region using `#+Arror`, and then **close** the window.

For both trails, I made sure that the window **closed** was the only the progress running at the time. (i.e. the last window).

However, it turns out that *Windows OS* **does not remember the "last known position"** in that it keeps opening the new windows at the main display "region", regardless of whatever "different region" I had moved the last running window/process. (As I have partition my main display into four regions, it is the one on the top right corner.)

Behavior of windows allocation is also different depending how I open the windows. Calling the window using `*.bat` file will have one starting region and starting the progress using `Run` dialog box will end up with another region. Trying to open the application using keyboard shortcuts defined in `AHK` would have another starting region.

This is exactly what I meant by describing the issue as "wildly" and I count on MaxTo as a solution to such chaotic behavior.

**Comment by vegardlarsen** [comment]
Starting in the 2.0.0 preview releases, you can now use a shortcut key to launch a program and place it in the region you want. In a later preview we will also support doing this from the command line (or scripts). See #220 for information on how to try out the preview.
