### ISSUE TITLE
Recipes don't support loading multiple presets for monitors (possibly) not having serial numbers

### ISSUE THREAD

**Issue by Ephron-WL** [digitalcreations/MaxTo#641]
**Describe the bug**
I've been using the original version for years.  Based on an email I received last night I took the plunge into the new version.  As a developer myself I find your recipe approach ambitious and impressive.  However, my enthusiasm has been squashed by the severity of bugs that make its use impossible and that may require me to return to the pre-version 2.

My three monitors are only enumerated.  I guess they don't have serial numbers.  When I create a recipe within three Load to Preset ingredients, each pointing to a different monitor and save the recipe and I unable to return to the ingredient later and have my previously selected monitor selected again.  Either nothing is selected or the Default is selected.  It is as if the software is not able to remap the monitor to my original selection.

When I try to use the recipe with hot keys it appears that only one of the Load Presets is working for all three monitors, even though I defined separate presets for each monitor.

**To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**System information:**
- Windows version: 
- MaxTo version: 

**Additional context**

**Comment by vegardlarsen** [comment]
Can you clarify that each monitor has no serial number listed under "Monitor details" (available while changing regions)?
