### ISSUE TITLE
Microsoft ToDo windows do not resize and leave a translucent “doppelgänger” window behind

### ISSUE THREAD

**Issue by jmroland** [digitalcreations/MaxTo#642]
When holding shifts or using hot keys to resize and position Microsoft ToDo window in Windows 10, the ToDo task list does not resize, but a second translucent window is created with no text content and that is resized.

To re-produce, hold shift and drag an MS ToDo window or position with hot keys in w10.

What should happen is the MS ToDo task list should be positioned and no second window created.

This is on MS Windows 10 Enterprise 10.0.1863 Build 18363, Lenovo Thinkpad

**Comment by vegardlarsen** [comment]
@jmroland I've tried reproducing this locally, with Microsoft To Do version 2.30.2010.29001, and it works exactly as it should on my machine. The "ghost window" should disappear by itself once you let go of Shift or the left mouse button.

Does the same behavior exist if you use e.g. Notepad or any other program?
