### ISSUE TITLE
Windows stay translucent after snapping to a region

### ISSUE THREAD

**Issue by matsjoonas** [digitalcreations/MaxTo#643]
**Describe the bug**
Quite often, program windows stay translucent after snapping to a region. 

**To Reproduce**
1. Drag a program window to a region
2. Let it snap to place
3. Program window stays translucent

**Expected behavior**
The program window should not stay translucent after snapping to place.

**Screenshots**
https://www.dropbox.com/s/61dhyhjfiv1o6xf/translucent_windows_issue.webm?dl=0

**System information:**
- Windows version: Version 2004 (OS Build 19041.572)
- MaxTo version: 2.1.0

**Comment by vegardlarsen** [comment]
Thank you for reporting this. I have had a look, and made a change that I think will fix this for version 2.1.1. Since we've been in contact before, I'll e-mail you with a private build so you can test this on your machine.
