### ISSUE TITLE
MaxTo crashes when running as Administrator

### ISSUE THREAD

**Issue by gary822** [digitalcreations/MaxTo#648]
Hello,

after deactivate Windows Services and optimized the Windows Startup MaxTo stop Working with the following Error.
In the Errorlog i cant find the Solution to fix that.

Yes i have reinstalled the tool after complete clean uninstall but after that the same error.

Please help i really need this tool.

Best regards

[maxto20201105.log](https://github.com/digitalcreations/MaxTo/files/5495956/maxto20201105.log)
![Error](https://user-images.githubusercontent.com/48492786/98274974-62509080-1f94-11eb-820c-88ed3df7ce4c.png)

**Comment by vegardlarsen** [comment]
@gary822 Can you please elaborate on what you did to deactivate Windows services and "optimize Windows Startup"?

**Comment by gary822** [comment]
@vegardlarsen 

i have only deaktivatet windows services, disable autostart Programms and clean the Registry.
But this are not the Problem because i have undone the optimazions and the Program still not working.

**Comment by vegardlarsen** [comment]
Are you running a non-standard shell?

**Comment by gary822** [comment]
no i dont use a other shell its a normal Windows 10

**Comment by vegardlarsen** [comment]
Try not running MaxTo as admin to see if that helps. You can change the setting in `%AppData%\MaxTo\config.json` (if you haven't made any settings of your own you can just delete that file).

**Comment by gary822** [comment]
can you tell me what key is relevant for the admin run?
Because im use the Admin account on this Windows PC but bevore the crash it works with this account

**Comment by vegardlarsen** [comment]
`startup.runElevated` should be `false`

**Comment by gary822** [comment]
startup.runElevated is false in my options:

[config.json.log](https://github.com/digitalcreations/MaxTo/files/5511777/config.json.log)

**Comment by gary822** [comment]
@vegardlarsen i have delete the config.json for testing but the tool crashed with the new generated config too.

**Comment by vegardlarsen** [comment]
@gary822 Try updating MaxTo to version 2.1.1 (released earlier today). Since you can't run MaxTo, you will need to download the installer. Make sure you uninstall the existing version and rebooting before installing the new version.

**Comment by gary822** [comment]
@vegardlarsen the version is not online at the moment

**Comment by vegardlarsen** [comment]
Give me 10 minutes. Caching issue :)

**Comment by vegardlarsen** [comment]
Deployments are a bit slow today, I am working on it. :)

**Comment by vegardlarsen** [comment]
You should be able to see the release now, @gary822. 😄

**Comment by gary822** [comment]
@vegardlarsen after the update the tool is not starting but now with a other error.

![Unbenannt](https://user-images.githubusercontent.com/48492786/99068892-9982fb00-25ad-11eb-965d-3f7d3a10b719.png)
[config.json.log](https://github.com/digitalcreations/MaxTo/files/5536534/config.json.log)
[maxto20201113.log](https://github.com/digitalcreations/MaxTo/files/5536535/maxto20201113.log)

**Comment by vegardlarsen** [comment]
OK, so you are running MaxTo on an actual Administrator account, without requiring UAC to run?

That could actually be something we need to take into account when starting MaxTo. At the moment, most of MaxTo's core processes should not be elevated, as they don't need to be. Only a few (`MaxTo.Companion.*` and `MaxTo.Core`) is started elevated, the other processes we attempt to de-elevate. What seems to be happening here is that MaxTo cannot de-elevate those processes, and therefore fails (because when running under UAC, running them elevated could lead to leaking privileges to other applications).

I will have to investigate this further to see what we can do about it.

**Comment by gary822** [comment]
yes i use the default Administrator Account on Windows 10 X64 2004 with the default settins in UAC:

![image](https://user-images.githubusercontent.com/48492786/99069949-a0127200-25af-11eb-940b-30fad103b2f1.png)

**Comment by vegardlarsen** [comment]
@gary822 So I activated the Administrator account on my machine (using `net user Administrator /Active:yes`), logged in and installed MaxTo. It does appear to run perfectly fine on my machine. Have you done anything else in particular to "get it to" crash?

**Comment by gary822** [comment]
@vegardlarsen nothing. i have installed the tool clean and the tool will not start.
Maybe MaxTo usses and Windows service wich ist not active?
[Services.log](https://github.com/digitalcreations/MaxTo/files/5547282/Services.log)

**Comment by vegardlarsen** [comment]
MaxTo does not rely on any specific Windows Services. It does rely on `explorer.exe` to do this de-elevation, and has a few fallback options if `explorer.exe` is not running, and I've tested these on a stock Windows install using the Administrator account, and it seems to work here.

If we can't figure out what exactly you've changed on your machine, I am afraid I can't really help. You wrote initially that you "optimized Windows startup". What did you mean by that?

**Comment by gary822** [comment]
@vegardlarsen after completly deinstall and new install i became zwo errors:

1. Error:
![image](https://user-images.githubusercontent.com/48492786/99545323-8f9a3700-29b5-11eb-9152-c8257f44f929.png)

i click on yes

2. Error:
![image](https://user-images.githubusercontent.com/48492786/99545393-a04aad00-29b5-11eb-9da5-2092d47834b0.png)


i have checket the system (chkdsk) and there are no errors on my ssd.

**Comment by gary822** [comment]
@vegardlarsen i have customized the Windows services, the autorun and the registry.
But i have undone the changes

**Comment by vegardlarsen** [comment]
Does MaxTo work if you run it as a standard user?

**Comment by gary822** [comment]
yes with an normal user i become only the first error but it runs:

![image](https://user-images.githubusercontent.com/48492786/99546783-11d72b00-29b7-11eb-9ed1-4d8c7f000d8c.png)

**Comment by gary822** [comment]
i have do an systemrecovery and now maxto is running without any problems.

**Comment by vegardlarsen** [comment]
OK, good to hear. I am closing this issue as it appears that there is nothing else for me to do here, then.
