### ISSUE TITLE
White list - Is there any way to exclude specific programs to affected by MaxTo regions?

### ISSUE THREAD

**Issue by dehghani-mehdi** [digitalcreations/MaxTo#649]
**Is your feature request related to a problem? Please describe.**
I think so, I need to run MaxTo all the times, but I also need to have some programs be in full size and not to resize to MaxTo's regions. I mean when I open them or when I click on Maximize button on their window, I want to have them in full size.

**Describe alternatives you've considered**
For now I disable MaxTo temporary when I want to work with that kind of programs.

I didn't see any related option, so having white list or whatever list to specify programs to not affected by MaxTo would be great option.

**Comment by vegardlarsen** [comment]
We do not currently have a user-controllable block-list for MaxTo. If there are programs that misbehave, we can however add it to our compatibility shims list.

You can also use recipes and keyboard shortcuts to maximize specific windows to the entire monitor. See e.g. the [window:maximize](https://docs.maxto.net/reference/commands/window/maximize) command.

**Comment by dehghani-mehdi** [comment]
No, there is no misbehave, I want that program be in maximize state because working with it in half size (I usually split my monitor in 2 region) is hard.
Your mentioned solution works fine and it's much better than my solution (_temporary disabling MaxTo_).

I don't know if my request is good enough to be in your todo list, so if you like you can close this issue or keep it open.

**Comment by RhinoFox** [comment]
> **Is your feature request related to a problem? Please describe.**
> I think so, I need to run MaxTo all the times, but I also need to have some programs be in full size and not to resize to MaxTo's regions. I mean when I open them or when I click on Maximize button on their window, I want to have them in full size.

This can be achieved in 2.1.0 by pressing Win+Alt+M

**Comment by vegardlarsen** [comment]
@dehghani-mehdi I am closing this issue, because I don't like having open issues that we do not know if we are going to do anything about. I am tagging it so we can easily find it later, however. :)
