### ISSUE TITLE
Problem with Start8

### ISSUE THREAD

**Issue by GeekinaCave** [digitalcreations/MaxTo#65]
Good day
Maxto is a really cool gadget but i have a problem.
 Im using the Start8 software for getting a small version of W8.1 start menu, and every time i start Maxto its kills the function of Start8 letting the start menu in fullscreen, but when close it; Start8 back to function as normal (?).

I hope you can help me

**Comment by vegardlarsen** [comment]
I am uncertain if this is a bug in MaxTo or in Start8. I will have a look at this, and see if I can figure out which is to blame.

**Comment by emeraldcurtain** [comment]
Wanted to jump in and report that I'm seeing the same problem combining W8.1, MaxTo and Start8.

**Comment by digitalchet** [comment]
Yeah, encountered this issue here on Windows 8.1 as well.  Hopefully you can get this sorted out, as it is kind of annoying that it interferes with the user settings.

**Comment by vegardlarsen** [comment]
I have had a good few hours of looking at this now. So far, no real progress.

- Start8 runs under the SYSTEM account, as a service, **without a session**. MaxTo runs as the current user (elevated). Hence, the Start8 process is outside of MaxTo's reach.
- The start menu itself runs as part of `explorer`. It runs in the same session as MaxTo.
- It makes no difference if MaxTo never subclasses `explorer`.
- MaxTo sets a `CBTHook`

I've reached out to Stardock with the hope that we can solve this together.

**Comment by reidrankin** [comment]
Just want to mention that I do NOT see this issue with Start10 on Windows 10. (At least not all the time. I've had the Start10 menu disappear on me a few times, but I'm not prepared to blame it on MaxTo.)

**Comment by vegardlarsen** [comment]
That is good. I have tried Stardock a few times, but I never heard anything back from them.

**Comment by vegardlarsen** [comment]
Closing this because of lack of feedback from Stardock.
