### ISSUE TITLE
while Dragging some windows, cursor is far away

### ISSUE THREAD

**Issue by JCas65** [digitalcreations/MaxTo#650]
When dragging a window, the window is seriously displaced at the left, being difficult to position that window at top of the right side

It only occurs in:
. In the second monitor (4k resolution, not checked other ones)
. MS Office O365 products such as Outlook, Word, Excel,..

**Comment by vegardlarsen** [comment]
I am aware of this issue, and its been with us for a long time. It happens when you drag a window out of a region, and the window restores its previous size, and that previous width places the mouse cursor outside the new size. I am not entirely sure how to fix it though.

**Comment by JCas65** [comment]
If it helps you.
. Open the MS Word (it opens out of any region) in the second monitor directly
. Now, if you move the window it works rightly only the first time (I don't move to any region)
. Next times does not work

If you change the focus to other window, and then comes back to the MS Word, the first time works rightly again. Next times it turns to fail, until you change the focus to other window.

thanks for your attention

**Comment by vegardlarsen** [comment]
This took me a while to figure out, but the issue should now be fixed for version 2.2.0.
