### ISSUE TITLE
Option to ignore missing windows / Trigger multiple recipes with the same hotkey

### ISSUE THREAD

**Issue by Brittliff** [digitalcreations/MaxTo#651]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but it's something that's hindering my current workflow.

**Describe the solution you'd like**
I'm using MaxTo to reset the windows my workspace into the predefined positions I have set up in my recipes. Often some of these windows won't be running, and currently if a step in the recipe is reached where a window can't be found, the recipe just stops there with a message "Could not execute recipe: There is currently no foreground window". 

It would be nice if there was an option to ignore missing windows and continue with the rest of the recipe, or something along those lines.

**Describe alternatives you've considered**
I tried setting up multiple recipes using the same hotkey, but it just doesn't run any of them due to the conflict.

**Comment by vegardlarsen** [comment]
Thank you for your report. Your request does make sense, and it may be something we will end up supporting in the future. I have quite a few ideas for how to improve the recipes feature; error handling is definitely one of them.

Know that I am aware of this, but I don't think it will be quick addition to MaxTo.

I am closing this issue as I won't do anything with this as of today, but we'll keep it around for reference.
