### ISSUE TITLE
Exit From Full Screen Cause Window Position And Size To Change

### ISSUE THREAD

**Issue by hermitpurple746** [digitalcreations/MaxTo#652]
Environment:
Windows 10
Firefox playing youtube video

Step to reproduce:
1. Set Firefox window to fit a MaxTo region
2. Enter full screen video
3. Exit full screen video
4. Observe that the Firefox window has moved and changed size

**Comment by vegardlarsen** [comment]
We're fixing this for version 2.1.1. This is a duplicate of #640, so I am closing this one.
