### ISSUE TITLE
Mikrotik Winbox v3.27 (64bit) / v3.19 (32bit) Crash when MaxTo is running

### ISSUE THREAD

**Issue by balaji-dutt** [digitalcreations/MaxTo#654]
**Describe the bug**
I see that there was a recent issue (#645) about Winbox crashes that was closed, however I'm still seeing the issue on my PC with different builds of Winbox.

**To Reproduce**
1. Ensure MaxTo is running and Compatibility Shims are enabled.
2. Launch either Winbox v3.27 (64bit) or Winbox v3.19 (32bit). Login to a Routerboard device as Admin.
3. Click on System > Scripts. Then Click on the "+" icon to create a new script
4. Click on the Cancel button or Hit the Esc key.

**Expected behavior**
The "New Script" window in Winbox will disappear and Winbox will continue to run.

**System information:**
- Windows version: Windows 10 v1909 (Build 18363.1198)
- MaxTo version: 2.1.0

**Additional context**
* Crash Log for Winbox 3.27 (64bit)
```
Faulting application name: winbox64.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: winbox64.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x000000000002eca0
Faulting process id: 0x65c0
Faulting application start time: 0x01d6b9581513627e
Faulting application path: C:\Program Files\Mikrotik\winbox64.exe
Faulting module path: C:\Program Files\Mikrotik\winbox64.exe
Report Id: 2db810f1-6001-4657-be59-0d250035fdc5
Faulting package full name: 
Faulting package-relative application ID: 
```

*Crash Log for Winbox 3.19 (32 bit)
```
Faulting application name: winbox.exe, version: 0.0.0.0, time stamp: 0x396c382a
Faulting module name: winbox.exe, version: 0.0.0.0, time stamp: 0x396c382a
Exception code: 0xc000041d
Fault offset: 0x000201dd
Faulting process id: 0x57f4
Faulting application start time: 0x01d6b958d4deb065
Faulting application path: C:\Program Files (x86)\Mikrotik\winbox.exe
Faulting module path: C:\Program Files (x86)\Mikrotik\winbox.exe
Report Id: 182a92dc-6739-4e4b-9b71-39ac4dd875d0
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by vegardlarsen** [comment]
This issue should be fixed in version 2.1.1, which I just now pushed the "Release" button for. It should be up on the website in a little while.
