### ISSUE TITLE
Since 13/11/2020 no longer works on a corporate work PC

### ISSUE THREAD

**Issue by mannbarry2** [digitalcreations/MaxTo#655]
The application now fails to launch and installation isn't possible. It was fine before I attempted to upgrade. 

I work for an org with a strict policy on corporate machines. Either they change the policy (most stuff does not install and we use portable apps according to policy) or more likely something no longer works. 2.1.0 refuses to install

I need either a previous build or ideally a portable version for all us folks that work for in Fintech!

**Comment by vegardlarsen** [comment]
@mannbarry2 You can always download previous releases from our [releases page](https://maxto.net/releases). Could you please see if you can find any install logs (I assume that is what is failing) or runtime logs and submit them. Please see [the documentation on log files](https://docs.maxto.net/reference/settings/logs) for where to find the log files. If you are concerned about privacy, you can e-mail them to me at support@maxto.net referencing this case.
