### ISSUE TITLE
Version 2.1.1 is active but is no longer snapping windows to other ones, regions or monitor

### ISSUE THREAD

**Issue by mja09006** [digitalcreations/MaxTo#657]
After the 2.1.1 update everything was still working fine and normal but just today it stopped. I cannot keep my windows organized by using the snapping function. I have restarted computer and issue still persists. Snap settings are turned on and Max.to is active.

I have yet to uninstall and reinstall.

Edit: I am using Windows 10 Pro. Here is other information about my specs:
MOTHERBOARD - ASRock Z390M-ITX/ac Mini ITX
CPU - Intel Core i9-9900K 8-Core 3.6 GHz
SSD - Samsung 970 EVO Plus 1TB
RAM - G.SKILL TridentZ RGB 32GB (2 x 16GB) 3200MHz
POWER SUPPLY - Seasonic Focus Plus 750W Gold
GPU(GRAPHICS) - NVIDIA GeForce RTX 2070 - ZOTAC AMP Extreme

**Comment by mja09006** [comment]
![image](https://user-images.githubusercontent.com/52556927/99155900-3a46e880-268a-11eb-8467-cf42145be8ba.png)

Just uninstalled and tried to reinstall but got this message.

**Comment by mja09006** [comment]
Update: I was not able to install for a while but after restarting my computer I was able to reinstall.

Program reinstalled successfully and I can now snap windows from File Explorer but some are not still working. So far this is what is and is not working:

_NOTE: Centering windows on the screen still works for every program._

**REGARDING SNAPPING WINDOWS**
WORKING: File Explorer, Windows Settings, Windows Calculator, 
NOT WORKING: Notepad, Chrome, Windows Program and Features, Microsoft Edge, Volume Mixer

Should I uninstall and delete every folder/file regarding MaxTo on my C:? I have some folders that remained in local and roaming after uninstalling the first time.

**Comment by bigslick87** [comment]
I'm having the same issues. We need to get an update rolled out ASAP!

**Comment by vegardlarsen** [comment]
The installer error is a separate issue, which happens when you try to run the installer while MaxTo is loaded in memory (and therefore the installer cannot delete the files). We are looking for a replacement for the installer because of this issue.

I can unfortunately not reproduce this issue here; any window I grab to move will snap to any other window. I know you've already rebooted, but rebooting again could help.

**Comment by sycraige21** [comment]
This now happens to me.  Yesterday I turned off MaxTo in order to practice a powerpoint presentation in presenter mode.  Today after turning MaxTo back on I cannot keep my windows organized by using the snapping function. Snap settings are turned on and MaxTo is active. I have uninstalled, cleared all roaming files, downloaded a fresh version and re-installed (now version 2.1.2) and still nothing.

**Comment by vegardlarsen** [comment]
@sycraige21 Even after a reboot? Do the windows you drag turn transparent while you are dragging them?

**Comment by sycraige21** [comment]
> @sycraige21 Even after a reboot? Do the windows you drag turn transparent while you are dragging them?

Not even after a reboot.  The windows do not turn transparent when I am moving them.
I have determined that the regions I selected are present in the background. If I place the window in the appropriate section then maximize, it will maximize to the defined region.  The snapping function, however, is not happening.

**Comment by vegardlarsen** [comment]
If you move the window twice in a row (move, let go, move again, without focusing another program), does the transparency (and the snapping) work then?

**Comment by sycraige21** [comment]
No I am afraid not.

On 17 Nov 2020, at 17:17, Vegard Andreas Larsen <notifications@github.com> wrote:

﻿

If you move the window twice in a row (move, let go, move again, without focusing another program), does the transparency (and the snapping) work then?

**Comment by Mrfuyu** [comment]
Same issue after upgrade to 2.1.1: Chrome, Firefox, Notepad can't be maximized to the region, while MS Excel, File Explorer are working.

Multiple Restart, Un-/Reinstall MaxTo, Delete complete Configuration wasn't helpful. After a downgrade to 2.1.0 everything is working again.

**Comment by alfiewild** [comment]
Same issue for me also.

**Comment by mja09006** [comment]
UPDATE (11/18/2020)

Yes I have done multiple reboots, uninstall > reinstall, etc. and still having the same exact issues. This is also occuring on another computer of mine (laptop) in which my account is synced with.

**Comment by vegardlarsen** [comment]
Please make sure you have version 2.1.2, which was released yesterday.

**Comment by sycraige21** [comment]
I am on version 2.1.2 and there is no improvement with regards this issue.

**Comment by ckas10** [comment]
> I am on version 2.1.2 and there is no improvement with regards this issue.

Same here. Multiple reboots and uninstall/reinstalls. Some windows snap (file explorer for example) but most do not.

**Comment by KimmoJ** [comment]
Snapping has definitely broken or semi broken in the new versions. The whole "hold shift and see white outlines to snap to" thing is gone. Snapping with a mouse - say from one region on screen 2, to another region on screen 1, fails every time, but does "release" the window from the snapped position - after that, you can drag it to another position and snap. But having to do everything twice at least is very aggravating. This is on 2.12.

**Comment by bigslick87** [comment]
I uinstalled, rebooted multiple times and was finally able to clean install 2.1.0. PERFECT.

Shut down my PC last night and it auto-updated to 2.1.2. Everything broken again.

If these issues can't be sorted out, I will have to request a refund.

**Comment by Mrfuyu** [comment]
@bigslick87 To prevent updating, you can deactivate this feature under Settings > Updates > Uncheck automatic updates and then downgrad to 2.1.0. This worked for me.

**Comment by Michael5122** [comment]
Thank you,
looking forward the fix,
Michail

**Comment by vegardlarsen** [comment]
This issue has been fixed for 2.1.3, which is rolling out now.

**Comment by Mrfuyu** [comment]
Just upgraded...chrome, notepad and so on again not draggable...deleted all config, rebooted multiple times...again not working...downgraded to 2.1.0 again...problems solved...

**Comment by ckas10** [comment]
> Just upgraded...chrome, notepad and so on again not draggable...deleted all config, rebooted multiple times...again not working...downgraded to 2.1.0 again...problems solved...

Similar results with 2.1.3 and multiple un/re-installs and reboots. Nothing is draggable/snappable anymore.

**Comment by Michael5122** [comment]
same here guys... :/

**Comment by vegardlarsen** [comment]
I am sorry about this. I can again consistently reproduce this with the released version (2.1.3), however when I build and run MaxTo on my machine (from the exact same source code), the issue has been fixed. I only tested this specific functionality with my local build (as we've never had this problem with the build server apparently building an older release). I am investigating what could have happened here before releasing a new version.

**Comment by vegardlarsen** [comment]
Thank you for sticking with me. This turned out to be a difference in build configurations locally and on our build server. The problem turns out to be [Link Time Code Generation](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=msvc-160), which we've had enabled for Release builds "forever", and it hasn't acted up until now. This could explain a whole host of other errors we've seen.

I am starting a build of 2.1.4 now, and that will be ready within an hour.

**Comment by Michael5122** [comment]
You are invited for a Pizza & Carbonara dinner in Rome Larsen!
Thanks

**Comment by vegardlarsen** [comment]
Grazie mille! :) I am assuming everything works for you now?

**Comment by Michael5122** [comment]
YESS!!!  I hadn't checked that before! thank youuuuuuu!
I have a very large screen and really love the SW
the past week was a mess,
again thank you very much! now all fine.
Michail

**Comment by ckas10** [comment]
Beauty. Thank you!
