### ISSUE TITLE
2.1.1 Windows becoming transparent after moving

### ISSUE THREAD

**Issue by RegisDahma** [digitalcreations/MaxTo#659]
MaxTo V 2.1.1
windows build 19041.572

Have transparent windows on dragging turned off, however almost every time that I move my discord window, and at random for other windows, the window will become permanently transparent.  

Happens especially often when maximizing a window on my second monitor which is just one region for the whole screen.

**Comment by vegardlarsen** [comment]
Please see issue #656 for a workaround. Closing this issue as a duplicate.
