### ISSUE TITLE
system hook errors cant get maxto to work on windows 7

### ISSUE THREAD

**Issue by chopin1968** [digitalcreations/MaxTo#66]
I have two windows 7 coms cant get it to work, monitor shows the split screens but they arn,t splitting,ran the test in options I have the system hook errors on both monitors and both coms many thanks

**Comment by Swoy** [comment]
I have the same issue, the MaxTo system hooks will not bind. Upon restart, the tray icon is not visible either - even though the program is running.

**Comment by vegardlarsen** [comment]
Normally these kinds of issues solve themselves after a reboot. If that is not the case here, check and see if MaxTo.Helper32.exe and MaxTo.Helper64.exe is running. If they are, try uninstalling, rebooting and reinstalling MaxTo.
