### ISSUE TITLE
Windows turn transparent regardless of setting and then never become opaque again

### ISSUE THREAD

**Issue by okand** [digitalcreations/MaxTo#662]
**Describe the bug**
When moving windows they go transparent and then just stay that way until closed and reopened regardless of what the transparent windows setting in MaxTo is set to. I have it turned off and suddenly now that MaxTo had updated to version 2.1.1 windows started turning transparent on me.

I've noticed this happening in several apps I regularly use on my work computer. Firefox, Outlook, Explorer, and Windows Terminal.

**To Reproduce**
1. Launch MaxTo
1. Move a window
1. The window goes transparent
1. The window then never returns to being opaque again

**Expected behavior**
1. Launch MaxTo
1. Move a window
1. The window has moved and is still fully opaque

**System information:**
- Windows version: Version 1909 (OS Build 18363.1198)
- MaxTo version: 2.1.1

**Additional context**
I only really use MaxTo to position a few windows on startup so I can put them in their zones, launch MaxTo and maximize the windows, followed by turning off MaxTo again so that it doesn't ruin any additional windows with transparency. But that is a bad workaround.

**Comment by vegardlarsen** [comment]
Please see issue #656, and make sure you have updated to version 2.1.2, which was released yesterday.

To update, restart MaxTo twice (that triggers both download and install of a new release using automatic updates), and then reboot or restart the applications that have permanently transparent windows.

Closing this issue as a duplicate.
