### ISSUE TITLE
Chrome window reduces to small dimentions every time i stick it from one region to another.

### ISSUE THREAD

**Issue by Michael5122** [digitalcreations/MaxTo#663]
Please look at the following screenshots:
1) there are my regions. Screen is a 49' philips 499P
2) I open chrome,  then I decide to stick it to my central region
3) it disappears
4) I click it on the taskbar two times and then it appears in super-reduced dimensions.
5) I maximize it and then move it slowly and manually to fit my central region, it doesn't stick automatically.

It used to happen a couple of times a day, now happens all the time.
I think it happens only with chrome.
Please help! it's so annoying
Kind regards
Michail

![1](https://user-images.githubusercontent.com/65541736/99550855-772d1b00-29bb-11eb-817c-79f394b7cc42.png)
![2](https://user-images.githubusercontent.com/65541736/99550869-7a280b80-29bb-11eb-98f2-c1d268e83024.png)
![3](https://user-images.githubusercontent.com/65541736/99550878-7bf1cf00-29bb-11eb-8c5d-b4f191d53606.png)
![4](https://user-images.githubusercontent.com/65541736/99550883-7dbb9280-29bb-11eb-86c0-ffc8740df581.png)
![5](https://user-images.githubusercontent.com/65541736/99550889-801dec80-29bb-11eb-8d6d-1d2d5e52e58c.png)

**Comment by vegardlarsen** [comment]
Can you upload [your log files](https://docs.maxto.net/reference/settings/logs) from around when this happens so I can have a look? If you are concerned about privacy, you can send them to me at support@maxto.net referencing this issue, and I'll extract the important parts.

**Comment by Michael5122** [comment]
Sent, thank you!
Michail

**Comment by vegardlarsen** [comment]
There are a lot of these in the log `[MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "<some window>" (0x"20486"), used mouse position to find region "{X=3944,Y=0,Width=1176,Height=694}".` I am quite sure this does not affect this functionality, but besides these messages I could not find any seemingly relevant messages.

@Michael5122 Is there any possibility that you could record a video of this happening, starting from when you start Chrome (it is important that you do not have any open Chrome windows before).

**Comment by Michael5122** [comment]
Created video and sent via email (youtube link)
Kind regards
Michail

**Comment by Michael5122** [comment]
> There are a lot of these in the log `[MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "<some window>" (0x"20486"), used mouse position to find region "{X=3944,Y=0,Width=1176,Height=694}".` I am quite sure this does not affect this functionality, but besides these messages, I could not find any seemingly relevant messages.
> 
> @Michael5122 Is there any possibility that you could record a video of this happening, starting from when you start Chrome (it is important that you do not have any open Chrome windows before).

The video I sent was done after restarting pc and with no other program opened.
The only programs that were running while I did the video were some file-sharing files working in the background (Syncplicity, google drive, one drive, Lightshot for screen capture, nothing else).

**Comment by vegardlarsen** [comment]
From your video, it appears that Chrome is resized back to its "last known size", but that the last known size is wrong. It appears to happen when you drag Chrome out of a region the first time. Am I right to assume that Shift+drag does not work with Chrome in your case?

**Comment by Michael5122** [comment]
> From your video, it appears that Chrome is resized back to its "last known size", but that the last known size is wrong. It appears to happen when you drag Chrome out of a region the first time. Am I right to assume that Shift+drag does not work with Chrome in your case?

Hello Larsen!
thanks for ur support,
- No, this is not the last known position, i have resized it manually many times with the hope that when gets ungry will go back to a bigger window, it keeps turning back in that small one.
- No also to the second thought, usually, after restarting my pc, for a couple of movements works fine. Then when I change region it turns to the small one. 
- No also to the third note, Shift+Drag is not working, it does an even stranger thing creating a semi-transparent big window and the famous small one. Then I have to kill chrome in order to remove the big semitransparent window. Please look at the screenshot:

![image](https://user-images.githubusercontent.com/65541736/99947643-94296b80-2d78-11eb-9728-0077db90d389.png)

**Comment by Michael5122** [comment]
let me know if you want a skype call to see the issue, or if i can help you in anyway.
My skype ID is name.surname (like my email).
Regards

**Comment by vegardlarsen** [comment]
This appears to be the same as #657, but with a different manifestation. Closing this as a duplicate.
