### ISSUE TITLE
Chrome isn't working any more

### ISSUE THREAD

**Issue by PaulWendt** [digitalcreations/MaxTo#666]
I'm not sure if it's due to a recent Chrome update, or a MaxTo update, but chrome isn't snapping any more.  When i double-click on the window title, it maximizes to full screen.  I'm on 2.1.2 of MaxTo.  This worked until recently.

I haven't seen problems with any other apps, even Edge.  I'd like to get MaxTo to work with Chrome again, though.  

Any ideas?

**Comment by PaulWendt** [comment]
In case anyone else runs into this (or something similar), even though I cannot maximize the application to a region (it maximizes to the monitor, instead), I am able to use the recipes Window+Arrows to move the app around, and it does respect the region boundaries.  

So, even if we don't get double-click to work on the app, we can use the recipes as a workaround.

**Comment by 1234Matt** [comment]
I am using this app first time and apparently, it is a bug, I thought the app is trash :D :D
Hope it will be solved soon :)

**Comment by BlackOpzFX** [comment]
I have same issue and came to the blog wondering why? I can get some apps to respect the regions but Chrome/Opera dont. Chrome/Opera also wont go transparent on drap/resize. Microsoft Edge snaps to regions but doesnt go transparent. Think it happened within the last update or two.

**Comment by vegardlarsen** [comment]
I can confirm that this is now happening on my machine as well; so I will hopefully be able to figure this out shortly.

**Comment by BlackOpzFX** [comment]
Can verify that 2.1.0 Works. I have a 'TV' PC that hasn't been restarted for weeks. 2.1.0 is still installed and works PERFECTLY with Chrome. Hopefully, we'll get a fix for the current version soon. Ver 2.1.2 is sitting on the machine waiting for a RESTART to Activate.

**Comment by vyrru5** [comment]
i downgrade version too, i got 2.1.0.

**Comment by vegardlarsen** [comment]
This has the same cause as #663, and a fix is coming for this issue shortly.

**Comment by Mrfuyu** [comment]
2.1.3 doesn't solve this for me :/

**Comment by vegardlarsen** [comment]
@Mrfuyu Have you rebooted your computer since the update?
