### ISSUE TITLE
transparency doesn't work at some programs.

### ISSUE THREAD

**Issue by wld159** [digitalcreations/MaxTo#667]
**Describe the bug**

Although the snapping and keyboard shortcuts work at visual studio 2017 and some programs, Transparency doesn’t work. 
   [maxto window transparency /amount "100"]

In my case, visual studio 2017 and FORK(https://git-fork.com). 

**Expected behavior**

**System information:**
- Windows version: 20H2(OS build 19042.630)
- MaxTo version: 2.1.2

**Additional context**

**Comment by vegardlarsen** [comment]
Thank you for reporting this. I am assuming this has the same cause as #663 and #666. PLease let me know if that is note the case. Closing this as a duplicate.
