### ISSUE TITLE
Stop windows from moving off screen

### ISSUE THREAD

**Issue by drozzy** [digitalcreations/MaxTo#67]
Currently it is possible to move the window completely off-screen.
There is no way to drag it back.

Let me know when this is fixed - and I'll buy it then.

**Comment by vegardlarsen** [comment]
@drozzy Can you please explain how you move a window off-screen? Since I haven't received any reports of this earlier, and have never experienced it myself, I really don't know how this could happen.

**Comment by drozzy** [comment]
Basically, when I am moving a window if I drag it too fast to the left, it may actually go off-screen.

**Comment by vegardlarsen** [comment]
@drozzy I think I am going to need a video to understand what you mean here.

**Comment by drozzy** [comment]
Sorry, can't seem to reproduce it. You can close it for now - if I have the problem again I'll video it.
