### ISSUE TITLE
Installer.exe not checking path in task scheduler

### ISSUE THREAD

**Issue by RhinoFox** [digitalcreations/MaxTo#670]
I had 2.1.1 installed in c:\Util\Maxto
When I ran MaxToSetup-2.1.2.exe it installed MaxTo in c:\Users\<xxx>\AppData\Local\MaxTo\app-2.1.2\
Because my config is in m:\....\MaxTo.config I had to copy my config file.

I noticed MaxTo won't start at Windows Start.

1. Why wasn't MaxTo installed in c:\Util\Maxto
2. Why isn't the MaxTo entry in the task scheduler not adjusted
   I did it myself to c:\Users\<xxx>\AppData\Local\MaxTo\MaxTo.Core.exe
3. How to install Maxto in c:\Util\Maxto with an automated update. 
   The Install.exe must be capable of checking the old location and config I presume.

BTW. I still run 2.1.2 but there but as I write there is a new dir ...\Local\MaxTo\app-2.1.3
I now have c:\Users\<xxx>\AppData\Local\MaxTo\ with the dirs ..\app-2.1.2 and ...\app-2.1.3
After stop/start it's updated but.... My own config file is gone. Not pointing to m:\....\MaxTo.config #$&(*Q#&$*

[maxto20201124.log](https://github.com/digitalc
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/5590654/SquirrelSetup.log)
reations/MaxTo/files/5590643/maxto20201124.log)

**Comment by vegardlarsen** [comment]
Thank you for your report. Unfortunately, the installer does not support installing in other directories than `%LocalAppData%\MaxTo`. If you have MaxTo "installed" in another folder, you've probably used the ZIP file to extract it there. To update, you will need to download the ZIP file and overwrite the existing installation. The installer does not know anything about your other "installation".

So you either use the ZIP file and lose automatic updates, or you use the installer and have it in the default folder.

I hope that clears it up.

**Comment by RhinoFox** [comment]
maybe e feature request?!?

**Comment by vegardlarsen** [comment]
I will keep this in mind when we switch out the installer, but I don't think a custom install location will be very high on my list of priorities (if that is something we can decide at all).
