### ISSUE TITLE
Sign... I wrote issue #657 - Chrome and other apps working but now Windows Explorer is NOT

### ISSUE THREAD

**Issue by mja09006** [digitalcreations/MaxTo#672]
**Describe the bug**
2.1.4 update fixes chrome, windows notepad and other applications but now the issue changed over to Windows File Explorer, which previously WAS working.

**To Reproduce**
1. Open a window from File Explorer
2. Click on the top of the window to move the window.
3. Able to move window but it will not turn transparent or snap to any other window/region/screen edge.

**Expected behavior**
Windows File Explorer windows should be transparent when being dragged and able to snap to other windows as well as the edge of my monitor/screen.

MOTHERBOARD - ASRock Z390M-ITX/ac Mini ITX
CPU - Intel Core i9-9900K 8-Core 3.6 GHz
SSD - Samsung 970 EVO Plus 1TB
RAM - G.SKILL TridentZ RGB 32GB (2 x 16GB) 3200MHz
POWER SUPPLY - Seasonic Focus Plus 750W Gold
GPU(GRAPHICS) - NVIDIA GeForce RTX 2070 - ZOTAC AMP Extreme
FAN - NZXT Aer RGB 2 120mm Fan x 2
CPU COOLING - NZXT Kraken X52 x 1
CASE - NZXT H200i x 1
- MaxTo version: 2.1.4

**Comment by Mrfuyu** [comment]
I have exactly the same issue now :D

**Comment by vegardlarsen** [comment]
@mja09006 Can you e-mail me at support@maxto.net so I can set you up with a test build that hopefully fixes the problem?

**Comment by mja09006** [comment]
This is mja09006 btw Sent from Mail for Windows 10 From: Vegard Andreas LarsenSent: Thursday, November 26, 2020 9:17 AMTo: digitalcreations/MaxToCc: mja09006; MentionSubject: Re: [digitalcreations/MaxTo] Sign... I wrote issue #657 - Chrome and other apps working but now Windows Explorer is NOT (#672) @mja09006 Can you e-mail me at support@maxto.net so I can set you up with a test build that hopefully fixes the problem?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
