### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by RobvanB** [digitalcreations/MaxTo#673]
Recently MaxTo seems to be using quite a bit of system resources.

MaxTo 2.1.4
Windows 10
Dell XPS 13 with external monitor

![maxtoCPU](https://user-images.githubusercontent.com/118380/100464502-b9c9b400-309b-11eb-8628-2243bc2779a3.jpg)

**Comment by vegardlarsen** [comment]
@RobvanB Restarting MaxTo should reset it temporarily. Then e-mail me at support@maxto.net and I'll get you a preview that fixes this issue.
