### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by DCGphos** [digitalcreations/MaxTo#674]
Hi

I purchased software today, but option drag don't work on my computer, when i move window don't show me option to put on one space

**Drag
Put any window into a region by holding Shift while dragging.**

Edition	Windows 10 Pro
Version	20H2
Installed on	‎25/‎11/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

Device name	WorkStation64
Processor	AMD Ryzen 7 3800X 8-Core Processor                3.90 GHz
Installed RAM	32.0 GB
Device ID	ED5E9032-3C73-452D-BC49-BFB01FEC5B52
Product ID	00330-80000-00000-AA378
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

I appreciate your help

**Comment by vegardlarsen** [comment]
Thank you for your report. Does this happen to any program, even simple ones such as Notepad? Does it persist after a reboot? Are you holding down Shift?

**Comment by DCGphos** [comment]
Good morning gentlemen
The problem solved by holding down the shift key, thank you for your help. Where I can find information about how to use the software? I appreciate your help.
Thanks
DCG

**Comment by vegardlarsen** [comment]
Great. We do have [documentation](https://docs.maxto.net) available, but please do let us know if there is anything in particular you would like to be covered.
