### ISSUE TITLE
unable to download new versions of max to.

### ISSUE THREAD

**Issue by podgfreak** [digitalcreations/MaxTo#677]
I have uninstalled maxto but I cannot download new version. I believes there is a current version running i believe. 
   Please fill in as many details as you can. 
   Text in comments (

**Describe the bug**

**To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**System information:**
- Windows version: 
- MaxTo version: 

**Additional context**

**Comment by vegardlarsen** [comment]
Do you mean that you cannot install the downloaded version? If you send me the log file I would assume it says something along these lines: `IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\%username%\AppData\Local\MaxTo\app-2.1.5\MaxTo.Hook.x86.dll' is denied.`

This issue can be fixed by:

1. Uninstalling MaxTo.
2. Rebooting.
3. Installing MaxTo again, taking care to only run the installer once.

**Comment by podgfreak** [comment]
It appears it is running but chrome is still not snapping to the windows

[https://drive.google.com/uc?id=1LiWxx7ih1D7SquEKyboad5ax5_nkEgT0]
[https://drive.google.com/uc?id=1MZxJFRiGipMd5zAPUBbv0Z95tyvZvVvF]
[facebook]<https://www.facebook.com/granthomeloans>
[linkedin]<https://www.linkedin.com/in/grantthemortgagebroker>
Grant  Alexander

Broker/Owner

Rapid Home Finance

NMLS #796642

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
616-304-4164<tel:616-304-4164>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
grant@rapidhomefinance.com<mailto:grant@rapidhomefinance.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.RapidHomeFinance.com<https://www.rapidhomefinance.com/>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
4301 Canal Ave SW, Suite G, Grandville, MI 49418


CONFIDENTIALITY AND PRIVILEGE NOTICE This electronic mail transmission and any attachment may contain confidential, proprietary, and/or legally privileged personal information, as that term is defined in the Gramm-Leach-Bliley Act (collectively, Confidential Information), intended for the named recipient(s) only. Any review, use, disclosure, distribution, copying or other action regarding the information contained in this transmission and any attachment by an unnamed recipient is legally prohibited. If you are not a named recipient, immediately call me at 800-555-2098 or send a reply email and then delete and purge this transmission and any attachment from your computer system. Thank you.

________________________________

**Comment by vegardlarsen** [comment]
@podgfreak Please try rebooting your computer before trying again.

**Comment by podgfreak** [comment]
I did. I was able to download the 2.1.5 but it still doesnt snap

[https://drive.google.com/uc?id=1LiWxx7ih1D7SquEKyboad5ax5_nkEgT0]
[https://drive.google.com/uc?id=1MZxJFRiGipMd5zAPUBbv0Z95tyvZvVvF]
[facebook]<https://www.facebook.com/granthomeloans>
[linkedin]<https://www.linkedin.com/in/grantthemortgagebroker>
Grant  Alexander

Broker/Owner

Rapid Home Finance

NMLS #796642

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
616-304-4164<tel:616-304-4164>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
grant@rapidhomefinance.com<mailto:grant@rapidhomefinance.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.RapidHomeFinance.com<https://www.rapidhomefinance.com/>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
4301 Canal Ave SW, Suite G, Grandville, MI 49418


CONFIDENTIALITY AND PRIVILEGE NOTICE This electronic mail transmission and any attachment may contain confidential, proprietary, and/or legally privileged personal information, as that term is defined in the Gramm-Leach-Bliley Act (collectively, Confidential Information), intended for the named recipient(s) only. Any review, use, disclosure, distribution, copying or other action regarding the information contained in this transmission and any attachment by an unnamed recipient is legally prohibited. If you are not a named recipient, immediately call me at 800-555-2098 or send a reply email and then delete and purge this transmission and any attachment from your computer system. Thank you.

________________________________

**Comment by vegardlarsen** [comment]
@podgfreak Does it work on simpler applications such as Notepad? Which functionality are you trying to use (maximize button, Shift+drag)?

**Comment by podgfreak** [comment]
Note pad will work. I am using maximize button


[https://drive.google.com/uc?id=1LiWxx7ih1D7SquEKyboad5ax5_nkEgT0]
[https://drive.google.com/uc?id=1MZxJFRiGipMd5zAPUBbv0Z95tyvZvVvF]
[facebook]<https://www.facebook.com/granthomeloans>
[linkedin]<https://www.linkedin.com/in/grantthemortgagebroker>
Grant  Alexander

Broker/Owner

Rapid Home Finance

NMLS #796642

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
616-304-4164<tel:616-304-4164>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
grant@rapidhomefinance.com<mailto:grant@rapidhomefinance.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.RapidHomeFinance.com<https://www.rapidhomefinance.com/>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
4301 Canal Ave SW, Suite G, Grandville, MI 49418


CONFIDENTIALITY AND PRIVILEGE NOTICE This electronic mail transmission and any attachment may contain confidential, proprietary, and/or legally privileged personal information, as that term is defined in the Gramm-Leach-Bliley Act (collectively, Confidential Information), intended for the named recipient(s) only. Any review, use, disclosure, distribution, copying or other action regarding the information contained in this transmission and any attachment by an unnamed recipient is legally prohibited. If you are not a named recipient, immediately call me at 800-555-2098 or send a reply email and then delete and purge this transmission and any attachment from your computer system. Thank you.

________________________________

**Comment by vegardlarsen** [comment]
If you drag Chrome around, does the Chrome window become transparent?

**Comment by podgfreak** [comment]
No it is not transparent when dragged

[https://drive.google.com/uc?id=1LiWxx7ih1D7SquEKyboad5ax5_nkEgT0]
[https://drive.google.com/uc?id=1MZxJFRiGipMd5zAPUBbv0Z95tyvZvVvF]
[facebook]<https://www.facebook.com/granthomeloans>
[linkedin]<https://www.linkedin.com/in/grantthemortgagebroker>
Grant  Alexander

Broker/Owner

Rapid Home Finance

NMLS #796642

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
616-304-4164<tel:616-304-4164>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
grant@rapidhomefinance.com<mailto:grant@rapidhomefinance.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.RapidHomeFinance.com<https://www.rapidhomefinance.com/>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
4301 Canal Ave SW, Suite G, Grandville, MI 49418


CONFIDENTIALITY AND PRIVILEGE NOTICE This electronic mail transmission and any attachment may contain confidential, proprietary, and/or legally privileged personal information, as that term is defined in the Gramm-Leach-Bliley Act (collectively, Confidential Information), intended for the named recipient(s) only. Any review, use, disclosure, distribution, copying or other action regarding the information contained in this transmission and any attachment by an unnamed recipient is legally prohibited. If you are not a named recipient, immediately call me at 800-555-2098 or send a reply email and then delete and purge this transmission and any attachment from your computer system. Thank you.

________________________________

**Comment by vegardlarsen** [comment]
Do the hotkeys work (Windows+arrow keys)? Is Chrome running as Administrator?

**Comment by podgfreak** [comment]
Windows and arrow keys work


[https://drive.google.com/uc?id=1LiWxx7ih1D7SquEKyboad5ax5_nkEgT0]
[https://drive.google.com/uc?id=1MZxJFRiGipMd5zAPUBbv0Z95tyvZvVvF]
[facebook]<https://www.facebook.com/granthomeloans>
[linkedin]<https://www.linkedin.com/in/grantthemortgagebroker>
Grant  Alexander

Broker/Owner

Rapid Home Finance

NMLS #796642

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
616-304-4164<tel:616-304-4164>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
grant@rapidhomefinance.com<mailto:grant@rapidhomefinance.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.RapidHomeFinance.com<https://www.rapidhomefinance.com/>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
4301 Canal Ave SW, Suite G, Grandville, MI 49418


CONFIDENTIALITY AND PRIVILEGE NOTICE This electronic mail transmission and any attachment may contain confidential, proprietary, and/or legally privileged personal information, as that term is defined in the Gramm-Leach-Bliley Act (collectively, Confidential Information), intended for the named recipient(s) only. Any review, use, disclosure, distribution, copying or other action regarding the information contained in this transmission and any attachment by an unnamed recipient is legally prohibited. If you are not a named recipient, immediately call me at 800-555-2098 or send a reply email and then delete and purge this transmission and any attachment from your computer system. Thank you.

________________________________

**Comment by vegardlarsen** [comment]
>  Is Chrome running as Administrator?
