### ISSUE TITLE
Windows snapping just below taskbar

### ISSUE THREAD

**Issue by alfiewild** [digitalcreations/MaxTo#678]
**Describe the bug**

When snapping a window, for instance Excel, the bottom of the window snaps below the task bar. In the case of excel it means that you are unable to click on new tabs within workbooks. This sometimes resolves itself after a reboot, but seems to randomly happen after that.
**To Reproduce**

1. Open a new window (Can confirm this behavior on at least Excel and Chrome)
2. Snap it to a Region
3. Part of the window will be obscured by the windows task bar

**Expected behavior**

The Window should snap so it touches the taskbar
**Screenshots**

https://i.imgur.com/zN38gjA.png

**System information:**
- Windows version:  Windows Version 1903 (OS Build 18362.1198)
- MaxTo version:  Maxto: 2.1.5

**Additional context**
In chrome, if you download an image and you see it sitting at the bottom of the page, when snapped the download is obscured

Unsnapped - https://i.imgur.com/V0yi69g.png
Snapped - - https://i.imgur.com/3E23yJl.png

**Comment by vegardlarsen** [comment]
This is unfortunately a known issue. It relates to how Windows refuses to give MaxTo updated information about the size of the working area (which is the area that the taskbar doesn't cover) until the taskbar is moved or changes size. You can move the taskbar to another location and back (or resize it), and MaxTo should pick it up immediately.
