### ISSUE TITLE
Windows doesn't fill all space

### ISSUE THREAD

**Issue by BenDavidson90** [digitalcreations/MaxTo#679]
**Describe the bug**
Windows doesn't fill all dedicated space when maximized whatever the application. There are empty space between left and right borders of each windows where we see desktop wallpaper (purple bars in my screenshots). 
Tried with all snapping settings (window edges, region edges, monitor edges) with no result.

**To Reproduce**
1. Make two zones (left: 1281x1400, right: 2159x1400)
2. Move one windows to left and one to right
3. Maximise each window
4. See that windows doesn't fill correctly: left window is 1278x1399, right window is 2158x1399

**Expected behavior**
Windows should fill all the dedicated spaces.

**Screenshots**
![Zones](https://user-images.githubusercontent.com/7091140/101627487-b7157a00-3a1e-11eb-89a5-8e1f9e9d74df.png)
![Result](https://user-images.githubusercontent.com/7091140/101627516-c1377880-3a1e-11eb-98e4-e82f56171e1a.png)

**System information:**
- Windows version: 20H2 (19042.630)
- MaxTo version: 2.1.5

**Additional context**
- Windows display scale is 100%
- Resolution is 3440x1440 (UWQHD)
- Config: [config.txt](https://github.com/digitalcreations/MaxTo/files/5665659/config.txt)

**Comment by vegardlarsen** [comment]
On your machine, does this also happen with other programs. I like to test this with Notepad, as it is the simplest program around.

**Comment by BenDavidson90** [comment]
Yes, it's the same with other programs.
Like I said I tried with several applications (including Notepad first, I thought the same thing as you: if the simplest program has the problem then the problem exists 😄).

**Comment by vegardlarsen** [comment]
Does the problem go away if you turn on "Show accent color on the following surfaces: Title bars and window borders" in Windows settings, under Personalization, Colors?

![image](https://user-images.githubusercontent.com/436508/101640109-60b13700-3a30-11eb-91af-1dc42a2c285c.png)

**Comment by BenDavidson90** [comment]
Sort of. The borders replaces the empty space (but the border are only displayed on the active window). It's as if your application constantly takes the borders into account even if they're not there.

**Comment by vegardlarsen** [comment]
OK, I understand. This is weird, as we specifically ask Windows for the sizes of these invisible borders, and adjust for them. I am currently running the exact same Windows and MaxTo builds as you are, and the edges align perfectly here. 

I am assuming you've rebooted since experiencing this?
