### ISSUE TITLE
After defining regions and saving, regions resize on their own

### ISSUE THREAD

**Issue by blendtuts** [digitalcreations/MaxTo#680]
Hi! I was looking into creating a window setup with specific measures, as I need to record a region of my screen and I need that region to be recorded to measure 1920x1080. For that to happen, the region itself has to be slightly bigger, to account for the Windows header and window borders (1922x1111 is what was giving me good results).

The issue comes when I set up the regions, apply them, and then find that the window is misaligned. I go back to check and adjust the regions, and see that the size of the main region changed on its own to 1919x1105.

It happens every time after I adjust the size of the regions again.

I use an Ultrawide monitor (3440x1440). This is the distribution I'm aiming for:

![Screen Distribution](https://user-images.githubusercontent.com/58919650/101638888-ef24b900-3a2e-11eb-98a5-1da75443ecf2.jpg)

Is it possible that regions around that one need to have a minimum height or something like that? If that's the case, is it possible to override that minimum, as those areas won't be used? (suggestion: an option to make some regions disabled so that windows don't snap to them would be helpful, as some regions are byproducts of the real desired ones, but not meant for windows to be adapting to them).

Windows 10
MaxTo v.2.1.5.732

Thanks!

**Comment by vegardlarsen** [comment]
Unfortunately, we are aware of this issue, and we've compensated for it as much as we can with the current limits of the underlying tech stack.

My suggestion for you, would be to create the main region a bit larger than what you intend to use, so you have a bit of padding on each side of the 1922x1111 window you need, and then use a recipe to place the window into an exact position, using the [`window:cycle-position`](https://docs.maxto.net/reference/commands/window/cycle-position) command. The documentation is a bit lacking, but you'd need to set the `window` and `positions` (to something like `145px,598px,1922px,1111px` from your image) to place it.

I hope that helps.
