### ISSUE TITLE
Chrome, Chromium & Electron apps no longer 'snap'

### ISSUE THREAD

**Issue by lucaslink** [digitalcreations/MaxTo#682]
**Describe the bug**
Chrome, Chromium and Electron apps no longer snap to other windows or to set regions.
This is a new (for me) behavior after upgrading MaxTo to 2.1.2.717 and Chrome to v87.

**To Reproduce**

1. Open Chrome
2. Move or resize window in attempt to snap it to other windows or regions

**Expected behavior**
Windows snap to other windows or regions

**System information:**
- Windows version: Windows 10 Pro 1909
- MaxTo version: 2.1.2.717

lease see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log` 
-->

**Comment by vegardlarsen** [comment]
@lucaslink Can you please try upgrading to the latest version of MaxTo (2.1.5) before retrying?

**Comment by lucaslink** [comment]
@vegardlarsen that fixed it! thanks!
new issue that was introduced with 2.1.2.717 and persists with 2.1.5 is a 1-2px gap between windows and monitor edges.

**Comment by vegardlarsen** [comment]
Please see issue #679 for the gap issue. We are not sure what causes it yet. I am closing this one as it has been solved.
