### ISSUE TITLE
Dragging the settings window is EXTREMELY slow with cursor lag

### ISSUE THREAD

**Issue by Connormgs** [digitalcreations/MaxTo#684]
**Describe the bug**
When you open the settings window and attempt to drag the window your cursor will go extremely slow and the window will slowly drag itself over and you can't interact with the window in any way until it is completed. 

**To Reproduce**

1. Install maxto
2. Open the settings window
3. Attempt to move the window

**Expected behavior**
Window should move with the same speed as the cursor instantaneously, not taking 10+ seconds to move across the screen. 

**Screenshots**
NA

**System information:**
- Windows version: Version 20H2 (OS Build 19042.685)
- MaxTo version: 2.1.5

**Additional context**

**Comment by vegardlarsen** [comment]
We are aware of this issue, but we have not yet been able to figure out exactly what is causing it. It doesn't happen on all machines, but we have reports that it may be even slower when running over RDP with multiple monitors connected.

**Comment by Connormgs** [comment]
> 
> 
> We are aware of this issue, but we have not yet been able to figure out exactly what is causing it. It doesn't happen on all machines, but we have reports that it may be even slower when running over RDP with multiple monitors connected.

I have two monitors on my system with an Nvidia GPU, not using RDP. Any log files I might be able to grab or additional system information that could help you out?

**Comment by vegardlarsen** [comment]
@Connormgs Not that I am aware of at this time. This is quite confounding, as it isn't really slow on all machines, but I have seen this happen myself, but I haven't been able to catch it properly under a profiler, so I don't know what causes it.

**Comment by repentsinner** [comment]
Can confirm that this reproduces here with MaxTo 2.1.5

Windows:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎7/‎22/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

NVidia P6000 on 430.86 (a little behind, will update and report back)

**Comment by vegardlarsen** [comment]
I have found that this is strongly related to the background acrylic we are applying, and removing the effect will cause this problem to be almost completely mitigated. As of version 2.2.0, we remove the acrylic effect on all of the MaxTo windows, and instead will use battleship gray where the acrylic effect used to be. When resizing regions, the gray will become partially transparent allowing you to see the window border underneath, which is a nice bonus.

All in all, MaxTo will look less designed, but will perform quite a bit faster.

See also issue #686.
