### ISSUE TITLE
Windows maximize behind taskbar

### ISSUE THREAD

**Issue by relaytheurgency** [digitalcreations/MaxTo#685]
When MaxTo regions are active and I maximize a window within a region the edge of the taskbar is ignored. Windows instead maximize to the bottom of the monitor. This seems to persist after a reboot. Resizing the taskbar (a fix suggested in closed issues) does not fix the problem. This makes a lot of applications inconvenient to use.

![image](https://user-images.githubusercontent.com/3387456/103326859-e0bb3300-4a17-11eb-9868-2baabb3156c6.png)

MaxTo Version: 2.1.5
Windows 10

**Comment by relaytheurgency** [comment]
I've verified that I have the same problem using the similar feature in DisplayFusion, so it's likely some behavior within Windows. Potentially there is some setting that I have enabled/disabled. I'd appreciate it if you have any tips for what to look at.

**Comment by relaytheurgency** [comment]
I've now discovered that my Windows installation has not actually updated for some time due to my disk not having an MSR partition. I'm going to do a clean installation of Windows and hopefully this will no longer be a problem.

**Comment by vegardlarsen** [comment]
Thank you for your issue. I was away on vacation, but feel free to re-open it if the issue should return.

PS! This issue is curable by moving the taskbar (you may have to right-click and "unlock" it first), and then moving it back. This signals MaxTo to reload the regions from scratch.

**Comment by relaytheurgency** [comment]
As stated, the issue unfortunately wasn't resolvable by moving the taskbar. I discovered the root of the issue was running MaxTo alongside Virtual Display Manager. I was running VDM for the full-screen feature that MaxTo doesn't offer. Uninstalling VDM solved the issue, but I've chosen VDM for the full-screen features in the end.
