### ISSUE TITLE
Region editor does not work over RDP

### ISSUE THREAD

**Issue by mmmmmtasty** [digitalcreations/MaxTo#687]
Hi

There are a few issues that are standing in the way of me (and my colleagues) making proper use of this tool related to how poorly it works over RDP (Microsoft's native Remote Desktop Protocol) currently. They totally seem like fixable issues though and will also benefit anyone else using remoting protocols. I'm creating separate issues for them to help tracking.

**Describe the bug**
  -  When connected to your workstation over the RDP protocol, you cannot open the regions tool as the Desktop Window Manager goes to 100% CPU usage until MaxTo finally crashes, quicker if you try and interact with it. I think what may help here is if I could turn off the special transparency/blurring effect that it uses. If it could instead use a single colour half transparent overlay, or even have the option for disabling any transparency at all then I suspect it would work just fine.
- The settings screen also has transparency on the left hand side, if we could disable that as well it would speed up general usage of the application.   - I only have 4k monitors in the house, so I don't know if it also happens with lower resolutions at this point.

**To Reproduce**
 - Install MaxTo on a workstation - Connect to that workstation using Microsoft's Remote Desktop Client from a Windows workstation with more than one monitor attached.
Double click the system tray icon and watch MaxTo appear on the monitors very, very slowly and crash if you interact with it
 - Use "maxto regions apply"

**Expected behavior**
The region editor opens quickly and allows me to interact with it to create a new layout.

**System information:**
- Windows version: 1607 LTSB, also happens on 1909 SAC though.
- MaxTo version: 2.1.5

**Additional context**
 - This was tested with 1, 2 and 4 4k monitors attached and the behaviour was the same each time. It was _almost_ usable with just one monitor attached but still crashed.
 - I am creating regions by editing the config.json file right now, it works but it isn't ideal

**Comment by vegardlarsen** [comment]
For future reference, this was a duplicate of #686.
