### ISSUE TITLE
Windows trapped in regions that are not sharing boarders.

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#69]
In addition to this, MaxTo may have windows trapped in `A2` and `B2` regions in way that once the window gets moved to `A2`, it cannot go to `C` or `D`.

![2015-04-09_121753](https://cloud.githubusercontent.com/assets/5890407/7071308/7b6d6e68-deb2-11e4-8e47-d19bb6891ea2.png)

Ideally, windows in `A2` and `B2` shall be transferable to `C` and `D`.

**Comment by vegardlarsen** [comment]
Is this when you are using the keyboard shortcuts, or is it something else entirely?

**Comment by vegardlarsen** [comment]
This issue should be gone since version 2.0.0.
