### ISSUE TITLE
Discord Compatibility

### ISSUE THREAD

**Issue by NiggDiggerBrixx** [digitalcreations/MaxTo#692]
**Describe the bug**

Discord is not recognised by MaxTo.

**System information:**

- Version 2004 (OS Build 19041.685)
- MaxTo version: 2.1.5

**Additional context**

As this is my first attempt to report issues with this software, and the fact that I just installed and tried it for the first time. Regarding attempts to fix this issue by myself, I have nothing further to add at this present time.

**Comment by vegardlarsen** [comment]
@NiggDiggerBrixx I apologize for the slow response to this. Discord (in the latest version) seems to work well on my machine with MaxTo. The window becomes transparent when dragging, and reacts correctly to maximize events. Have you tried rebooting?

**Comment by NiggDiggerBrixx** [comment]
@vegardlarsen Yes. I did try it first to no avail. I later found out that I need at least MaxTo or even both processes opened with admin privileges/run as admin and now it works fine, thank god.

Thank you very much for the response and input that it indeed is functioning, anyways.
