### ISSUE TITLE
Sunsama compatibility

### ISSUE THREAD

**Issue by repentsinner** [digitalcreations/MaxTo#693]
The Sunsama desktop app (https://app.sunsama.com/desktop) does not honor any of MaxTo's regions when maximizing via the maximize button in the window title bar. It _does_ appear to honor the region if I double-click on the window title bar, however.

**To Reproduce**

1. Install the Sunsama Windows desktop app
2. Click on the maximize button in a region, the app maximizes to the whole display instead
3. Double-click in the title bar, the app maximizes to the region as expected

**Expected behavior**

Expect the maximize button to maximize to the region, not the whole display.

**Screenshots**

**System information:**
- Windows version: 
Version 20H2 (OS Build 19042.746)

- MaxTo version: 
2.1.5

**Additional context**

For now, the double-click workaround works, however it would be nice if the behavior was consistent with the other apps on my system.

**Comment by vegardlarsen** [comment]
@repentsinner Does the application go to the correct region when you hold Shift while moving it? Does the problem still occur after a reboot?

It sounds strange that there should be different behavior for double-clicking and using the maximize button, as they normally map to the same underlying behavior.

**Comment by repentsinner** [comment]
Hi @vegardlarsen, yes the application goes to the correct place when holding shift and moving (didn't know about that capability/behavior), and the problem still occurs after a reboot.

For what it's worth, I have filed an issue with the developers of Sunsama as well and will report back here with their comments.

**Comment by repentsinner** [comment]
Sunsama:

> Not playing nicely with MaxTo is a new one though. We're planning on releasing a new version of the desktop app in ~1 week that _might_ fix that, but it's a long shot. There's a lot of variability in how Electron apps (the framework we use for the desktop app) play with desktop managers.

Me:

> I use Signal pretty regularly and I understand that on desktop it is using Electron (and is open source: https://github.com/signalapp/Signal-Desktop) and it behaves correctly if that helps you narrow things down. It also works correctly regarding top edge resizing and the maximize button.

Sunsama:

> Thanks for the tip, I'll take a look at how they do it. We built our own top nav bar, which is why just our app has this limitation. For the resizing, we use a custom package that I'm hoping to remove in a future release, although not sure what the status of Electron's latest window state management behavior is.

**Comment by vegardlarsen** [comment]
Thank you for that update. That means there really isn't anything we can do about this issue.

But thanks for the tip about Sunsama though, it looks like a cool app that I may try out myself :)
