### ISSUE TITLE
Chocolatey Support

### ISSUE THREAD

**Issue by aphex** [digitalcreations/MaxTo#696]
This has quickly become a must have for any windows machine I am using. Any chance someone can get this up on Chocolatey so I can automate the installation?

**Comment by vegardlarsen** [comment]
It is absolutely something that we want to support. Our long term goal is to support:

- Chocolatey
- Winget
- Microsoft Store

For all of these we would need to invest the time required to create proper support for them, and have them automatically update when we create updates.
