### ISSUE TITLE
Startup at logon disabled, but starts up anyway

### ISSUE THREAD

**Issue by josezulu** [digitalcreations/MaxTo#699]
**Describe the bug**
Startup at logon is disabled on the settings. However MaxTo starts up anyway at PC restart.
I can see that the json file has the relevant settings set to false.
I can see that the task scheduler has a task named "maxto" which is set to "ready".

**To Reproduce**
Disable startup at logon in the settings, restart computer. MaxTo still starts up.

**Expected behavior**
MaxTo should not start at logon/computer restart.

**Screenshots**
N/A

**System information:**
- Windows version: Windows 10 - Version 2004 (OS Build 19041.746)
- MaxTo version: 2.2.0-beta1

**Additional context**
I'm running MaxTo as normal user, not elevated.

**Comment by vegardlarsen** [comment]
@josezulu Thank you for raising this issue. Can you try deleting the Task scheduler task manually? My guess is that it was created when MaxTo was running as admin, and when you run MaxTo as a standard user it cannot delete it.

**Comment by josezulu** [comment]
@vegardlarsen Thank you for the response. I was able to delete the task manually. Now MaxTo doesn't run any more at longon time.
