### ISSUE TITLE
Shifting fo windows after waking from sleep-mode or screen-shutdown.

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#70]
After either of the following actions: 
1. The computer resumes from sleep-mode or locked-up-status;
2. The screen shutdown (like a screen saver)

MaxTo will screw up the alignment of all the windows by shifting them everywhere in a random manner. This is a bit annoying since it takes quite a bunch of keystrokes to move all the windows to their original position. Maybe this happened after the new update, as I do not recall anything like this prior 2015.

**Comment by vegardlarsen** [comment]
I'll investigate and see if I can reproduce before the next release.

**Comment by camel36** [comment]
I also have this issue.  I have two monitors, Windows 10, and after the screen goes to sleep, the windows are all over the place.

**Comment by sandiwinter** [comment]
I found out that this only happens on displayport and huge resolution like 3440 x 1440.

**Comment by camel36** [comment]
HI,

 

Thanks for the update.

 

I use a displayport and screen resolution is 3840 x 2160.

 

Can MaxTo be upgraded to these size screens?

 

Peter Cameron

**Comment by sandiwinter** [comment]
I also found out that this is not only MaxTo issue, even without MaxTo widnows are shifting, this is probably global displayport + ATI and displayport + Intel driver issue. SOme gays told me that this doesn't happen on NVIDIA cards. Which VGA you have?

This app partly help me: http://www.ninjacrab.com/persistent-windows/

**Comment by camel36** [comment]
HI,

 

I have a NVIDIA GeForce GTX 660 Ti card.

**Comment by vegardlarsen** [comment]
Does this issue still occur for anyone with Catalyst drivers newer than April 22nd 2015? I see the author of PersistentWindows [has noted that his tool is no longer needed](http://www.ninjacrab.com/persistent-windows/).

I am closing this as I am assuming that this is no longer a problem.

**Comment by llinfeng** [comment]
No, the problem is persistent.

By mentioning "MaxTo will screw up the alignment of all the windows by shifting them everywhere in a random manner.", I am not talking about the floating *windows*, but rather *"regions" arranged/assigned by MaxTo*. That is, the partition of areas on screens (bounded by screen), as well as the ordering of screens.

For my setup, if I start MaxTo on a three-monitor setup, and turn to laptop-screen only (when I leave office), and come back to the three-monitor setup, the whole MaxTo setup will be screwed up. I will lose all the preset regions, and loose the ability to move windows around using shortcuts defined through MaxTo. To my understanding, this is the case where the "regions" assigned by MaxTo is no longer valid, both internally to MaxTo, but also externally to the Windows system.

Worse still, the *problem" of MaxTo losing control over its very regions happens with remote desktop connection. It is not accommodating the regions with respect to changes to the monitor-setup in a similar manner.

Let me know if you shall need further details.

All the best, 

-Linfeng

**Comment by llinfeng** [comment]
@vegardlarsen, could you reopen this issue?
