### ISSUE TITLE
Doesn't remember my regions between reboots

### ISSUE THREAD

**Issue by matthiash82** [digitalcreations/MaxTo#701]
Not sure when it started, but perhaps a week or two back, but MaxTo no longer remember my regions between reboots. After each reboot I need to right-click on icon in tray, select "Change regions" and then for each monitor load a preset. Once the presets are applied, everything works again. Until next reboot that is.

**To Reproduce**

1. Set up regions. They work
2. Reboot
3. MaxTo i started
4. Regions are lost

**Expected behavior**

MaxTo should remember regions between reboots

**Screenshots**

No applicable

**System information:**
- Windows version:

![image](https://user-images.githubusercontent.com/4104141/107006185-111d8c00-6791-11eb-9394-096eea35367f.png)

- MaxTo version: 

2.2.0-beta1

**Additional context**

[config.zip](https://github.com/digitalcreations/MaxTo/files/5930996/config.zip)

**Comment by matthiash82** [comment]
I should add that this is explicitely _reboots_. If I just quit and restart MaxTo the regions are preserved.

**Comment by vegardlarsen** [comment]
@matthiash82 Thank you for your issue. I would hazard a guess that you either updated Windows or your video card drivers around that time? I would also guess that if you [change monitor identification in MaxTo's settings to "Number"](https://docs.maxto.net/reference/settings/monitor), it would go back to working pretty well.

Please let me know how that works for you.

**Comment by matthiash82** [comment]
@vegardlarsen sadly that didn't work. Regions are still lost between reboots. And logically, unless Windows for some reason report random monitor serial numbers on each boot, shouldn't MaxTo remember regions anyway after one load preset / apply?

I wonder if it is a permission problem? Can I verify somewhere where the preset information is stored?

**Comment by vegardlarsen** [comment]
It could be a permission problem, or something could be deleting the settings across reboots. I've seen that happen before with "cleaner" software removing all our settings every reboot. Do you have any of those running?

Can you check your `%AppData%\MaxTo` folder and send me the contents (via e-mail support@maxto.net, or exclude the `license.txt` file if you publish it here)?

That folder contains log files and configuration files for your monitors, and I should be able to ascertain something about what is happening from it.

**Comment by matthiash82** [comment]
@vegardlarsen thank you, I have sent a mail to support@maxto.net with my configuration.

I have no custom cleaner software of any sorts installed. My machine is a pretty standard Windows 10-installation. I haven't either noticed any similar problems with other software.

**Comment by vegardlarsen** [comment]
@matthiash82 Thank you for the log files. Do you have 10 different virtual desktops?

If the answer is no: can you try turning off the "Use different regions on each virtual desktop" feature (Win+Ctrl+T, look at the bottom of the Monitor tab). Then set up your regions again, and reboot. If your regions are preserved, I think I know what causes it.

Virtual desktops are not identified by numbers, but by GUIDs (Globally Unique Identifiers). Those GUIDs have previously appeared to be stable across reboots (i.e. they are not regenerated after a reboot), and therefore MaxTo uses them as part of its identifiers to save your regions. However, if your virtual desktops suddenly got a new virtual desktop identifier the next time the machine started, MaxTo doesn't recognize the monitor and will set it up without regions.

**Comment by matthiash82** [comment]
@vegardlarsen thank you, after a few reboots now I can no longer see the problem. I do not use virtual desktops and simply disabled them. I also went back to "Serial number (default)".

Completely unrelated, but as for region presets I have noticed that they always become ever so slightly off. For example, my middle monitor is 3440x1440 and I use a region with left, middle, right. Left and right with perhaps 650 px in width, and middle the remaining. But then after next start, the pixels will have changed slightly. Perhaps 653 on the left, 652 on the right etc. I'm _guessing_ that this is due to the fact that MaxTo only stores percentages and a rounding error is introduced, likely to be able to apply a given preset on a monitor with arbitrary resolution. A small small feature request would be to _also_ store the actual dimensions as well, and use them when the monitor being applied to matches exactly, and only otherwise use percentage fallback :)

**Comment by vegardlarsen** [comment]
Sorry for not seeing this response until now.

I am aware that the sizes may "glide" off. It is indeed related to storing percentages, and:

- high DPI may mean that one device pixel != one logical pixel
- inaccuracies in WPF's GridSplitter

We are looking at this problem, but so far have been unable to determine the exact cause of this non-deterministic behavior.

**Comment by matthiash82** [comment]
No problem, it's such a minor issue regardless :)
