### ISSUE TITLE
Region not automatically adjust

### ISSUE THREAD

**Issue by Zino49** [digitalcreations/MaxTo#705]
Hello, I have the problem that when I enlarge program-windows that are in one region, the other region does not automatically adjust, as it was in an older version. Maybe only one setting has to be made, unfortunately I haven't found it yet. Can someone help me there?

**Comment by vegardlarsen** [comment]
Thank you for your issue, @Zino49. I am afraid I don't entirely understand your problem. MaxTo has never adjusted regions automatically when windows are resized, or resized other windows in that manner.

Can you try rephrasing your question?
