### ISSUE TITLE
Disable and copy options for a recipe

### ISSUE THREAD

**Issue by rastkov** [digitalcreations/MaxTo#707]
I think it would be nice to have an option to disable a recipes instead to only be able to delete it and recreate it if needed later on. Perhaps a toggle button next to a recipe?

Also, I found that most of the recipes I create are similar one to another (move/swap window left/right/up/down) with minimal differences. So it might be good to have an option to create a duplicate of an existing recipe.

**Comment by vegardlarsen** [comment]
This is absolutely something I want to do, and I have been thinking about. This goes well with something else I want to do; namely separating default recipes from user-created recipes, which should simplify the interface around this quite a bit (and at least limit the number of recipes you see by default).

**Comment by rastkov** [comment]
Looking forward to this. Separating default recipes and user-created makes sense.
Perhaps also a bulk import/export option so that people can make a backup of their recipes and share them more easily, rather then one by one as it is now (as far as I can tell and other than saving the config.json from AppData/Roaming).

**Comment by vegardlarsen** [comment]
I have just finished implementing this, and there is a lot to cover here:

- Built-in recipes are now saved in the configuration with simply an identifier (something like `__builtin.move.left`) and a `enabled` flag. This lets you easily turn off the built-in recipes. It will also allow us to add or remove built-in recipes at a later stage, and new ones will be automatically enabled.
- There is new UI around this: recipes now have a little badge that marks it as "built-in" or "custom". Built-in recipes cannot be edited.
- There is now an option to "Use as template" on recipes, that will create a new recipe with the same triggers and ingredients, and this lets you easily modify the built-in recipes.
- You can filter between "built-in" and "custom" recipes when viewing the recipes.
- Disabled recipes are highlighted so you know why they won't work.

**Comment by vegardlarsen** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/436508/109305620-483a0700-783e-11eb-845e-f83955afa1fb.png)
