### ISSUE TITLE
PicPick Screen/Window shot program

### ISSUE THREAD

**Issue by andus58** [digitalcreations/MaxTo#710]
**Describe the bug**

A transparency issue when moving PicPick application window. The transparency stays on and makes app impossible to use. It's the best screendump application for training and generally creating user guides and inserting annotations on images. Even for modifying images its pretty damn good. I have to make sure NOT to move the window otherwise it goes and stays transparent. Could you include it please in your COMPATIBILITY menu. Windows snipping tool doesn't come near the effectiveness of this app. Surprise...

Cheers, A.

**To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

When moving window for PicPick, on release I expect transparency to turn off.
**Screenshots**

![picpick](https://user-images.githubusercontent.com/18455989/110224029-5669e080-7f2c-11eb-9af5-40b949df82e7.png)

**System information:**
- Windows version: 
- MaxTo version: 2.1.5 

**Additional context**

**Comment by vegardlarsen** [comment]
Thank you for reporting this issue. This should be easy to fix in a compatibility shim, so I am adding it to my to-do list.

In the mean-time, you should be able to disable window transparency in MaxTo's settings, and the problem should go away.

**Comment by andus58** [comment]
Thanks I have disabled. I do like the transparency, I find it helpful when moving a window across multi monitor. I use Display Fusion which is very good and has screen splitters. One monitor is LG with it’s own screen app and splitters. I’ve tried Win 10 too –

 

… end of day I have tried a few screen splitters and after initially uninstalling MaxTo as I assumed it was interfering with Windows 10 Insider speed. In the end I have come full circle and reinstalled and actively use ONLY MaxTo to organise my screens & monitors real estate. The simplest, easiest and most reliable and does  not interfere with Win 10 speed. Highly recommended….

 

Feel free to use. 😊

 

 

Sincerely

 

André Dussart

Director

Andus WebIT Services

 <https://www.conundrums.com.au/> 

9 Compass Close

SALAMANDER BAY   NSW   2317

* E-Mail :  <mailto:webit@andus.com.au> webit@andus.com.au

* Mobile:   +61-412 424 121
* Web:       <http://www.conundrums.com.au> www.conundrums.com.au 

                                                                                                            

This message may contain confidential and/or privileged information. 
If you are not the addressee or authorized to receive this for the addressee, 
do not use, copy, disclose or take any action based on any part of this message. 
If you have received this message in error, please advise the sender immediately 
and delete this message. Thank you.

**Comment by vegardlarsen** [comment]
Thank you for the kind words, @andus58. Please do let me know if you should encounter any other issues. :)

**Comment by vegardlarsen** [comment]
@andus58 Thank you for reporting this issue. I think this may be fixed in version 2.2.0-beta.2 of MaxTo. I tried downloading PicPick (version 5.1.5) today, and it does not exhibit this behavior (on my machine neither with MaxTo 2.1.5 or 2.2.0-beta.2). We did make some changes in 2.2 related to transparency, so hopefully the problem will be fixed if you update (easy way: MaxTo settings, under Updates, set Update channel to Beta).

**Comment by andus58** [comment]
Thx Vegard… in the end my HDD finally got fried which was an excellent opportunity to install a new WinPro10 as that key got fried too, along with an SSD. I don’t store much locally on C:, mainly the apps and I use many but everything backed up and accessed on a server. Maxto is working great now and smoothly.

 

Fyi the one thing I did notice was Powertoys on my previous PC version seemed to interfere a lot even after I uninstalled it. What a useless piece of Microsoft **app.  Cheers.

 

 

Sincerely

 

André Dussart

Director

Andus WebIT Services

 <https://www.conundrums.com.au/> 

9 Compass Close

SALAMANDER BAY   NSW   2317

* E-Mail :  ***@***.***> ***@***.***

* Mobile:   +61-412 424 121
* Web:       <http://www.conundrums.com.au> www.conundrums.com.au 

                                                                                                            

This message may contain confidential and/or privileged information. 
If you are not the addressee or authorized to receive this for the addressee, 
do not use, copy, disclose or take any action based on any part of this message. 
If you have received this message in error, please advise the sender immediately 
and delete this message. Thank you.

**Comment by vegardlarsen** [comment]
That is great to hear. Closing this as the issue now appears to be fixed.
