### ISSUE TITLE
Slightly Inaccurate divisions on Config splits

### ISSUE THREAD

**Issue by BillionJothi** [digitalcreations/MaxTo#715]
**Describe the bug**
Multiple inaccurate divisions of splits (slightly). On a 5120x2160 screen (in multi-monitor set-up). Have been manually adding presets to the JSON config file successfully. However, upon usage and checks, notice multiple division inaccurate.

Present setting set to split at 0.75. The on-screen resolution would result in a 3840 region & a 1280 region. Got 3837 & 1284 instead.

**To Reproduce**

1. Add `{
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.75,
        "child1": null,
        "child2": null
      },
      "name": "4k[1k:F9\r\n00000000#00\r\n00000000#00\r\n00000000#00\r\n00000000#00\r\n00000000#00"
    },` to config file.
2. Manually Load Preset using MaxTo Interface.
3. Values appear off. The total width appears to be slightly over the actual screen resolution as well.
4. Expanding the application into the region and checking the window's width confirm the issue. To compensate (since total over screen resolution already) the 4k region (3837) would set windows to 3835 (windows size) and the 1k (1284) would set windows to 1283.
5. Reloading the Regions UI shows the regions at values of 3834 and 1287 (instead of the original as well)

**Expected behaviour**
Expected accurate divisions. A 4K (0.75 x 5120 = 3820) to 1K (0.25 x 5120 = 1280) Split instead of current.

**Screenshots**
<img width="2562" alt="maxto-github-error2_optimized - Copy" src="https://user-images.githubusercontent.com/23436862/113490893-99a17a00-94ff-11eb-839a-ece4d170a31f.png">

![image](https://user-images.githubusercontent.com/23436862/113491447-78428d00-9503-11eb-9bf0-3f1d5f26830c.png)

**System information:**
- Windows version: 
Edition		Windows 10 Pro
Version		20H2
Installed on	‎16/‎1/‎2021
OS build		19042.870
Experience	Windows Feature Experience Pack 120.2212.551.0
- MaxTo version: 2.1.5
- Scaling on both monitors (5120 x 2160) & (2160 x 3840) at 150% (No window resizing when dragging across)

**Additional context**
Relevant config.json "presets":
` {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.75,
        "child1": null,
        "child2": null
      },
      "name": "4k[1k:F9\r\n00000000#00\r\n00000000#00\r\n00000000#00\r\n00000000#00\r\n00000000#00"
    },
`

**Comment by vegardlarsen** [comment]
We are aware of this issue, and it comes up from time to time. Unfortunately, we have multiple sources of this inaccuracy, and fixing it completely is not going to happen anytime soon.

Sources of this inaccuracy:

- Different DPI modes on different screens.
- Inaccurate `GridSplitter` in WPF, would need a rewrite.
- Nested `GridSplitter` in MaxTo compounds the problem.

There are multiple other issues mentioning this as well.
