### ISSUE TITLE
Regions UI stays open on secondary monitor when closed on Primary monitor

### ISSUE THREAD

**Issue by BillionJothi** [digitalcreations/MaxTo#716]
Regions UI does not close (on Secondary monitor) when closed on Primary monitor. The regions UI stays open on the secondary monitor. Loading the UI (opening it again) results in it opening again on both monitors.

As a result, could have 3-5 (unlimited) of the regions UI opened on the secondary monitor if forgotten to close it and multiple uses.

Have tested. Closing (Cancelling Changes) on the secondary monitor UI results in both UI's (on Primary & Secondary monitor) closing. Does not close previous un-closed versions left on the secondary monitor. (Require manual closing of each)

**To Reproduce**

1. Double-Click MaxTo Icon to load Regions UI (Place to build Regions/load/apply etc)
2. Click Cancel Changes on the pa multi-monitor set-up
3. Regions UI closes on Primary
4. Opening it again, loads a new window/UI, results in 2 of it opened on secondary monitor stack/with later one overlapping older one (unable to capture in the screenshot)

**Expected behaviour**
All Regions UI to close.

**Screenshots**
(Other monitor [monitor 2] is ordinary 4k monitor)
![image](https://user-images.githubusercontent.com/23436862/113491627-dde34900-9504-11eb-8d74-21ed2a387907.png)

(After Closing Regions UI on the main monitor)
<img width="3640" alt="maxto-github-error3_optimized" src="https://user-images.githubusercontent.com/23436862/113491718-564a0a00-9505-11eb-9317-7e4ecd8defb6.png">

**System information:**
System information:
- Windows version:
Edition Windows 10 Pro
Version 20H2
Installed on ‎16/‎1/‎2021
OS build 19042.870
Experience Windows Feature Experience Pack 120.2212.551.0
- MaxTo version: 2.1.5
- Scaling on both monitors (5120 x 2160) & (2160 x 3840) at 150% (No window resizing when dragging across)

**Comment by vegardlarsen** [comment]
I can reproduce this, but only when closing from the non-primary monitor.

**Comment by vegardlarsen** [comment]
This issue has been fixed and will be in the next 2.2.0-release (either beta or final release).
