### ISSUE TITLE
MaxTo settings window extremely slow and sluggish when dragged across screen

### ISSUE THREAD

**Issue by xblubbx2** [digitalcreations/MaxTo#717]
**Describe the bug**
I've just installed MaxTo on a 5 days old Windows 10 and activated it using my license. When I right click the system tray icon and click on "Settings", the settings window opens. When I drag this window across the screen, the window moves extremely slowly and sluggishly. Every other window on my screen behaves just fine when dragged.

**To Reproduce**
Open the MaxTo settings and drag the window across the screen.

**Expected behavior**
I expected the settings window to move as fast and smoothly across the screen as any other window.

**Screenshots**

**System information:**
- Windows version: 20H2 (OS Build 19042.928)
- MaxTo version: 2.1.5

**Additional context**
System is a 5950x with an RTX 3090

**Comment by vegardlarsen** [comment]
Thank you for writing. We are painfully aware of this issue. It should be a bit better in version 2.2.0-beta.2, which you can get by changing your update channel to "Beta" under MaxTo's settings (under Updates).

We already have at least one (#684) issue for this, so I am closing this as a duplicate.
