### ISSUE TITLE
Taskbar Height in Windows 10, Build 10061

### ISSUE THREAD

**Issue by mhannant** [digitalcreations/MaxTo#72]
MaxTo does not take into consideration the height of the Taskbar in Windows 10, Build 10061. When application windows are maximised to fill a MaxTo section, the bottom of the application window extends beyond the top of the Taskbar to the very  bottom of the screen. This prevents any interaction with the bottom area of the application which is sitting behind the Taskbar. I don't recall this happening with previous builds of Windows 10.

**Comment by ryanjkelly2** [comment]
I noticed that as well, and it happened whether MaxTo was open or not. When I maximized a window on my secondary monitor, it extended behind the taskbar and was extremely annoying.

I think you'll be happy to know that this is fixed in Build 10074.

**Comment by vegardlarsen** [comment]
First, I apologize for the slow reply, I have been at Microsoft's //Build/-conference all week. Since this was fixed by a new build of Windows 10, I am closing this.
