### ISSUE TITLE
Office apps stay transparent while moving around

### ISSUE THREAD

**Issue by thedatabuddy** [digitalcreations/MaxTo#721]
Office apps like Outlook and Powerpoint are staying transparent while they are moved around.

**Comment by vegardlarsen** [comment]
Thank you for your issue.

Do you mean transparent after they have been moved?

Have you updated to version 2.2.0-beta.2? (Update in MaxTo's settings, under Updates, by setting your Update channel to Beta)

**Comment by vegardlarsen** [comment]
Closing this in favor of #676. Should be the same issue.
