### ISSUE TITLE
Move window [direction] recipes not working correctly with ConEmu

### ISSUE THREAD

**Issue by TheRotag** [digitalcreations/MaxTo#722]
**Describe the bug**
The recipes for "Move window [direction]" (e.g. "Move window left") are not moving my window for [ConEmu](https://conemu.github.io/) as I would expect. For other windows (e.g. Notepad), they work as expected (they move the window between regions, filling the next region to the left, right, etc. However, with ConEmu, though they do move my windows, they don't seem to honor the current regions. They seem to be using some sort of default regions maybe? Oddly, the Windows-**Alt**-[direction] ("Snap window [direction]") recipes seem to work fine with ConEmu.

I use both MaxTo and ConEmu on my work computer as well (yes, separate license), and only today set up MaxTo on my personal computer. I started by updating my config file from the one on my work computer (to grab my settings and some custom recipes). On my work computer, Windows+Left and Windows+Right work as expected with ConEmu, but on my personal computer, the same hotkeys with the same recipes and the same program (ConEmu) behave differently.

**To Reproduce**
Since these are default recipes, just set up some regions, open Notepad, press Windows+Left and Windows+Right a few times and watch the window move around. Then open ConEmu, use the same hotkeys, and watch it move around differently.

**Expected behavior**
ConEmu should move around with the "Move window [direction]" recipes just like any other window.

**System information:**
- Windows version: Version 1909 (OS Build 18363.1440)
- MaxTo version: 2.1.5

**Additional context**
[config.json.txt](https://github.com/digitalcreations/MaxTo/files/6370348/config.json.txt) _(Renamed to config.json_**.txt**_, since GitHub doesn't support attaching .json files)_

**Comment by vegardlarsen** [comment]
Without trying this out myself (typing this on a ***gasp*** Mac), I would assume ConEmu relies on Conhost (which is the same that hosts regular console windows). Could you try out if e.g. Command Prompt or PowerShell exhibits the same behavior as you reported?

There is some special handling in MaxTo for console windows; as they really don't like being resized externally. E.g. to fit entire characters, the windows will be resized in increments of the font size. It could be that this handling needs to be extended to ConEmu.

**Comment by TheRotag** [comment]
That's a reasonable theory. I just tried out both the Command Prompt and PowerShell, and both behave as expected (i.e. as Notepad does), not as ConEmu does.

You mentioned possibly needing to extend the special handling for console windows to ConEmu; is that something I could try locally via settings, or does that require a code change?

**Comment by vegardlarsen** [comment]
If we are to use the same handling, that requires a code change.

Now, having tried ConEmu with MaxTo myself, I can say that version 2.2.0-beta.2 of MaxTo does not trigger this behavior (while I was able to confirm that version 2.1.5 does). You can easily update to version 2.2.0-beta.2 by setting your MaxTo update channel to Beta in MaxTo's settings.

**Comment by TheRotag** [comment]
I updated to 2.2.0-beta2 and saw no change at first, but realized my ConEmu install was out of date. I updated ConEmu as well (since I figured you probably tested this with the latest version), and that did the trick. Thanks for the help!

**Comment by vegardlarsen** [comment]
Great to hear! :)
