### ISSUE TITLE
How to maximize to fullscreen certain applications.

### ISSUE THREAD

**Issue by nativekative** [digitalcreations/MaxTo#727]
Hello there,
Yes i have searched but i couldn't find the solution to it.I just want mainly musicbee to maximized to full screen and after reading other post and instructions on this https://docs.maxto.net/reference/commands/window/maximize
still not able to get it work.Plz help as what commands to use?
I know another way is that by holding shift key and enabling passive mode but then i don't want to do that everytime.
I tried different settings in vain.
https://i.imgur.com/IY6gnpf.png

**Comment by nativekative** [comment]
Hi thx for replying. I just installed windows and it is just working fine. I didn't do anything and rest of windows are maximized to specified regions as they should be and to my surprise musicbee is maximized to fullest. I didn't do any change in recipe. I was hoping to export this settings but i couldn't find how to do so.
I just assumed it must be located here with config.json?
C:\Users\username\AppData\Roaming\MaxTo

**Comment by vegardlarsen** [comment]
@nativekative So the problem here is that Musicbee is maximized to the entire screen? If that is the case, can you try using the keyboard shortcuts to get around the issue? E.g. try pressing Window+arrow keys to move that window into a region?

**Comment by nativekative** [comment]
No that is not the problem...I want musicbee to be maximized,earlier it was not working like that.I tried as much as i can then i posted here.Later on i installed windows 21h1 and now musicbee is maximized without being bother about specific regioins.So all is good.I haven't done any changes n all,everything in default settings.Just i don't know how MAXTO actually responds to certain apps.
thank again for helping.

**Comment by vegardlarsen** [comment]
Thank you. In that case I consider the issue to be solved, and I am therefore closing this issue. :)
