### ISSUE TITLE
Constant nag bubble annoying

### ISSUE THREAD

**Issue by cjrobe** [digitalcreations/MaxTo#73]
I'm trialing MaxTo and considering uninstalling just because I don't know if I'll be able to stand the nag bubble 2-3 times every day while working. Can you limit it to once when it opens like most softwares do? I installed MaxTo to potentially increase my work efficiency, not distract and annoy me.

**Comment by vegardlarsen** [comment]
@cjrobe Yes, I can. Currently it tags the window as having shown the nag bubble in that session, but it will probably be better if we have an internal list of items that you have already been nagged about.

With the current behavior, if you close a window and open a new identical one, the bubble will show. If I change this, it will only show one bubble per window type as long as MaxTo is left running.

**Comment by cjrobe** [comment]
Thanks for the response, that sounds like a good solution. I'm really liking the software so far.
