### ISSUE TITLE
Problem with Unity3d

### ISSUE THREAD

**Issue by JohanSimu** [digitalcreations/MaxTo#74]
If I have MaxTo running and open the unity3d (5.0.1) editor then the editor window turns black and unresponsive when I try to resize it. I am using MaxTo 2015.3.1.0.

**Comment by vegardlarsen** [comment]
Thank you for the report. This sounds very strange, and I will investigate this before the next release. It may be something that Unity3d does that causes this, but for now you can probably work around it by adding the following entry to `C:\Program files (x86)\MaxTo\shims.xml` under `<nosubclass>` and `<ignore>`, and then restarting MaxTo:

```xml
<process>unity3d</process>
```

(I am assuming the executable name of Unity3d is "unity3d", it may not be. Just use the name of the executable without the file extension and it should work)

**Comment by JohanSimu** [comment]
Thanks I will do that!

I suspect all unity3d windows are directx or opengl contexts so maybe that
can give some hint what the issue is.

/Johan

**Comment by vegardlarsen** [comment]
Hi @JohanSimu, did this work for you?

**Comment by JohanSimu** [comment]
Hi,

unfortunately it didn't. The name of the executable is just Unity, but when
I add it to shims.xml as you explained nothing happens and I get the same
error that windows turns black when I re-size unity.

**Comment by nakdeyes** [comment]
Hey there! I just started using Unity and I am also experiencing this issue.. I just thought it was an issue with Unity and not MaxTo, but when googling around I found this thread. I tried shutting down MaxTo and now Unity's window can scale correctly. 

I tried the above mentioned fix and it also did not work for me. I put it in the shims.xml as follows:

<?xml version="1.0" encoding="utf-8"?>

<compatibility>
  <no_subclass>
    <process title="iTunes">iTunes</process>
    <process title="iTunes">iTunesHelper</process>
    <process title="Unity">Unity</process>
    
    <process title="MediaMonkey">MediaMonkey (non-skinned)</process>
    <process title="MediaMonkey">MediaMonkey</process>
    <windowclass title="Adobe Acrobat">AcrobatSDIWindow</windowclass>
    
    <windowclass title="wxWidget-based software">wxWindow</windowclass>
    
    
  </no_subclass>
  <ignore>
    <process title="iTunes">iTunes</process>
    <process title="iTunes">iTunesHelper</process>
    <process title="Unity">Unity</process>
    
    <windowclass title="The Windows taskbar">Shell_TrayWnd</windowclass>
    
    <windowclass title="Sidebar gadgets">SideBar_HTMLHostWindow</windowclass>
    
    <windowclass title="Sidebar gadgets">Internet Explorer_Server</windowclass>
    
    <process title="Sidebar gadgets">sidebar</process>
    
    <windowclass title="UltraMon">UltraMonDeskTaskBar</windowclass>
    <windowclass title="Adobe Acrobat">AcrobatSDIWindow</windowclass>
    <windowclass title="Google Chrome">Chrome_WidgetWin_0</windowclass>
    <process title="ManicTime">ManicTime</process>
    <process title="ManicTime">ManicTimeClient</process>
    <process title="KakaoTalk">KakaoTalk</process>
    <process title="Quickbooks">QBW32</process>
  </ignore>
  <no_snap>
    <windowclass title="Spotify">SpotifyShadow</windowclass>
  </no_snap>
  <use_movewindow>
    <windowclass title="Console windows">ConsoleWindowClass</windowclass>
  </use_movewindow>
  <emulate_maximize>
    
    <windowclass title="Winamp">BaseWindow_RootWnd</windowclass>
  </emulate_maximize>
</compatibility>

**Comment by vegardlarsen** [comment]
I will have a look at this for the next release and see if I can figure out what is happening. When you add Unity to the ignore list, MaxTo should not touch it at all.

**Comment by nakdeyes** [comment]
Maybe we are just using the wrong process identifier? 

If I look at Task Manager, under Applications, the name is "Unity Personal (64-bit)", if I look under processes, I see "Unity.exe" "UnityHelper.exe" and "UnityShaderCompiler.exe".. 

The two things I have seen suggested in this thread are "Unity" ( what I tried ) and "unity3d" ( just haven't seen this identifier elsewhere, so I didn't try ). Should I try "Unity.exe" or something?

**Comment by vegardlarsen** [comment]
The way to find those identifiers is to look in Task Manager under Details. Find the process name, it should end with `.exe`. You use that name minus the `.exe` at the end. Those names are case-insensitive.

The other way is to find the window class and use that instead. You'll need a tool like Spy++ or Winspector to find it. There are some example, but instead of `<process>Unity</process>` you would use `<windowclass>Unity_WndClass</windowclass>` or whatever the actual window class is.

**Comment by imukai** [comment]
I just started using Unity and noticed this same behavior, was wondering if it was a Unity problem or a MaxTo problem.  Considering the suggestion to ignore Unity, I am guessing a fix was never found?

**Comment by vegardlarsen** [comment]
MaxTo backs away at the earliest opportunity it has from interacting with Unity. It may not be early enough.

However, try adding `<process>` tags for each of the processes mentioned above, and restarting your machine before trying if it works.

**Comment by imukai** [comment]
I was able to add the process ignore which worked - I was just curious if the root problem was going to be fixed so that MaxTo could work with Unity.

**Comment by vegardlarsen** [comment]
The root problem here is Unity, and we can't fix it. MaxTo is doing things that should be supported by Windows apps, but sometimes there are issues because that app is doing strange things. This may not even be Unity's fault, but sometimes can be because of some UI library they are using.

So the short answer here is "most likely not".

**Comment by vegardlarsen** [comment]
I am closing this issue, as #165 is the same issue. We think we may have fixed this in the 2.0.0 previews released earlier this week. See issue #220 for details about that, and please feel free to comment on #165 if this is still happening to you.
