### ISSUE TITLE
Return to how it was 1 month ago?

### ISSUE THREAD

**Issue by Matt5432** [digitalcreations/MaxTo#746]
Hi , might seem silly but can we get access to a older version , about 1 month ago. I had 0 issues and worked fine. 
Since then it snapping odd, when I drag windows about its sliding and just annoying/ having to turn the program off.

Thanks

**Comment by vegardlarsen** [comment]
Older releases are [available from our website](https://maxto.net/en/release). You may have to use ZIP file (and not the regular installer) to avoid being automatically updated to the latest version.
