### ISSUE TITLE
Microsoft .NET Framework error after starting Windows

### ISSUE THREAD

**Issue by nepumax** [digitalcreations/MaxTo#753]
When I start my computer, the following error message pops up immediately and MaxTo doesn't work. I have to manually close MaxTo and start it again, then it works.

![maxto](https://user-images.githubusercontent.com/2079937/128325358-26558331-df26-46de-a2c4-a26feec8ad81.png)

Windows 10 Version 21H1 (Build 19043.1151)
MaxTo Version 2.2.0 (Stable)

[NETFramework.txt](https://github.com/digitalcreations/MaxTo/files/6937464/NETFramework.txt)
[maxto20210805.log](https://github.com/digitalcreations/MaxTo/files/6937465/maxto20210805.log)

**Comment by vegardlarsen** [comment]
Thank you for your report. We will investigate this to see if we can determine what is causing it.

Full stack-trace from the report above for my reference:

```
************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei MaxTo.Companion.MessageHandlers.MaximizeWindowMessageHandler.ActInternal(String name, Message message)
   bei MaxTo.Companion.MessageHandlers.WindowMessageHandlerBase.Act(Message message)
   bei MaxTo.Companion.MessageHandlers.WindowMessageHandlerDispatcher.Dispatch(Message message)
   bei MaxTo.Companion.Hook.HookController.MessageSourceOnWindowMessage(Object sender, Message message)
   bei MaxTo.Core.Native.HiddenWindowMessageSource.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by SalmanRavoof** [comment]
I get a similar error, though it says something else. 

> See the end of this message for details on invoking 
> 
> just-in-time (JIT) debugging instead of this dialog box.
> ```
> ************** Exception Text **************
> System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
>    at MaxTo.Core.Native.VirtualDesktops.Interop.IVirtualDesktopNotificationService.Unregister(UInt32 cookie)
>    at MaxTo.Core.Native.VirtualDesktops.VirtualDesktop.set_EnableRaisingEvents(Boolean value)
>    at MaxTo.Core.Recipes.Triggers.VirtualDesktopTriggerController.Dispose()
>    at MaxTo.Core.Events.EventDriver.Dispose()
>    at MaxTo.Core.MainForm.Dispose(Boolean disposing)
>    at System.Windows.Forms.Form.WmClose(Message& m)
>    at MaxTo.Core.Native.HiddenWindowMessageSource.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> MaxTo.Core
>     Assembly Version: 2.2.0.764
>     Win32 Version: 2.2.0.764
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/MaxTo.Core.exe
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> Serilog
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.8.0.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Serilog.DLL
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> CommandLine
>     Assembly Version: 2.0.273.0
>     Win32 Version: 2.0.273.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/CommandLine.DLL
> ----------------------------------------
> Serilog.Sinks.Debug
>     Assembly Version: 1.0.1.0
>     Win32 Version: 1.0.1.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Serilog.Sinks.Debug.DLL
> ----------------------------------------
> Serilog.Sinks.File
>     Assembly Version: 2.0.0.0
>     Win32 Version: 4.0.0.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Serilog.Sinks.File.DLL
> ----------------------------------------
> Serilog.Sinks.Raygun
>     Assembly Version: 3.0.0.0
>     Win32 Version: 3.0.0.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Serilog.Sinks.Raygun.DLL
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> Mindscape.Raygun4Net4
>     Assembly Version: 5.5.2.0
>     Win32 Version: 5.5.2.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Mindscape.Raygun4Net4.DLL
> ----------------------------------------
> Mindscape.Raygun4Net
>     Assembly Version: 5.5.2.0
>     Win32 Version: 5.5.2.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Mindscape.Raygun4Net.DLL
> ----------------------------------------
> System.Web
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Caliburn.Micro
>     Assembly Version: 3.2.0.0
>     Win32 Version: 3.2.0.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Caliburn.Micro.DLL
> ----------------------------------------
> System.Runtime
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
> ----------------------------------------
> System.Collections
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
> ----------------------------------------
> System.Linq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
> ----------------------------------------
> System.Reflection
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
> ----------------------------------------
> System.Reflection.Extensions
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 12.0.0.0
>     Win32 Version: 12.0.2.23222
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Newtonsoft.Json.DLL
> ----------------------------------------
> System.Threading
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
> ----------------------------------------
> DigitalCreations.Rett
>     Assembly Version: 1.0.41.0
>     Win32 Version: 1.0.41
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/DigitalCreations.Rett.DLL
> ----------------------------------------
> netstandard
>     Assembly Version: 2.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
> ----------------------------------------
> System.Net.Http
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
> ----------------------------------------
> MahApps.Metro.IconPacks.Modern
>     Assembly Version: 2.3.0.4
>     Win32 Version: 2.3.0.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/MahApps.Metro.IconPacks.Modern.DLL
> ----------------------------------------
> NuGet.Squirrel
>     Assembly Version: 3.0.0.0
>     Win32 Version: 3.0.0.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/NuGet.Squirrel.DLL
> ----------------------------------------
> Squirrel
>     Assembly Version: 1.9.1.0
>     Win32 Version: 1.9.1.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Squirrel.DLL
> ----------------------------------------
> Splat
>     Assembly Version: 1.6.2.0
>     Win32 Version: 1.6.2
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Splat.DLL
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> Microsoft.Win32.TaskScheduler
>     Assembly Version: 2.8.12.0
>     Win32 Version: 2.8.12.0
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/Microsoft.Win32.TaskScheduler.DLL
> ----------------------------------------
> UACHelper
>     Assembly Version: 1.3.0.4
>     Win32 Version: 1.3.0.4
>     CodeBase: file:///C:/Users/salma/AppData/Local/MaxTo/app-2.2.0/UACHelper.DLL
> ----------------------------------------
> System.ComponentModel.DataAnnotations
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> ```

**Comment by vegardlarsen** [comment]
@SalmanRavoof I created #755 to track your issue. Please continue that discussion there.

**Comment by vegardlarsen** [comment]
This issue will be fixed in the next release.
