### ISSUE TITLE
Help Cant get Maxto.net start and launch and arrange windows over 2 virtual desktops

### ISSUE THREAD

**Issue by boogotti8** [digitalcreations/MaxTo#754]
Hey,
I cant get Maxto to launch my programmes and arrange over two virtual desktops. I think this is possible?
using one monitor
Is there any examples scripts or forum i can see?

I manged to get it to work over one virtual desktop, but when i try to create two it doesn't work?

**Comment by vegardlarsen** [comment]
@boogotti8 There may be some issues in version 2.2.0. Try setting your update channel to Alpha (in MaxTo's settings, under Updates), and then make sure you get version 2.2.1-alpha.1. Let me know if that resolves the issues for you.

**Comment by boogotti8** [comment]
> @boogotti8 There may be some issues in version 2.2.0. Try setting your update channel to Alpha (in MaxTo's settings, under Updates), and then make sure you get version 2.2.1-alpha.1. Let me know if that resolves the issues for you.

Great thank will give this an go!

**Comment by vegardlarsen** [comment]
Closing this as it was fixed in 2.2.1.
