### ISSUE TITLE
Window Snapping, snapped window snap really hard to the edge

### ISSUE THREAD

**Issue by dehghani-mehdi** [digitalcreations/MaxTo#757]
**Describe the bug**
Snapping feature cause snapped window snap really hard to the edge of window/monitor/region. the window always stuck on the edge and takes ~10 times grab and dragging in order to release it form the edge.

**To Reproduce**
1. Go to `Settings` and then `Window behavior`
2. In `Window snapping` section check `Snap to monitor edges`
3. Open up notepad and drag it to the right/left edge of the monitor, notepad should snap to the edge of the monitor
4. Try to release the notepad from the edge

**Expected behavior**
Snapped window should be release easily and in 1 try. snap amount should be much less than current value (or something like that)

**Screenshots**
![maxto](https://user-images.githubusercontent.com/9152330/129508062-3bd8d708-8ce5-4daf-a598-5cd43596bcc3.png)

**System information:**
- Windows version: 1909
- MaxTo version: 2.2.0.764

**Comment by vegardlarsen** [comment]
Please update to version 2.2.1-alpha.1, which you can most easily do by setting your *Update channel* to Alpha in MaxTo's settings, then clicking Check for updates.

Please feel free to comment here if this issue has not been solved in that version.
