### ISSUE TITLE
How to resize beyond the autolimit imposed on height

### ISSUE THREAD

**Issue by mjsr-sr** [digitalcreations/MaxTo#761]
Hi guys, I would like to reach beyond the limit imposed automatically.
![image](https://user-images.githubusercontent.com/81977947/132394461-fa16293f-3f07-4e0c-b440-308a182372bd.png)
For example on previous image, I would like to make the inferior part smaller than 136.

I would like to go beyond the limit to use the inferior part with some tools, gadgets that use very small portions of the screen size, for instance the toggl mini timer. It is shown in this picture:
![image](https://user-images.githubusercontent.com/81977947/132393915-5c5556f6-9fd7-4c7d-8257-053fefbe4ade.png)
You see the immense gap at the bottom, that is because I can't shrink it more. 

If there isn't a regular way to do it, is it there at least something I could do on configurations files?

Thanks!

**Comment by vegardlarsen** [comment]
@mjsr-sr Thanks for writing. Unfortunately, there is a minimum window size in Windows. What you are bumping up against here is that minimum window size; and MaxTo won't allow you to make a region that is smaller than that minimum.

**Comment by mjsr-sr** [comment]
Hi @vegardlarsen ... I found a bit of a hack, went to the config files and set the value for 'distance' directly on the configuration per monitor per desktop (I played with the value and 0.955 was perfect for the mini tool at the bottom)
![image](https://user-images.githubusercontent.com/81977947/132397245-961a1957-c334-4d76-ace6-51893dd22b49.png)

I did that with the application turned off and then when it open it worked as I expected.
![image](https://user-images.githubusercontent.com/81977947/132397950-ebf8f572-1159-4802-981b-d959d5432bb1.png)


Obviously If I go again to the regions configurator UI my changes are overwritten, but as the configuration is pretty stable, it is a good workaround for now.

**Comment by vegardlarsen** [comment]
@mjsr-sr That's good to know; it is definitely not a supported configuration, and will break once you try to drop a window in that mini-region, but good to know :)
