### ISSUE TITLE
All recipes got overwritten with builtin

### ISSUE THREAD

**Issue by rustamsh** [digitalcreations/MaxTo#766]
**Describe the bug**
I was creating shortcuts for expanding left/up/right/bottom and suddenly all my custom recipes disappeared and new builtin recipes appeared (until then only window moving builtin recipes were available now there are about 20 of them)

**To Reproduce**
Don't really know at what time exactly my config got overwritten, it suddenly just disappeared. Actually I named one of my recipes "Expand left" which I think was the issue, all my custom recipes disappeared and new built in recipes appeared

**Expected behavior**
custom recipes should not be cleared

**Screenshots**

**System information:**
- Windows version: Version 20H2 (OS BUILD 19042.1165)
- MaxTo version: 2.2.1

**Additional context**
I had a lot of custom recipes and now I will need to recreate them. Probably it will take about half a day

**Comment by vegardlarsen** [comment]
Thank you for reporting this issue. It has been fixed for version 2.3.
