### ISSUE TITLE
Some features of MaxTo do not work on Windows 11

### ISSUE THREAD

**Issue by tynril** [digitalcreations/MaxTo#769]
**Describe the bug**
Windows 11 released to the general public yesterday (October 5th, 2021). While it can be started, and areas can be defined, it does not seem to be working (maximizing a window takes the full screen, regardless of MaxTo's configuration).

**To Reproduce**
1. Run Windows 11;
2. Attempt to maximize a window;
3. Notice that the window takes up the whole monitor, rather than the area defined in MaxTo.

**Expected behavior**
MaxTo should behave with Windows 11 like it does with Windows 10.

**System information:**
- Windows version: 21H2 (OS Build 22000.194)
- MaxTo version: 2.2.1.772

**Comment by tynril** [comment]
I just noticed that the hotkey recipes to move windows to regions ("Move window down", "Move window left", etc.) are still working just fine. So it seems like this is only an issue when maximizing a window by either double-clicking on its title bar, or by using the "maximize" button.

I've updated the issue title to reflect that.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. This is likely not related to Windows 11 at all, but should resolve itself after a reboot. It is possible for MaxTo/Windows to get stuck in a situation where MaxTo does not receive the events it needs from Windows; and the problem won't resolve itself until the system has been rebooted (it seems to trigger some state in Windows that persists across multiple restarts of MaxTo).

Please let me know if this problem does not go away after a reboot.
