### ISSUE TITLE
Internet Explorer Window Always On Top

### ISSUE THREAD

**Issue by collegechristopher90** [digitalcreations/MaxTo#77]
My Internet Explorer window has somehow become locked on top.  I can drag other windows into that region, and even maximize them there, but they are behind the Internet Explorer window and I cannot see them unless I first minimize it.  If I move the Internet Explorer window into a different region the same thing happens there.

![maxto issue](https://cloud.githubusercontent.com/assets/12970714/8260501/1d6a1c86-1692-11e5-9c6e-6be97dcd4452.png)

As you can see in the image, I am dragging the Windows Explorer window but it appears behind the Internet Explorer window.

**Comment by vegardlarsen** [comment]
@collegechristopher90 Do you have any software installed that is supposed to enable "always on top" for different windows?

What happens if you move IE around when this happens, and then switch back to the other window?

**Comment by collegechristopher90** [comment]
I do not have any other software installed. It is a new computer at work. I can switch to different windows and move everything around but that internet explorer window is always on top. I opened a separate window for Internet explorer and that one behaved normally. I was not able to recreate the issue after rebooting my computer.

**Comment by vegardlarsen** [comment]
Since I am unable to reproduce this (I have tried in a few different VMs), and it seems the problem went away on its own, I am treating this as a once-off. If it happens again, I would be very interested to know what lead up to it, and especially how to reproduce it. Thanks for reporting it!
