### ISSUE TITLE
After purchasing MaxTo we can't validate the new serial code we recieved...

### ISSUE THREAD

**Issue by fernandovedal** [digitalcreations/MaxTo#78]
We've tested the product for the past month and just complete the purchase however while entering our serial number in the register dialog box the "Validate" button is NOT active and we can't click it to complete our registration.  

Why the validate button is inactive we have no clue?  So we tried the follow with NO success:

1) Manually typed in the serial & email
2) Copy & pasted in the serial & email from the website receipt.
3) Restarted MaxTo and re-attempted both 1 & 2 above.
4) Uninstalled & re-installed then re-attempted both 1 & 2 above.

We've verified the internet is working as we've just sent this email and purchased the product online.

Frustrating when you purchase software which the installer can't get past the validation.

Any help would be appreciated!

Thank you,
Mark

**Comment by fernandovedal** [comment]
SOLUTION FOUND...  There's a typo during the validation process, it asks for your email AND serial number which WILL NOT WORK.  The field "Email Address"  should read "Register Name" NOT "Email Address".  When we erased the email address we had on file with MaxTo and entered our registered name instead the "Validate" button works and we could complete our registration. 

![image](https://cloud.githubusercontent.com/assets/8107582/8503553/c9aa4eec-2175-11e5-81a0-1e3e05e43383.png)

I'm surprised this was not discovered sooner & fixed, it's frustrating to waste so much time over a simple typo...

**Comment by vegardlarsen** [comment]
Hi Fernando,

We are aware of the issue, and there is a notice in the e-mail you received
when you purchased.

It will be fixed in the next release of the app.

I apologize for the inconvenience.

Best regards,
Vegard
3. jul. 2015 20.24 skrev "fernandovedal" <notifications@github.com>:

**Comment by fernandovedal** [comment]
We just noticed that.   Perhaps this should not be a "PS" rather a bold " IMPORTANT" or even a separate email.  Personally you can't use the software without knowing this.   

 

We're not mad, we just think this could be conveyed better until the new release comes out.  

 

On a side note, you're tool is excellent & does everything we need, thank you!

 

Mark

**Comment by vegardlarsen** [comment]
I've updated the e-mail that is sent out to customers, and a notice will appear on the website when I return from vacation. Thanks for letting me know.
