### ISSUE TITLE
min region size

### ISSUE THREAD

**Issue by robertplanetweb** [digitalcreations/MaxTo#782]
can you remove min region size?

**Comment by ZeronoFreya** [comment]
Agreed, I need a small area for special content. Please don't teach me what to do, that's why I'm back on version 17

**Comment by vegardlarsen** [comment]
Unfortunately, we will not be removing this limitation, it is there for good reasons. It follows the minimum allowed window size in Windows, and going smaller than that would break windows for some users.

PS! If you modify your regions by editing the settings manually, you should be able to bypass this, but it requires you do some math.

**Comment by flyingwolf79** [comment]
There is no reason you cannot leave the setting there and available with a simple checkbox that states "Going smaller than XX can break windows, click this box to procced at your own risk, doing so is not supported."

Then it would still be available.

**Comment by robertplanetweb** [comment]
alright, i found the config file and changed it manually. still, no reason to include a min height, assuming that almost all of your users are devs or tech people they would know what the implications would be

**Comment by flyingwolf79** [comment]
I ended up abandoning the MaxTo program, PowerToys and the built-in Fancy Zones with overlays has been able to replace the majority of the MaxTo operations for my use case. I used it for a good while, happy to have paid for it, but it seems like it has come to an end at this time.
