### ISSUE TITLE
passive mode and active mode at the same time for a screen

### ISSUE THREAD

**Issue by robertplanetweb** [digitalcreations/MaxTo#783]
i dont know how hard this would be to implement but i felt its need and maybe other have too.

here's my scenario:
- i have passive mode enabled (which is great)
- i split my second screen in a T shape (1 full width section at the top, 2 50% sections below)
- i would like an active mode split on the same screen like so 1 section full width at the top, and 1 section full width at the bottom. so when i maximize a window (in active mode) it should follow the active mode sections, so it should get fully maximized.

what do you think?
thanks

**Comment by robertplanetweb** [comment]
or maybe have any number sectioned layouts, which could be triggered by different customizable keys (like passive mode is triggered now by pressing shift)
all passive mode by default and when only one can be active mode.

**Comment by vegardlarsen** [comment]
The problem with implementing such a feature, is that it would be very hard to explain to someone how it works. So the idea is that if you drag a window to the top half of the screen while holding Shift, it will maximize to that region, but if you drag it to the bottom two regions, you would get the same behavior if you were not holding Shift?

This seems extremely confusing to me.

**Comment by flyingwolf79** [comment]
Wait, you closed it because you did not understand it and the ability to explain it is "too hard"?

The idea is simple, not holding shift gets you one set, holding shift gets you a second set, you know, like THIS versus this. 

Holding shift to translate to a new layer is as old as the first keyboards.

**Comment by robertplanetweb** [comment]
lol that's weird reason. but you understood what i wanted lol.
you could have an "advanced" option and leave it default the way it is now.
but i get it if it's too complicated to do and you dont have proper motivation to keep developing this program

**Comment by flyingwolf79** [comment]
@robertplanetweb I think you nailed it. The last few responses by the dev have shown a clear lack of enjoyment and motivation to continue going, and you know, I cannot blame them. This started out as a fork of Winsplit and has grown, it was great for a while but focus creep and whatnot seems to have taken a toll and the dev could probably use a vacation. 

I have the project starred⭐and will check on it from time to time, but I think for now the dev could probably just use a short vacation to regroup and find their passion again. 

Here is to hoping.

**Comment by vegardlarsen** [comment]
Friends, I believe I did understand the original request, and I made a judgement call on what I feel would be the right direction to take the project. I think it is important that features that we do implement in a project such as MaxTo, meet a few criteria (I haven't spelled these out before, so I am likely missing some steps here):

1. Is useful to at least a large part of our user base.
2. Corresponds to the mental model user's would have of how the product will work.
3. That it will not significantly impact maintainability of the project over time.

From what I understand of this feature, it does not meet my bar for any of these 3 points. Also, [remember that features "start out with minus 100 points"](https://devblogs.microsoft.com/oldnewthing/20090928-00/?p=16573).

**Comment by flyingwolf79** [comment]
Point 1. I would argue that the ability to have modifier keys and multiple layers to position windows as you wish would be useful to a large part of the userbase. 

Point 2. What mental model are you basing this off of? 

Point 3. Simply reads as: "I do not want to maintain it as it is too hard for me". You have dismissed it out of hand without any discussion after just over 24 hours. 

This is just sad. Hello Power Toys.

**Comment by robertplanetweb** [comment]
@flyingwolf79 it's strange you mentioned twice power toys. i've tried it (along a number of others) and i reinstalled it to see if there's something i missed. but weirdly enough, it has the same behaviour as maxto:
- there's a min height (which on maxto you can bypass through configs, havent tried it on power toys but i guess you could do that same)
- zones activate while holding shift but you can't change that shortcut. but.... there's a way to switch between layouts, by setting them a shortcut which is waaaay too complicated for me to actually use (and i've played starcraft and i was pretty decent). 
- upside is it's free but i've already payed maxto so it doesnt matter anymore.

let me know if they change those ridiculous shortcuts

**Comment by flyingwolf79** [comment]
I mentioned it because I was looking for other options. 
The min-height is not an issue for me, but the response by the dev was just ridiculous. 
How complicated is Windows key+arrow key?
I paid for MaxTo also, and I have recommended it to friends, as I said though, it seems the dev is just tired and could use a break. Simple as that.
