### ISSUE TITLE
Beginner's help

### ISSUE THREAD

**Issue by tcison** [digitalcreations/MaxTo#802]
Please help a beginner's attempt to understand the app's capabilities more.  I am looking for documentation, video or any and all tutorial material that explains/demonstrates the app's functions and some of the terms like contracting to edge vs expand to edge.  I am using trial and error to experiment and learn, but I am getting frustrated with my progress.  I have a 27 inch and a 4K 55 inch monitor that I am working with.  One specific question I have... Is it possible to move a window from a region on one monitor to a specific region on another monitor with a recipe other than to cycle?  Thanks for any help.

**Comment by vegardlarsen** [comment]
@tcison Have you seen [our documentation website](https://docs.maxto.net/) at all? It has tutorials, descriptions of most of the key terms we use. However, we haven't made video content yet.

You can create your own recipe to move a window to a specific region, for that you would really only need one command in the recipe: `window:move` [(docs)](https://docs.maxto.net/reference/commands/window/move). To set it up, you should set `Monitor` to a specific monitor (e.g. `2` if doing it from the command line) and `region` should describe the position of the region you want it to move into, it can be as simple as `top left` or more complicated as `20%, 30%` (which would pick the region beneath the 20%, 30% coordinate (x, y).

If you want to move the foreground window, you leave the `Window` option at its default, but you can also choose to move a specific window if you would like.

**Comment by tcison** [comment]
Thank you very much for the comprehensive response.  I will give this a shot and contact you if I have any additional questions, but it looks like I have everything I need now.  Thanks again.  Tc
