### ISSUE TITLE
MaxTo not starting up with Windows

### ISSUE THREAD

**Issue by philipbroadhead** [digitalcreations/MaxTo#81]
Randomly MaxTo stopped starting up on boot one day and has not done it since.  A reinstall hasn't fixed the issue, nor is there a task scheduler item.

Creating a scheduled task myself works to a point, but does load the overlay each time rather than just the program in the background.

**Comment by vegardlarsen** [comment]
Modify your task scheduler item to include `--start-hidden` as a parameter to `MaxTo.exe`, and it will work the way it should. Or you can delete your existing task, go into MaxTo options, uncheck "Start with Windows", click OK. Then re-open options, check it again, and click OK.

The reason for the involved procedure ? it is a slow operation working with scheduled tasks, so MaxTo tries to avoid setting it when it doesn't have to. It may be the detection is off here, I am looking at it now.

**Comment by vegardlarsen** [comment]
I've fixed the case where MaxTo was not set to start with Windows during installation.

**Comment by philipbroadhead** [comment]
Great, that's fixed it!  Thanks.
