### ISSUE TITLE
Windows 10 - MaxTo Crashes when Entering OS from Lock Screen

### ISSUE THREAD

**Issue by jodilark** [digitalcreations/MaxTo#82]
Found on windows 10 tech preview build 9926. 

Create a local account with a password
Require password to unlock PC
Start windows 10
Log in to windows 10
Wait for all startup programs to load (including Maxto autostart)
Verify MaxTo is started
On your keyboard, perform Win + L to go to lock screen
Unlock PC using password.

Error stating that the MaxTo application has crashed

**Comment by vegardlarsen** [comment]
@jodilark I tried this on a fresh install of Windows 10 build 10074 (the 9926 build is very old and no longer possible to get) in VirtualBox. I could not get it to crash when unlocking. I tried the latest release (2015.03.1) and my latest debug build, no crashes.

I then tried the same procedure on a non-local account and repeated. Still no crash. I'm closing this as not reproducible. If anyone else can reproduce, please let me know.
