### ISSUE TITLE
should be able to switch between main and alternate windows

### ISSUE THREAD

**Issue by ecpo** [digitalcreations/MaxTo#83]
[improvement recommendation] 
It should be able to switch by hotkey between main and alternate windows

**Comment by nakdeyes** [comment]
Fully agree, I would LOVE this feature.

**Comment by vegardlarsen** [comment]
This is possible now in the 2.0.0-alphas, except there are no more "main" and "alternate" regions. Instead we have one set of active regions; but you can extremely quickly load presets using keyboard shortcuts. Have a look at *Recipes* in the *Settings* when you try it out. Details in issue #220.
