### ISSUE TITLE
Notification area popup for iTunes

### ISSUE THREAD

**Issue by valentinalexeev** [digitalcreations/MaxTo#84]
When opening and "..." item or menu in latest iTunes (12.2.1.16 64bit) MaxTo shows a dialog in the notification area with text "There are issues with iTunes which prevent MaxTo from working correctly".

It is ok to show it once but it keeps on popping up every time I navigate the interface of iTunes.

**Comment by vegardlarsen** [comment]
This is the same as #73. It has been fixed, and will be in the next release.
