### ISSUE TITLE
Installer failure issues

### ISSUE THREAD

**Issue by sflanagan180251** [digitalcreations/MaxTo#86]
I just installed the latest version after being notified of it.  It worked fine on my desktop, however when installing on my laptop, it 

gave me 2 windows notifying me that it would need to restart.
Didn't complete the install process.
Left me in a loop where this error showed up:

---
## WerFault.exe - Application Error

The instruction at 0x3d091960 referenced memory at 0x07a1235f. The memory could not be written.

Click on OK to terminate the program
## OK   Cancel   

And then wouldn't reboot.  

I was remoted into the machine at the time, and I tried running 'shutdown /r' which failed.  I tried bringing up task manager but the dialog would not show up.  I physically walked over to the machine and attempted to log in and was told that 'all the connections were taken and I couldn't log in' so I had to choose shutdown from the login screen.

This is windows 8.1

detected that it would need to restart two times

**Comment by vegardlarsen** [comment]
This seems very strange. I will attempt an install on Windows 8.1 tomorrow, and see if I can reproduce. Anything special about this machine?

**Comment by sflanagan180251** [comment]
It's a dev machine with visual studio 2015 and 2013 and a bunch of other dev tools on it.  I had just run driverupdate and it wanted to reboot due to installing an update to MS security essetials or windows defender.  I don't recall, but driver update always wants to reboot regardless.  I ran the maxto installer and when the process completed, I got that error. Clicking 'ok' or 'cancel' would just bring up the same window again, so there wasn't much I could do further.

**Comment by vegardlarsen** [comment]
I think this is actually Visual Studio 2015 crashing, and not MaxTo. I installed VS'15 on a clean Windows 8.1 VM. When the VS'15 installer exited and wanted to reboot, I got the exact same message (weirdly, the entire VM crashed when I tried to take a screenshot). MaxTo wasn't even installed on that machine.

Without VS'15 installed, the MaxTo installer runs just fine. It may be that the VS'15 setup somehow corrupts the MSI installer for the system. I'll re-run this and see if it is reproducible with just VS'15 on this VM, if that is the case, I'll try to file a bug with Microsoft.

**Comment by vegardlarsen** [comment]
PS! After rebooting the VM, MaxTo installed just fine on this machine. Strange indeed.

**Comment by sflanagan180251** [comment]
Yep.  If you find anything out and need me to test, I'll be happy to do so.

**Comment by digitalchet** [comment]
Hmm... I think I've encountered the same issue on Windows 10 with the latest release.  With the difference that although I can see two or three windows coming up in the taskbar after launch, they exit out immediately and I'm unable to see any error messages.

Any ideas as to what could be causing this?

**Comment by vegardlarsen** [comment]
@digitalchet Not really. With the latest version we've dropped dependencies on the Visual C++ redist files, so the only thing besides MaxTo the installer should install, is the [.NET Framework](https://www.microsoft.com/en-us/download/details.aspx?id=48130). If you pre-install that, and try again?

**Comment by vegardlarsen** [comment]
We are replacing the entire installer system in version 2.0.0, which means this bug report is no longer relevant. See #220 for trying out the preview release of 2.0.0.
