### ISSUE TITLE
Loading profile is not preserving settings specified on save

### ISSUE THREAD

**Issue by khayk** [digitalcreations/MaxTo#88]
Screen have 2560x1440 dimension. I split the screen in a following way:
1. Vertically (Left side have size 1650), right side spit in two, no metter how.
2. Save profile.
3. Done
4. Activate MaxTo again
5. Done.
Every time performing steps 4, 5, the size of left side decreased by 1 pixel.

**Comment by vegardlarsen** [comment]
This is fully reproducible. I'll have a look to see if it can be fixed easily.

**Comment by vegardlarsen** [comment]
I've fixed this and it will be in the next release. Thank you for reporting it!

**Comment by khayk** [comment]
Thank you too! 
I would like to report one more issue but I don't think it is a good idea to report it here now. How can I send you description of the problem privately? Then you'll decide where to keep it. My Skype username is k_hayk.

**Comment by vegardlarsen** [comment]
@khayk There is an e-mail address in the about dialog. Also, I poked you on Skype, but haven't received a reply... :)

**Comment by khayk** [comment]
I didn't get any notification from Skype. You mean e-mail support@maxto.net ? I'll send the description to that address.

**Comment by vegardlarsen** [comment]
Thanks :) You probably have your Skype account set to not allow messages from strangers...

**Comment by khayk** [comment]
I've sent a report to support team. Good luck!
