### ISSUE TITLE
Windows 10 Shortcuts?

### ISSUE THREAD

**Issue by joshjingles** [digitalcreations/MaxTo#89]
I recall when upgrading to Windows 10 MaxTo mentioned that the shortcuts have changed because windows 10 requires certain keys.

I probably recall the notification message incorrectly, but if I'm using Win-Arrows and Alt-Win-Arrows are there any issues with how the OS wants to use those shortcuts?

Thanks

**Comment by vegardlarsen** [comment]
Unless you go into Windows' Settings, System, Multitasking, and uncheck all of the Snap features, this won't work.

Virtual Desktop further reserves the Ctrl+Windows+left/right combination, and this cannot be turned off in the settings, as far as I know. This means you cannot use Ctrl+Windows+arrow keys for anything useful in MaxTo.

My suggestion is that you try out the new defaults, they seem to work really well for me at least.
