### ISSUE TITLE
MaxTo does not start at logon after installation on a clean Windows 10 installation

### ISSUE THREAD

**Issue by glat** [digitalcreations/MaxTo#90]
As in subject.

Here are some points to help you debug:

- At the end of installation the installer opens the program folder of MaxTo. I think it's a signal something is wrong during installation.
- MaxTo should be run by scheduler which has an action to run: "C:\Windows\SysWOW64\rundll32.exe" --start-hidden Of course it is not MaxTo executable

Kind regards

**Comment by vegardlarsen** [comment]
Thanks for reporting this. This was reported as a bug in the previous release as well (then for Windows 8.1), so I had a long look at it, found a few bugs, squashed them, and everything seemed to be OK in a blank VM after trying it out a few times.

I'll make sure I try this on a new Windows 10 installation before the next release, and see if I can figure out what is happening.

**Comment by 57thkafka** [comment]
MaxTo doesn't auto-start on my Windows 8.1 64-bit since updating to the latest version 2015.07.1

**Comment by 57thkafka** [comment]
I have now upgraded to Windows 10 64-bit and can confirm that the bug persists with latest MaxTo version 2015.07.1

**Comment by CaptainBraindead** [comment]
Same here - MaxTo works, but no startup. Also, it tends to geet closed after long computer hours

**Comment by vegardlarsen** [comment]
I have identified and fixed this issue in the source. It will be fixed in the next release.

**Comment by skworden** [comment]
FYI this happens on 7 pro, 8 home or 8 pro as well.

**Comment by mas-co** [comment]
MaxTo does not start with Windows 10 on my machine either.  Also, i may have experienced at least one instance of MaxTo spontaneously closing.
