### ISSUE TITLE
Shift+Win+M causes uncontrollable window arrangement

### ISSUE THREAD

**Issue by SteffenLanger** [digitalcreations/MaxTo#92]
Hey MaxTo-Team!

I'm on a Windows 7 laptop with an additional external monitor. Every time I press Win+M, my windows are minimized correctly. However, when bringing them back up again, I get a completely different window arrangement than before. It seems like they are reopened in random regions.

Here's a screenshot:
![screenshot_new_arrangement](https://cloud.githubusercontent.com/assets/13887114/9383811/0784bd14-474c-11e5-98e2-e0b0b121a109.png)

**Comment by vegardlarsen** [comment]
Hey! I just tried this on my main machine, running Windows 10, with both an Explorer and a Word window. When clicking them in the taskbar, they show up exactly where they were before.

Did I misunderstand how it was done?

**Comment by SteffenLanger** [comment]
Instead of clicking, use Shift+Win+M. That is supposed to revert Win+M.

Thank you!

Mit freundlichen Grüßen
Steffen Langer
Geschäftsführung - Engineering
*MS Eisberg GbR*
Tel: +49 5251 1358 10
Mobil: +49 1634 1358 02
Am Ehrenmal 2 DE-33178 Borchen-Alfen
Geschäftsführer: Mark Langer & Steffen Langer
http://www.ms-eisberg.de

**Comment by SteffenLanger** [comment]
Any ideas, Vegard?

**Comment by vegardlarsen** [comment]
I still cannot reproduce this on Windows 10. I am assuming this is a bug, but I'll know more once I have had a look at it on Windows 7.

**Comment by vegardlarsen** [comment]
After experimenting with this for a bit, I've discovered the case where this does happen:

- You have an active window
- You press Win+M
- You press Shift+Win+M while the mouse is in a specific region
- The last active window will maximize to the region the mouse is in

I am looking at ways to mitigate this.

**Comment by vegardlarsen** [comment]
I am hitting a brick wall figuring out how to detect when a restore event happens in the context of Aero Shake. I am putting the investigation on hold for now to focus on easier pickings, and will come back to it.

**Comment by SteffenLanger** [comment]
Thank you!

**Comment by vegardlarsen** [comment]
While going through old issues, and testing this in version 2.1.0-beta.2 (not yet available), this does no longer appear to be a problem. Closing this issue.
