### ISSUE TITLE
Dragging offset when dragging maximized window

### ISSUE THREAD

**Issue by SteffenLanger** [digitalcreations/MaxTo#93]
Hey MaxTo-Team!

I'm on a Windows 7 laptop with an additional external monitor.

When I drag and drop a window like Firefox or Total Commander from their maximized state, my mouse pointer is off. I can still drag the window but my mouse does not even touch it.
Interestingly, this does not happen when I drag the Word 2013 window which looks different (maybe it is different? :-) ).

I attach a screenshot. In this state, I can move my mouse and move the window but the mouse does not touch the window.
![window_draggable](https://cloud.githubusercontent.com/assets/13887114/9383872/7bc22b08-474c-11e5-8c2b-83f598d32982.png)

**Comment by vegardlarsen** [comment]
You are right. I should fix this.

It happens because the restored size is smaller than the area you clicked. I'll probably fix this so the window is placed either horizontally centered around the mouse cursor, or using some sort of algorithm to calculate a decent placement.

**Comment by vegardlarsen** [comment]
I just fixed this issue in my local build. Look for it in the next release :)

**Comment by SteffenLanger** [comment]
Thanks!
