### ISSUE TITLE
shortcut feature request

### ISSUE THREAD

**Issue by MikeBadescu** [digitalcreations/MaxTo#94]
1. Specific option for moving a window to a different screen preserving its size.
2. More flexibility in defining the shortcuts (I would like to be able to reproduce some of the easy re-sizing features of WinSplit)

**Comment by vegardlarsen** [comment]
What would your ideal resizing shortcuts be? Would it be interesting to have a "lock size" button for windows?

**Comment by MikeBadescu** [comment]
I use Ctr-Alt-{Arrows} to move the windows on different screens and Ctr-Alt-{numpad} to set the position of a window inside a screen. However, different people have different tastes (and some people do not have the numerical pad), so I guess the best way would be to allow full flexibility. 

I am not sure about the "lock size" feature - I enjoy the flexibility of "quantized" (i.e., take on only certain discrete values) sizes what WinSplit has.

**Comment by vegardlarsen** [comment]
Check out the preview program; it has a lot of what you want with regards to more flexible keyboard shortcuts. See #220 for details of how to try the preview.
