### ISSUE TITLE
PyCharm's floating windows

### ISSUE THREAD

**Issue by MikeBadescu** [digitalcreations/MaxTo#95]
[PyCharm](https://www.jetbrains.com/pycharm/) has floating / un-docked windows that MaxTo is not able to identify. It is these small windows that need to be organized. On Windows 7, WinSplit has no problem identifying them.

In general, it may be a good idea to target the IDEs, it may bring more people to MaxTo. Once you do this, do not forget to spread the word.

Also, keep in mind that Adobe Acrobat is widely used. Please consider identifying Pro vs Reader and being able to resize Reader as well. 
https://github.com/digitalcreations/MaxTo/issues/31

Thank you for your work, MaxTo is on it's way to be a good replacement for WinSplit!

**Comment by vegardlarsen** [comment]
If the floating windows are anything like the ones in PhpStorm (which I guess they are), they are identified as toolbox windows, meaning that they don't have maximize/minimize buttons. Can you confirm that? If not, can you send me a screenshot of one?

This restriction in MaxTo is to prevent resizing windows that really shouldn't be resized. I can see if I can fine-tune this a bit. 

Regarding Adobe Acrobat; I am working on a better workaround to this problem, but I am very limited in what I can do.

**Comment by MikeBadescu** [comment]
Indeed, they are similar to PhpStorm. 
![pycharm floating window](https://cloud.githubusercontent.com/assets/6641575/9439268/e9430720-4a2a-11e5-91ec-7f5eff449005.png)

Thank you!

**Comment by vegardlarsen** [comment]
So, the reason that this does not work, is that PhpStorm and PyCharm windows do not declare the `WS_MAXIMIZEBOX` window style. They are `WS_POPUP` windows, which normally aren't meant to be resized. 

I can easily let all `WS_POPUP` windows be affected by MaxTo, but this breaks (horribly) a lot of other applications. This was what happened when I forced a resize of a Spy++ popup window:

![image](https://cloud.githubusercontent.com/assets/436508/9631267/0f1100c2-5180-11e5-965b-6e9ccfa731e1.png)

I see two possible solutions here:

- We nag JetBrains to fix their windows to use the correct window styles (my guess is that is not going to happen)
- I create a new type of compatibility shim that allows us to target specific window types, and allow resizing them.

I am going to go with option 2. It is going to take some time before this is available in a release.

**Comment by MikeBadescu** [comment]
Thank you, this sounds great.

**Comment by vegardlarsen** [comment]
Just a quick note that this issue is still on my mind, even though I haven't gotten around to fixing it for the upcoming release this month. There is a large update coming to the way we do compatibility shims (this [secret part of MaxTo's website](https://maxto.net/shim) is part of that), and this change fits better in with that work.
