### ISSUE TITLE
Weird Behavior

### ISSUE THREAD

**Issue by steven10172** [digitalcreations/MaxTo#96]
I've been using MaxTo for a while and it seems that just recently I'm having weird issues on my left monitor and only my left monitor (I have 4). And as soon as I move the window to another monitor it works normally. MaxTo has never crashed and I've tried re-installing it multiple times and re-installing Chrome/Firefox.

Setup:
vc1 = GeForce GT 630
vc2 = GeForce GTX 750
...........[ vc2 ]
[ vc1 ] [ vc1 ] [ vc2 ]

List of Issues:
 - Artifacts (that randomly flicker between the below issues)
  - Desktop bleeding through
  - Background windows bleeding through
  - Black spots
  - Chrome Developer Tools panels bleed through

 - Firefox
  - onMouseMove events randomly get 200-300 pixel jumps off of where you're actually moving (always in a positive displacement on the X axis)

![2015-08-12_16-43-35](https://cloud.githubusercontent.com/assets/1575003/9508757/276ca41c-4c1e-11e5-9a37-a1b09930b159.png)

**Comment by vegardlarsen** [comment]
When you say artifacts, I immediately think of video driver issues. Does this happen when MaxTo is not running as well?

**Comment by steven10172** [comment]
When MaxTo isn't running everything is normal.

**Comment by steven10172** [comment]
Here is a video showing the Firefox mouse event issue: https://www.dropbox.com/s/gpq09q2585va8mb/2015-08-27_10-57-50.mp4?dl=0

At 20-30 seconds into the video you can see the graphic randomly jumping to the right side of the canvas multiple times and is generally choppy looking as there are constantly random events that are a few pixels in a positive X displacement.

**Comment by steven10172** [comment]
To further clarify the artifacts they only seem to appear when Chrome Developer Tools is active and in the bottom left split of Monitor 3:

![w1ojxv2 1](https://cloud.githubusercontent.com/assets/1575003/9526244/c346ac54-4cad-11e5-8c0a-04fd33ef1997.png)

**Comment by vegardlarsen** [comment]
Do you have that Firefox test page somewhere I can try it easily?

I am struggling with figuring out what may be happening here. MaxTo will try to subclass any window currently active. Firefox is one of those. Subclassing means MaxTo gets a chance to inspect any window message that arrives, including mouse move messages. MaxTo simply passes these messages through unless you are doing something special (such as dragging the window).

One thing you could try, is to add Firefox to MaxTo's no-subclass list. Open Notepad as Administrator, and find `%ProgramFiles%\MaxTo\shims.xml`. Under the `<no_subclass>` tag, add `<process title="Firefox">Firefox</process>`. Restart MaxTo. Now, when you drag Firefox around, the window will not turn transparent, and you should get a notice from MaxTo saying that some features have been disabled.

Now retry the mouse-move test.

**Comment by steven10172** [comment]
Unfortunately that version of the website won't be live for possibly a few weeks. I can share it at that time.

I added the tag to `<no_subclass>` and it's still having issues. To further clarify the issue is only occurring when Firefox is on the top half of monitor 3.

**Comment by steven10172** [comment]
The artifacts seem to have gone away now that I stopped using iDisplay (http://www.getidisplay.com/).

**Comment by vegardlarsen** [comment]
I am going to attribute this behavior to iDisplay. It is a relatively minor issue with a little-used 3rd-party utility in a specific case where things are slow but work.

And if I understand you correctly, the issue is completely resolved when not using iDisplay?
