### ISSUE TITLE
Accept different payment methods

### ISSUE THREAD

**Issue by skworden** [digitalcreations/MaxTo#98]
Your site maxto.net was flagged by my banks as a fraudulent site and won't let us purchase it. You should accept PayPal or something reputable.

**Comment by vegardlarsen** [comment]
@skworden Thanks for letting us know. It is strange that we should be flagged as fraudulent, as we are using the largest credit card processor in the Nordics ([Nets](https://www.nets.eu)). My guess is that your bank is flagging it as a foreign site, and that your card is blocked from paying outside your country.

We do have a Paypal account, but we are not very happy with Paypal. We may still accept Paypal in the future in some specific cases.

Send me an e-mail with the details you want on your license to our support address, and we'll give you instructions to pay via Paypal. It would also be very interesting to know which bank you have, and the exact message you received from them, so we can investigate exactly what happened.
